version: "3.4"

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"
services:
  mandatarissen-consumer:
    image: lblod/gelinkt-notuleren-consumer:0.1.3
    environment:
      SERVICE_NAME: "gelinkt-notuleren-madatarissen-consumer"
      # replace with link to MDB API
      #SYNC_BASE_URL: 'https://mandaten.lblod.info'
      SYNC_BASE_URL: 'https://dev.mandaten.lblod.info'
      SYNC_FILES_PATH: '/sync/mandatarissen/files'
      DOWNLOAD_FILE_PATH: '/delta-files/:id/download'
      INGEST_INTERVAL: 60000 # each minute
    volumes:
      - ./config/consumer/mandatarissen/:/config/
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  functionarissen-consumer:
    image: lblod/gelinkt-notuleren-consumer:0.1.3
    environment:
      SERVICE_NAME: "gelinkt-notuleren-functionarissen-consumer"
      # replace with link to MDB API
      #SYNC_BASE_URL: 'https://leidinggevenden.lblod.info'
      SYNC_BASE_URL: 'https://dev.leidinggevenden.lblod.info'
      SYNC_FILES_PATH: '/sync/functionarissen/files'
      DOWNLOAD_FILE_PATH: '/files/:id/download'
      INGEST_INTERVAL: 60000 # each minute
    volumes:
      - ./config/consumer/functionarissen/:/config/
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
