version: "3.4"
services:
  blockchain:
    image: trase/blockchain-event-broker:0.1.0
    restart: always
    environment:
      NODE_ENV: ${NODE_ENV}
    links:
      - virtuoso:database
    ports:
      - "8888:80"
  blockchainNotifier:
    image: lblod/blockchain-informing-service
    restart: always
    links:
      - virtuoso:database
      - blockchain:blockchain
  decisionservice:
    image: trase/decision-service:0.1.0
    restart: always
    environment:
      NODE_ENV: ${NODE_ENV}
      ADMIN_PW: ${ADMIN_PW}
      MONGO_URI: ${MONGO_URI}
    links:
      - virtuoso:database
    volumes:
      - "./config/blockchain/clients/:/clients/"
      - "./config/blockchain/config/:/config/"
      - "./config/blockchain/certs/:/usr/src/app/certs/"
  authentication:
    image: trase/authentication-service:0.1.0
    restart: always
    environment:
      NODE_ENV: ${NODE_ENV}
      ADMIN_PW: ${ADMIN_PW}
    volumes:
      - "./config/blockchain/clients/:/clients/"
      - "./config/blockchain/config/:/config/"
  frontend:
    image: trase/frontend:0.1.0
    ports:
      - "82:1234"
