version: "3.4"
services:
  blockchain:
    image: trase/blockchain-event-broker
    restart: always
    environment:
      NODE_ENV: ${NODE_ENV}
    links:
      - virtuoso:database
  blockchainNotifier:
    image: lblod/blockchain-informing-service
    restart: always
    links:
      - virtuoso:database
      - blockchain:blockchain
  decisionservice:
    image: trase/decision-service
    restart: always
    environment:
      NODE_ENV: ${NODE_ENV}
      ADMIN_PW: ${ADMIN_PW}
      MONGO_URI: ${MONGO_URI}
    links:
      - virtuoso:database
    volumes:
      - "PATH_TO_CLIENT_CONFIG:/clients/"
      - "PARG_TO_NETWORK_CONFIG:/config/"
      - "PATH_TO_HTTPS_CERTS/:/usr/src/app/certs/"
  authentication:
    image: trase/authentication-service
    restart: always
    environment:
      NODE_ENV: ${NODE_ENV}
      ADMIN_PW: ${ADMIN_PW}
    volumes:
      - "PATH_TO_CLIENT_CONFIG:/clients/"
      - "PARG_TO_NETWORK_CONFIG:/config/"
  frontend:
    image: trase/frontend
    ports:
      - "82:1234"
