version: "3.4"
services:
  blockchain:
    image: trase/blockchain-event-broker:0.1.2
    restart: always
    environment:
      NODE_ENV: ${NODE_ENV}
    links:
      - virtuoso:database
    ports:
      - "8888:80"
    volumes:
      - "/Users/wouter/Documents/Hyperledger/lblod/LBLOD/lblod-blockchain-event-broker/:/app/"
  blockchainNotifier:
    image: lblod/blockchain-informing-service:0.0.3
    restart: always
    links:
      - virtuoso:database
      - blockchain:blockchain
  decisionservice:
    image: trase/decision-service:0.1.1
    restart: always
    environment:
      NODE_ENV: ${NODE_ENV}
      ADMIN_PW: ${ADMIN_PW}
    links:
      - virtuoso:database
      - mongodb
    volumes:
      - "/Users/wouter/Documents/Hyperledger/lblod/LBLOD/lblod-decision-service/:/app/"
      - "../../network/artifacts/clients/:/clients/"
      - "../../network/artifacts/config/:/config/"
      - "./config/blockchain/certs/:/usr/src/app/certs/"
    depends_on:
      - mongodb
  authentication:
    image: trase/authentication-service:0.1.0
    restart: always
    environment:
      NODE_ENV: ${NODE_ENV}
      ADMIN_PW: ${ADMIN_PW}
    volumes:
      - "/Users/wouter/Documents/Hyperledger/lblod/LBLOD/lblod-authentication-integration-service/:/app/"
      - "../../network/artifacts/clients/:/clients/"
      - "../../network/artifacts/config/:/config/"
  frontend:
    image: trase/frontend:0.1.0
    ports:
      - "82:1234"
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/data/logs
    volumes:
      - ./data/bcdb:/data/db
    ports:
      - 27017:27017
    command: mongod
