version: "3.4"
services:
  blockchainNotifier:
    image: lblod/blockchain-informing-service
    restart: always
    links:
      - virtuoso:database
      - blockchain:blockchain
  blockchain:
    image: trase/blockchain-event-broker
    restart: always
    environment:
      NODE_ENV: ${NODE_ENV}
    links:
      - virtuoso:database
    ports:
      - "8888:80"
    volumes:
      - "../lblod-services/event-broker/:/app/"
  decisionservice:
    image: trase/decision-service
    restart: always
    environment:
      NODE_ENV: ${NODE_ENV}
      ADMIN_PW: ${ADMIN_PW}
      APP_MONGO_USER: ${APP_MONGO_USER}
      APP_MONGO_PASS: ${APP_MONGO_PASS}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    links:
      - virtuoso:database
      - mongodb
    volumes:
      - "../lblod-services/decision-service/:/app/"
      - "../network/artifacts/clients/:/clients/"
      - "../network/artifacts/config/:/config/"
    depends_on:
      - mongodb
  authentication:
    image: trase/authentication-service
    restart: always
    environment:
      NODE_ENV: ${NODE_ENV}
      ADMIN_PW: ${ADMIN_PW}
    volumes:
      - "../lblod-services/authentication-service/:/app/"
      - "../network/artifacts/clients/:/clients/"
      - "../network/artifacts/config/:/config/"
  blockchain-frontend:
    image: trase/frontend
    environment:
      SERVICE_URL: "http://localhost:80"
    ports:
      - "82:1234"
    volumes:
      - "../lblod-services/frontend/:/usr/src/app/"
  mongodb:
    image: mongo:4
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      APP_MONGO_USER: ${APP_MONGO_USER}
      APP_MONGO_PASS: ${APP_MONGO_PASS}
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /data/logs
    volumes:
      - "./config/blockchain/userCreation.sh:/docker-entrypoint-initdb.d/userCreation.sh"
      - ./data/bcdb:/data/db
    command: mongod
