# started voornamen-update-7149-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:05:53+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/7a2f46d82fcc258fc6c8dd47eff740a21c5f05bd47a53568d1cba95d4857eb06> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7a2f46d82fcc258fc6c8dd47eff740a21c5f05bd47a53568d1cba95d4857eb06> a person:Person.
           <http://data.lblod.info/id/personen/7a2f46d82fcc258fc6c8dd47eff740a21c5f05bd47a53568d1cba95d4857eb06> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7a2f46d82fcc258fc6c8dd47eff740a21c5f05bd47a53568d1cba95d4857eb06> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Liesbeth".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7a2f46d82fcc258fc6c8dd47eff740a21c5f05bd47a53568d1cba95d4857eb06> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/14fc9b2c228e9195fe991c72febcb0ea50e68349e92dfe1c365b43945e6b4661> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/14fc9b2c228e9195fe991c72febcb0ea50e68349e92dfe1c365b43945e6b4661> a person:Person.
           <http://data.lblod.info/id/personen/14fc9b2c228e9195fe991c72febcb0ea50e68349e92dfe1c365b43945e6b4661> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/14fc9b2c228e9195fe991c72febcb0ea50e68349e92dfe1c365b43945e6b4661> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ludo".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/14fc9b2c228e9195fe991c72febcb0ea50e68349e92dfe1c365b43945e6b4661> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/d46b889c-076b-41e0-ace8-d319a99bd6a6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d46b889c-076b-41e0-ace8-d319a99bd6a6> a person:Person.
           <http://data.lblod.info/id/personen/d46b889c-076b-41e0-ace8-d319a99bd6a6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d46b889c-076b-41e0-ace8-d319a99bd6a6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Annemie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d46b889c-076b-41e0-ace8-d319a99bd6a6> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e466a77d95f9bec08c618ee324013d8c09284fce314c842bc5f5d2fbca352914> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e466a77d95f9bec08c618ee324013d8c09284fce314c842bc5f5d2fbca352914> a person:Person.
           <http://data.lblod.info/id/personen/e466a77d95f9bec08c618ee324013d8c09284fce314c842bc5f5d2fbca352914> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e466a77d95f9bec08c618ee324013d8c09284fce314c842bc5f5d2fbca352914> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Liese".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e466a77d95f9bec08c618ee324013d8c09284fce314c842bc5f5d2fbca352914> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/a363b7e8f6f62e4fa27a3be66c2b6a169427167d5c46e702833a4f00e88d7774> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a363b7e8f6f62e4fa27a3be66c2b6a169427167d5c46e702833a4f00e88d7774> a person:Person.
           <http://data.lblod.info/id/personen/a363b7e8f6f62e4fa27a3be66c2b6a169427167d5c46e702833a4f00e88d7774> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a363b7e8f6f62e4fa27a3be66c2b6a169427167d5c46e702833a4f00e88d7774> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Bieke".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a363b7e8f6f62e4fa27a3be66c2b6a169427167d5c46e702833a4f00e88d7774> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/3940e68b902d016e9bc830554f806c2cfc259e6e57cbce37fe7c1fb62fc82fae> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3940e68b902d016e9bc830554f806c2cfc259e6e57cbce37fe7c1fb62fc82fae> a person:Person.
           <http://data.lblod.info/id/personen/3940e68b902d016e9bc830554f806c2cfc259e6e57cbce37fe7c1fb62fc82fae> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3940e68b902d016e9bc830554f806c2cfc259e6e57cbce37fe7c1fb62fc82fae> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Rob".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3940e68b902d016e9bc830554f806c2cfc259e6e57cbce37fe7c1fb62fc82fae> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/4e96131a-9f7e-4367-9f67-1bb31c6782d9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4e96131a-9f7e-4367-9f67-1bb31c6782d9> a person:Person.
           <http://data.lblod.info/id/personen/4e96131a-9f7e-4367-9f67-1bb31c6782d9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4e96131a-9f7e-4367-9f67-1bb31c6782d9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Leo".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4e96131a-9f7e-4367-9f67-1bb31c6782d9> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/fb48e78c-d5e7-4323-bb09-ccca11998387> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/fb48e78c-d5e7-4323-bb09-ccca11998387> a person:Person.
           <http://data.lblod.info/id/personen/fb48e78c-d5e7-4323-bb09-ccca11998387> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/fb48e78c-d5e7-4323-bb09-ccca11998387> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jan".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/fb48e78c-d5e7-4323-bb09-ccca11998387> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/7d7921f9-b3b9-4dc0-a978-41018dab8a87> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7d7921f9-b3b9-4dc0-a978-41018dab8a87> a person:Person.
           <http://data.lblod.info/id/personen/7d7921f9-b3b9-4dc0-a978-41018dab8a87> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7d7921f9-b3b9-4dc0-a978-41018dab8a87> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Josée".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7d7921f9-b3b9-4dc0-a978-41018dab8a87> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/59ab46c0-a874-4a22-9b43-689486099b3b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/59ab46c0-a874-4a22-9b43-689486099b3b> a person:Person.
           <http://data.lblod.info/id/personen/59ab46c0-a874-4a22-9b43-689486099b3b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/59ab46c0-a874-4a22-9b43-689486099b3b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Arnout".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/59ab46c0-a874-4a22-9b43-689486099b3b> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/4cd51f8bb150bd433ee425d608a4b2af7a8e86ce5c3cdf320bc709bc9449d963> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4cd51f8bb150bd433ee425d608a4b2af7a8e86ce5c3cdf320bc709bc9449d963> a person:Person.
           <http://data.lblod.info/id/personen/4cd51f8bb150bd433ee425d608a4b2af7a8e86ce5c3cdf320bc709bc9449d963> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4cd51f8bb150bd433ee425d608a4b2af7a8e86ce5c3cdf320bc709bc9449d963> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ariane".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4cd51f8bb150bd433ee425d608a4b2af7a8e86ce5c3cdf320bc709bc9449d963> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/d98ceeb80a0f95dd9d6bb2efd9ffa8e92fc7370774fa6f37018b4a8384744259> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d98ceeb80a0f95dd9d6bb2efd9ffa8e92fc7370774fa6f37018b4a8384744259> a person:Person.
           <http://data.lblod.info/id/personen/d98ceeb80a0f95dd9d6bb2efd9ffa8e92fc7370774fa6f37018b4a8384744259> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d98ceeb80a0f95dd9d6bb2efd9ffa8e92fc7370774fa6f37018b4a8384744259> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Vic".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d98ceeb80a0f95dd9d6bb2efd9ffa8e92fc7370774fa6f37018b4a8384744259> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/a6c00763-b39d-4835-bf89-c2ec876bd94e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a6c00763-b39d-4835-bf89-c2ec876bd94e> a person:Person.
           <http://data.lblod.info/id/personen/a6c00763-b39d-4835-bf89-c2ec876bd94e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a6c00763-b39d-4835-bf89-c2ec876bd94e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Fred".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a6c00763-b39d-4835-bf89-c2ec876bd94e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/06d7b926-e94c-4fa7-a534-251d305c51f1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/06d7b926-e94c-4fa7-a534-251d305c51f1> a person:Person.
           <http://data.lblod.info/id/personen/06d7b926-e94c-4fa7-a534-251d305c51f1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/06d7b926-e94c-4fa7-a534-251d305c51f1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Lieve".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/06d7b926-e94c-4fa7-a534-251d305c51f1> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/37d2b980-8793-4b58-b068-03175cb4c512> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/37d2b980-8793-4b58-b068-03175cb4c512> a person:Person.
           <http://data.lblod.info/id/personen/37d2b980-8793-4b58-b068-03175cb4c512> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/37d2b980-8793-4b58-b068-03175cb4c512> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Eddy".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/37d2b980-8793-4b58-b068-03175cb4c512> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/c1d5cd63-ec32-417f-8290-e54bfbf41904> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c1d5cd63-ec32-417f-8290-e54bfbf41904> a person:Person.
           <http://data.lblod.info/id/personen/c1d5cd63-ec32-417f-8290-e54bfbf41904> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c1d5cd63-ec32-417f-8290-e54bfbf41904> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Guy".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c1d5cd63-ec32-417f-8290-e54bfbf41904> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2e16317b867d0e470793837c4d03e5f3652c970f8c61a41231bf7db196299018> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2e16317b867d0e470793837c4d03e5f3652c970f8c61a41231bf7db196299018> a person:Person.
           <http://data.lblod.info/id/personen/2e16317b867d0e470793837c4d03e5f3652c970f8c61a41231bf7db196299018> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2e16317b867d0e470793837c4d03e5f3652c970f8c61a41231bf7db196299018> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Guy".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2e16317b867d0e470793837c4d03e5f3652c970f8c61a41231bf7db196299018> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/be97f6455083748e2b63fb349b166027e59f8b4bfdee5d041f505c705fe7f0ac> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/be97f6455083748e2b63fb349b166027e59f8b4bfdee5d041f505c705fe7f0ac> a person:Person.
           <http://data.lblod.info/id/personen/be97f6455083748e2b63fb349b166027e59f8b4bfdee5d041f505c705fe7f0ac> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/be97f6455083748e2b63fb349b166027e59f8b4bfdee5d041f505c705fe7f0ac> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marleen".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/be97f6455083748e2b63fb349b166027e59f8b4bfdee5d041f505c705fe7f0ac> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e304d45d8c35c28c21d76682e8f64a56b9dedf5f7183f670f3b52c449a4f674d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e304d45d8c35c28c21d76682e8f64a56b9dedf5f7183f670f3b52c449a4f674d> a person:Person.
           <http://data.lblod.info/id/personen/e304d45d8c35c28c21d76682e8f64a56b9dedf5f7183f670f3b52c449a4f674d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e304d45d8c35c28c21d76682e8f64a56b9dedf5f7183f670f3b52c449a4f674d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Leen".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e304d45d8c35c28c21d76682e8f64a56b9dedf5f7183f670f3b52c449a4f674d> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/1bb52661-9c9d-4021-afeb-ea24367721bf> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1bb52661-9c9d-4021-afeb-ea24367721bf> a person:Person.
           <http://data.lblod.info/id/personen/1bb52661-9c9d-4021-afeb-ea24367721bf> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1bb52661-9c9d-4021-afeb-ea24367721bf> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Willy".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1bb52661-9c9d-4021-afeb-ea24367721bf> [] [].
          }
        }
     # finished voornamen-update-7149-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:05:53+00:00