# started voornamen-update-23438-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:33+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/23672064-0e44-4437-862e-c6f702be0373> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/23672064-0e44-4437-862e-c6f702be0373> a person:Person.
           <http://data.lblod.info/id/personen/23672064-0e44-4437-862e-c6f702be0373> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/23672064-0e44-4437-862e-c6f702be0373> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/23672064-0e44-4437-862e-c6f702be0373> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/c22030beaf26b1c1827ded968dd295cacaf866f625933e92238d4e27bcd348bc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c22030beaf26b1c1827ded968dd295cacaf866f625933e92238d4e27bcd348bc> a person:Person.
           <http://data.lblod.info/id/personen/c22030beaf26b1c1827ded968dd295cacaf866f625933e92238d4e27bcd348bc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c22030beaf26b1c1827ded968dd295cacaf866f625933e92238d4e27bcd348bc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Harry".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c22030beaf26b1c1827ded968dd295cacaf866f625933e92238d4e27bcd348bc> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/0453fe57-2416-4cc5-bda0-01cae395dfd3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0453fe57-2416-4cc5-bda0-01cae395dfd3> a person:Person.
           <http://data.lblod.info/id/personen/0453fe57-2416-4cc5-bda0-01cae395dfd3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0453fe57-2416-4cc5-bda0-01cae395dfd3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marc".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0453fe57-2416-4cc5-bda0-01cae395dfd3> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/24787edd-9089-4e16-ade3-3c4ed132221b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/24787edd-9089-4e16-ade3-3c4ed132221b> a person:Person.
           <http://data.lblod.info/id/personen/24787edd-9089-4e16-ade3-3c4ed132221b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/24787edd-9089-4e16-ade3-3c4ed132221b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Johanna".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/24787edd-9089-4e16-ade3-3c4ed132221b> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/8be75917-ed25-4e40-bf54-db348ada828d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8be75917-ed25-4e40-bf54-db348ada828d> a person:Person.
           <http://data.lblod.info/id/personen/8be75917-ed25-4e40-bf54-db348ada828d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8be75917-ed25-4e40-bf54-db348ada828d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marie-Jeanne".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8be75917-ed25-4e40-bf54-db348ada828d> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2c7095e8-86d0-4d52-9278-8f18e4fafa1c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2c7095e8-86d0-4d52-9278-8f18e4fafa1c> a person:Person.
           <http://data.lblod.info/id/personen/2c7095e8-86d0-4d52-9278-8f18e4fafa1c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2c7095e8-86d0-4d52-9278-8f18e4fafa1c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Gert-Jan".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2c7095e8-86d0-4d52-9278-8f18e4fafa1c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/6e6da14d-9bb6-47af-ba75-2412e8a84ae2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6e6da14d-9bb6-47af-ba75-2412e8a84ae2> a person:Person.
           <http://data.lblod.info/id/personen/6e6da14d-9bb6-47af-ba75-2412e8a84ae2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6e6da14d-9bb6-47af-ba75-2412e8a84ae2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Gerda".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6e6da14d-9bb6-47af-ba75-2412e8a84ae2> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/5383692b-8026-4372-8ec4-aca51e2c45e0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5383692b-8026-4372-8ec4-aca51e2c45e0> a person:Person.
           <http://data.lblod.info/id/personen/5383692b-8026-4372-8ec4-aca51e2c45e0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5383692b-8026-4372-8ec4-aca51e2c45e0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Nick".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5383692b-8026-4372-8ec4-aca51e2c45e0> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/4a61a74c007716ec8fee9be8e46a57053a60dd47be39e01b231f1c7de098c939> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4a61a74c007716ec8fee9be8e46a57053a60dd47be39e01b231f1c7de098c939> a person:Person.
           <http://data.lblod.info/id/personen/4a61a74c007716ec8fee9be8e46a57053a60dd47be39e01b231f1c7de098c939> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4a61a74c007716ec8fee9be8e46a57053a60dd47be39e01b231f1c7de098c939> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "An".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4a61a74c007716ec8fee9be8e46a57053a60dd47be39e01b231f1c7de098c939> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ddf11375e1be4d4703743b3c8c2baf5bd5b3b85debc85bfc9d8cef9ba091850a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ddf11375e1be4d4703743b3c8c2baf5bd5b3b85debc85bfc9d8cef9ba091850a> a person:Person.
           <http://data.lblod.info/id/personen/ddf11375e1be4d4703743b3c8c2baf5bd5b3b85debc85bfc9d8cef9ba091850a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ddf11375e1be4d4703743b3c8c2baf5bd5b3b85debc85bfc9d8cef9ba091850a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Inge".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ddf11375e1be4d4703743b3c8c2baf5bd5b3b85debc85bfc9d8cef9ba091850a> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/cfd82e7a-dc4f-4bee-94ea-e1084787a8e9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cfd82e7a-dc4f-4bee-94ea-e1084787a8e9> a person:Person.
           <http://data.lblod.info/id/personen/cfd82e7a-dc4f-4bee-94ea-e1084787a8e9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cfd82e7a-dc4f-4bee-94ea-e1084787a8e9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marianne".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cfd82e7a-dc4f-4bee-94ea-e1084787a8e9> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/df781d1e-83ec-479a-aae8-e0b379503c77> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/df781d1e-83ec-479a-aae8-e0b379503c77> a person:Person.
           <http://data.lblod.info/id/personen/df781d1e-83ec-479a-aae8-e0b379503c77> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/df781d1e-83ec-479a-aae8-e0b379503c77> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Nadine".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/df781d1e-83ec-479a-aae8-e0b379503c77> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/77518cba89045c8f39ede36590093d2ec71fef9ab6534a2b3e7e55a2630df99e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/77518cba89045c8f39ede36590093d2ec71fef9ab6534a2b3e7e55a2630df99e> a person:Person.
           <http://data.lblod.info/id/personen/77518cba89045c8f39ede36590093d2ec71fef9ab6534a2b3e7e55a2630df99e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/77518cba89045c8f39ede36590093d2ec71fef9ab6534a2b3e7e55a2630df99e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Sara".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/77518cba89045c8f39ede36590093d2ec71fef9ab6534a2b3e7e55a2630df99e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ede6e411-7981-4c4f-b3f0-9feef75bbc6e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ede6e411-7981-4c4f-b3f0-9feef75bbc6e> a person:Person.
           <http://data.lblod.info/id/personen/ede6e411-7981-4c4f-b3f0-9feef75bbc6e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ede6e411-7981-4c4f-b3f0-9feef75bbc6e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Johan".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ede6e411-7981-4c4f-b3f0-9feef75bbc6e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/26af9e72-e5d9-4710-9d67-150caf0906e3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/26af9e72-e5d9-4710-9d67-150caf0906e3> a person:Person.
           <http://data.lblod.info/id/personen/26af9e72-e5d9-4710-9d67-150caf0906e3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/26af9e72-e5d9-4710-9d67-150caf0906e3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Rosette".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/26af9e72-e5d9-4710-9d67-150caf0906e3> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/3c85eb41-c6ab-4e7e-b4c9-5caaf9910cd0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3c85eb41-c6ab-4e7e-b4c9-5caaf9910cd0> a person:Person.
           <http://data.lblod.info/id/personen/3c85eb41-c6ab-4e7e-b4c9-5caaf9910cd0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3c85eb41-c6ab-4e7e-b4c9-5caaf9910cd0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ronny".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3c85eb41-c6ab-4e7e-b4c9-5caaf9910cd0> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/d39f2f11-a8c1-49f4-8e8d-d7d214210d45> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d39f2f11-a8c1-49f4-8e8d-d7d214210d45> a person:Person.
           <http://data.lblod.info/id/personen/d39f2f11-a8c1-49f4-8e8d-d7d214210d45> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d39f2f11-a8c1-49f4-8e8d-d7d214210d45> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Thyas".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d39f2f11-a8c1-49f4-8e8d-d7d214210d45> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/970a0264-876c-4e4f-b57a-84e9c2daebb3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/970a0264-876c-4e4f-b57a-84e9c2daebb3> a person:Person.
           <http://data.lblod.info/id/personen/970a0264-876c-4e4f-b57a-84e9c2daebb3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/970a0264-876c-4e4f-b57a-84e9c2daebb3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Eric".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/970a0264-876c-4e4f-b57a-84e9c2daebb3> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/5b74b8b5-1daf-4185-a90d-b5581201973c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5b74b8b5-1daf-4185-a90d-b5581201973c> a person:Person.
           <http://data.lblod.info/id/personen/5b74b8b5-1daf-4185-a90d-b5581201973c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5b74b8b5-1daf-4185-a90d-b5581201973c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Frieda".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5b74b8b5-1daf-4185-a90d-b5581201973c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/3d94d67a-986e-480c-8c42-b15f19742dff> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3d94d67a-986e-480c-8c42-b15f19742dff> a person:Person.
           <http://data.lblod.info/id/personen/3d94d67a-986e-480c-8c42-b15f19742dff> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3d94d67a-986e-480c-8c42-b15f19742dff> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jackie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3d94d67a-986e-480c-8c42-b15f19742dff> [] [].
          }
        }
     # finished voornamen-update-23438-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:33+00:00