# started voornamen-update-11074-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:03+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/c890cc9dc9e06aa1c4323209f886822571f940f23e2f94d0355a667fd5e64d5a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c890cc9dc9e06aa1c4323209f886822571f940f23e2f94d0355a667fd5e64d5a> a person:Person.
           <http://data.lblod.info/id/personen/c890cc9dc9e06aa1c4323209f886822571f940f23e2f94d0355a667fd5e64d5a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c890cc9dc9e06aa1c4323209f886822571f940f23e2f94d0355a667fd5e64d5a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Lieve".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c890cc9dc9e06aa1c4323209f886822571f940f23e2f94d0355a667fd5e64d5a> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/5729b398-cd35-4149-bce0-f6eda7b5997c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5729b398-cd35-4149-bce0-f6eda7b5997c> a person:Person.
           <http://data.lblod.info/id/personen/5729b398-cd35-4149-bce0-f6eda7b5997c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5729b398-cd35-4149-bce0-f6eda7b5997c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Greta".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5729b398-cd35-4149-bce0-f6eda7b5997c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/b3ae63f1-d313-4133-8ca6-770d4315085f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b3ae63f1-d313-4133-8ca6-770d4315085f> a person:Person.
           <http://data.lblod.info/id/personen/b3ae63f1-d313-4133-8ca6-770d4315085f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b3ae63f1-d313-4133-8ca6-770d4315085f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Roger".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b3ae63f1-d313-4133-8ca6-770d4315085f> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/957b9abf-f90d-474b-9ced-1f5ea8889e4d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/957b9abf-f90d-474b-9ced-1f5ea8889e4d> a person:Person.
           <http://data.lblod.info/id/personen/957b9abf-f90d-474b-9ced-1f5ea8889e4d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/957b9abf-f90d-474b-9ced-1f5ea8889e4d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marita".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/957b9abf-f90d-474b-9ced-1f5ea8889e4d> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/caaee1bb-767e-46e6-8689-b21303afdc99> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/caaee1bb-767e-46e6-8689-b21303afdc99> a person:Person.
           <http://data.lblod.info/id/personen/caaee1bb-767e-46e6-8689-b21303afdc99> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/caaee1bb-767e-46e6-8689-b21303afdc99> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Sven".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/caaee1bb-767e-46e6-8689-b21303afdc99> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/a1293717f31e6ca0524676565d1c4470cb43236932e7c78366e84ff8a831ea65> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a1293717f31e6ca0524676565d1c4470cb43236932e7c78366e84ff8a831ea65> a person:Person.
           <http://data.lblod.info/id/personen/a1293717f31e6ca0524676565d1c4470cb43236932e7c78366e84ff8a831ea65> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a1293717f31e6ca0524676565d1c4470cb43236932e7c78366e84ff8a831ea65> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Hilde".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a1293717f31e6ca0524676565d1c4470cb43236932e7c78366e84ff8a831ea65> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/7c72319d-ce38-4b8b-b95c-afe977a04aee> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7c72319d-ce38-4b8b-b95c-afe977a04aee> a person:Person.
           <http://data.lblod.info/id/personen/7c72319d-ce38-4b8b-b95c-afe977a04aee> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7c72319d-ce38-4b8b-b95c-afe977a04aee> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Lutgarde".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7c72319d-ce38-4b8b-b95c-afe977a04aee> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/472ec9ab-53e0-4d52-99df-b9f40f44c993> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/472ec9ab-53e0-4d52-99df-b9f40f44c993> a person:Person.
           <http://data.lblod.info/id/personen/472ec9ab-53e0-4d52-99df-b9f40f44c993> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/472ec9ab-53e0-4d52-99df-b9f40f44c993> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marc".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/472ec9ab-53e0-4d52-99df-b9f40f44c993> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/7727a888-6294-4699-9947-9bdd393c1658> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7727a888-6294-4699-9947-9bdd393c1658> a person:Person.
           <http://data.lblod.info/id/personen/7727a888-6294-4699-9947-9bdd393c1658> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7727a888-6294-4699-9947-9bdd393c1658> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marc".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7727a888-6294-4699-9947-9bdd393c1658> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/4a7fee09-9ebd-4af9-a954-0664956c524e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4a7fee09-9ebd-4af9-a954-0664956c524e> a person:Person.
           <http://data.lblod.info/id/personen/4a7fee09-9ebd-4af9-a954-0664956c524e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4a7fee09-9ebd-4af9-a954-0664956c524e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Michel".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4a7fee09-9ebd-4af9-a954-0664956c524e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/79b3e2e1-d90d-4d37-ab07-3af4f39f5893> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/79b3e2e1-d90d-4d37-ab07-3af4f39f5893> a person:Person.
           <http://data.lblod.info/id/personen/79b3e2e1-d90d-4d37-ab07-3af4f39f5893> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/79b3e2e1-d90d-4d37-ab07-3af4f39f5893> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Stef".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/79b3e2e1-d90d-4d37-ab07-3af4f39f5893> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/0c5dfd05-50a5-426a-88cd-477c222807df> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0c5dfd05-50a5-426a-88cd-477c222807df> a person:Person.
           <http://data.lblod.info/id/personen/0c5dfd05-50a5-426a-88cd-477c222807df> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0c5dfd05-50a5-426a-88cd-477c222807df> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Veysel".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0c5dfd05-50a5-426a-88cd-477c222807df> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/d0aba8f6-deb8-46aa-ad76-6ba55063e585> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d0aba8f6-deb8-46aa-ad76-6ba55063e585> a person:Person.
           <http://data.lblod.info/id/personen/d0aba8f6-deb8-46aa-ad76-6ba55063e585> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d0aba8f6-deb8-46aa-ad76-6ba55063e585> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jocelyne".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d0aba8f6-deb8-46aa-ad76-6ba55063e585> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/b034c770a3afb54a7fe0eb9df187af209c7b9457f0dbc16c8b6ac877c1c2dfda> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b034c770a3afb54a7fe0eb9df187af209c7b9457f0dbc16c8b6ac877c1c2dfda> a person:Person.
           <http://data.lblod.info/id/personen/b034c770a3afb54a7fe0eb9df187af209c7b9457f0dbc16c8b6ac877c1c2dfda> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b034c770a3afb54a7fe0eb9df187af209c7b9457f0dbc16c8b6ac877c1c2dfda> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jean".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b034c770a3afb54a7fe0eb9df187af209c7b9457f0dbc16c8b6ac877c1c2dfda> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/66a03f61-28fc-415b-b3f1-3aa377bf2505> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/66a03f61-28fc-415b-b3f1-3aa377bf2505> a person:Person.
           <http://data.lblod.info/id/personen/66a03f61-28fc-415b-b3f1-3aa377bf2505> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/66a03f61-28fc-415b-b3f1-3aa377bf2505> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Patrick".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/66a03f61-28fc-415b-b3f1-3aa377bf2505> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e8ef3ff7fda1f9254ed20105abc8958305ff48e37fa9fc5ac8175ffc08e319c0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e8ef3ff7fda1f9254ed20105abc8958305ff48e37fa9fc5ac8175ffc08e319c0> a person:Person.
           <http://data.lblod.info/id/personen/e8ef3ff7fda1f9254ed20105abc8958305ff48e37fa9fc5ac8175ffc08e319c0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e8ef3ff7fda1f9254ed20105abc8958305ff48e37fa9fc5ac8175ffc08e319c0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Sandra".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e8ef3ff7fda1f9254ed20105abc8958305ff48e37fa9fc5ac8175ffc08e319c0> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e061355abd3a73bf5a8d5fa49774cf4cdf98b95cb3bcd5b8c64b7d2062df7f56> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e061355abd3a73bf5a8d5fa49774cf4cdf98b95cb3bcd5b8c64b7d2062df7f56> a person:Person.
           <http://data.lblod.info/id/personen/e061355abd3a73bf5a8d5fa49774cf4cdf98b95cb3bcd5b8c64b7d2062df7f56> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e061355abd3a73bf5a8d5fa49774cf4cdf98b95cb3bcd5b8c64b7d2062df7f56> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Mark".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e061355abd3a73bf5a8d5fa49774cf4cdf98b95cb3bcd5b8c64b7d2062df7f56> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/0552446b4b04a2dc8ae696ec4b4feb4b4e97b8e801ecb4e04d124559966c79b6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0552446b4b04a2dc8ae696ec4b4feb4b4e97b8e801ecb4e04d124559966c79b6> a person:Person.
           <http://data.lblod.info/id/personen/0552446b4b04a2dc8ae696ec4b4feb4b4e97b8e801ecb4e04d124559966c79b6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0552446b4b04a2dc8ae696ec4b4feb4b4e97b8e801ecb4e04d124559966c79b6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Michel".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0552446b4b04a2dc8ae696ec4b4feb4b4e97b8e801ecb4e04d124559966c79b6> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/68f008d3-3c8c-4309-a77f-2927b23af39e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/68f008d3-3c8c-4309-a77f-2927b23af39e> a person:Person.
           <http://data.lblod.info/id/personen/68f008d3-3c8c-4309-a77f-2927b23af39e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/68f008d3-3c8c-4309-a77f-2927b23af39e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Hilde".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/68f008d3-3c8c-4309-a77f-2927b23af39e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/29f101eb-5f4c-47dc-abd7-49d91bbe1cc5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/29f101eb-5f4c-47dc-abd7-49d91bbe1cc5> a person:Person.
           <http://data.lblod.info/id/personen/29f101eb-5f4c-47dc-abd7-49d91bbe1cc5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/29f101eb-5f4c-47dc-abd7-49d91bbe1cc5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Martine".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/29f101eb-5f4c-47dc-abd7-49d91bbe1cc5> [] [].
          }
        }
     # finished voornamen-update-11074-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:03+00:00