# started voornamen-update-666-2490de85e718ffa3e23344f4cd674bd5d9f40252833c8af6fb7fa3b82f44b008 at 2018-12-27T15:07:09+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/139a8d98c29cacae6075439e7fda6e943554d9298e585bbd19e0921bd4ae0a76> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/139a8d98c29cacae6075439e7fda6e943554d9298e585bbd19e0921bd4ae0a76> a person:Person.
           <http://data.lblod.info/id/personen/139a8d98c29cacae6075439e7fda6e943554d9298e585bbd19e0921bd4ae0a76> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/139a8d98c29cacae6075439e7fda6e943554d9298e585bbd19e0921bd4ae0a76> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Liliane".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/139a8d98c29cacae6075439e7fda6e943554d9298e585bbd19e0921bd4ae0a76> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/97d8617d-df4c-4938-afc4-d7efd28b8171> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/97d8617d-df4c-4938-afc4-d7efd28b8171> a person:Person.
           <http://data.lblod.info/id/personen/97d8617d-df4c-4938-afc4-d7efd28b8171> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/97d8617d-df4c-4938-afc4-d7efd28b8171> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Meredith".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/97d8617d-df4c-4938-afc4-d7efd28b8171> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e18811f1-5c88-460f-b57f-710ef67375da> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e18811f1-5c88-460f-b57f-710ef67375da> a person:Person.
           <http://data.lblod.info/id/personen/e18811f1-5c88-460f-b57f-710ef67375da> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e18811f1-5c88-460f-b57f-710ef67375da> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Shauni".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e18811f1-5c88-460f-b57f-710ef67375da> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/0de8ed9b690125c620f3c0c7bc7e3086b9f56545d092094c77259721336e625e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0de8ed9b690125c620f3c0c7bc7e3086b9f56545d092094c77259721336e625e> a person:Person.
           <http://data.lblod.info/id/personen/0de8ed9b690125c620f3c0c7bc7e3086b9f56545d092094c77259721336e625e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0de8ed9b690125c620f3c0c7bc7e3086b9f56545d092094c77259721336e625e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ronny".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0de8ed9b690125c620f3c0c7bc7e3086b9f56545d092094c77259721336e625e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/de8f5ce8-13a1-42f4-94d8-1469dbadfabc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/de8f5ce8-13a1-42f4-94d8-1469dbadfabc> a person:Person.
           <http://data.lblod.info/id/personen/de8f5ce8-13a1-42f4-94d8-1469dbadfabc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/de8f5ce8-13a1-42f4-94d8-1469dbadfabc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Eva".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/de8f5ce8-13a1-42f4-94d8-1469dbadfabc> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/4fe9f425-ca1c-47d0-8559-0d6fd9e5c327> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4fe9f425-ca1c-47d0-8559-0d6fd9e5c327> a person:Person.
           <http://data.lblod.info/id/personen/4fe9f425-ca1c-47d0-8559-0d6fd9e5c327> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4fe9f425-ca1c-47d0-8559-0d6fd9e5c327> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Robert".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4fe9f425-ca1c-47d0-8559-0d6fd9e5c327> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ad9c5efe18f94f31a76c1c8ee5a87f032a33d0c4213c9e63ea07bd411c30be0c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ad9c5efe18f94f31a76c1c8ee5a87f032a33d0c4213c9e63ea07bd411c30be0c> a person:Person.
           <http://data.lblod.info/id/personen/ad9c5efe18f94f31a76c1c8ee5a87f032a33d0c4213c9e63ea07bd411c30be0c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ad9c5efe18f94f31a76c1c8ee5a87f032a33d0c4213c9e63ea07bd411c30be0c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Eefje".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ad9c5efe18f94f31a76c1c8ee5a87f032a33d0c4213c9e63ea07bd411c30be0c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f12dddfa-53b5-466c-baa1-906d738a0122> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f12dddfa-53b5-466c-baa1-906d738a0122> a person:Person.
           <http://data.lblod.info/id/personen/f12dddfa-53b5-466c-baa1-906d738a0122> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f12dddfa-53b5-466c-baa1-906d738a0122> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Vera".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f12dddfa-53b5-466c-baa1-906d738a0122> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/115d5f0636b2ad45500f2b0c26489642aff733fe3f2cc18ce31c1bdfb125b3ab> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/115d5f0636b2ad45500f2b0c26489642aff733fe3f2cc18ce31c1bdfb125b3ab> a person:Person.
           <http://data.lblod.info/id/personen/115d5f0636b2ad45500f2b0c26489642aff733fe3f2cc18ce31c1bdfb125b3ab> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/115d5f0636b2ad45500f2b0c26489642aff733fe3f2cc18ce31c1bdfb125b3ab> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Luce".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/115d5f0636b2ad45500f2b0c26489642aff733fe3f2cc18ce31c1bdfb125b3ab> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/d1b79bbe4efc396a89a3419bb70a7e2e1e371ea9021b475999497f1ea614c534> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d1b79bbe4efc396a89a3419bb70a7e2e1e371ea9021b475999497f1ea614c534> a person:Person.
           <http://data.lblod.info/id/personen/d1b79bbe4efc396a89a3419bb70a7e2e1e371ea9021b475999497f1ea614c534> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d1b79bbe4efc396a89a3419bb70a7e2e1e371ea9021b475999497f1ea614c534> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Hans".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d1b79bbe4efc396a89a3419bb70a7e2e1e371ea9021b475999497f1ea614c534> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f69c2c26-b438-45a4-8828-c48c53bdd840> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f69c2c26-b438-45a4-8828-c48c53bdd840> a person:Person.
           <http://data.lblod.info/id/personen/f69c2c26-b438-45a4-8828-c48c53bdd840> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f69c2c26-b438-45a4-8828-c48c53bdd840> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Julie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f69c2c26-b438-45a4-8828-c48c53bdd840> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/73fa8f1c-8a44-43b9-85b0-033ea83cb548> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/73fa8f1c-8a44-43b9-85b0-033ea83cb548> a person:Person.
           <http://data.lblod.info/id/personen/73fa8f1c-8a44-43b9-85b0-033ea83cb548> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/73fa8f1c-8a44-43b9-85b0-033ea83cb548> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Eriq".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/73fa8f1c-8a44-43b9-85b0-033ea83cb548> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f68da970-7f6d-4dd2-aa85-24e0f3be7073> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f68da970-7f6d-4dd2-aa85-24e0f3be7073> a person:Person.
           <http://data.lblod.info/id/personen/f68da970-7f6d-4dd2-aa85-24e0f3be7073> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f68da970-7f6d-4dd2-aa85-24e0f3be7073> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Tim".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f68da970-7f6d-4dd2-aa85-24e0f3be7073> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/5597221d-5532-4476-b281-6f2a1459b0ba> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5597221d-5532-4476-b281-6f2a1459b0ba> a person:Person.
           <http://data.lblod.info/id/personen/5597221d-5532-4476-b281-6f2a1459b0ba> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5597221d-5532-4476-b281-6f2a1459b0ba> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marita".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5597221d-5532-4476-b281-6f2a1459b0ba> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/6f004c9e-0d1c-42bb-9797-dfa9dc5901f2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6f004c9e-0d1c-42bb-9797-dfa9dc5901f2> a person:Person.
           <http://data.lblod.info/id/personen/6f004c9e-0d1c-42bb-9797-dfa9dc5901f2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6f004c9e-0d1c-42bb-9797-dfa9dc5901f2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jelle".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6f004c9e-0d1c-42bb-9797-dfa9dc5901f2> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/b72674f4-5f0e-4138-99af-cf2ef09fcc6f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b72674f4-5f0e-4138-99af-cf2ef09fcc6f> a person:Person.
           <http://data.lblod.info/id/personen/b72674f4-5f0e-4138-99af-cf2ef09fcc6f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b72674f4-5f0e-4138-99af-cf2ef09fcc6f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Anton".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b72674f4-5f0e-4138-99af-cf2ef09fcc6f> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/05a71537-7ab3-4051-82f0-1a37dcea0851> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/05a71537-7ab3-4051-82f0-1a37dcea0851> a person:Person.
           <http://data.lblod.info/id/personen/05a71537-7ab3-4051-82f0-1a37dcea0851> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/05a71537-7ab3-4051-82f0-1a37dcea0851> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Geertrui".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/05a71537-7ab3-4051-82f0-1a37dcea0851> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/a9013710-ff16-4b23-aece-e397f6609e6c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a9013710-ff16-4b23-aece-e397f6609e6c> a person:Person.
           <http://data.lblod.info/id/personen/a9013710-ff16-4b23-aece-e397f6609e6c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a9013710-ff16-4b23-aece-e397f6609e6c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Roland".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a9013710-ff16-4b23-aece-e397f6609e6c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/27115c01-5bbb-42a9-a6b9-fd2c3a6bec65> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/27115c01-5bbb-42a9-a6b9-fd2c3a6bec65> a person:Person.
           <http://data.lblod.info/id/personen/27115c01-5bbb-42a9-a6b9-fd2c3a6bec65> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/27115c01-5bbb-42a9-a6b9-fd2c3a6bec65> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jeannine".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/27115c01-5bbb-42a9-a6b9-fd2c3a6bec65> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/3ec55a527c837077880a378bff592df2eaaba92afa83d64bd102610f07049e57> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3ec55a527c837077880a378bff592df2eaaba92afa83d64bd102610f07049e57> a person:Person.
           <http://data.lblod.info/id/personen/3ec55a527c837077880a378bff592df2eaaba92afa83d64bd102610f07049e57> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3ec55a527c837077880a378bff592df2eaaba92afa83d64bd102610f07049e57> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jeff".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3ec55a527c837077880a378bff592df2eaaba92afa83d64bd102610f07049e57> [] [].
          }
        }
     # finished voornamen-update-666-2490de85e718ffa3e23344f4cd674bd5d9f40252833c8af6fb7fa3b82f44b008 at 2018-12-27T15:07:09+00:00