# started voornamen-update-16901-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:17+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/c50d434e-9022-476a-a323-01af66f0e041> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c50d434e-9022-476a-a323-01af66f0e041> a person:Person.
           <http://data.lblod.info/id/personen/c50d434e-9022-476a-a323-01af66f0e041> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c50d434e-9022-476a-a323-01af66f0e041> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Tom".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c50d434e-9022-476a-a323-01af66f0e041> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e4d6cd51be263b653d2dabb2de73eddc2eee6c593585e6ee0844973245cba39e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e4d6cd51be263b653d2dabb2de73eddc2eee6c593585e6ee0844973245cba39e> a person:Person.
           <http://data.lblod.info/id/personen/e4d6cd51be263b653d2dabb2de73eddc2eee6c593585e6ee0844973245cba39e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e4d6cd51be263b653d2dabb2de73eddc2eee6c593585e6ee0844973245cba39e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Vera".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e4d6cd51be263b653d2dabb2de73eddc2eee6c593585e6ee0844973245cba39e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/b1435a97-7eb5-401b-9b73-77fa0b6568fe> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b1435a97-7eb5-401b-9b73-77fa0b6568fe> a person:Person.
           <http://data.lblod.info/id/personen/b1435a97-7eb5-401b-9b73-77fa0b6568fe> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b1435a97-7eb5-401b-9b73-77fa0b6568fe> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ronny".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b1435a97-7eb5-401b-9b73-77fa0b6568fe> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/0efd3cb058f417d84f3e2ac96792bbb7388f7c28199565a0ee17167f01bd37f1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0efd3cb058f417d84f3e2ac96792bbb7388f7c28199565a0ee17167f01bd37f1> a person:Person.
           <http://data.lblod.info/id/personen/0efd3cb058f417d84f3e2ac96792bbb7388f7c28199565a0ee17167f01bd37f1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0efd3cb058f417d84f3e2ac96792bbb7388f7c28199565a0ee17167f01bd37f1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jacqueline".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0efd3cb058f417d84f3e2ac96792bbb7388f7c28199565a0ee17167f01bd37f1> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/7f44d6cb76dafeb8edfd33b87a8e33c8d129d80eac42d5b20ccc2bb036413798> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7f44d6cb76dafeb8edfd33b87a8e33c8d129d80eac42d5b20ccc2bb036413798> a person:Person.
           <http://data.lblod.info/id/personen/7f44d6cb76dafeb8edfd33b87a8e33c8d129d80eac42d5b20ccc2bb036413798> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7f44d6cb76dafeb8edfd33b87a8e33c8d129d80eac42d5b20ccc2bb036413798> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ann".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7f44d6cb76dafeb8edfd33b87a8e33c8d129d80eac42d5b20ccc2bb036413798> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/18cfc09b-e1c1-4177-a8f9-67ba5e2d7ee7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/18cfc09b-e1c1-4177-a8f9-67ba5e2d7ee7> a person:Person.
           <http://data.lblod.info/id/personen/18cfc09b-e1c1-4177-a8f9-67ba5e2d7ee7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/18cfc09b-e1c1-4177-a8f9-67ba5e2d7ee7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Bart".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/18cfc09b-e1c1-4177-a8f9-67ba5e2d7ee7> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/8d6cd481faaabb3794bf8b4a1fcc0a6b2734394b15f39fa319a1b2bba2e9897e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8d6cd481faaabb3794bf8b4a1fcc0a6b2734394b15f39fa319a1b2bba2e9897e> a person:Person.
           <http://data.lblod.info/id/personen/8d6cd481faaabb3794bf8b4a1fcc0a6b2734394b15f39fa319a1b2bba2e9897e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8d6cd481faaabb3794bf8b4a1fcc0a6b2734394b15f39fa319a1b2bba2e9897e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Roos".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8d6cd481faaabb3794bf8b4a1fcc0a6b2734394b15f39fa319a1b2bba2e9897e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/33a8a7a10fb067c40f0b1467b401d29b6fc13cd025de5bbbbed3847104706285> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/33a8a7a10fb067c40f0b1467b401d29b6fc13cd025de5bbbbed3847104706285> a person:Person.
           <http://data.lblod.info/id/personen/33a8a7a10fb067c40f0b1467b401d29b6fc13cd025de5bbbbed3847104706285> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/33a8a7a10fb067c40f0b1467b401d29b6fc13cd025de5bbbbed3847104706285> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Rolle".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/33a8a7a10fb067c40f0b1467b401d29b6fc13cd025de5bbbbed3847104706285> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/6e08b7c8-5209-41a8-9f70-2699d631322d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6e08b7c8-5209-41a8-9f70-2699d631322d> a person:Person.
           <http://data.lblod.info/id/personen/6e08b7c8-5209-41a8-9f70-2699d631322d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6e08b7c8-5209-41a8-9f70-2699d631322d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Martine".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6e08b7c8-5209-41a8-9f70-2699d631322d> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/6b1a07b6670a27bf860e161529519e74a7749fb66707b4d00e57001dafd5d0a7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6b1a07b6670a27bf860e161529519e74a7749fb66707b4d00e57001dafd5d0a7> a person:Person.
           <http://data.lblod.info/id/personen/6b1a07b6670a27bf860e161529519e74a7749fb66707b4d00e57001dafd5d0a7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6b1a07b6670a27bf860e161529519e74a7749fb66707b4d00e57001dafd5d0a7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ignace".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6b1a07b6670a27bf860e161529519e74a7749fb66707b4d00e57001dafd5d0a7> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/6127ba49a2e4dc3461c11baf90c4c01b91acc607464532317cd153af6aa746f9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6127ba49a2e4dc3461c11baf90c4c01b91acc607464532317cd153af6aa746f9> a person:Person.
           <http://data.lblod.info/id/personen/6127ba49a2e4dc3461c11baf90c4c01b91acc607464532317cd153af6aa746f9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6127ba49a2e4dc3461c11baf90c4c01b91acc607464532317cd153af6aa746f9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Annette".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6127ba49a2e4dc3461c11baf90c4c01b91acc607464532317cd153af6aa746f9> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/098644da796434683ea54ec47e5c358c518d7d092e67c962f9e4ecc932a6a9e6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/098644da796434683ea54ec47e5c358c518d7d092e67c962f9e4ecc932a6a9e6> a person:Person.
           <http://data.lblod.info/id/personen/098644da796434683ea54ec47e5c358c518d7d092e67c962f9e4ecc932a6a9e6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/098644da796434683ea54ec47e5c358c518d7d092e67c962f9e4ecc932a6a9e6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jaklien".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/098644da796434683ea54ec47e5c358c518d7d092e67c962f9e4ecc932a6a9e6> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ce45c19b-1e12-4a18-a24f-f57cd288fa10> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ce45c19b-1e12-4a18-a24f-f57cd288fa10> a person:Person.
           <http://data.lblod.info/id/personen/ce45c19b-1e12-4a18-a24f-f57cd288fa10> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ce45c19b-1e12-4a18-a24f-f57cd288fa10> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Yvan".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ce45c19b-1e12-4a18-a24f-f57cd288fa10> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ee25b399acb8284e5a08313c4439b79538c627a6d52ffc313ccd11feaedea5bf> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ee25b399acb8284e5a08313c4439b79538c627a6d52ffc313ccd11feaedea5bf> a person:Person.
           <http://data.lblod.info/id/personen/ee25b399acb8284e5a08313c4439b79538c627a6d52ffc313ccd11feaedea5bf> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ee25b399acb8284e5a08313c4439b79538c627a6d52ffc313ccd11feaedea5bf> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jan-Klaas".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ee25b399acb8284e5a08313c4439b79538c627a6d52ffc313ccd11feaedea5bf> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/a025c98a-4cc2-47f7-b1ad-a851d6421e17> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a025c98a-4cc2-47f7-b1ad-a851d6421e17> a person:Person.
           <http://data.lblod.info/id/personen/a025c98a-4cc2-47f7-b1ad-a851d6421e17> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a025c98a-4cc2-47f7-b1ad-a851d6421e17> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Joseph".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a025c98a-4cc2-47f7-b1ad-a851d6421e17> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/4ca6dfcbc1108ebc6535fd0dada3449748f65629c556669f3a752cc1a3005b39> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4ca6dfcbc1108ebc6535fd0dada3449748f65629c556669f3a752cc1a3005b39> a person:Person.
           <http://data.lblod.info/id/personen/4ca6dfcbc1108ebc6535fd0dada3449748f65629c556669f3a752cc1a3005b39> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4ca6dfcbc1108ebc6535fd0dada3449748f65629c556669f3a752cc1a3005b39> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Lut".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4ca6dfcbc1108ebc6535fd0dada3449748f65629c556669f3a752cc1a3005b39> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/c40b159f-4038-4c8e-b01b-2c140073c18e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c40b159f-4038-4c8e-b01b-2c140073c18e> a person:Person.
           <http://data.lblod.info/id/personen/c40b159f-4038-4c8e-b01b-2c140073c18e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c40b159f-4038-4c8e-b01b-2c140073c18e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Bianca".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c40b159f-4038-4c8e-b01b-2c140073c18e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/c2812a7a71b1e04f20f19657885ba9b1e1f4f90e02d8060d6274256c71117e41> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c2812a7a71b1e04f20f19657885ba9b1e1f4f90e02d8060d6274256c71117e41> a person:Person.
           <http://data.lblod.info/id/personen/c2812a7a71b1e04f20f19657885ba9b1e1f4f90e02d8060d6274256c71117e41> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c2812a7a71b1e04f20f19657885ba9b1e1f4f90e02d8060d6274256c71117e41> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Kelly".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c2812a7a71b1e04f20f19657885ba9b1e1f4f90e02d8060d6274256c71117e41> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/c24a46fe-3fbb-476f-908d-def249576001> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c24a46fe-3fbb-476f-908d-def249576001> a person:Person.
           <http://data.lblod.info/id/personen/c24a46fe-3fbb-476f-908d-def249576001> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c24a46fe-3fbb-476f-908d-def249576001> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Milan".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c24a46fe-3fbb-476f-908d-def249576001> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/cd62716f5e2a1a0b4a0bcead11ad354198f6460a877c0b68beae1898e3acbb59> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cd62716f5e2a1a0b4a0bcead11ad354198f6460a877c0b68beae1898e3acbb59> a person:Person.
           <http://data.lblod.info/id/personen/cd62716f5e2a1a0b4a0bcead11ad354198f6460a877c0b68beae1898e3acbb59> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cd62716f5e2a1a0b4a0bcead11ad354198f6460a877c0b68beae1898e3acbb59> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Bart".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cd62716f5e2a1a0b4a0bcead11ad354198f6460a877c0b68beae1898e3acbb59> [] [].
          }
        }
     # finished voornamen-update-16901-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:17+00:00