# started voornamen-update-7034-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:05:53+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/a67e40c4-bc01-4aad-8aff-8b3f61e0917b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a67e40c4-bc01-4aad-8aff-8b3f61e0917b> a person:Person.
           <http://data.lblod.info/id/personen/a67e40c4-bc01-4aad-8aff-8b3f61e0917b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a67e40c4-bc01-4aad-8aff-8b3f61e0917b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jos".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a67e40c4-bc01-4aad-8aff-8b3f61e0917b> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/9b70acd77fdb1ca8d5002f8d353986ad8bb86a9ed55f79670a9ff6178e5c8867> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9b70acd77fdb1ca8d5002f8d353986ad8bb86a9ed55f79670a9ff6178e5c8867> a person:Person.
           <http://data.lblod.info/id/personen/9b70acd77fdb1ca8d5002f8d353986ad8bb86a9ed55f79670a9ff6178e5c8867> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9b70acd77fdb1ca8d5002f8d353986ad8bb86a9ed55f79670a9ff6178e5c8867> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Greet".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9b70acd77fdb1ca8d5002f8d353986ad8bb86a9ed55f79670a9ff6178e5c8867> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/efc017a36b7d0a32b74d960ff658f59c0c976a299096337ae6e3f166456be2bd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/efc017a36b7d0a32b74d960ff658f59c0c976a299096337ae6e3f166456be2bd> a person:Person.
           <http://data.lblod.info/id/personen/efc017a36b7d0a32b74d960ff658f59c0c976a299096337ae6e3f166456be2bd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/efc017a36b7d0a32b74d960ff658f59c0c976a299096337ae6e3f166456be2bd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ester".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/efc017a36b7d0a32b74d960ff658f59c0c976a299096337ae6e3f166456be2bd> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/c1c7e30fba390faa28db2e7ef2de303d0cfb897699cac54131a5b69e33c2043f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c1c7e30fba390faa28db2e7ef2de303d0cfb897699cac54131a5b69e33c2043f> a person:Person.
           <http://data.lblod.info/id/personen/c1c7e30fba390faa28db2e7ef2de303d0cfb897699cac54131a5b69e33c2043f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c1c7e30fba390faa28db2e7ef2de303d0cfb897699cac54131a5b69e33c2043f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ludo".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c1c7e30fba390faa28db2e7ef2de303d0cfb897699cac54131a5b69e33c2043f> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ea214029a35f53d9659defe21fb70526212332ce479db05dbcf895b9f95e5960> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ea214029a35f53d9659defe21fb70526212332ce479db05dbcf895b9f95e5960> a person:Person.
           <http://data.lblod.info/id/personen/ea214029a35f53d9659defe21fb70526212332ce479db05dbcf895b9f95e5960> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ea214029a35f53d9659defe21fb70526212332ce479db05dbcf895b9f95e5960> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Krishna".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ea214029a35f53d9659defe21fb70526212332ce479db05dbcf895b9f95e5960> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2fa587ae-ad86-4a8b-ac49-8d3202ea923a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2fa587ae-ad86-4a8b-ac49-8d3202ea923a> a person:Person.
           <http://data.lblod.info/id/personen/2fa587ae-ad86-4a8b-ac49-8d3202ea923a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2fa587ae-ad86-4a8b-ac49-8d3202ea923a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Miet".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2fa587ae-ad86-4a8b-ac49-8d3202ea923a> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/b917c906-ed46-45f6-a6af-8e2d78fdbbfb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b917c906-ed46-45f6-a6af-8e2d78fdbbfb> a person:Person.
           <http://data.lblod.info/id/personen/b917c906-ed46-45f6-a6af-8e2d78fdbbfb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b917c906-ed46-45f6-a6af-8e2d78fdbbfb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Stefan".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b917c906-ed46-45f6-a6af-8e2d78fdbbfb> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/fe56490b-9cec-43e1-bb40-960c4e3dfbde> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/fe56490b-9cec-43e1-bb40-960c4e3dfbde> a person:Person.
           <http://data.lblod.info/id/personen/fe56490b-9cec-43e1-bb40-960c4e3dfbde> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/fe56490b-9cec-43e1-bb40-960c4e3dfbde> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Luc".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/fe56490b-9cec-43e1-bb40-960c4e3dfbde> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/04e50ba3-6151-4fce-aec9-4c7cecdac011> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/04e50ba3-6151-4fce-aec9-4c7cecdac011> a person:Person.
           <http://data.lblod.info/id/personen/04e50ba3-6151-4fce-aec9-4c7cecdac011> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/04e50ba3-6151-4fce-aec9-4c7cecdac011> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Stefan".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/04e50ba3-6151-4fce-aec9-4c7cecdac011> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/37fd5c45-633b-43c6-9a78-fc5df52d4aad> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/37fd5c45-633b-43c6-9a78-fc5df52d4aad> a person:Person.
           <http://data.lblod.info/id/personen/37fd5c45-633b-43c6-9a78-fc5df52d4aad> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/37fd5c45-633b-43c6-9a78-fc5df52d4aad> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "John".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/37fd5c45-633b-43c6-9a78-fc5df52d4aad> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/8e6b9cd7-fb0f-4699-81f6-2cf514cba767> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8e6b9cd7-fb0f-4699-81f6-2cf514cba767> a person:Person.
           <http://data.lblod.info/id/personen/8e6b9cd7-fb0f-4699-81f6-2cf514cba767> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8e6b9cd7-fb0f-4699-81f6-2cf514cba767> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jan".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8e6b9cd7-fb0f-4699-81f6-2cf514cba767> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/5c0b8809-2321-4947-8606-00d8f6189747> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5c0b8809-2321-4947-8606-00d8f6189747> a person:Person.
           <http://data.lblod.info/id/personen/5c0b8809-2321-4947-8606-00d8f6189747> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5c0b8809-2321-4947-8606-00d8f6189747> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Nancy".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5c0b8809-2321-4947-8606-00d8f6189747> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/07a32350-815b-4b27-82d1-896f10293671> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/07a32350-815b-4b27-82d1-896f10293671> a person:Person.
           <http://data.lblod.info/id/personen/07a32350-815b-4b27-82d1-896f10293671> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/07a32350-815b-4b27-82d1-896f10293671> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Patricia".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/07a32350-815b-4b27-82d1-896f10293671> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/dbc67972874db86a954e68baa6f173700fd2840cea0f1bf97d799a9b8362c93b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/dbc67972874db86a954e68baa6f173700fd2840cea0f1bf97d799a9b8362c93b> a person:Person.
           <http://data.lblod.info/id/personen/dbc67972874db86a954e68baa6f173700fd2840cea0f1bf97d799a9b8362c93b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/dbc67972874db86a954e68baa6f173700fd2840cea0f1bf97d799a9b8362c93b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jef".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/dbc67972874db86a954e68baa6f173700fd2840cea0f1bf97d799a9b8362c93b> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2eb9b7234923d1a1e97755c5832c6732af68a085e8d225792498bbba4daa60df> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2eb9b7234923d1a1e97755c5832c6732af68a085e8d225792498bbba4daa60df> a person:Person.
           <http://data.lblod.info/id/personen/2eb9b7234923d1a1e97755c5832c6732af68a085e8d225792498bbba4daa60df> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2eb9b7234923d1a1e97755c5832c6732af68a085e8d225792498bbba4daa60df> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "MAARTEN".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2eb9b7234923d1a1e97755c5832c6732af68a085e8d225792498bbba4daa60df> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/d8d145c13fa42b6e6cd8c48a0a3bf70722f25892677230d591f975cd4e03b0c2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d8d145c13fa42b6e6cd8c48a0a3bf70722f25892677230d591f975cd4e03b0c2> a person:Person.
           <http://data.lblod.info/id/personen/d8d145c13fa42b6e6cd8c48a0a3bf70722f25892677230d591f975cd4e03b0c2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d8d145c13fa42b6e6cd8c48a0a3bf70722f25892677230d591f975cd4e03b0c2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "ELS".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d8d145c13fa42b6e6cd8c48a0a3bf70722f25892677230d591f975cd4e03b0c2> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2e6c6329-88e5-46f9-bf16-6a1d3719830c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2e6c6329-88e5-46f9-bf16-6a1d3719830c> a person:Person.
           <http://data.lblod.info/id/personen/2e6c6329-88e5-46f9-bf16-6a1d3719830c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2e6c6329-88e5-46f9-bf16-6a1d3719830c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "GORDANA".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2e6c6329-88e5-46f9-bf16-6a1d3719830c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/1c6e9ca6-cad6-468d-80c8-7afca169dc64> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1c6e9ca6-cad6-468d-80c8-7afca169dc64> a person:Person.
           <http://data.lblod.info/id/personen/1c6e9ca6-cad6-468d-80c8-7afca169dc64> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1c6e9ca6-cad6-468d-80c8-7afca169dc64> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "LUDWIG".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1c6e9ca6-cad6-468d-80c8-7afca169dc64> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/77246dea-dbfd-434c-ab9a-c80949b21158> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/77246dea-dbfd-434c-ab9a-c80949b21158> a person:Person.
           <http://data.lblod.info/id/personen/77246dea-dbfd-434c-ab9a-c80949b21158> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/77246dea-dbfd-434c-ab9a-c80949b21158> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "SANDRA".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/77246dea-dbfd-434c-ab9a-c80949b21158> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/6d1308f4-1806-4a82-b2d8-a08417744786> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6d1308f4-1806-4a82-b2d8-a08417744786> a person:Person.
           <http://data.lblod.info/id/personen/6d1308f4-1806-4a82-b2d8-a08417744786> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6d1308f4-1806-4a82-b2d8-a08417744786> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "DIRK".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6d1308f4-1806-4a82-b2d8-a08417744786> [] [].
          }
        }
     # finished voornamen-update-7034-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:05:53+00:00