# started voornamen-update-12185-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:05+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/797c48f9157f8dbe98dae70b5ed6d8fea967a164504b37e30c71779da577828f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/797c48f9157f8dbe98dae70b5ed6d8fea967a164504b37e30c71779da577828f> a person:Person.
           <http://data.lblod.info/id/personen/797c48f9157f8dbe98dae70b5ed6d8fea967a164504b37e30c71779da577828f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/797c48f9157f8dbe98dae70b5ed6d8fea967a164504b37e30c71779da577828f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jos".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/797c48f9157f8dbe98dae70b5ed6d8fea967a164504b37e30c71779da577828f> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/8fcd5caa4cee80ec10ab69887d7db2508dc3f6c4de9bf9c682727be94e4207bc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8fcd5caa4cee80ec10ab69887d7db2508dc3f6c4de9bf9c682727be94e4207bc> a person:Person.
           <http://data.lblod.info/id/personen/8fcd5caa4cee80ec10ab69887d7db2508dc3f6c4de9bf9c682727be94e4207bc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8fcd5caa4cee80ec10ab69887d7db2508dc3f6c4de9bf9c682727be94e4207bc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Monique".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8fcd5caa4cee80ec10ab69887d7db2508dc3f6c4de9bf9c682727be94e4207bc> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/a4496ff2-e728-4753-9d42-355e098510d1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a4496ff2-e728-4753-9d42-355e098510d1> a person:Person.
           <http://data.lblod.info/id/personen/a4496ff2-e728-4753-9d42-355e098510d1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a4496ff2-e728-4753-9d42-355e098510d1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Klaas".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a4496ff2-e728-4753-9d42-355e098510d1> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/15a3625d-159e-4083-bef7-c0878b8d5a6b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/15a3625d-159e-4083-bef7-c0878b8d5a6b> a person:Person.
           <http://data.lblod.info/id/personen/15a3625d-159e-4083-bef7-c0878b8d5a6b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/15a3625d-159e-4083-bef7-c0878b8d5a6b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Nena".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/15a3625d-159e-4083-bef7-c0878b8d5a6b> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/0475d97a11e02898218934f88159c7d1c1547919482c6458a5a0263565b3e222> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0475d97a11e02898218934f88159c7d1c1547919482c6458a5a0263565b3e222> a person:Person.
           <http://data.lblod.info/id/personen/0475d97a11e02898218934f88159c7d1c1547919482c6458a5a0263565b3e222> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0475d97a11e02898218934f88159c7d1c1547919482c6458a5a0263565b3e222> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Patrick".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0475d97a11e02898218934f88159c7d1c1547919482c6458a5a0263565b3e222> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e8fb429d905186cfc6f41f333a863bbd8a561889d252f1db5c71abae93ec8f93> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e8fb429d905186cfc6f41f333a863bbd8a561889d252f1db5c71abae93ec8f93> a person:Person.
           <http://data.lblod.info/id/personen/e8fb429d905186cfc6f41f333a863bbd8a561889d252f1db5c71abae93ec8f93> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e8fb429d905186cfc6f41f333a863bbd8a561889d252f1db5c71abae93ec8f93> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Sandra".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e8fb429d905186cfc6f41f333a863bbd8a561889d252f1db5c71abae93ec8f93> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/51118de353e9c85505395cf4d00c718eb840c646aedc361be4851c73658f6700> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/51118de353e9c85505395cf4d00c718eb840c646aedc361be4851c73658f6700> a person:Person.
           <http://data.lblod.info/id/personen/51118de353e9c85505395cf4d00c718eb840c646aedc361be4851c73658f6700> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/51118de353e9c85505395cf4d00c718eb840c646aedc361be4851c73658f6700> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Magda".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/51118de353e9c85505395cf4d00c718eb840c646aedc361be4851c73658f6700> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/7355e466-728e-4bd5-840b-1e812c971b95> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7355e466-728e-4bd5-840b-1e812c971b95> a person:Person.
           <http://data.lblod.info/id/personen/7355e466-728e-4bd5-840b-1e812c971b95> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7355e466-728e-4bd5-840b-1e812c971b95> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Dries".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7355e466-728e-4bd5-840b-1e812c971b95> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/9d35bdfb-aed4-42c5-a733-ab4c4fb99cb4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9d35bdfb-aed4-42c5-a733-ab4c4fb99cb4> a person:Person.
           <http://data.lblod.info/id/personen/9d35bdfb-aed4-42c5-a733-ab4c4fb99cb4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9d35bdfb-aed4-42c5-a733-ab4c4fb99cb4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Sandra".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9d35bdfb-aed4-42c5-a733-ab4c4fb99cb4> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/9d038d3c-e5d1-4204-9981-9da6ecfbef4f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9d038d3c-e5d1-4204-9981-9da6ecfbef4f> a person:Person.
           <http://data.lblod.info/id/personen/9d038d3c-e5d1-4204-9981-9da6ecfbef4f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9d038d3c-e5d1-4204-9981-9da6ecfbef4f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jeroen".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9d038d3c-e5d1-4204-9981-9da6ecfbef4f> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/0033fced-0617-4ec0-93db-72cddb3d4339> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0033fced-0617-4ec0-93db-72cddb3d4339> a person:Person.
           <http://data.lblod.info/id/personen/0033fced-0617-4ec0-93db-72cddb3d4339> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0033fced-0617-4ec0-93db-72cddb3d4339> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Myrtila".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0033fced-0617-4ec0-93db-72cddb3d4339> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/331beb0a-4136-4925-9040-e9fe643b7e3a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/331beb0a-4136-4925-9040-e9fe643b7e3a> a person:Person.
           <http://data.lblod.info/id/personen/331beb0a-4136-4925-9040-e9fe643b7e3a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/331beb0a-4136-4925-9040-e9fe643b7e3a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Joris".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/331beb0a-4136-4925-9040-e9fe643b7e3a> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/197f1f86-e6b9-4f05-a1d2-b7d6ff92d7eb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/197f1f86-e6b9-4f05-a1d2-b7d6ff92d7eb> a person:Person.
           <http://data.lblod.info/id/personen/197f1f86-e6b9-4f05-a1d2-b7d6ff92d7eb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/197f1f86-e6b9-4f05-a1d2-b7d6ff92d7eb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Angela".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/197f1f86-e6b9-4f05-a1d2-b7d6ff92d7eb> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/543166da-3fc7-493c-b9a6-091fde6e98c2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/543166da-3fc7-493c-b9a6-091fde6e98c2> a person:Person.
           <http://data.lblod.info/id/personen/543166da-3fc7-493c-b9a6-091fde6e98c2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/543166da-3fc7-493c-b9a6-091fde6e98c2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Johan".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/543166da-3fc7-493c-b9a6-091fde6e98c2> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/7b33cfd5-0613-40e6-9d9a-5584e79cb5cb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7b33cfd5-0613-40e6-9d9a-5584e79cb5cb> a person:Person.
           <http://data.lblod.info/id/personen/7b33cfd5-0613-40e6-9d9a-5584e79cb5cb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7b33cfd5-0613-40e6-9d9a-5584e79cb5cb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Joske".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7b33cfd5-0613-40e6-9d9a-5584e79cb5cb> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/cd1d3983ce353f8714f0363fdf44c27274be0eaac6a5f536ca72b4ca3f47416c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cd1d3983ce353f8714f0363fdf44c27274be0eaac6a5f536ca72b4ca3f47416c> a person:Person.
           <http://data.lblod.info/id/personen/cd1d3983ce353f8714f0363fdf44c27274be0eaac6a5f536ca72b4ca3f47416c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cd1d3983ce353f8714f0363fdf44c27274be0eaac6a5f536ca72b4ca3f47416c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Rafael".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cd1d3983ce353f8714f0363fdf44c27274be0eaac6a5f536ca72b4ca3f47416c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/58e02e74-dbc4-4c1a-8ab4-939ef33602c6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/58e02e74-dbc4-4c1a-8ab4-939ef33602c6> a person:Person.
           <http://data.lblod.info/id/personen/58e02e74-dbc4-4c1a-8ab4-939ef33602c6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/58e02e74-dbc4-4c1a-8ab4-939ef33602c6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Chantal".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/58e02e74-dbc4-4c1a-8ab4-939ef33602c6> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2e44ed6a-ded3-491e-ab33-5abaf35887ae> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2e44ed6a-ded3-491e-ab33-5abaf35887ae> a person:Person.
           <http://data.lblod.info/id/personen/2e44ed6a-ded3-491e-ab33-5abaf35887ae> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2e44ed6a-ded3-491e-ab33-5abaf35887ae> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Miguel".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2e44ed6a-ded3-491e-ab33-5abaf35887ae> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/79e11bc69bb48916381c5ff8529eca4357d35562020970076999c1b4487df885> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/79e11bc69bb48916381c5ff8529eca4357d35562020970076999c1b4487df885> a person:Person.
           <http://data.lblod.info/id/personen/79e11bc69bb48916381c5ff8529eca4357d35562020970076999c1b4487df885> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/79e11bc69bb48916381c5ff8529eca4357d35562020970076999c1b4487df885> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Wim".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/79e11bc69bb48916381c5ff8529eca4357d35562020970076999c1b4487df885> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/d34d657331eef848d41732c99b5b8ca73e0d5fe42c01804db9ebff7ea03b3a03> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d34d657331eef848d41732c99b5b8ca73e0d5fe42c01804db9ebff7ea03b3a03> a person:Person.
           <http://data.lblod.info/id/personen/d34d657331eef848d41732c99b5b8ca73e0d5fe42c01804db9ebff7ea03b3a03> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d34d657331eef848d41732c99b5b8ca73e0d5fe42c01804db9ebff7ea03b3a03> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Barbara".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d34d657331eef848d41732c99b5b8ca73e0d5fe42c01804db9ebff7ea03b3a03> [] [].
          }
        }
     # finished voornamen-update-12185-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:05+00:00