# started voornamen-update-503-2490de85e718ffa3e23344f4cd674bd5d9f40252833c8af6fb7fa3b82f44b008 at 2018-12-27T15:07:09+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/5734dc86b4a5a1a416e3c5ed827d71cb874cda81ab1e48c3831e0dd156faf651> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5734dc86b4a5a1a416e3c5ed827d71cb874cda81ab1e48c3831e0dd156faf651> a person:Person.
           <http://data.lblod.info/id/personen/5734dc86b4a5a1a416e3c5ed827d71cb874cda81ab1e48c3831e0dd156faf651> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5734dc86b4a5a1a416e3c5ed827d71cb874cda81ab1e48c3831e0dd156faf651> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jean".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5734dc86b4a5a1a416e3c5ed827d71cb874cda81ab1e48c3831e0dd156faf651> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/43867093-7a21-4be5-848c-dfbfa542af6f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/43867093-7a21-4be5-848c-dfbfa542af6f> a person:Person.
           <http://data.lblod.info/id/personen/43867093-7a21-4be5-848c-dfbfa542af6f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/43867093-7a21-4be5-848c-dfbfa542af6f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Herman".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/43867093-7a21-4be5-848c-dfbfa542af6f> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/d6017817-8f26-4032-aec2-6b26d2e1b0c4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d6017817-8f26-4032-aec2-6b26d2e1b0c4> a person:Person.
           <http://data.lblod.info/id/personen/d6017817-8f26-4032-aec2-6b26d2e1b0c4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d6017817-8f26-4032-aec2-6b26d2e1b0c4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Caro".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d6017817-8f26-4032-aec2-6b26d2e1b0c4> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f549bd41-58d6-4709-a6a2-bac0fde11ca5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f549bd41-58d6-4709-a6a2-bac0fde11ca5> a person:Person.
           <http://data.lblod.info/id/personen/f549bd41-58d6-4709-a6a2-bac0fde11ca5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f549bd41-58d6-4709-a6a2-bac0fde11ca5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Raymond".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f549bd41-58d6-4709-a6a2-bac0fde11ca5> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/825cc368-51a4-403b-96cb-a003dc27e69e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/825cc368-51a4-403b-96cb-a003dc27e69e> a person:Person.
           <http://data.lblod.info/id/personen/825cc368-51a4-403b-96cb-a003dc27e69e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/825cc368-51a4-403b-96cb-a003dc27e69e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Hélène".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/825cc368-51a4-403b-96cb-a003dc27e69e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/bf5b7dff-435e-462e-bd2f-10707847cbbb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bf5b7dff-435e-462e-bd2f-10707847cbbb> a person:Person.
           <http://data.lblod.info/id/personen/bf5b7dff-435e-462e-bd2f-10707847cbbb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bf5b7dff-435e-462e-bd2f-10707847cbbb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Kwame".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bf5b7dff-435e-462e-bd2f-10707847cbbb> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/cab138b6-5706-46ae-a023-fe934d76ccc8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cab138b6-5706-46ae-a023-fe934d76ccc8> a person:Person.
           <http://data.lblod.info/id/personen/cab138b6-5706-46ae-a023-fe934d76ccc8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cab138b6-5706-46ae-a023-fe934d76ccc8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Myriam".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cab138b6-5706-46ae-a023-fe934d76ccc8> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/bfa70647-f301-4850-8d01-6380fb70e136> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bfa70647-f301-4850-8d01-6380fb70e136> a person:Person.
           <http://data.lblod.info/id/personen/bfa70647-f301-4850-8d01-6380fb70e136> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bfa70647-f301-4850-8d01-6380fb70e136> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marcelo".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bfa70647-f301-4850-8d01-6380fb70e136> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/90543756-7bc6-49cc-8b83-5089c8820fe1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/90543756-7bc6-49cc-8b83-5089c8820fe1> a person:Person.
           <http://data.lblod.info/id/personen/90543756-7bc6-49cc-8b83-5089c8820fe1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/90543756-7bc6-49cc-8b83-5089c8820fe1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Eva".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/90543756-7bc6-49cc-8b83-5089c8820fe1> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/7af583cf8c07105be57d2bdc6c063db4e852407db3d40b6e140d2cb8a1852d51> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7af583cf8c07105be57d2bdc6c063db4e852407db3d40b6e140d2cb8a1852d51> a person:Person.
           <http://data.lblod.info/id/personen/7af583cf8c07105be57d2bdc6c063db4e852407db3d40b6e140d2cb8a1852d51> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7af583cf8c07105be57d2bdc6c063db4e852407db3d40b6e140d2cb8a1852d51> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Kris".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7af583cf8c07105be57d2bdc6c063db4e852407db3d40b6e140d2cb8a1852d51> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/79739514-f80f-4b6d-9082-b8d39bab0c49> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/79739514-f80f-4b6d-9082-b8d39bab0c49> a person:Person.
           <http://data.lblod.info/id/personen/79739514-f80f-4b6d-9082-b8d39bab0c49> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/79739514-f80f-4b6d-9082-b8d39bab0c49> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Christel".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/79739514-f80f-4b6d-9082-b8d39bab0c49> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e5b0ef89-4a28-4e3e-b7db-ce946bab1ec8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e5b0ef89-4a28-4e3e-b7db-ce946bab1ec8> a person:Person.
           <http://data.lblod.info/id/personen/e5b0ef89-4a28-4e3e-b7db-ce946bab1ec8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e5b0ef89-4a28-4e3e-b7db-ce946bab1ec8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Wouter".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e5b0ef89-4a28-4e3e-b7db-ce946bab1ec8> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/07c20322-2487-4b0c-97a0-ad248a6073f0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/07c20322-2487-4b0c-97a0-ad248a6073f0> a person:Person.
           <http://data.lblod.info/id/personen/07c20322-2487-4b0c-97a0-ad248a6073f0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/07c20322-2487-4b0c-97a0-ad248a6073f0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Betty".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/07c20322-2487-4b0c-97a0-ad248a6073f0> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ccc017a2484c2d6fbec4f6688239c621f6dfe59f87f27acc041f484cbd907ca0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ccc017a2484c2d6fbec4f6688239c621f6dfe59f87f27acc041f484cbd907ca0> a person:Person.
           <http://data.lblod.info/id/personen/ccc017a2484c2d6fbec4f6688239c621f6dfe59f87f27acc041f484cbd907ca0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ccc017a2484c2d6fbec4f6688239c621f6dfe59f87f27acc041f484cbd907ca0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ludo".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ccc017a2484c2d6fbec4f6688239c621f6dfe59f87f27acc041f484cbd907ca0> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/7756a29b-cf5f-4fc3-8d3c-d161e37ba116> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7756a29b-cf5f-4fc3-8d3c-d161e37ba116> a person:Person.
           <http://data.lblod.info/id/personen/7756a29b-cf5f-4fc3-8d3c-d161e37ba116> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7756a29b-cf5f-4fc3-8d3c-d161e37ba116> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Kevin".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7756a29b-cf5f-4fc3-8d3c-d161e37ba116> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/7f61daeb4e06ed4fe14a5e06396ad57f18f05a1ee72e66ec97a8c4ba8f8fef44> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7f61daeb4e06ed4fe14a5e06396ad57f18f05a1ee72e66ec97a8c4ba8f8fef44> a person:Person.
           <http://data.lblod.info/id/personen/7f61daeb4e06ed4fe14a5e06396ad57f18f05a1ee72e66ec97a8c4ba8f8fef44> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7f61daeb4e06ed4fe14a5e06396ad57f18f05a1ee72e66ec97a8c4ba8f8fef44> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Annie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7f61daeb4e06ed4fe14a5e06396ad57f18f05a1ee72e66ec97a8c4ba8f8fef44> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/508efa50-6adf-452d-948f-bc7ff179278d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/508efa50-6adf-452d-948f-bc7ff179278d> a person:Person.
           <http://data.lblod.info/id/personen/508efa50-6adf-452d-948f-bc7ff179278d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/508efa50-6adf-452d-948f-bc7ff179278d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Vera".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/508efa50-6adf-452d-948f-bc7ff179278d> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2bbe747603a8b18102f7e2455d515a6596a58d67b46d8cec32dfd01675835871> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2bbe747603a8b18102f7e2455d515a6596a58d67b46d8cec32dfd01675835871> a person:Person.
           <http://data.lblod.info/id/personen/2bbe747603a8b18102f7e2455d515a6596a58d67b46d8cec32dfd01675835871> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2bbe747603a8b18102f7e2455d515a6596a58d67b46d8cec32dfd01675835871> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Romain".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2bbe747603a8b18102f7e2455d515a6596a58d67b46d8cec32dfd01675835871> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/81b0e61b47adcda56c464015d483fcc43ea4c54546e32a2e80298e67590b13e4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/81b0e61b47adcda56c464015d483fcc43ea4c54546e32a2e80298e67590b13e4> a person:Person.
           <http://data.lblod.info/id/personen/81b0e61b47adcda56c464015d483fcc43ea4c54546e32a2e80298e67590b13e4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/81b0e61b47adcda56c464015d483fcc43ea4c54546e32a2e80298e67590b13e4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Mieke".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/81b0e61b47adcda56c464015d483fcc43ea4c54546e32a2e80298e67590b13e4> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/a2b864cb82e6485ff67bf4bbc24729b8082e9901176bada16a33e65d66f94167> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a2b864cb82e6485ff67bf4bbc24729b8082e9901176bada16a33e65d66f94167> a person:Person.
           <http://data.lblod.info/id/personen/a2b864cb82e6485ff67bf4bbc24729b8082e9901176bada16a33e65d66f94167> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a2b864cb82e6485ff67bf4bbc24729b8082e9901176bada16a33e65d66f94167> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Lily".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a2b864cb82e6485ff67bf4bbc24729b8082e9901176bada16a33e65d66f94167> [] [].
          }
        }
     # finished voornamen-update-503-2490de85e718ffa3e23344f4cd674bd5d9f40252833c8af6fb7fa3b82f44b008 at 2018-12-27T15:07:09+00:00