# started voornamen-update-26017-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:40+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/c78916e1-7a7b-4285-93a8-bb2df8d85152> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c78916e1-7a7b-4285-93a8-bb2df8d85152> a person:Person.
           <http://data.lblod.info/id/personen/c78916e1-7a7b-4285-93a8-bb2df8d85152> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c78916e1-7a7b-4285-93a8-bb2df8d85152> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Diane".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c78916e1-7a7b-4285-93a8-bb2df8d85152> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/048817a6bfdf6d9233352f9b171760584e5e4aedeb8549ee67a44a48fbd05d67> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/048817a6bfdf6d9233352f9b171760584e5e4aedeb8549ee67a44a48fbd05d67> a person:Person.
           <http://data.lblod.info/id/personen/048817a6bfdf6d9233352f9b171760584e5e4aedeb8549ee67a44a48fbd05d67> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/048817a6bfdf6d9233352f9b171760584e5e4aedeb8549ee67a44a48fbd05d67> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Patrick".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/048817a6bfdf6d9233352f9b171760584e5e4aedeb8549ee67a44a48fbd05d67> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/7ca6e591-96ed-4487-b0cc-793a94c9e8a5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7ca6e591-96ed-4487-b0cc-793a94c9e8a5> a person:Person.
           <http://data.lblod.info/id/personen/7ca6e591-96ed-4487-b0cc-793a94c9e8a5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7ca6e591-96ed-4487-b0cc-793a94c9e8a5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Vicky".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7ca6e591-96ed-4487-b0cc-793a94c9e8a5> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/26f50fd9-c8da-4cce-8ea8-6af27ccd4b8c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/26f50fd9-c8da-4cce-8ea8-6af27ccd4b8c> a person:Person.
           <http://data.lblod.info/id/personen/26f50fd9-c8da-4cce-8ea8-6af27ccd4b8c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/26f50fd9-c8da-4cce-8ea8-6af27ccd4b8c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Kevin".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/26f50fd9-c8da-4cce-8ea8-6af27ccd4b8c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/873b79c6382ee219b07a8a6d66d6637a9ae8afe5a4ac5b741bdcfe7f3f1cab6f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/873b79c6382ee219b07a8a6d66d6637a9ae8afe5a4ac5b741bdcfe7f3f1cab6f> a person:Person.
           <http://data.lblod.info/id/personen/873b79c6382ee219b07a8a6d66d6637a9ae8afe5a4ac5b741bdcfe7f3f1cab6f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/873b79c6382ee219b07a8a6d66d6637a9ae8afe5a4ac5b741bdcfe7f3f1cab6f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jannine".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/873b79c6382ee219b07a8a6d66d6637a9ae8afe5a4ac5b741bdcfe7f3f1cab6f> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/3b40f8aad2550afa2d985be08d7cb0fb2dbce534d231cb03e60c778524702da6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3b40f8aad2550afa2d985be08d7cb0fb2dbce534d231cb03e60c778524702da6> a person:Person.
           <http://data.lblod.info/id/personen/3b40f8aad2550afa2d985be08d7cb0fb2dbce534d231cb03e60c778524702da6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3b40f8aad2550afa2d985be08d7cb0fb2dbce534d231cb03e60c778524702da6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Christa".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3b40f8aad2550afa2d985be08d7cb0fb2dbce534d231cb03e60c778524702da6> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f04ac1787665c26682ae4e5a24eb1ba1cad4186f07b66f8b1923639fee5ae9d2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f04ac1787665c26682ae4e5a24eb1ba1cad4186f07b66f8b1923639fee5ae9d2> a person:Person.
           <http://data.lblod.info/id/personen/f04ac1787665c26682ae4e5a24eb1ba1cad4186f07b66f8b1923639fee5ae9d2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f04ac1787665c26682ae4e5a24eb1ba1cad4186f07b66f8b1923639fee5ae9d2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Chantal".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f04ac1787665c26682ae4e5a24eb1ba1cad4186f07b66f8b1923639fee5ae9d2> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/bbe94a6bbbc12337c0309ce3b7fadb11c5f39554a741006c5fe7418faa9d2569> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bbe94a6bbbc12337c0309ce3b7fadb11c5f39554a741006c5fe7418faa9d2569> a person:Person.
           <http://data.lblod.info/id/personen/bbe94a6bbbc12337c0309ce3b7fadb11c5f39554a741006c5fe7418faa9d2569> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bbe94a6bbbc12337c0309ce3b7fadb11c5f39554a741006c5fe7418faa9d2569> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Mike".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bbe94a6bbbc12337c0309ce3b7fadb11c5f39554a741006c5fe7418faa9d2569> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/efe933e1-8906-49ed-abb1-02b5a36b7dd2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/efe933e1-8906-49ed-abb1-02b5a36b7dd2> a person:Person.
           <http://data.lblod.info/id/personen/efe933e1-8906-49ed-abb1-02b5a36b7dd2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/efe933e1-8906-49ed-abb1-02b5a36b7dd2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Gunther".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/efe933e1-8906-49ed-abb1-02b5a36b7dd2> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/fd8045ac4fcae3ef8b153bd5c62e2876229822e018ab27a34100b7483dce9932> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/fd8045ac4fcae3ef8b153bd5c62e2876229822e018ab27a34100b7483dce9932> a person:Person.
           <http://data.lblod.info/id/personen/fd8045ac4fcae3ef8b153bd5c62e2876229822e018ab27a34100b7483dce9932> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/fd8045ac4fcae3ef8b153bd5c62e2876229822e018ab27a34100b7483dce9932> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Rita".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/fd8045ac4fcae3ef8b153bd5c62e2876229822e018ab27a34100b7483dce9932> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/4db470238a1417beb9abb6dcef615d11b47dc1c6a67d2c68b93739403132b7c6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4db470238a1417beb9abb6dcef615d11b47dc1c6a67d2c68b93739403132b7c6> a person:Person.
           <http://data.lblod.info/id/personen/4db470238a1417beb9abb6dcef615d11b47dc1c6a67d2c68b93739403132b7c6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4db470238a1417beb9abb6dcef615d11b47dc1c6a67d2c68b93739403132b7c6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Karine".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4db470238a1417beb9abb6dcef615d11b47dc1c6a67d2c68b93739403132b7c6> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/4f14a624-c9cb-4900-8968-9ee112c929e0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4f14a624-c9cb-4900-8968-9ee112c929e0> a person:Person.
           <http://data.lblod.info/id/personen/4f14a624-c9cb-4900-8968-9ee112c929e0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4f14a624-c9cb-4900-8968-9ee112c929e0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Arne".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4f14a624-c9cb-4900-8968-9ee112c929e0> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/09689bb8ca8ef8102ce72c484904a38a0d12aee4250c6a8f85063715fe4e44ac> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/09689bb8ca8ef8102ce72c484904a38a0d12aee4250c6a8f85063715fe4e44ac> a person:Person.
           <http://data.lblod.info/id/personen/09689bb8ca8ef8102ce72c484904a38a0d12aee4250c6a8f85063715fe4e44ac> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/09689bb8ca8ef8102ce72c484904a38a0d12aee4250c6a8f85063715fe4e44ac> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jacques".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/09689bb8ca8ef8102ce72c484904a38a0d12aee4250c6a8f85063715fe4e44ac> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/37a2f3b2-18df-478c-8bbe-2dae0444691c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/37a2f3b2-18df-478c-8bbe-2dae0444691c> a person:Person.
           <http://data.lblod.info/id/personen/37a2f3b2-18df-478c-8bbe-2dae0444691c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/37a2f3b2-18df-478c-8bbe-2dae0444691c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marleen".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/37a2f3b2-18df-478c-8bbe-2dae0444691c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/27176657-8d3f-464c-817f-3b2025f0af9a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/27176657-8d3f-464c-817f-3b2025f0af9a> a person:Person.
           <http://data.lblod.info/id/personen/27176657-8d3f-464c-817f-3b2025f0af9a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/27176657-8d3f-464c-817f-3b2025f0af9a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Helene".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/27176657-8d3f-464c-817f-3b2025f0af9a> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/459721821920f429f3fe9a359452e5c67338ecece0c458529f9409b8bebb9e2f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/459721821920f429f3fe9a359452e5c67338ecece0c458529f9409b8bebb9e2f> a person:Person.
           <http://data.lblod.info/id/personen/459721821920f429f3fe9a359452e5c67338ecece0c458529f9409b8bebb9e2f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/459721821920f429f3fe9a359452e5c67338ecece0c458529f9409b8bebb9e2f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Fons".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/459721821920f429f3fe9a359452e5c67338ecece0c458529f9409b8bebb9e2f> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/d9790f7c-8e31-44b9-b971-998a0c67b4e5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d9790f7c-8e31-44b9-b971-998a0c67b4e5> a person:Person.
           <http://data.lblod.info/id/personen/d9790f7c-8e31-44b9-b971-998a0c67b4e5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d9790f7c-8e31-44b9-b971-998a0c67b4e5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Renaat".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d9790f7c-8e31-44b9-b971-998a0c67b4e5> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/9aa90319-af3d-4ae0-92da-bf286dc50461> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9aa90319-af3d-4ae0-92da-bf286dc50461> a person:Person.
           <http://data.lblod.info/id/personen/9aa90319-af3d-4ae0-92da-bf286dc50461> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9aa90319-af3d-4ae0-92da-bf286dc50461> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Maaike".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9aa90319-af3d-4ae0-92da-bf286dc50461> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/097bfc07-9b82-4207-8ff5-5209982b661a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/097bfc07-9b82-4207-8ff5-5209982b661a> a person:Person.
           <http://data.lblod.info/id/personen/097bfc07-9b82-4207-8ff5-5209982b661a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/097bfc07-9b82-4207-8ff5-5209982b661a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Geert".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/097bfc07-9b82-4207-8ff5-5209982b661a> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/b4ea965dfb502a2a4ef01495c775eb84c2e977442168b3992d095f5ea8b59cb6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b4ea965dfb502a2a4ef01495c775eb84c2e977442168b3992d095f5ea8b59cb6> a person:Person.
           <http://data.lblod.info/id/personen/b4ea965dfb502a2a4ef01495c775eb84c2e977442168b3992d095f5ea8b59cb6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b4ea965dfb502a2a4ef01495c775eb84c2e977442168b3992d095f5ea8b59cb6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Christiane".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b4ea965dfb502a2a4ef01495c775eb84c2e977442168b3992d095f5ea8b59cb6> [] [].
          }
        }
     # finished voornamen-update-26017-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:40+00:00