# started voornamen-update-33899-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:07:00+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/6d0d68fc89968151ce9e5a2792dae6ac6e1a3f830331f6323c392f3c96a22239> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6d0d68fc89968151ce9e5a2792dae6ac6e1a3f830331f6323c392f3c96a22239> a person:Person.
           <http://data.lblod.info/id/personen/6d0d68fc89968151ce9e5a2792dae6ac6e1a3f830331f6323c392f3c96a22239> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6d0d68fc89968151ce9e5a2792dae6ac6e1a3f830331f6323c392f3c96a22239> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marianne".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6d0d68fc89968151ce9e5a2792dae6ac6e1a3f830331f6323c392f3c96a22239> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/7d13f732d0d56bc0caf07c21a259f089a45968df1765848ddf05e253acddac2f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7d13f732d0d56bc0caf07c21a259f089a45968df1765848ddf05e253acddac2f> a person:Person.
           <http://data.lblod.info/id/personen/7d13f732d0d56bc0caf07c21a259f089a45968df1765848ddf05e253acddac2f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7d13f732d0d56bc0caf07c21a259f089a45968df1765848ddf05e253acddac2f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Filip".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7d13f732d0d56bc0caf07c21a259f089a45968df1765848ddf05e253acddac2f> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/086d018c-d670-47d6-8cf9-940b54871859> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/086d018c-d670-47d6-8cf9-940b54871859> a person:Person.
           <http://data.lblod.info/id/personen/086d018c-d670-47d6-8cf9-940b54871859> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/086d018c-d670-47d6-8cf9-940b54871859> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Leo".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/086d018c-d670-47d6-8cf9-940b54871859> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e2c81e8d-1117-41bc-8d5d-40ac62aeea6f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e2c81e8d-1117-41bc-8d5d-40ac62aeea6f> a person:Person.
           <http://data.lblod.info/id/personen/e2c81e8d-1117-41bc-8d5d-40ac62aeea6f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e2c81e8d-1117-41bc-8d5d-40ac62aeea6f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Geertje".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e2c81e8d-1117-41bc-8d5d-40ac62aeea6f> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ae6286e1f0643852dfb978cb68ed3bed6b11334ca3e68da3b217365d762ae919> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ae6286e1f0643852dfb978cb68ed3bed6b11334ca3e68da3b217365d762ae919> a person:Person.
           <http://data.lblod.info/id/personen/ae6286e1f0643852dfb978cb68ed3bed6b11334ca3e68da3b217365d762ae919> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ae6286e1f0643852dfb978cb68ed3bed6b11334ca3e68da3b217365d762ae919> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Bert".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ae6286e1f0643852dfb978cb68ed3bed6b11334ca3e68da3b217365d762ae919> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/b86bfbcf-2694-4a9d-9816-5301bda7a114> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b86bfbcf-2694-4a9d-9816-5301bda7a114> a person:Person.
           <http://data.lblod.info/id/personen/b86bfbcf-2694-4a9d-9816-5301bda7a114> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b86bfbcf-2694-4a9d-9816-5301bda7a114> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Carine".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b86bfbcf-2694-4a9d-9816-5301bda7a114> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/71f3c56525c99704636844dd1e99b0088b5ea83e92a2c17ad8db8767c0320b25> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/71f3c56525c99704636844dd1e99b0088b5ea83e92a2c17ad8db8767c0320b25> a person:Person.
           <http://data.lblod.info/id/personen/71f3c56525c99704636844dd1e99b0088b5ea83e92a2c17ad8db8767c0320b25> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/71f3c56525c99704636844dd1e99b0088b5ea83e92a2c17ad8db8767c0320b25> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Guido".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/71f3c56525c99704636844dd1e99b0088b5ea83e92a2c17ad8db8767c0320b25> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/64a26532087db5afdeb5be9de5992fe61f64ef75d10e465d395608531d88b3a4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/64a26532087db5afdeb5be9de5992fe61f64ef75d10e465d395608531d88b3a4> a person:Person.
           <http://data.lblod.info/id/personen/64a26532087db5afdeb5be9de5992fe61f64ef75d10e465d395608531d88b3a4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/64a26532087db5afdeb5be9de5992fe61f64ef75d10e465d395608531d88b3a4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Lieve".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/64a26532087db5afdeb5be9de5992fe61f64ef75d10e465d395608531d88b3a4> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/54351a2b479ea00615e3266cd6bcd0b0337ee44615a5c0a2ff67274e71256894> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/54351a2b479ea00615e3266cd6bcd0b0337ee44615a5c0a2ff67274e71256894> a person:Person.
           <http://data.lblod.info/id/personen/54351a2b479ea00615e3266cd6bcd0b0337ee44615a5c0a2ff67274e71256894> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/54351a2b479ea00615e3266cd6bcd0b0337ee44615a5c0a2ff67274e71256894> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marcel".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/54351a2b479ea00615e3266cd6bcd0b0337ee44615a5c0a2ff67274e71256894> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/9f6ed863cd2b3f5b965ecdeb2aae4edaaf42f225d5f9fca7cf4434ae4149aa6c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9f6ed863cd2b3f5b965ecdeb2aae4edaaf42f225d5f9fca7cf4434ae4149aa6c> a person:Person.
           <http://data.lblod.info/id/personen/9f6ed863cd2b3f5b965ecdeb2aae4edaaf42f225d5f9fca7cf4434ae4149aa6c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9f6ed863cd2b3f5b965ecdeb2aae4edaaf42f225d5f9fca7cf4434ae4149aa6c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jos".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9f6ed863cd2b3f5b965ecdeb2aae4edaaf42f225d5f9fca7cf4434ae4149aa6c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/58c2c54db64251baa92f75dc09781f7c32f93f9d14c8db2fac0f07965d7b7347> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/58c2c54db64251baa92f75dc09781f7c32f93f9d14c8db2fac0f07965d7b7347> a person:Person.
           <http://data.lblod.info/id/personen/58c2c54db64251baa92f75dc09781f7c32f93f9d14c8db2fac0f07965d7b7347> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/58c2c54db64251baa92f75dc09781f7c32f93f9d14c8db2fac0f07965d7b7347> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Mia".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/58c2c54db64251baa92f75dc09781f7c32f93f9d14c8db2fac0f07965d7b7347> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/0ba9d343-d489-48fd-99b1-adf25d9f3d8e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0ba9d343-d489-48fd-99b1-adf25d9f3d8e> a person:Person.
           <http://data.lblod.info/id/personen/0ba9d343-d489-48fd-99b1-adf25d9f3d8e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0ba9d343-d489-48fd-99b1-adf25d9f3d8e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Luc".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0ba9d343-d489-48fd-99b1-adf25d9f3d8e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/fea21b1e-3a73-4f11-828a-48f76978e656> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/fea21b1e-3a73-4f11-828a-48f76978e656> a person:Person.
           <http://data.lblod.info/id/personen/fea21b1e-3a73-4f11-828a-48f76978e656> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/fea21b1e-3a73-4f11-828a-48f76978e656> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Henri".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/fea21b1e-3a73-4f11-828a-48f76978e656> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/bb29f596-2ca1-4ef2-a7f4-72bb78548d09> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bb29f596-2ca1-4ef2-a7f4-72bb78548d09> a person:Person.
           <http://data.lblod.info/id/personen/bb29f596-2ca1-4ef2-a7f4-72bb78548d09> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bb29f596-2ca1-4ef2-a7f4-72bb78548d09> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Cathy".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bb29f596-2ca1-4ef2-a7f4-72bb78548d09> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/a918ee3b-e0c7-4e5e-a31d-3dcedb9e6386> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a918ee3b-e0c7-4e5e-a31d-3dcedb9e6386> a person:Person.
           <http://data.lblod.info/id/personen/a918ee3b-e0c7-4e5e-a31d-3dcedb9e6386> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a918ee3b-e0c7-4e5e-a31d-3dcedb9e6386> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Tom".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a918ee3b-e0c7-4e5e-a31d-3dcedb9e6386> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/39e36a081dcb36cf399a4a7dedf433eccb11dfbbea79f0ebc90fbf9759b31d68> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/39e36a081dcb36cf399a4a7dedf433eccb11dfbbea79f0ebc90fbf9759b31d68> a person:Person.
           <http://data.lblod.info/id/personen/39e36a081dcb36cf399a4a7dedf433eccb11dfbbea79f0ebc90fbf9759b31d68> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/39e36a081dcb36cf399a4a7dedf433eccb11dfbbea79f0ebc90fbf9759b31d68> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Renate".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/39e36a081dcb36cf399a4a7dedf433eccb11dfbbea79f0ebc90fbf9759b31d68> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2cde093a12dc36c6c45e1d2e21841563a1ef17135b8ed55ebb9419ad4e1c7f83> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2cde093a12dc36c6c45e1d2e21841563a1ef17135b8ed55ebb9419ad4e1c7f83> a person:Person.
           <http://data.lblod.info/id/personen/2cde093a12dc36c6c45e1d2e21841563a1ef17135b8ed55ebb9419ad4e1c7f83> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2cde093a12dc36c6c45e1d2e21841563a1ef17135b8ed55ebb9419ad4e1c7f83> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jeannine".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2cde093a12dc36c6c45e1d2e21841563a1ef17135b8ed55ebb9419ad4e1c7f83> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f6df772f-8259-4826-b314-b2528e073011> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f6df772f-8259-4826-b314-b2528e073011> a person:Person.
           <http://data.lblod.info/id/personen/f6df772f-8259-4826-b314-b2528e073011> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f6df772f-8259-4826-b314-b2528e073011> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marc".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f6df772f-8259-4826-b314-b2528e073011> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f58567003e3ee92832d42196d3d690e63c61e6b19017610a680b7d66749a8096> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f58567003e3ee92832d42196d3d690e63c61e6b19017610a680b7d66749a8096> a person:Person.
           <http://data.lblod.info/id/personen/f58567003e3ee92832d42196d3d690e63c61e6b19017610a680b7d66749a8096> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f58567003e3ee92832d42196d3d690e63c61e6b19017610a680b7d66749a8096> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jos".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f58567003e3ee92832d42196d3d690e63c61e6b19017610a680b7d66749a8096> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/8d3947c8e88afba7e8631e7eb7c32814bb7ea955876a6bd40df0995f5feee907> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8d3947c8e88afba7e8631e7eb7c32814bb7ea955876a6bd40df0995f5feee907> a person:Person.
           <http://data.lblod.info/id/personen/8d3947c8e88afba7e8631e7eb7c32814bb7ea955876a6bd40df0995f5feee907> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8d3947c8e88afba7e8631e7eb7c32814bb7ea955876a6bd40df0995f5feee907> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Nicole".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8d3947c8e88afba7e8631e7eb7c32814bb7ea955876a6bd40df0995f5feee907> [] [].
          }
        }
     # finished voornamen-update-33899-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:07:00+00:00