# started voornamen-update-25900-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:40+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/220b608db4a2e4342e562c523c057fd53004fce64bc8e0285a9e72fa8c67f44e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/220b608db4a2e4342e562c523c057fd53004fce64bc8e0285a9e72fa8c67f44e> a person:Person.
           <http://data.lblod.info/id/personen/220b608db4a2e4342e562c523c057fd53004fce64bc8e0285a9e72fa8c67f44e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/220b608db4a2e4342e562c523c057fd53004fce64bc8e0285a9e72fa8c67f44e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Rita".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/220b608db4a2e4342e562c523c057fd53004fce64bc8e0285a9e72fa8c67f44e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ce08f2a4-d393-4930-9d48-795af4de7cf4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ce08f2a4-d393-4930-9d48-795af4de7cf4> a person:Person.
           <http://data.lblod.info/id/personen/ce08f2a4-d393-4930-9d48-795af4de7cf4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ce08f2a4-d393-4930-9d48-795af4de7cf4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ollie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ce08f2a4-d393-4930-9d48-795af4de7cf4> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/00c9a94d902b8bb6bc36b97e9fafee1047af00a6adcb15c35c9cfd15175db85b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/00c9a94d902b8bb6bc36b97e9fafee1047af00a6adcb15c35c9cfd15175db85b> a person:Person.
           <http://data.lblod.info/id/personen/00c9a94d902b8bb6bc36b97e9fafee1047af00a6adcb15c35c9cfd15175db85b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/00c9a94d902b8bb6bc36b97e9fafee1047af00a6adcb15c35c9cfd15175db85b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Thierry".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/00c9a94d902b8bb6bc36b97e9fafee1047af00a6adcb15c35c9cfd15175db85b> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/45d9dd26b22a70e29e4e3442a547420a36c4fc3e71dfbe7a20c8b6fd28c1a304> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/45d9dd26b22a70e29e4e3442a547420a36c4fc3e71dfbe7a20c8b6fd28c1a304> a person:Person.
           <http://data.lblod.info/id/personen/45d9dd26b22a70e29e4e3442a547420a36c4fc3e71dfbe7a20c8b6fd28c1a304> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/45d9dd26b22a70e29e4e3442a547420a36c4fc3e71dfbe7a20c8b6fd28c1a304> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jempi".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/45d9dd26b22a70e29e4e3442a547420a36c4fc3e71dfbe7a20c8b6fd28c1a304> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2e9cd5d0-5256-4c14-a3d4-01c5eb5f686f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2e9cd5d0-5256-4c14-a3d4-01c5eb5f686f> a person:Person.
           <http://data.lblod.info/id/personen/2e9cd5d0-5256-4c14-a3d4-01c5eb5f686f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2e9cd5d0-5256-4c14-a3d4-01c5eb5f686f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jonna".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2e9cd5d0-5256-4c14-a3d4-01c5eb5f686f> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/6b472323-f173-4d77-8c00-9f913bb16ed2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6b472323-f173-4d77-8c00-9f913bb16ed2> a person:Person.
           <http://data.lblod.info/id/personen/6b472323-f173-4d77-8c00-9f913bb16ed2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6b472323-f173-4d77-8c00-9f913bb16ed2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Mathieu".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6b472323-f173-4d77-8c00-9f913bb16ed2> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/58ed92c2-ab07-4a31-9278-1dee8e59f3b2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/58ed92c2-ab07-4a31-9278-1dee8e59f3b2> a person:Person.
           <http://data.lblod.info/id/personen/58ed92c2-ab07-4a31-9278-1dee8e59f3b2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/58ed92c2-ab07-4a31-9278-1dee8e59f3b2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Wendy".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/58ed92c2-ab07-4a31-9278-1dee8e59f3b2> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/8290960f-fdbd-4d75-b9c8-8dea60a14a9d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8290960f-fdbd-4d75-b9c8-8dea60a14a9d> a person:Person.
           <http://data.lblod.info/id/personen/8290960f-fdbd-4d75-b9c8-8dea60a14a9d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8290960f-fdbd-4d75-b9c8-8dea60a14a9d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Kristine".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8290960f-fdbd-4d75-b9c8-8dea60a14a9d> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/96b942061d1200ed6b56376706947aee6524a400bd3254eec11354c2175f80c0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/96b942061d1200ed6b56376706947aee6524a400bd3254eec11354c2175f80c0> a person:Person.
           <http://data.lblod.info/id/personen/96b942061d1200ed6b56376706947aee6524a400bd3254eec11354c2175f80c0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/96b942061d1200ed6b56376706947aee6524a400bd3254eec11354c2175f80c0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Patsy".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/96b942061d1200ed6b56376706947aee6524a400bd3254eec11354c2175f80c0> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/503fac8a-fcd6-49cc-82aa-1435060829f8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/503fac8a-fcd6-49cc-82aa-1435060829f8> a person:Person.
           <http://data.lblod.info/id/personen/503fac8a-fcd6-49cc-82aa-1435060829f8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/503fac8a-fcd6-49cc-82aa-1435060829f8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Stijn".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/503fac8a-fcd6-49cc-82aa-1435060829f8> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/99cfd191-b9ad-49d7-8229-9981f84e73e5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/99cfd191-b9ad-49d7-8229-9981f84e73e5> a person:Person.
           <http://data.lblod.info/id/personen/99cfd191-b9ad-49d7-8229-9981f84e73e5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/99cfd191-b9ad-49d7-8229-9981f84e73e5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Eline".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/99cfd191-b9ad-49d7-8229-9981f84e73e5> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e20ca9b8-6a8d-4ccc-a47f-9601d0ddfaf0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e20ca9b8-6a8d-4ccc-a47f-9601d0ddfaf0> a person:Person.
           <http://data.lblod.info/id/personen/e20ca9b8-6a8d-4ccc-a47f-9601d0ddfaf0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e20ca9b8-6a8d-4ccc-a47f-9601d0ddfaf0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Noria".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e20ca9b8-6a8d-4ccc-a47f-9601d0ddfaf0> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f59159c2-a2fc-4ea6-bb38-110af1486387> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f59159c2-a2fc-4ea6-bb38-110af1486387> a person:Person.
           <http://data.lblod.info/id/personen/f59159c2-a2fc-4ea6-bb38-110af1486387> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f59159c2-a2fc-4ea6-bb38-110af1486387> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Monique".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f59159c2-a2fc-4ea6-bb38-110af1486387> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/1fd4da34-0ba6-4aa2-94dc-1685d305bd46> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1fd4da34-0ba6-4aa2-94dc-1685d305bd46> a person:Person.
           <http://data.lblod.info/id/personen/1fd4da34-0ba6-4aa2-94dc-1685d305bd46> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1fd4da34-0ba6-4aa2-94dc-1685d305bd46> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Kristof".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1fd4da34-0ba6-4aa2-94dc-1685d305bd46> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/03d98f3d-f8a4-477f-96ae-1dc7f39f5601> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/03d98f3d-f8a4-477f-96ae-1dc7f39f5601> a person:Person.
           <http://data.lblod.info/id/personen/03d98f3d-f8a4-477f-96ae-1dc7f39f5601> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/03d98f3d-f8a4-477f-96ae-1dc7f39f5601> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Brigitte".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/03d98f3d-f8a4-477f-96ae-1dc7f39f5601> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/46552135-60ec-4a45-a2e7-775cca2875dc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/46552135-60ec-4a45-a2e7-775cca2875dc> a person:Person.
           <http://data.lblod.info/id/personen/46552135-60ec-4a45-a2e7-775cca2875dc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/46552135-60ec-4a45-a2e7-775cca2875dc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Kristel".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/46552135-60ec-4a45-a2e7-775cca2875dc> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/635a5a32-65e3-40a9-b459-ba59a01801f5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/635a5a32-65e3-40a9-b459-ba59a01801f5> a person:Person.
           <http://data.lblod.info/id/personen/635a5a32-65e3-40a9-b459-ba59a01801f5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/635a5a32-65e3-40a9-b459-ba59a01801f5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Tom".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/635a5a32-65e3-40a9-b459-ba59a01801f5> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/20b47964-d681-4321-a04d-8759a4c8b2a3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/20b47964-d681-4321-a04d-8759a4c8b2a3> a person:Person.
           <http://data.lblod.info/id/personen/20b47964-d681-4321-a04d-8759a4c8b2a3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/20b47964-d681-4321-a04d-8759a4c8b2a3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Luc".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/20b47964-d681-4321-a04d-8759a4c8b2a3> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/4ed18116-3cd7-4f63-bc2a-5ab9bae97e6f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4ed18116-3cd7-4f63-bc2a-5ab9bae97e6f> a person:Person.
           <http://data.lblod.info/id/personen/4ed18116-3cd7-4f63-bc2a-5ab9bae97e6f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4ed18116-3cd7-4f63-bc2a-5ab9bae97e6f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Leo".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4ed18116-3cd7-4f63-bc2a-5ab9bae97e6f> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/536eede6-49e5-49af-aff5-162cf0e29327> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/536eede6-49e5-49af-aff5-162cf0e29327> a person:Person.
           <http://data.lblod.info/id/personen/536eede6-49e5-49af-aff5-162cf0e29327> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/536eede6-49e5-49af-aff5-162cf0e29327> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Chris".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/536eede6-49e5-49af-aff5-162cf0e29327> [] [].
          }
        }
     # finished voornamen-update-25900-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:40+00:00