# started voornamen-update-1736-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:05:40+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ed79acb2-3c58-402a-bd34-02eb11af44c7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ed79acb2-3c58-402a-bd34-02eb11af44c7> a person:Person.
           <http://data.lblod.info/id/personen/ed79acb2-3c58-402a-bd34-02eb11af44c7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ed79acb2-3c58-402a-bd34-02eb11af44c7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Rose-Marie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ed79acb2-3c58-402a-bd34-02eb11af44c7> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/8ac59b36-f6f1-4876-acb6-6099d2a88a43> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8ac59b36-f6f1-4876-acb6-6099d2a88a43> a person:Person.
           <http://data.lblod.info/id/personen/8ac59b36-f6f1-4876-acb6-6099d2a88a43> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8ac59b36-f6f1-4876-acb6-6099d2a88a43> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Herman".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8ac59b36-f6f1-4876-acb6-6099d2a88a43> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/d65ba4c4-e11c-4e20-91c6-2ce1f06769f4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d65ba4c4-e11c-4e20-91c6-2ce1f06769f4> a person:Person.
           <http://data.lblod.info/id/personen/d65ba4c4-e11c-4e20-91c6-2ce1f06769f4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d65ba4c4-e11c-4e20-91c6-2ce1f06769f4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Hedwig".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d65ba4c4-e11c-4e20-91c6-2ce1f06769f4> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/9a1f648760bcc31b18e7a3eabba5bd9461d0df43fd3776328991a891d4c190af> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9a1f648760bcc31b18e7a3eabba5bd9461d0df43fd3776328991a891d4c190af> a person:Person.
           <http://data.lblod.info/id/personen/9a1f648760bcc31b18e7a3eabba5bd9461d0df43fd3776328991a891d4c190af> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9a1f648760bcc31b18e7a3eabba5bd9461d0df43fd3776328991a891d4c190af> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jean Pierre".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9a1f648760bcc31b18e7a3eabba5bd9461d0df43fd3776328991a891d4c190af> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/abc728f2-6e55-4d08-9db6-9608342e73a2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/abc728f2-6e55-4d08-9db6-9608342e73a2> a person:Person.
           <http://data.lblod.info/id/personen/abc728f2-6e55-4d08-9db6-9608342e73a2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/abc728f2-6e55-4d08-9db6-9608342e73a2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Carine".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/abc728f2-6e55-4d08-9db6-9608342e73a2> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/83c3739d6ca6fafa74b3332f23657abd30c2c3a07496929d9d178c58721206d3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/83c3739d6ca6fafa74b3332f23657abd30c2c3a07496929d9d178c58721206d3> a person:Person.
           <http://data.lblod.info/id/personen/83c3739d6ca6fafa74b3332f23657abd30c2c3a07496929d9d178c58721206d3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/83c3739d6ca6fafa74b3332f23657abd30c2c3a07496929d9d178c58721206d3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Nicole".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/83c3739d6ca6fafa74b3332f23657abd30c2c3a07496929d9d178c58721206d3> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/4ed5efb2-c983-4490-9fe6-3aa448d5398b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4ed5efb2-c983-4490-9fe6-3aa448d5398b> a person:Person.
           <http://data.lblod.info/id/personen/4ed5efb2-c983-4490-9fe6-3aa448d5398b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4ed5efb2-c983-4490-9fe6-3aa448d5398b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Danie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4ed5efb2-c983-4490-9fe6-3aa448d5398b> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/0b992e51b50bf6fcbc65f198ac69d00e96b58a74d43bda647707ce41a18a004e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0b992e51b50bf6fcbc65f198ac69d00e96b58a74d43bda647707ce41a18a004e> a person:Person.
           <http://data.lblod.info/id/personen/0b992e51b50bf6fcbc65f198ac69d00e96b58a74d43bda647707ce41a18a004e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0b992e51b50bf6fcbc65f198ac69d00e96b58a74d43bda647707ce41a18a004e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Walter".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0b992e51b50bf6fcbc65f198ac69d00e96b58a74d43bda647707ce41a18a004e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/1aeff0263198bc5ab27c4ab261b12e29d843eabc60301eee4bd1f7f564f4257d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1aeff0263198bc5ab27c4ab261b12e29d843eabc60301eee4bd1f7f564f4257d> a person:Person.
           <http://data.lblod.info/id/personen/1aeff0263198bc5ab27c4ab261b12e29d843eabc60301eee4bd1f7f564f4257d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1aeff0263198bc5ab27c4ab261b12e29d843eabc60301eee4bd1f7f564f4257d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jan".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1aeff0263198bc5ab27c4ab261b12e29d843eabc60301eee4bd1f7f564f4257d> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/fc3f5f1b-9fa9-44a8-a9fa-db2b0ef1ec52> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/fc3f5f1b-9fa9-44a8-a9fa-db2b0ef1ec52> a person:Person.
           <http://data.lblod.info/id/personen/fc3f5f1b-9fa9-44a8-a9fa-db2b0ef1ec52> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/fc3f5f1b-9fa9-44a8-a9fa-db2b0ef1ec52> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ignaz".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/fc3f5f1b-9fa9-44a8-a9fa-db2b0ef1ec52> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/a992a74a-7d63-41f5-8f93-75db295d5f1e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a992a74a-7d63-41f5-8f93-75db295d5f1e> a person:Person.
           <http://data.lblod.info/id/personen/a992a74a-7d63-41f5-8f93-75db295d5f1e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a992a74a-7d63-41f5-8f93-75db295d5f1e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Cédric".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a992a74a-7d63-41f5-8f93-75db295d5f1e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/831425273037ab02e0abc5a349eb271a4660353699b4749f1cbcbfccfe5abc84> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/831425273037ab02e0abc5a349eb271a4660353699b4749f1cbcbfccfe5abc84> a person:Person.
           <http://data.lblod.info/id/personen/831425273037ab02e0abc5a349eb271a4660353699b4749f1cbcbfccfe5abc84> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/831425273037ab02e0abc5a349eb271a4660353699b4749f1cbcbfccfe5abc84> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Flor".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/831425273037ab02e0abc5a349eb271a4660353699b4749f1cbcbfccfe5abc84> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f779b695946d3259664fb9859a411bec6352220784a0c4d85db2edf85096bc6a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f779b695946d3259664fb9859a411bec6352220784a0c4d85db2edf85096bc6a> a person:Person.
           <http://data.lblod.info/id/personen/f779b695946d3259664fb9859a411bec6352220784a0c4d85db2edf85096bc6a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f779b695946d3259664fb9859a411bec6352220784a0c4d85db2edf85096bc6a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Christine".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f779b695946d3259664fb9859a411bec6352220784a0c4d85db2edf85096bc6a> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/676684a2-31a2-4556-912b-529dc017a0fa> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/676684a2-31a2-4556-912b-529dc017a0fa> a person:Person.
           <http://data.lblod.info/id/personen/676684a2-31a2-4556-912b-529dc017a0fa> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/676684a2-31a2-4556-912b-529dc017a0fa> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Patrick".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/676684a2-31a2-4556-912b-529dc017a0fa> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/a0b4e75b86320ebc98a2fe0be1cd024fd47c679682194e2c49014ede08367618> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a0b4e75b86320ebc98a2fe0be1cd024fd47c679682194e2c49014ede08367618> a person:Person.
           <http://data.lblod.info/id/personen/a0b4e75b86320ebc98a2fe0be1cd024fd47c679682194e2c49014ede08367618> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a0b4e75b86320ebc98a2fe0be1cd024fd47c679682194e2c49014ede08367618> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Kurt".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a0b4e75b86320ebc98a2fe0be1cd024fd47c679682194e2c49014ede08367618> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/afcdf38c-03e4-4ec5-80dd-4cee9671a20a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/afcdf38c-03e4-4ec5-80dd-4cee9671a20a> a person:Person.
           <http://data.lblod.info/id/personen/afcdf38c-03e4-4ec5-80dd-4cee9671a20a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/afcdf38c-03e4-4ec5-80dd-4cee9671a20a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Vivi".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/afcdf38c-03e4-4ec5-80dd-4cee9671a20a> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/678e89cf-2d9a-4090-808d-5a8a431366f4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/678e89cf-2d9a-4090-808d-5a8a431366f4> a person:Person.
           <http://data.lblod.info/id/personen/678e89cf-2d9a-4090-808d-5a8a431366f4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/678e89cf-2d9a-4090-808d-5a8a431366f4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Annie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/678e89cf-2d9a-4090-808d-5a8a431366f4> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/db9e845faa88ddc3cbcf9789e72dffd346b2dc0ebb916753ce4c93b36e2ae66c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/db9e845faa88ddc3cbcf9789e72dffd346b2dc0ebb916753ce4c93b36e2ae66c> a person:Person.
           <http://data.lblod.info/id/personen/db9e845faa88ddc3cbcf9789e72dffd346b2dc0ebb916753ce4c93b36e2ae66c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/db9e845faa88ddc3cbcf9789e72dffd346b2dc0ebb916753ce4c93b36e2ae66c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "José".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/db9e845faa88ddc3cbcf9789e72dffd346b2dc0ebb916753ce4c93b36e2ae66c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/6e6bb7e5754aa4c4919980bac4f0e899f8492888029c39079bfc7601ddb44f00> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6e6bb7e5754aa4c4919980bac4f0e899f8492888029c39079bfc7601ddb44f00> a person:Person.
           <http://data.lblod.info/id/personen/6e6bb7e5754aa4c4919980bac4f0e899f8492888029c39079bfc7601ddb44f00> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6e6bb7e5754aa4c4919980bac4f0e899f8492888029c39079bfc7601ddb44f00> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Elvira".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6e6bb7e5754aa4c4919980bac4f0e899f8492888029c39079bfc7601ddb44f00> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/d2838a9b08919afb4e0ca5727758aed1bd373301647b94528cdf633016fdfd3d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d2838a9b08919afb4e0ca5727758aed1bd373301647b94528cdf633016fdfd3d> a person:Person.
           <http://data.lblod.info/id/personen/d2838a9b08919afb4e0ca5727758aed1bd373301647b94528cdf633016fdfd3d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d2838a9b08919afb4e0ca5727758aed1bd373301647b94528cdf633016fdfd3d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Albert".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d2838a9b08919afb4e0ca5727758aed1bd373301647b94528cdf633016fdfd3d> [] [].
          }
        }
     # finished voornamen-update-1736-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:05:40+00:00