# started voornamen-update-21687-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:29+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/160c72d6-d4d6-4a7b-8dad-99c144c8dc76> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/160c72d6-d4d6-4a7b-8dad-99c144c8dc76> a person:Person.
           <http://data.lblod.info/id/personen/160c72d6-d4d6-4a7b-8dad-99c144c8dc76> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/160c72d6-d4d6-4a7b-8dad-99c144c8dc76> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Natacha".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/160c72d6-d4d6-4a7b-8dad-99c144c8dc76> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/0ddb2e29aee0a84200fc49ada56b14f04b684b4b42182e8f1cb381eb9cde667a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0ddb2e29aee0a84200fc49ada56b14f04b684b4b42182e8f1cb381eb9cde667a> a person:Person.
           <http://data.lblod.info/id/personen/0ddb2e29aee0a84200fc49ada56b14f04b684b4b42182e8f1cb381eb9cde667a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0ddb2e29aee0a84200fc49ada56b14f04b684b4b42182e8f1cb381eb9cde667a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Constant".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0ddb2e29aee0a84200fc49ada56b14f04b684b4b42182e8f1cb381eb9cde667a> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/487fff779197a332bd289ee0dc836a0716d454ff4b1822408c47a4602b1b96ad> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/487fff779197a332bd289ee0dc836a0716d454ff4b1822408c47a4602b1b96ad> a person:Person.
           <http://data.lblod.info/id/personen/487fff779197a332bd289ee0dc836a0716d454ff4b1822408c47a4602b1b96ad> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/487fff779197a332bd289ee0dc836a0716d454ff4b1822408c47a4602b1b96ad> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Godelieve".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/487fff779197a332bd289ee0dc836a0716d454ff4b1822408c47a4602b1b96ad> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/099890de-f50c-46e8-b04d-4a470e0a9d4d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/099890de-f50c-46e8-b04d-4a470e0a9d4d> a person:Person.
           <http://data.lblod.info/id/personen/099890de-f50c-46e8-b04d-4a470e0a9d4d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/099890de-f50c-46e8-b04d-4a470e0a9d4d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Kris".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/099890de-f50c-46e8-b04d-4a470e0a9d4d> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/8f560af7a0a296cef7ae179103fba4d4b0922f1ad2abc9c8435dd20a4490d7af> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8f560af7a0a296cef7ae179103fba4d4b0922f1ad2abc9c8435dd20a4490d7af> a person:Person.
           <http://data.lblod.info/id/personen/8f560af7a0a296cef7ae179103fba4d4b0922f1ad2abc9c8435dd20a4490d7af> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8f560af7a0a296cef7ae179103fba4d4b0922f1ad2abc9c8435dd20a4490d7af> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Nele".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8f560af7a0a296cef7ae179103fba4d4b0922f1ad2abc9c8435dd20a4490d7af> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/32048e8c-cd41-437d-85b4-d77cb3a28564> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/32048e8c-cd41-437d-85b4-d77cb3a28564> a person:Person.
           <http://data.lblod.info/id/personen/32048e8c-cd41-437d-85b4-d77cb3a28564> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/32048e8c-cd41-437d-85b4-d77cb3a28564> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jean Marie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/32048e8c-cd41-437d-85b4-d77cb3a28564> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/01a99f36-8dbf-4a79-ba39-83a8ee893e25> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/01a99f36-8dbf-4a79-ba39-83a8ee893e25> a person:Person.
           <http://data.lblod.info/id/personen/01a99f36-8dbf-4a79-ba39-83a8ee893e25> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/01a99f36-8dbf-4a79-ba39-83a8ee893e25> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Naomie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/01a99f36-8dbf-4a79-ba39-83a8ee893e25> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/96a8597f-101c-491d-80d0-c5406349b214> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/96a8597f-101c-491d-80d0-c5406349b214> a person:Person.
           <http://data.lblod.info/id/personen/96a8597f-101c-491d-80d0-c5406349b214> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/96a8597f-101c-491d-80d0-c5406349b214> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Raf".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/96a8597f-101c-491d-80d0-c5406349b214> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/56cde291-8643-48fc-bae5-58d5eb95f064> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/56cde291-8643-48fc-bae5-58d5eb95f064> a person:Person.
           <http://data.lblod.info/id/personen/56cde291-8643-48fc-bae5-58d5eb95f064> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/56cde291-8643-48fc-bae5-58d5eb95f064> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Samuel".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/56cde291-8643-48fc-bae5-58d5eb95f064> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/144f22d9-0618-4fc3-8a4d-86d8f13b2e6e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/144f22d9-0618-4fc3-8a4d-86d8f13b2e6e> a person:Person.
           <http://data.lblod.info/id/personen/144f22d9-0618-4fc3-8a4d-86d8f13b2e6e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/144f22d9-0618-4fc3-8a4d-86d8f13b2e6e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Christel".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/144f22d9-0618-4fc3-8a4d-86d8f13b2e6e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/5d1cd381-9730-450a-9ffe-ba8324e4ccac> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5d1cd381-9730-450a-9ffe-ba8324e4ccac> a person:Person.
           <http://data.lblod.info/id/personen/5d1cd381-9730-450a-9ffe-ba8324e4ccac> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5d1cd381-9730-450a-9ffe-ba8324e4ccac> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Wendel".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5d1cd381-9730-450a-9ffe-ba8324e4ccac> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ad78c4de-7901-4c0f-9e6a-215fb5951a20> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ad78c4de-7901-4c0f-9e6a-215fb5951a20> a person:Person.
           <http://data.lblod.info/id/personen/ad78c4de-7901-4c0f-9e6a-215fb5951a20> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ad78c4de-7901-4c0f-9e6a-215fb5951a20> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Tess".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ad78c4de-7901-4c0f-9e6a-215fb5951a20> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/68d18dda-668e-40c2-bd95-ea14bbed7979> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/68d18dda-668e-40c2-bd95-ea14bbed7979> a person:Person.
           <http://data.lblod.info/id/personen/68d18dda-668e-40c2-bd95-ea14bbed7979> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/68d18dda-668e-40c2-bd95-ea14bbed7979> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Johan".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/68d18dda-668e-40c2-bd95-ea14bbed7979> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/21c16f8f16fa5844e9339644ed8adf6c767f466b12520e29f6e8f3c7341d00b1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/21c16f8f16fa5844e9339644ed8adf6c767f466b12520e29f6e8f3c7341d00b1> a person:Person.
           <http://data.lblod.info/id/personen/21c16f8f16fa5844e9339644ed8adf6c767f466b12520e29f6e8f3c7341d00b1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/21c16f8f16fa5844e9339644ed8adf6c767f466b12520e29f6e8f3c7341d00b1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Luc".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/21c16f8f16fa5844e9339644ed8adf6c767f466b12520e29f6e8f3c7341d00b1> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/c7c55115-0a79-4208-9b2b-5547a16f6552> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c7c55115-0a79-4208-9b2b-5547a16f6552> a person:Person.
           <http://data.lblod.info/id/personen/c7c55115-0a79-4208-9b2b-5547a16f6552> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c7c55115-0a79-4208-9b2b-5547a16f6552> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Didier".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c7c55115-0a79-4208-9b2b-5547a16f6552> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/4889262c-ed4d-4d43-9783-013ec36c7979> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4889262c-ed4d-4d43-9783-013ec36c7979> a person:Person.
           <http://data.lblod.info/id/personen/4889262c-ed4d-4d43-9783-013ec36c7979> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4889262c-ed4d-4d43-9783-013ec36c7979> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Myriam".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4889262c-ed4d-4d43-9783-013ec36c7979> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/a3a2b172-d57a-4f56-9dc8-1681c54b0c1d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a3a2b172-d57a-4f56-9dc8-1681c54b0c1d> a person:Person.
           <http://data.lblod.info/id/personen/a3a2b172-d57a-4f56-9dc8-1681c54b0c1d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a3a2b172-d57a-4f56-9dc8-1681c54b0c1d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jill".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a3a2b172-d57a-4f56-9dc8-1681c54b0c1d> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/8f033091-6b93-46ce-b36f-b125c1b492df> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8f033091-6b93-46ce-b36f-b125c1b492df> a person:Person.
           <http://data.lblod.info/id/personen/8f033091-6b93-46ce-b36f-b125c1b492df> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8f033091-6b93-46ce-b36f-b125c1b492df> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Willy".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8f033091-6b93-46ce-b36f-b125c1b492df> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/fed37307d0a57e3bf2bdbea06ec2deb57e51a5b55a13416de91c3ff16cb509e5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/fed37307d0a57e3bf2bdbea06ec2deb57e51a5b55a13416de91c3ff16cb509e5> a person:Person.
           <http://data.lblod.info/id/personen/fed37307d0a57e3bf2bdbea06ec2deb57e51a5b55a13416de91c3ff16cb509e5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/fed37307d0a57e3bf2bdbea06ec2deb57e51a5b55a13416de91c3ff16cb509e5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Rudy".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/fed37307d0a57e3bf2bdbea06ec2deb57e51a5b55a13416de91c3ff16cb509e5> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/4b090061-f3b5-4ea1-aefb-cefc5050f793> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4b090061-f3b5-4ea1-aefb-cefc5050f793> a person:Person.
           <http://data.lblod.info/id/personen/4b090061-f3b5-4ea1-aefb-cefc5050f793> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4b090061-f3b5-4ea1-aefb-cefc5050f793> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Nadja".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4b090061-f3b5-4ea1-aefb-cefc5050f793> [] [].
          }
        }
     # finished voornamen-update-21687-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:29+00:00