# started voornamen-update-577-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:05:36+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/33cb4af6-e95f-4c0b-8830-6ae957b2ec50> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/33cb4af6-e95f-4c0b-8830-6ae957b2ec50> a person:Person.
           <http://data.lblod.info/id/personen/33cb4af6-e95f-4c0b-8830-6ae957b2ec50> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/33cb4af6-e95f-4c0b-8830-6ae957b2ec50> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ken".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/33cb4af6-e95f-4c0b-8830-6ae957b2ec50> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ddb914c8085428752cf77abb487bbc975d0a6268bfce3cae044f464e598d27cd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ddb914c8085428752cf77abb487bbc975d0a6268bfce3cae044f464e598d27cd> a person:Person.
           <http://data.lblod.info/id/personen/ddb914c8085428752cf77abb487bbc975d0a6268bfce3cae044f464e598d27cd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ddb914c8085428752cf77abb487bbc975d0a6268bfce3cae044f464e598d27cd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Christophe".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ddb914c8085428752cf77abb487bbc975d0a6268bfce3cae044f464e598d27cd> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/6871ced6-6581-4908-9997-d41e5ebca909> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6871ced6-6581-4908-9997-d41e5ebca909> a person:Person.
           <http://data.lblod.info/id/personen/6871ced6-6581-4908-9997-d41e5ebca909> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6871ced6-6581-4908-9997-d41e5ebca909> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Genoveva".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6871ced6-6581-4908-9997-d41e5ebca909> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/d97f805229ec3e42bfee72e809ba039bac78f1e90c13fd08a3d6162efdc95b10> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d97f805229ec3e42bfee72e809ba039bac78f1e90c13fd08a3d6162efdc95b10> a person:Person.
           <http://data.lblod.info/id/personen/d97f805229ec3e42bfee72e809ba039bac78f1e90c13fd08a3d6162efdc95b10> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d97f805229ec3e42bfee72e809ba039bac78f1e90c13fd08a3d6162efdc95b10> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jelle".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d97f805229ec3e42bfee72e809ba039bac78f1e90c13fd08a3d6162efdc95b10> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/6dfcd6c1-0911-45e5-afc5-524838c8e586> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6dfcd6c1-0911-45e5-afc5-524838c8e586> a person:Person.
           <http://data.lblod.info/id/personen/6dfcd6c1-0911-45e5-afc5-524838c8e586> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6dfcd6c1-0911-45e5-afc5-524838c8e586> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Laura".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6dfcd6c1-0911-45e5-afc5-524838c8e586> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/74e6fe6e-99c5-4e95-9b42-5af23c52c90a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/74e6fe6e-99c5-4e95-9b42-5af23c52c90a> a person:Person.
           <http://data.lblod.info/id/personen/74e6fe6e-99c5-4e95-9b42-5af23c52c90a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/74e6fe6e-99c5-4e95-9b42-5af23c52c90a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Asha".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/74e6fe6e-99c5-4e95-9b42-5af23c52c90a> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/d9fe6d94-491e-4343-9516-1602793da9bc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d9fe6d94-491e-4343-9516-1602793da9bc> a person:Person.
           <http://data.lblod.info/id/personen/d9fe6d94-491e-4343-9516-1602793da9bc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d9fe6d94-491e-4343-9516-1602793da9bc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Trui".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d9fe6d94-491e-4343-9516-1602793da9bc> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/086713dc7743500f0c8282a4bc55d0fd3cef2936206031a73a3307993565557e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/086713dc7743500f0c8282a4bc55d0fd3cef2936206031a73a3307993565557e> a person:Person.
           <http://data.lblod.info/id/personen/086713dc7743500f0c8282a4bc55d0fd3cef2936206031a73a3307993565557e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/086713dc7743500f0c8282a4bc55d0fd3cef2936206031a73a3307993565557e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Koen".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/086713dc7743500f0c8282a4bc55d0fd3cef2936206031a73a3307993565557e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/9020d7f0-d608-41e9-8726-b1670e7bae27> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9020d7f0-d608-41e9-8726-b1670e7bae27> a person:Person.
           <http://data.lblod.info/id/personen/9020d7f0-d608-41e9-8726-b1670e7bae27> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9020d7f0-d608-41e9-8726-b1670e7bae27> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Michaëla".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9020d7f0-d608-41e9-8726-b1670e7bae27> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/00a6492f-3c78-4d85-8654-ad0937ad33be> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/00a6492f-3c78-4d85-8654-ad0937ad33be> a person:Person.
           <http://data.lblod.info/id/personen/00a6492f-3c78-4d85-8654-ad0937ad33be> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/00a6492f-3c78-4d85-8654-ad0937ad33be> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Joery".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/00a6492f-3c78-4d85-8654-ad0937ad33be> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/08de1c36-6ab6-4689-aa72-af5126806916> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/08de1c36-6ab6-4689-aa72-af5126806916> a person:Person.
           <http://data.lblod.info/id/personen/08de1c36-6ab6-4689-aa72-af5126806916> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/08de1c36-6ab6-4689-aa72-af5126806916> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Sarah".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/08de1c36-6ab6-4689-aa72-af5126806916> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/7034a56a-465b-4916-baae-2722c16b8a63> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7034a56a-465b-4916-baae-2722c16b8a63> a person:Person.
           <http://data.lblod.info/id/personen/7034a56a-465b-4916-baae-2722c16b8a63> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7034a56a-465b-4916-baae-2722c16b8a63> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Kishan".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7034a56a-465b-4916-baae-2722c16b8a63> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/90e9760f-d8c4-4e89-a033-a0900715eb48> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/90e9760f-d8c4-4e89-a033-a0900715eb48> a person:Person.
           <http://data.lblod.info/id/personen/90e9760f-d8c4-4e89-a033-a0900715eb48> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/90e9760f-d8c4-4e89-a033-a0900715eb48> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Kathy".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/90e9760f-d8c4-4e89-a033-a0900715eb48> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/cb59b8a2-ee50-42a9-a288-e3d594dc9c43> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cb59b8a2-ee50-42a9-a288-e3d594dc9c43> a person:Person.
           <http://data.lblod.info/id/personen/cb59b8a2-ee50-42a9-a288-e3d594dc9c43> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cb59b8a2-ee50-42a9-a288-e3d594dc9c43> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Stefan".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cb59b8a2-ee50-42a9-a288-e3d594dc9c43> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/d0da51a1-3a78-4176-8bb1-acee1ece4435> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d0da51a1-3a78-4176-8bb1-acee1ece4435> a person:Person.
           <http://data.lblod.info/id/personen/d0da51a1-3a78-4176-8bb1-acee1ece4435> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d0da51a1-3a78-4176-8bb1-acee1ece4435> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Geert".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d0da51a1-3a78-4176-8bb1-acee1ece4435> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/5cb87334-cc4c-4be7-8a3a-26754c7ed3a0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5cb87334-cc4c-4be7-8a3a-26754c7ed3a0> a person:Person.
           <http://data.lblod.info/id/personen/5cb87334-cc4c-4be7-8a3a-26754c7ed3a0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5cb87334-cc4c-4be7-8a3a-26754c7ed3a0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Hiske".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5cb87334-cc4c-4be7-8a3a-26754c7ed3a0> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/5e182337-3233-4d95-93d8-0ef4fc405334> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5e182337-3233-4d95-93d8-0ef4fc405334> a person:Person.
           <http://data.lblod.info/id/personen/5e182337-3233-4d95-93d8-0ef4fc405334> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5e182337-3233-4d95-93d8-0ef4fc405334> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Manu".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5e182337-3233-4d95-93d8-0ef4fc405334> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/77771bfc-149d-45e9-a8a0-aae2160b11bd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/77771bfc-149d-45e9-a8a0-aae2160b11bd> a person:Person.
           <http://data.lblod.info/id/personen/77771bfc-149d-45e9-a8a0-aae2160b11bd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/77771bfc-149d-45e9-a8a0-aae2160b11bd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marcel".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/77771bfc-149d-45e9-a8a0-aae2160b11bd> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/c31120e91202ebc41ba97fff9310f253232ea656c8449db547edfedf01045b2d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c31120e91202ebc41ba97fff9310f253232ea656c8449db547edfedf01045b2d> a person:Person.
           <http://data.lblod.info/id/personen/c31120e91202ebc41ba97fff9310f253232ea656c8449db547edfedf01045b2d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c31120e91202ebc41ba97fff9310f253232ea656c8449db547edfedf01045b2d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Deborah".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c31120e91202ebc41ba97fff9310f253232ea656c8449db547edfedf01045b2d> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ce9b9b82-f4c3-4fab-8c73-2949a154f4df> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ce9b9b82-f4c3-4fab-8c73-2949a154f4df> a person:Person.
           <http://data.lblod.info/id/personen/ce9b9b82-f4c3-4fab-8c73-2949a154f4df> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ce9b9b82-f4c3-4fab-8c73-2949a154f4df> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jorinde".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ce9b9b82-f4c3-4fab-8c73-2949a154f4df> [] [].
          }
        }
     # finished voornamen-update-577-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:05:36+00:00