# started voornamen-update-1920-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:05:40+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/39865474-4b41-48f8-a6d5-f7e57be8a4e5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/39865474-4b41-48f8-a6d5-f7e57be8a4e5> a person:Person.
           <http://data.lblod.info/id/personen/39865474-4b41-48f8-a6d5-f7e57be8a4e5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/39865474-4b41-48f8-a6d5-f7e57be8a4e5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Peter".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/39865474-4b41-48f8-a6d5-f7e57be8a4e5> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/40c6af82-e805-4276-a99a-c23128dd6bd2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/40c6af82-e805-4276-a99a-c23128dd6bd2> a person:Person.
           <http://data.lblod.info/id/personen/40c6af82-e805-4276-a99a-c23128dd6bd2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/40c6af82-e805-4276-a99a-c23128dd6bd2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Lusi".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/40c6af82-e805-4276-a99a-c23128dd6bd2> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/bc3a8a5543f836047861bdd651734e01454522f0d0cfb917be2d1b4ef7d436ee> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bc3a8a5543f836047861bdd651734e01454522f0d0cfb917be2d1b4ef7d436ee> a person:Person.
           <http://data.lblod.info/id/personen/bc3a8a5543f836047861bdd651734e01454522f0d0cfb917be2d1b4ef7d436ee> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bc3a8a5543f836047861bdd651734e01454522f0d0cfb917be2d1b4ef7d436ee> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ria".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bc3a8a5543f836047861bdd651734e01454522f0d0cfb917be2d1b4ef7d436ee> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ae576844-c595-4c5d-bb8e-760ed135152a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ae576844-c595-4c5d-bb8e-760ed135152a> a person:Person.
           <http://data.lblod.info/id/personen/ae576844-c595-4c5d-bb8e-760ed135152a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ae576844-c595-4c5d-bb8e-760ed135152a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marleen".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ae576844-c595-4c5d-bb8e-760ed135152a> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/8ddde0b4-ad4c-4722-9d18-4bfe67a81913> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8ddde0b4-ad4c-4722-9d18-4bfe67a81913> a person:Person.
           <http://data.lblod.info/id/personen/8ddde0b4-ad4c-4722-9d18-4bfe67a81913> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8ddde0b4-ad4c-4722-9d18-4bfe67a81913> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jan".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8ddde0b4-ad4c-4722-9d18-4bfe67a81913> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/21956b7a-1aef-4f1f-90ae-7d7940f46129> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/21956b7a-1aef-4f1f-90ae-7d7940f46129> a person:Person.
           <http://data.lblod.info/id/personen/21956b7a-1aef-4f1f-90ae-7d7940f46129> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/21956b7a-1aef-4f1f-90ae-7d7940f46129> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Nathan".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/21956b7a-1aef-4f1f-90ae-7d7940f46129> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/921416b7-6a15-4b92-9a5f-81f01d96a501> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/921416b7-6a15-4b92-9a5f-81f01d96a501> a person:Person.
           <http://data.lblod.info/id/personen/921416b7-6a15-4b92-9a5f-81f01d96a501> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/921416b7-6a15-4b92-9a5f-81f01d96a501> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Cindy".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/921416b7-6a15-4b92-9a5f-81f01d96a501> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/12ed19d4e6621ded66f3e7cf262bd67d4a4e66706a94842b673b82686986df71> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/12ed19d4e6621ded66f3e7cf262bd67d4a4e66706a94842b673b82686986df71> a person:Person.
           <http://data.lblod.info/id/personen/12ed19d4e6621ded66f3e7cf262bd67d4a4e66706a94842b673b82686986df71> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/12ed19d4e6621ded66f3e7cf262bd67d4a4e66706a94842b673b82686986df71> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Lea".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/12ed19d4e6621ded66f3e7cf262bd67d4a4e66706a94842b673b82686986df71> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ac0e20634430932af2669dd3e7a55f9fedd754e5a9deb93b2b048b1f458f9eb5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ac0e20634430932af2669dd3e7a55f9fedd754e5a9deb93b2b048b1f458f9eb5> a person:Person.
           <http://data.lblod.info/id/personen/ac0e20634430932af2669dd3e7a55f9fedd754e5a9deb93b2b048b1f458f9eb5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ac0e20634430932af2669dd3e7a55f9fedd754e5a9deb93b2b048b1f458f9eb5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Wies".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ac0e20634430932af2669dd3e7a55f9fedd754e5a9deb93b2b048b1f458f9eb5> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/76fbe350-ea0e-4651-8c7c-ae2fd8bfcd22> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/76fbe350-ea0e-4651-8c7c-ae2fd8bfcd22> a person:Person.
           <http://data.lblod.info/id/personen/76fbe350-ea0e-4651-8c7c-ae2fd8bfcd22> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/76fbe350-ea0e-4651-8c7c-ae2fd8bfcd22> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Maxime".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/76fbe350-ea0e-4651-8c7c-ae2fd8bfcd22> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/50ff2bc48a5f1654f3d2f04b08676f6e168417638d23444cd349f64808db4d9d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/50ff2bc48a5f1654f3d2f04b08676f6e168417638d23444cd349f64808db4d9d> a person:Person.
           <http://data.lblod.info/id/personen/50ff2bc48a5f1654f3d2f04b08676f6e168417638d23444cd349f64808db4d9d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/50ff2bc48a5f1654f3d2f04b08676f6e168417638d23444cd349f64808db4d9d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Leen".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/50ff2bc48a5f1654f3d2f04b08676f6e168417638d23444cd349f64808db4d9d> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2a4b81742f7f5ebcfc3e9dbf2f15fc126f4052329566d0941877d8a61a5a5a02> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2a4b81742f7f5ebcfc3e9dbf2f15fc126f4052329566d0941877d8a61a5a5a02> a person:Person.
           <http://data.lblod.info/id/personen/2a4b81742f7f5ebcfc3e9dbf2f15fc126f4052329566d0941877d8a61a5a5a02> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2a4b81742f7f5ebcfc3e9dbf2f15fc126f4052329566d0941877d8a61a5a5a02> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Gert".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2a4b81742f7f5ebcfc3e9dbf2f15fc126f4052329566d0941877d8a61a5a5a02> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/cc5fa246-00aa-43d2-b7ea-adc6af989df8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cc5fa246-00aa-43d2-b7ea-adc6af989df8> a person:Person.
           <http://data.lblod.info/id/personen/cc5fa246-00aa-43d2-b7ea-adc6af989df8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cc5fa246-00aa-43d2-b7ea-adc6af989df8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Lies".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cc5fa246-00aa-43d2-b7ea-adc6af989df8> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/97dc58d4-5a68-4657-9836-da4d94dfc702> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/97dc58d4-5a68-4657-9836-da4d94dfc702> a person:Person.
           <http://data.lblod.info/id/personen/97dc58d4-5a68-4657-9836-da4d94dfc702> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/97dc58d4-5a68-4657-9836-da4d94dfc702> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Tom".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/97dc58d4-5a68-4657-9836-da4d94dfc702> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e284bd6b-8f95-412b-92c3-21b62fec28dd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e284bd6b-8f95-412b-92c3-21b62fec28dd> a person:Person.
           <http://data.lblod.info/id/personen/e284bd6b-8f95-412b-92c3-21b62fec28dd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e284bd6b-8f95-412b-92c3-21b62fec28dd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Agnes".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e284bd6b-8f95-412b-92c3-21b62fec28dd> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/98eb0f59-2bb8-4a53-98c9-50388487ee48> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/98eb0f59-2bb8-4a53-98c9-50388487ee48> a person:Person.
           <http://data.lblod.info/id/personen/98eb0f59-2bb8-4a53-98c9-50388487ee48> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/98eb0f59-2bb8-4a53-98c9-50388487ee48> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Anita".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/98eb0f59-2bb8-4a53-98c9-50388487ee48> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/8838b401-1f45-4f5b-9c51-e661e1e61986> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8838b401-1f45-4f5b-9c51-e661e1e61986> a person:Person.
           <http://data.lblod.info/id/personen/8838b401-1f45-4f5b-9c51-e661e1e61986> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8838b401-1f45-4f5b-9c51-e661e1e61986> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Theo".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8838b401-1f45-4f5b-9c51-e661e1e61986> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f580dac6c2480ea6df62c534a17c5bb6213ad93b6d98e1cae07a7f7d6f8edce7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f580dac6c2480ea6df62c534a17c5bb6213ad93b6d98e1cae07a7f7d6f8edce7> a person:Person.
           <http://data.lblod.info/id/personen/f580dac6c2480ea6df62c534a17c5bb6213ad93b6d98e1cae07a7f7d6f8edce7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f580dac6c2480ea6df62c534a17c5bb6213ad93b6d98e1cae07a7f7d6f8edce7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Monique".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f580dac6c2480ea6df62c534a17c5bb6213ad93b6d98e1cae07a7f7d6f8edce7> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/0a51b61467330ab8c11825b215df0f0f880f21ac9c070553c85269f6257173c8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0a51b61467330ab8c11825b215df0f0f880f21ac9c070553c85269f6257173c8> a person:Person.
           <http://data.lblod.info/id/personen/0a51b61467330ab8c11825b215df0f0f880f21ac9c070553c85269f6257173c8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0a51b61467330ab8c11825b215df0f0f880f21ac9c070553c85269f6257173c8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Daniel".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0a51b61467330ab8c11825b215df0f0f880f21ac9c070553c85269f6257173c8> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2bc0c43a-51ab-4c89-9d92-1346edafac5a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2bc0c43a-51ab-4c89-9d92-1346edafac5a> a person:Person.
           <http://data.lblod.info/id/personen/2bc0c43a-51ab-4c89-9d92-1346edafac5a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2bc0c43a-51ab-4c89-9d92-1346edafac5a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jelinke".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2bc0c43a-51ab-4c89-9d92-1346edafac5a> [] [].
          }
        }
     # finished voornamen-update-1920-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:05:40+00:00