# started voornamen-update-16098-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:15+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/1070bb83-ffd8-461b-877b-f28bede65978> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1070bb83-ffd8-461b-877b-f28bede65978> a person:Person.
           <http://data.lblod.info/id/personen/1070bb83-ffd8-461b-877b-f28bede65978> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1070bb83-ffd8-461b-877b-f28bede65978> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ahmed".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1070bb83-ffd8-461b-877b-f28bede65978> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2923495e-f5f8-4685-b146-2d0a2abb7716> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2923495e-f5f8-4685-b146-2d0a2abb7716> a person:Person.
           <http://data.lblod.info/id/personen/2923495e-f5f8-4685-b146-2d0a2abb7716> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2923495e-f5f8-4685-b146-2d0a2abb7716> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Selina".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2923495e-f5f8-4685-b146-2d0a2abb7716> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/98ff5b5a-1686-4d3c-9d3e-ce7f3cdcba19> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/98ff5b5a-1686-4d3c-9d3e-ce7f3cdcba19> a person:Person.
           <http://data.lblod.info/id/personen/98ff5b5a-1686-4d3c-9d3e-ce7f3cdcba19> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/98ff5b5a-1686-4d3c-9d3e-ce7f3cdcba19> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Louis".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/98ff5b5a-1686-4d3c-9d3e-ce7f3cdcba19> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/d96a666e-b370-4a2c-a783-72a587037d45> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d96a666e-b370-4a2c-a783-72a587037d45> a person:Person.
           <http://data.lblod.info/id/personen/d96a666e-b370-4a2c-a783-72a587037d45> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d96a666e-b370-4a2c-a783-72a587037d45> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Michiel".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d96a666e-b370-4a2c-a783-72a587037d45> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/a0ccbcb7-2164-4dde-91cd-076d9b5c563e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a0ccbcb7-2164-4dde-91cd-076d9b5c563e> a person:Person.
           <http://data.lblod.info/id/personen/a0ccbcb7-2164-4dde-91cd-076d9b5c563e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a0ccbcb7-2164-4dde-91cd-076d9b5c563e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Robin".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a0ccbcb7-2164-4dde-91cd-076d9b5c563e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/4c2c1ad6-2ffc-414b-8763-e532af9c7371> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4c2c1ad6-2ffc-414b-8763-e532af9c7371> a person:Person.
           <http://data.lblod.info/id/personen/4c2c1ad6-2ffc-414b-8763-e532af9c7371> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4c2c1ad6-2ffc-414b-8763-e532af9c7371> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Annelies".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4c2c1ad6-2ffc-414b-8763-e532af9c7371> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/7c499234-a9d6-49ae-acd5-9b8e12821200> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7c499234-a9d6-49ae-acd5-9b8e12821200> a person:Person.
           <http://data.lblod.info/id/personen/7c499234-a9d6-49ae-acd5-9b8e12821200> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7c499234-a9d6-49ae-acd5-9b8e12821200> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Werner".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7c499234-a9d6-49ae-acd5-9b8e12821200> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2bb0655cd27c2227dd996208c4a20353745abeab6882cd50bdeb632f34b18a30> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2bb0655cd27c2227dd996208c4a20353745abeab6882cd50bdeb632f34b18a30> a person:Person.
           <http://data.lblod.info/id/personen/2bb0655cd27c2227dd996208c4a20353745abeab6882cd50bdeb632f34b18a30> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2bb0655cd27c2227dd996208c4a20353745abeab6882cd50bdeb632f34b18a30> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jeannine".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2bb0655cd27c2227dd996208c4a20353745abeab6882cd50bdeb632f34b18a30> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/28c76cdf-999b-40db-9892-b74aa0490ea5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/28c76cdf-999b-40db-9892-b74aa0490ea5> a person:Person.
           <http://data.lblod.info/id/personen/28c76cdf-999b-40db-9892-b74aa0490ea5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/28c76cdf-999b-40db-9892-b74aa0490ea5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Roland".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/28c76cdf-999b-40db-9892-b74aa0490ea5> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/b0c03628-2204-4da2-92bf-5953b661f72f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b0c03628-2204-4da2-92bf-5953b661f72f> a person:Person.
           <http://data.lblod.info/id/personen/b0c03628-2204-4da2-92bf-5953b661f72f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b0c03628-2204-4da2-92bf-5953b661f72f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Annie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b0c03628-2204-4da2-92bf-5953b661f72f> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/cb6d5abc2f5a316c224a8c5dcf2633d43040640d43ba024ed80db378bbc57c97> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cb6d5abc2f5a316c224a8c5dcf2633d43040640d43ba024ed80db378bbc57c97> a person:Person.
           <http://data.lblod.info/id/personen/cb6d5abc2f5a316c224a8c5dcf2633d43040640d43ba024ed80db378bbc57c97> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cb6d5abc2f5a316c224a8c5dcf2633d43040640d43ba024ed80db378bbc57c97> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Martine".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cb6d5abc2f5a316c224a8c5dcf2633d43040640d43ba024ed80db378bbc57c97> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f2f60db3-6c92-436a-8f25-1d0f0a40874d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f2f60db3-6c92-436a-8f25-1d0f0a40874d> a person:Person.
           <http://data.lblod.info/id/personen/f2f60db3-6c92-436a-8f25-1d0f0a40874d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f2f60db3-6c92-436a-8f25-1d0f0a40874d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jan".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f2f60db3-6c92-436a-8f25-1d0f0a40874d> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/c1c27c0a03d7dbf9ad0928fee875274023630f1d79745180b6468d31b542d9a1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c1c27c0a03d7dbf9ad0928fee875274023630f1d79745180b6468d31b542d9a1> a person:Person.
           <http://data.lblod.info/id/personen/c1c27c0a03d7dbf9ad0928fee875274023630f1d79745180b6468d31b542d9a1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c1c27c0a03d7dbf9ad0928fee875274023630f1d79745180b6468d31b542d9a1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marijke".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c1c27c0a03d7dbf9ad0928fee875274023630f1d79745180b6468d31b542d9a1> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/0f46603bb59d415de76e5e12e06c540bca9ffc8bb22ea0ffd76e8628c2b39bd0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0f46603bb59d415de76e5e12e06c540bca9ffc8bb22ea0ffd76e8628c2b39bd0> a person:Person.
           <http://data.lblod.info/id/personen/0f46603bb59d415de76e5e12e06c540bca9ffc8bb22ea0ffd76e8628c2b39bd0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0f46603bb59d415de76e5e12e06c540bca9ffc8bb22ea0ffd76e8628c2b39bd0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Wouter".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0f46603bb59d415de76e5e12e06c540bca9ffc8bb22ea0ffd76e8628c2b39bd0> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/cd054d05-339f-42fa-a03b-54a3e55e87d4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cd054d05-339f-42fa-a03b-54a3e55e87d4> a person:Person.
           <http://data.lblod.info/id/personen/cd054d05-339f-42fa-a03b-54a3e55e87d4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cd054d05-339f-42fa-a03b-54a3e55e87d4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Anny".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cd054d05-339f-42fa-a03b-54a3e55e87d4> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/5d13ac44-67e1-48ed-b3c7-a22214093392> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5d13ac44-67e1-48ed-b3c7-a22214093392> a person:Person.
           <http://data.lblod.info/id/personen/5d13ac44-67e1-48ed-b3c7-a22214093392> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5d13ac44-67e1-48ed-b3c7-a22214093392> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Bart".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5d13ac44-67e1-48ed-b3c7-a22214093392> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/535f95b8-e424-4dbf-8a37-231705941ca9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/535f95b8-e424-4dbf-8a37-231705941ca9> a person:Person.
           <http://data.lblod.info/id/personen/535f95b8-e424-4dbf-8a37-231705941ca9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/535f95b8-e424-4dbf-8a37-231705941ca9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Kris".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/535f95b8-e424-4dbf-8a37-231705941ca9> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/1eae0597ba6473f29bb9274854d0d853d53c5989861dedf94e989334b198d959> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1eae0597ba6473f29bb9274854d0d853d53c5989861dedf94e989334b198d959> a person:Person.
           <http://data.lblod.info/id/personen/1eae0597ba6473f29bb9274854d0d853d53c5989861dedf94e989334b198d959> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1eae0597ba6473f29bb9274854d0d853d53c5989861dedf94e989334b198d959> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Christianne".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1eae0597ba6473f29bb9274854d0d853d53c5989861dedf94e989334b198d959> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/6237dad6-822a-4a91-b304-1733b37f9307> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6237dad6-822a-4a91-b304-1733b37f9307> a person:Person.
           <http://data.lblod.info/id/personen/6237dad6-822a-4a91-b304-1733b37f9307> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6237dad6-822a-4a91-b304-1733b37f9307> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Karel".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6237dad6-822a-4a91-b304-1733b37f9307> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/1240e179ce1d85c34e7892567780057ec0875b762748e79154f3f9d576fcdd2d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1240e179ce1d85c34e7892567780057ec0875b762748e79154f3f9d576fcdd2d> a person:Person.
           <http://data.lblod.info/id/personen/1240e179ce1d85c34e7892567780057ec0875b762748e79154f3f9d576fcdd2d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1240e179ce1d85c34e7892567780057ec0875b762748e79154f3f9d576fcdd2d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Elisabeth".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1240e179ce1d85c34e7892567780057ec0875b762748e79154f3f9d576fcdd2d> [] [].
          }
        }
     # finished voornamen-update-16098-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:15+00:00