# started voornamen-update-1342-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:05:39+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/8f18ad34c3756586554c0033cbee9f8516dac35ce66864d5e1fcecc4a046cbd5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8f18ad34c3756586554c0033cbee9f8516dac35ce66864d5e1fcecc4a046cbd5> a person:Person.
           <http://data.lblod.info/id/personen/8f18ad34c3756586554c0033cbee9f8516dac35ce66864d5e1fcecc4a046cbd5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8f18ad34c3756586554c0033cbee9f8516dac35ce66864d5e1fcecc4a046cbd5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Kristian".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8f18ad34c3756586554c0033cbee9f8516dac35ce66864d5e1fcecc4a046cbd5> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/186fcf2aadbd4a91d54dfc75ee180be9105ac35ef17a6ca40027ca3e633fe450> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/186fcf2aadbd4a91d54dfc75ee180be9105ac35ef17a6ca40027ca3e633fe450> a person:Person.
           <http://data.lblod.info/id/personen/186fcf2aadbd4a91d54dfc75ee180be9105ac35ef17a6ca40027ca3e633fe450> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/186fcf2aadbd4a91d54dfc75ee180be9105ac35ef17a6ca40027ca3e633fe450> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Simonne".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/186fcf2aadbd4a91d54dfc75ee180be9105ac35ef17a6ca40027ca3e633fe450> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/d0751ba8-c56e-4c67-9486-5f8df5bfb01d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d0751ba8-c56e-4c67-9486-5f8df5bfb01d> a person:Person.
           <http://data.lblod.info/id/personen/d0751ba8-c56e-4c67-9486-5f8df5bfb01d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d0751ba8-c56e-4c67-9486-5f8df5bfb01d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jozef".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d0751ba8-c56e-4c67-9486-5f8df5bfb01d> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e42dd2f075613d737cd0962213ad160ee3c30967bde71d9ac69d5690507958cd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e42dd2f075613d737cd0962213ad160ee3c30967bde71d9ac69d5690507958cd> a person:Person.
           <http://data.lblod.info/id/personen/e42dd2f075613d737cd0962213ad160ee3c30967bde71d9ac69d5690507958cd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e42dd2f075613d737cd0962213ad160ee3c30967bde71d9ac69d5690507958cd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Monique".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e42dd2f075613d737cd0962213ad160ee3c30967bde71d9ac69d5690507958cd> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/c8935248a048f67b0256bbecb63584e90dd565ad1e8492c20cbba96f06ae138a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c8935248a048f67b0256bbecb63584e90dd565ad1e8492c20cbba96f06ae138a> a person:Person.
           <http://data.lblod.info/id/personen/c8935248a048f67b0256bbecb63584e90dd565ad1e8492c20cbba96f06ae138a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c8935248a048f67b0256bbecb63584e90dd565ad1e8492c20cbba96f06ae138a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Paul".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c8935248a048f67b0256bbecb63584e90dd565ad1e8492c20cbba96f06ae138a> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/96beb1c6d38288bcefa173a6f8a2b829294196b79d1ccb5c2589863a6d3255fd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/96beb1c6d38288bcefa173a6f8a2b829294196b79d1ccb5c2589863a6d3255fd> a person:Person.
           <http://data.lblod.info/id/personen/96beb1c6d38288bcefa173a6f8a2b829294196b79d1ccb5c2589863a6d3255fd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/96beb1c6d38288bcefa173a6f8a2b829294196b79d1ccb5c2589863a6d3255fd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jacqueline".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/96beb1c6d38288bcefa173a6f8a2b829294196b79d1ccb5c2589863a6d3255fd> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e25f95907f2d6a70952794b0c052f39790af08e747b53de1522cdd5ad94a98bb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e25f95907f2d6a70952794b0c052f39790af08e747b53de1522cdd5ad94a98bb> a person:Person.
           <http://data.lblod.info/id/personen/e25f95907f2d6a70952794b0c052f39790af08e747b53de1522cdd5ad94a98bb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e25f95907f2d6a70952794b0c052f39790af08e747b53de1522cdd5ad94a98bb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Peter".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e25f95907f2d6a70952794b0c052f39790af08e747b53de1522cdd5ad94a98bb> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/b01cb659-892c-4015-8ddc-c670bb5bf87f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b01cb659-892c-4015-8ddc-c670bb5bf87f> a person:Person.
           <http://data.lblod.info/id/personen/b01cb659-892c-4015-8ddc-c670bb5bf87f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b01cb659-892c-4015-8ddc-c670bb5bf87f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Margot".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b01cb659-892c-4015-8ddc-c670bb5bf87f> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/0292adf1-d259-4f6c-8d73-79b185e99e27> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0292adf1-d259-4f6c-8d73-79b185e99e27> a person:Person.
           <http://data.lblod.info/id/personen/0292adf1-d259-4f6c-8d73-79b185e99e27> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0292adf1-d259-4f6c-8d73-79b185e99e27> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marlene".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0292adf1-d259-4f6c-8d73-79b185e99e27> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/d3cc69c0-4573-42ba-b25d-11bc4b5f9a5d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d3cc69c0-4573-42ba-b25d-11bc4b5f9a5d> a person:Person.
           <http://data.lblod.info/id/personen/d3cc69c0-4573-42ba-b25d-11bc4b5f9a5d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d3cc69c0-4573-42ba-b25d-11bc4b5f9a5d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Chris".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d3cc69c0-4573-42ba-b25d-11bc4b5f9a5d> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/1a267f72-5fb7-4810-92ef-041199ff9c0d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1a267f72-5fb7-4810-92ef-041199ff9c0d> a person:Person.
           <http://data.lblod.info/id/personen/1a267f72-5fb7-4810-92ef-041199ff9c0d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1a267f72-5fb7-4810-92ef-041199ff9c0d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jeannette".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1a267f72-5fb7-4810-92ef-041199ff9c0d> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/bcd028a3-b9ae-42dc-8f2a-c957627ae214> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bcd028a3-b9ae-42dc-8f2a-c957627ae214> a person:Person.
           <http://data.lblod.info/id/personen/bcd028a3-b9ae-42dc-8f2a-c957627ae214> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bcd028a3-b9ae-42dc-8f2a-c957627ae214> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Luc".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bcd028a3-b9ae-42dc-8f2a-c957627ae214> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e9b4ce94-908b-4abc-b3fb-63a961843654> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e9b4ce94-908b-4abc-b3fb-63a961843654> a person:Person.
           <http://data.lblod.info/id/personen/e9b4ce94-908b-4abc-b3fb-63a961843654> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e9b4ce94-908b-4abc-b3fb-63a961843654> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marleen".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e9b4ce94-908b-4abc-b3fb-63a961843654> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ab4176f8-4295-4c23-b98d-051234212340> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ab4176f8-4295-4c23-b98d-051234212340> a person:Person.
           <http://data.lblod.info/id/personen/ab4176f8-4295-4c23-b98d-051234212340> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ab4176f8-4295-4c23-b98d-051234212340> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jean".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ab4176f8-4295-4c23-b98d-051234212340> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/05ee2b19-10fd-4053-8a0f-d8ea87903e2a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/05ee2b19-10fd-4053-8a0f-d8ea87903e2a> a person:Person.
           <http://data.lblod.info/id/personen/05ee2b19-10fd-4053-8a0f-d8ea87903e2a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/05ee2b19-10fd-4053-8a0f-d8ea87903e2a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Eddy".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/05ee2b19-10fd-4053-8a0f-d8ea87903e2a> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2a33ef4c-dd39-45fb-9f72-6e53a57ba382> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2a33ef4c-dd39-45fb-9f72-6e53a57ba382> a person:Person.
           <http://data.lblod.info/id/personen/2a33ef4c-dd39-45fb-9f72-6e53a57ba382> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2a33ef4c-dd39-45fb-9f72-6e53a57ba382> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "John".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2a33ef4c-dd39-45fb-9f72-6e53a57ba382> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/eaacb733a0fa19d4e437a7efd86a190b5e0887fa4d18040c8c4fad8625d34099> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/eaacb733a0fa19d4e437a7efd86a190b5e0887fa4d18040c8c4fad8625d34099> a person:Person.
           <http://data.lblod.info/id/personen/eaacb733a0fa19d4e437a7efd86a190b5e0887fa4d18040c8c4fad8625d34099> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/eaacb733a0fa19d4e437a7efd86a190b5e0887fa4d18040c8c4fad8625d34099> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ilse".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/eaacb733a0fa19d4e437a7efd86a190b5e0887fa4d18040c8c4fad8625d34099> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/a8f2f1df2eef052d72506a1971790dfd82618757b3c3382e4a7f16463f2758c7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a8f2f1df2eef052d72506a1971790dfd82618757b3c3382e4a7f16463f2758c7> a person:Person.
           <http://data.lblod.info/id/personen/a8f2f1df2eef052d72506a1971790dfd82618757b3c3382e4a7f16463f2758c7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a8f2f1df2eef052d72506a1971790dfd82618757b3c3382e4a7f16463f2758c7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Machteld".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a8f2f1df2eef052d72506a1971790dfd82618757b3c3382e4a7f16463f2758c7> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/c9e534091fd42a05c668a8463da0193d1cf7273ec674bdbf63982dd1ed38a1d8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c9e534091fd42a05c668a8463da0193d1cf7273ec674bdbf63982dd1ed38a1d8> a person:Person.
           <http://data.lblod.info/id/personen/c9e534091fd42a05c668a8463da0193d1cf7273ec674bdbf63982dd1ed38a1d8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c9e534091fd42a05c668a8463da0193d1cf7273ec674bdbf63982dd1ed38a1d8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Peter".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c9e534091fd42a05c668a8463da0193d1cf7273ec674bdbf63982dd1ed38a1d8> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/5a041a11c0af89b21783861f7e321bc58a353170cb485a760ce3eb2276258735> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5a041a11c0af89b21783861f7e321bc58a353170cb485a760ce3eb2276258735> a person:Person.
           <http://data.lblod.info/id/personen/5a041a11c0af89b21783861f7e321bc58a353170cb485a760ce3eb2276258735> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5a041a11c0af89b21783861f7e321bc58a353170cb485a760ce3eb2276258735> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Rita".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5a041a11c0af89b21783861f7e321bc58a353170cb485a760ce3eb2276258735> [] [].
          }
        }
     # finished voornamen-update-1342-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:05:39+00:00