# started voornamen-update-3723-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:05:44+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/fad62f3c-6b7c-4f69-a95d-c33ed0a46428> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/fad62f3c-6b7c-4f69-a95d-c33ed0a46428> a person:Person.
           <http://data.lblod.info/id/personen/fad62f3c-6b7c-4f69-a95d-c33ed0a46428> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/fad62f3c-6b7c-4f69-a95d-c33ed0a46428> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Koen".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/fad62f3c-6b7c-4f69-a95d-c33ed0a46428> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e8b7ac05-6aee-4a11-a3cd-f9fdb2c82a00> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e8b7ac05-6aee-4a11-a3cd-f9fdb2c82a00> a person:Person.
           <http://data.lblod.info/id/personen/e8b7ac05-6aee-4a11-a3cd-f9fdb2c82a00> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e8b7ac05-6aee-4a11-a3cd-f9fdb2c82a00> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Sandra".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e8b7ac05-6aee-4a11-a3cd-f9fdb2c82a00> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/eeefe40b-abbb-4cf7-b6bd-b963873359d3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/eeefe40b-abbb-4cf7-b6bd-b963873359d3> a person:Person.
           <http://data.lblod.info/id/personen/eeefe40b-abbb-4cf7-b6bd-b963873359d3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/eeefe40b-abbb-4cf7-b6bd-b963873359d3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marcel".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/eeefe40b-abbb-4cf7-b6bd-b963873359d3> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/479facc0-9fd7-48ff-a28d-200ff39e288a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/479facc0-9fd7-48ff-a28d-200ff39e288a> a person:Person.
           <http://data.lblod.info/id/personen/479facc0-9fd7-48ff-a28d-200ff39e288a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/479facc0-9fd7-48ff-a28d-200ff39e288a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Paul".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/479facc0-9fd7-48ff-a28d-200ff39e288a> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/1f363f9e-d354-4d5e-90f4-21371625fd4b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1f363f9e-d354-4d5e-90f4-21371625fd4b> a person:Person.
           <http://data.lblod.info/id/personen/1f363f9e-d354-4d5e-90f4-21371625fd4b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1f363f9e-d354-4d5e-90f4-21371625fd4b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Sandra".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1f363f9e-d354-4d5e-90f4-21371625fd4b> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/4f04fbd4-d5c5-4395-ab00-65a0e21543c2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4f04fbd4-d5c5-4395-ab00-65a0e21543c2> a person:Person.
           <http://data.lblod.info/id/personen/4f04fbd4-d5c5-4395-ab00-65a0e21543c2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4f04fbd4-d5c5-4395-ab00-65a0e21543c2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Philippe".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4f04fbd4-d5c5-4395-ab00-65a0e21543c2> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e088a913-1405-47c5-b793-a484da99298a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e088a913-1405-47c5-b793-a484da99298a> a person:Person.
           <http://data.lblod.info/id/personen/e088a913-1405-47c5-b793-a484da99298a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e088a913-1405-47c5-b793-a484da99298a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Kim".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e088a913-1405-47c5-b793-a484da99298a> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/becd1573-8a9f-460c-82a8-66adc5a788be> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/becd1573-8a9f-460c-82a8-66adc5a788be> a person:Person.
           <http://data.lblod.info/id/personen/becd1573-8a9f-460c-82a8-66adc5a788be> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/becd1573-8a9f-460c-82a8-66adc5a788be> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ivan".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/becd1573-8a9f-460c-82a8-66adc5a788be> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/c25d6a7a-05f9-4e7e-95b6-4ea7bf933035> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c25d6a7a-05f9-4e7e-95b6-4ea7bf933035> a person:Person.
           <http://data.lblod.info/id/personen/c25d6a7a-05f9-4e7e-95b6-4ea7bf933035> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c25d6a7a-05f9-4e7e-95b6-4ea7bf933035> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Sarah".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c25d6a7a-05f9-4e7e-95b6-4ea7bf933035> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/887f52e2-5d9b-477a-b0f9-0f7030cd1eb8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/887f52e2-5d9b-477a-b0f9-0f7030cd1eb8> a person:Person.
           <http://data.lblod.info/id/personen/887f52e2-5d9b-477a-b0f9-0f7030cd1eb8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/887f52e2-5d9b-477a-b0f9-0f7030cd1eb8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marie-Louise".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/887f52e2-5d9b-477a-b0f9-0f7030cd1eb8> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f60636da-c450-4964-81b9-c5256d1c8290> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f60636da-c450-4964-81b9-c5256d1c8290> a person:Person.
           <http://data.lblod.info/id/personen/f60636da-c450-4964-81b9-c5256d1c8290> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f60636da-c450-4964-81b9-c5256d1c8290> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Tom".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f60636da-c450-4964-81b9-c5256d1c8290> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/81c1f429-8212-422e-a643-0887e29ea5d9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/81c1f429-8212-422e-a643-0887e29ea5d9> a person:Person.
           <http://data.lblod.info/id/personen/81c1f429-8212-422e-a643-0887e29ea5d9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/81c1f429-8212-422e-a643-0887e29ea5d9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Alexander".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/81c1f429-8212-422e-a643-0887e29ea5d9> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/181af646-529a-45c2-a947-1b87885a5151> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/181af646-529a-45c2-a947-1b87885a5151> a person:Person.
           <http://data.lblod.info/id/personen/181af646-529a-45c2-a947-1b87885a5151> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/181af646-529a-45c2-a947-1b87885a5151> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Yve".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/181af646-529a-45c2-a947-1b87885a5151> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/cae6675a5a81d4f93b50e17a7c219aed427935ea047c0162c9c966b5a637c601> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cae6675a5a81d4f93b50e17a7c219aed427935ea047c0162c9c966b5a637c601> a person:Person.
           <http://data.lblod.info/id/personen/cae6675a5a81d4f93b50e17a7c219aed427935ea047c0162c9c966b5a637c601> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cae6675a5a81d4f93b50e17a7c219aed427935ea047c0162c9c966b5a637c601> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jef".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cae6675a5a81d4f93b50e17a7c219aed427935ea047c0162c9c966b5a637c601> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/5906bb81-b7e4-465f-baa6-33f010e046e7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5906bb81-b7e4-465f-baa6-33f010e046e7> a person:Person.
           <http://data.lblod.info/id/personen/5906bb81-b7e4-465f-baa6-33f010e046e7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5906bb81-b7e4-465f-baa6-33f010e046e7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Benjamin".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5906bb81-b7e4-465f-baa6-33f010e046e7> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/db44e16e-7ba6-4918-88b2-588c7a3cb86e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/db44e16e-7ba6-4918-88b2-588c7a3cb86e> a person:Person.
           <http://data.lblod.info/id/personen/db44e16e-7ba6-4918-88b2-588c7a3cb86e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/db44e16e-7ba6-4918-88b2-588c7a3cb86e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Lindsey".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/db44e16e-7ba6-4918-88b2-588c7a3cb86e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/d63f9840-38dd-4e66-bb42-fa4f36094b31> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d63f9840-38dd-4e66-bb42-fa4f36094b31> a person:Person.
           <http://data.lblod.info/id/personen/d63f9840-38dd-4e66-bb42-fa4f36094b31> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d63f9840-38dd-4e66-bb42-fa4f36094b31> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Vicky".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d63f9840-38dd-4e66-bb42-fa4f36094b31> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/3ad2299ce90877711f3fe3de34ece9e0f033122ab41dcea35b485958a7199a13> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3ad2299ce90877711f3fe3de34ece9e0f033122ab41dcea35b485958a7199a13> a person:Person.
           <http://data.lblod.info/id/personen/3ad2299ce90877711f3fe3de34ece9e0f033122ab41dcea35b485958a7199a13> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3ad2299ce90877711f3fe3de34ece9e0f033122ab41dcea35b485958a7199a13> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Aline".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3ad2299ce90877711f3fe3de34ece9e0f033122ab41dcea35b485958a7199a13> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/45dcb836-58f9-4da8-a27e-28e3efdb08d8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/45dcb836-58f9-4da8-a27e-28e3efdb08d8> a person:Person.
           <http://data.lblod.info/id/personen/45dcb836-58f9-4da8-a27e-28e3efdb08d8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/45dcb836-58f9-4da8-a27e-28e3efdb08d8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Maria".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/45dcb836-58f9-4da8-a27e-28e3efdb08d8> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/7d80b18dab664179f35e8f84c054ceb680b047840242c893e45699c76745ec14> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7d80b18dab664179f35e8f84c054ceb680b047840242c893e45699c76745ec14> a person:Person.
           <http://data.lblod.info/id/personen/7d80b18dab664179f35e8f84c054ceb680b047840242c893e45699c76745ec14> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7d80b18dab664179f35e8f84c054ceb680b047840242c893e45699c76745ec14> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Maria".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7d80b18dab664179f35e8f84c054ceb680b047840242c893e45699c76745ec14> [] [].
          }
        }
     # finished voornamen-update-3723-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:05:44+00:00