# started voornamen-update-35412-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:07:04+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/d5127ef3-a9d1-4660-b6d5-96f4e9267eaa> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d5127ef3-a9d1-4660-b6d5-96f4e9267eaa> a person:Person.
           <http://data.lblod.info/id/personen/d5127ef3-a9d1-4660-b6d5-96f4e9267eaa> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d5127ef3-a9d1-4660-b6d5-96f4e9267eaa> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Patrick".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d5127ef3-a9d1-4660-b6d5-96f4e9267eaa> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/01df6ab3-8f27-4f9b-b051-cd8b99ca2295> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/01df6ab3-8f27-4f9b-b051-cd8b99ca2295> a person:Person.
           <http://data.lblod.info/id/personen/01df6ab3-8f27-4f9b-b051-cd8b99ca2295> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/01df6ab3-8f27-4f9b-b051-cd8b99ca2295> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Yoshi".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/01df6ab3-8f27-4f9b-b051-cd8b99ca2295> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/fa5c99dd-8b7a-4676-a991-703ddfce7833> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/fa5c99dd-8b7a-4676-a991-703ddfce7833> a person:Person.
           <http://data.lblod.info/id/personen/fa5c99dd-8b7a-4676-a991-703ddfce7833> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/fa5c99dd-8b7a-4676-a991-703ddfce7833> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Luc".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/fa5c99dd-8b7a-4676-a991-703ddfce7833> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/98491048-af22-4249-b58b-12b7946fa4bf> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/98491048-af22-4249-b58b-12b7946fa4bf> a person:Person.
           <http://data.lblod.info/id/personen/98491048-af22-4249-b58b-12b7946fa4bf> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/98491048-af22-4249-b58b-12b7946fa4bf> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Paula".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/98491048-af22-4249-b58b-12b7946fa4bf> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f1db51de-7058-40b6-a254-84e72bf07f61> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f1db51de-7058-40b6-a254-84e72bf07f61> a person:Person.
           <http://data.lblod.info/id/personen/f1db51de-7058-40b6-a254-84e72bf07f61> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f1db51de-7058-40b6-a254-84e72bf07f61> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Frank".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f1db51de-7058-40b6-a254-84e72bf07f61> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/5b6278101abac829a114102d200660e86fe34e9b5391da9f53ca5bb58ba66365> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5b6278101abac829a114102d200660e86fe34e9b5391da9f53ca5bb58ba66365> a person:Person.
           <http://data.lblod.info/id/personen/5b6278101abac829a114102d200660e86fe34e9b5391da9f53ca5bb58ba66365> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5b6278101abac829a114102d200660e86fe34e9b5391da9f53ca5bb58ba66365> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Dominiek".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5b6278101abac829a114102d200660e86fe34e9b5391da9f53ca5bb58ba66365> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ec8f8fa4-acff-4e64-8205-ffa9a32783e1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ec8f8fa4-acff-4e64-8205-ffa9a32783e1> a person:Person.
           <http://data.lblod.info/id/personen/ec8f8fa4-acff-4e64-8205-ffa9a32783e1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ec8f8fa4-acff-4e64-8205-ffa9a32783e1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ria".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ec8f8fa4-acff-4e64-8205-ffa9a32783e1> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/47cfdf97c506a6a8ec77bcb661e1dfd8166bbaccccf93e200e5e0130a247ac3b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/47cfdf97c506a6a8ec77bcb661e1dfd8166bbaccccf93e200e5e0130a247ac3b> a person:Person.
           <http://data.lblod.info/id/personen/47cfdf97c506a6a8ec77bcb661e1dfd8166bbaccccf93e200e5e0130a247ac3b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/47cfdf97c506a6a8ec77bcb661e1dfd8166bbaccccf93e200e5e0130a247ac3b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Johan".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/47cfdf97c506a6a8ec77bcb661e1dfd8166bbaccccf93e200e5e0130a247ac3b> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/32a223c2528588ba97db3976589ff91f611134d652bdfc3b8eeed2051dab4dff> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/32a223c2528588ba97db3976589ff91f611134d652bdfc3b8eeed2051dab4dff> a person:Person.
           <http://data.lblod.info/id/personen/32a223c2528588ba97db3976589ff91f611134d652bdfc3b8eeed2051dab4dff> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/32a223c2528588ba97db3976589ff91f611134d652bdfc3b8eeed2051dab4dff> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Chantal".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/32a223c2528588ba97db3976589ff91f611134d652bdfc3b8eeed2051dab4dff> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e584c084-dd89-473a-96fd-c792f64d0be5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e584c084-dd89-473a-96fd-c792f64d0be5> a person:Person.
           <http://data.lblod.info/id/personen/e584c084-dd89-473a-96fd-c792f64d0be5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e584c084-dd89-473a-96fd-c792f64d0be5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Gilbert".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e584c084-dd89-473a-96fd-c792f64d0be5> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/81c1c2cbe35869d5fde0a7cc2158de5cc0722f7d2fc91982efc4da837a40b20f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/81c1c2cbe35869d5fde0a7cc2158de5cc0722f7d2fc91982efc4da837a40b20f> a person:Person.
           <http://data.lblod.info/id/personen/81c1c2cbe35869d5fde0a7cc2158de5cc0722f7d2fc91982efc4da837a40b20f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/81c1c2cbe35869d5fde0a7cc2158de5cc0722f7d2fc91982efc4da837a40b20f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Theo".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/81c1c2cbe35869d5fde0a7cc2158de5cc0722f7d2fc91982efc4da837a40b20f> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/93b41c81-2dd4-4f51-a149-ea3f4f793435> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/93b41c81-2dd4-4f51-a149-ea3f4f793435> a person:Person.
           <http://data.lblod.info/id/personen/93b41c81-2dd4-4f51-a149-ea3f4f793435> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/93b41c81-2dd4-4f51-a149-ea3f4f793435> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Nathalie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/93b41c81-2dd4-4f51-a149-ea3f4f793435> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f716224e-33c2-46e0-934a-b50afe6224e9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f716224e-33c2-46e0-934a-b50afe6224e9> a person:Person.
           <http://data.lblod.info/id/personen/f716224e-33c2-46e0-934a-b50afe6224e9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f716224e-33c2-46e0-934a-b50afe6224e9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Guido".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f716224e-33c2-46e0-934a-b50afe6224e9> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/8daee25847064de0767182e852df8c8e3f288326d9a3cd50515e505165e905b3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8daee25847064de0767182e852df8c8e3f288326d9a3cd50515e505165e905b3> a person:Person.
           <http://data.lblod.info/id/personen/8daee25847064de0767182e852df8c8e3f288326d9a3cd50515e505165e905b3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8daee25847064de0767182e852df8c8e3f288326d9a3cd50515e505165e905b3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Germaine".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8daee25847064de0767182e852df8c8e3f288326d9a3cd50515e505165e905b3> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/dc145225da66f92dab1df2be46313e7d35b36c6b2f7b35f1b7358ed3373827fb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/dc145225da66f92dab1df2be46313e7d35b36c6b2f7b35f1b7358ed3373827fb> a person:Person.
           <http://data.lblod.info/id/personen/dc145225da66f92dab1df2be46313e7d35b36c6b2f7b35f1b7358ed3373827fb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/dc145225da66f92dab1df2be46313e7d35b36c6b2f7b35f1b7358ed3373827fb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Eddy".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/dc145225da66f92dab1df2be46313e7d35b36c6b2f7b35f1b7358ed3373827fb> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/65403e7f77029fde06eca6d90283b81425d12b97e1ca9619ac0cdf7d8a07b6eb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/65403e7f77029fde06eca6d90283b81425d12b97e1ca9619ac0cdf7d8a07b6eb> a person:Person.
           <http://data.lblod.info/id/personen/65403e7f77029fde06eca6d90283b81425d12b97e1ca9619ac0cdf7d8a07b6eb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/65403e7f77029fde06eca6d90283b81425d12b97e1ca9619ac0cdf7d8a07b6eb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jef".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/65403e7f77029fde06eca6d90283b81425d12b97e1ca9619ac0cdf7d8a07b6eb> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/937f37dd-e666-462b-9a9b-b17dd6ee13bf> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/937f37dd-e666-462b-9a9b-b17dd6ee13bf> a person:Person.
           <http://data.lblod.info/id/personen/937f37dd-e666-462b-9a9b-b17dd6ee13bf> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/937f37dd-e666-462b-9a9b-b17dd6ee13bf> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Cathy".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/937f37dd-e666-462b-9a9b-b17dd6ee13bf> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/c812864f-799d-48fb-b22a-7c3bf50a3263> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c812864f-799d-48fb-b22a-7c3bf50a3263> a person:Person.
           <http://data.lblod.info/id/personen/c812864f-799d-48fb-b22a-7c3bf50a3263> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c812864f-799d-48fb-b22a-7c3bf50a3263> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Benny".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c812864f-799d-48fb-b22a-7c3bf50a3263> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/4f7f8829-3b29-44cd-8352-9886fd315d3a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4f7f8829-3b29-44cd-8352-9886fd315d3a> a person:Person.
           <http://data.lblod.info/id/personen/4f7f8829-3b29-44cd-8352-9886fd315d3a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4f7f8829-3b29-44cd-8352-9886fd315d3a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Steffen".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4f7f8829-3b29-44cd-8352-9886fd315d3a> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2450407c87463d0b9996963b3ea9a528282e386d20c2fbda146f786c5854f848> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2450407c87463d0b9996963b3ea9a528282e386d20c2fbda146f786c5854f848> a person:Person.
           <http://data.lblod.info/id/personen/2450407c87463d0b9996963b3ea9a528282e386d20c2fbda146f786c5854f848> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2450407c87463d0b9996963b3ea9a528282e386d20c2fbda146f786c5854f848> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Bianca".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2450407c87463d0b9996963b3ea9a528282e386d20c2fbda146f786c5854f848> [] [].
          }
        }
     # finished voornamen-update-35412-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:07:04+00:00