# started voornamen-update-2032-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:05:40+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/251cc567-f187-43ed-9b62-5da4d3975550> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/251cc567-f187-43ed-9b62-5da4d3975550> a person:Person.
           <http://data.lblod.info/id/personen/251cc567-f187-43ed-9b62-5da4d3975550> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/251cc567-f187-43ed-9b62-5da4d3975550> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marina".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/251cc567-f187-43ed-9b62-5da4d3975550> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/6b85b13f-f9ec-400e-8c8b-6451b151fdb3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6b85b13f-f9ec-400e-8c8b-6451b151fdb3> a person:Person.
           <http://data.lblod.info/id/personen/6b85b13f-f9ec-400e-8c8b-6451b151fdb3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6b85b13f-f9ec-400e-8c8b-6451b151fdb3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marijke".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6b85b13f-f9ec-400e-8c8b-6451b151fdb3> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2a162075-c706-4ed8-b3e9-e60e3725729d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2a162075-c706-4ed8-b3e9-e60e3725729d> a person:Person.
           <http://data.lblod.info/id/personen/2a162075-c706-4ed8-b3e9-e60e3725729d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2a162075-c706-4ed8-b3e9-e60e3725729d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Carl".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2a162075-c706-4ed8-b3e9-e60e3725729d> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e7146a926a3a358d17c2084c22fe154adf5c007bbc89aef241c18cde84e20be0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e7146a926a3a358d17c2084c22fe154adf5c007bbc89aef241c18cde84e20be0> a person:Person.
           <http://data.lblod.info/id/personen/e7146a926a3a358d17c2084c22fe154adf5c007bbc89aef241c18cde84e20be0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e7146a926a3a358d17c2084c22fe154adf5c007bbc89aef241c18cde84e20be0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Koenraad".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e7146a926a3a358d17c2084c22fe154adf5c007bbc89aef241c18cde84e20be0> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/fdfe592d0fa8aa2738ea4913e79111a78bda138a32954365daa8029fb9f0ef3d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/fdfe592d0fa8aa2738ea4913e79111a78bda138a32954365daa8029fb9f0ef3d> a person:Person.
           <http://data.lblod.info/id/personen/fdfe592d0fa8aa2738ea4913e79111a78bda138a32954365daa8029fb9f0ef3d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/fdfe592d0fa8aa2738ea4913e79111a78bda138a32954365daa8029fb9f0ef3d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Rosette".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/fdfe592d0fa8aa2738ea4913e79111a78bda138a32954365daa8029fb9f0ef3d> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/68029ec9970fdd7bacb4c3dc28dc3aa4d7961b13ddef5247d9ba839989cd8509> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/68029ec9970fdd7bacb4c3dc28dc3aa4d7961b13ddef5247d9ba839989cd8509> a person:Person.
           <http://data.lblod.info/id/personen/68029ec9970fdd7bacb4c3dc28dc3aa4d7961b13ddef5247d9ba839989cd8509> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/68029ec9970fdd7bacb4c3dc28dc3aa4d7961b13ddef5247d9ba839989cd8509> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Valerie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/68029ec9970fdd7bacb4c3dc28dc3aa4d7961b13ddef5247d9ba839989cd8509> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/c7e77c4f-245b-40d3-82d7-cc73d97f027e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c7e77c4f-245b-40d3-82d7-cc73d97f027e> a person:Person.
           <http://data.lblod.info/id/personen/c7e77c4f-245b-40d3-82d7-cc73d97f027e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c7e77c4f-245b-40d3-82d7-cc73d97f027e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Nancy".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c7e77c4f-245b-40d3-82d7-cc73d97f027e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/25402e5e-bddb-4489-8bea-aa74f5354f4f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/25402e5e-bddb-4489-8bea-aa74f5354f4f> a person:Person.
           <http://data.lblod.info/id/personen/25402e5e-bddb-4489-8bea-aa74f5354f4f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/25402e5e-bddb-4489-8bea-aa74f5354f4f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Firoozeh".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/25402e5e-bddb-4489-8bea-aa74f5354f4f> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2563042ab0f73631707001008243feed0eb6e07d10f19ae70f04de6a439941ae> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2563042ab0f73631707001008243feed0eb6e07d10f19ae70f04de6a439941ae> a person:Person.
           <http://data.lblod.info/id/personen/2563042ab0f73631707001008243feed0eb6e07d10f19ae70f04de6a439941ae> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2563042ab0f73631707001008243feed0eb6e07d10f19ae70f04de6a439941ae> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Hendrik".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2563042ab0f73631707001008243feed0eb6e07d10f19ae70f04de6a439941ae> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/854799d62a995b6b55b06e98d0cd032a0badf6564ef4b71df815b38206d981be> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/854799d62a995b6b55b06e98d0cd032a0badf6564ef4b71df815b38206d981be> a person:Person.
           <http://data.lblod.info/id/personen/854799d62a995b6b55b06e98d0cd032a0badf6564ef4b71df815b38206d981be> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/854799d62a995b6b55b06e98d0cd032a0badf6564ef4b71df815b38206d981be> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Lieva".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/854799d62a995b6b55b06e98d0cd032a0badf6564ef4b71df815b38206d981be> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ddc9f401-b4a4-491b-a13f-d875230d2bad> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ddc9f401-b4a4-491b-a13f-d875230d2bad> a person:Person.
           <http://data.lblod.info/id/personen/ddc9f401-b4a4-491b-a13f-d875230d2bad> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ddc9f401-b4a4-491b-a13f-d875230d2bad> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Gilbert".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ddc9f401-b4a4-491b-a13f-d875230d2bad> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/c5ab315d-6116-4995-9813-a9a2cc2b4d88> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c5ab315d-6116-4995-9813-a9a2cc2b4d88> a person:Person.
           <http://data.lblod.info/id/personen/c5ab315d-6116-4995-9813-a9a2cc2b4d88> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c5ab315d-6116-4995-9813-a9a2cc2b4d88> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Nicole".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c5ab315d-6116-4995-9813-a9a2cc2b4d88> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/49829003ed4e551b35664f03fab452cc1341487f71789ef3816b64bc66c54b95> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/49829003ed4e551b35664f03fab452cc1341487f71789ef3816b64bc66c54b95> a person:Person.
           <http://data.lblod.info/id/personen/49829003ed4e551b35664f03fab452cc1341487f71789ef3816b64bc66c54b95> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/49829003ed4e551b35664f03fab452cc1341487f71789ef3816b64bc66c54b95> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Lieve".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/49829003ed4e551b35664f03fab452cc1341487f71789ef3816b64bc66c54b95> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/cc86568b-adac-43ff-9b9d-ee6114cf4b99> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cc86568b-adac-43ff-9b9d-ee6114cf4b99> a person:Person.
           <http://data.lblod.info/id/personen/cc86568b-adac-43ff-9b9d-ee6114cf4b99> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cc86568b-adac-43ff-9b9d-ee6114cf4b99> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ronald".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cc86568b-adac-43ff-9b9d-ee6114cf4b99> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/59b225c2-3328-4fa9-9052-d457037e55b2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/59b225c2-3328-4fa9-9052-d457037e55b2> a person:Person.
           <http://data.lblod.info/id/personen/59b225c2-3328-4fa9-9052-d457037e55b2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/59b225c2-3328-4fa9-9052-d457037e55b2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Mireille".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/59b225c2-3328-4fa9-9052-d457037e55b2> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/d668d1e7-7e1c-404f-8660-073477e6ddb5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d668d1e7-7e1c-404f-8660-073477e6ddb5> a person:Person.
           <http://data.lblod.info/id/personen/d668d1e7-7e1c-404f-8660-073477e6ddb5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d668d1e7-7e1c-404f-8660-073477e6ddb5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Peter".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d668d1e7-7e1c-404f-8660-073477e6ddb5> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/93e21707-92f9-48e9-ab1b-51db1a8d71cf> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/93e21707-92f9-48e9-ab1b-51db1a8d71cf> a person:Person.
           <http://data.lblod.info/id/personen/93e21707-92f9-48e9-ab1b-51db1a8d71cf> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/93e21707-92f9-48e9-ab1b-51db1a8d71cf> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Anne-Sophie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/93e21707-92f9-48e9-ab1b-51db1a8d71cf> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/782306a8-396d-49cd-8bc2-c59fd9761b03> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/782306a8-396d-49cd-8bc2-c59fd9761b03> a person:Person.
           <http://data.lblod.info/id/personen/782306a8-396d-49cd-8bc2-c59fd9761b03> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/782306a8-396d-49cd-8bc2-c59fd9761b03> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Wilfried".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/782306a8-396d-49cd-8bc2-c59fd9761b03> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/02f8f220986c0b5f04d8c5bbf768a67c237765cd66a15b942dffd60090ae482b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/02f8f220986c0b5f04d8c5bbf768a67c237765cd66a15b942dffd60090ae482b> a person:Person.
           <http://data.lblod.info/id/personen/02f8f220986c0b5f04d8c5bbf768a67c237765cd66a15b942dffd60090ae482b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/02f8f220986c0b5f04d8c5bbf768a67c237765cd66a15b942dffd60090ae482b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Winne".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/02f8f220986c0b5f04d8c5bbf768a67c237765cd66a15b942dffd60090ae482b> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/619b87b3-bf63-44fa-b682-e1bc8b838e85> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/619b87b3-bf63-44fa-b682-e1bc8b838e85> a person:Person.
           <http://data.lblod.info/id/personen/619b87b3-bf63-44fa-b682-e1bc8b838e85> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/619b87b3-bf63-44fa-b682-e1bc8b838e85> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Niels".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/619b87b3-bf63-44fa-b682-e1bc8b838e85> [] [].
          }
        }
     # finished voornamen-update-2032-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:05:40+00:00