# started voornamen-update-1081-210375db6a6848160966cb7c5aeecf1a8b0d75c2bb93e0f0e03001e306f62438 at 2018-12-27T15:07:14+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/eced882e-2c42-4153-91b0-851233fcc7b3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/eced882e-2c42-4153-91b0-851233fcc7b3> a person:Person.
           <http://data.lblod.info/id/personen/eced882e-2c42-4153-91b0-851233fcc7b3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/eced882e-2c42-4153-91b0-851233fcc7b3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jan".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/eced882e-2c42-4153-91b0-851233fcc7b3> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/b6b38f47c08eabddb0094a595d87033f9afe8629e6bb46143329a5300ed90cfb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b6b38f47c08eabddb0094a595d87033f9afe8629e6bb46143329a5300ed90cfb> a person:Person.
           <http://data.lblod.info/id/personen/b6b38f47c08eabddb0094a595d87033f9afe8629e6bb46143329a5300ed90cfb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b6b38f47c08eabddb0094a595d87033f9afe8629e6bb46143329a5300ed90cfb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Sabine".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b6b38f47c08eabddb0094a595d87033f9afe8629e6bb46143329a5300ed90cfb> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/c19e1850-a49a-463f-bebc-a423316fec39> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c19e1850-a49a-463f-bebc-a423316fec39> a person:Person.
           <http://data.lblod.info/id/personen/c19e1850-a49a-463f-bebc-a423316fec39> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c19e1850-a49a-463f-bebc-a423316fec39> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Wim".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c19e1850-a49a-463f-bebc-a423316fec39> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/d1f5b0c333edaf74ca407d8302b1f7e09bcb10c47b6071be737c3c338e222d68> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d1f5b0c333edaf74ca407d8302b1f7e09bcb10c47b6071be737c3c338e222d68> a person:Person.
           <http://data.lblod.info/id/personen/d1f5b0c333edaf74ca407d8302b1f7e09bcb10c47b6071be737c3c338e222d68> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d1f5b0c333edaf74ca407d8302b1f7e09bcb10c47b6071be737c3c338e222d68> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Patricia".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d1f5b0c333edaf74ca407d8302b1f7e09bcb10c47b6071be737c3c338e222d68> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/19b6a7e90eea4826e728bcc5163f0829fdce0ea075b7028d5793e1cabc04431d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/19b6a7e90eea4826e728bcc5163f0829fdce0ea075b7028d5793e1cabc04431d> a person:Person.
           <http://data.lblod.info/id/personen/19b6a7e90eea4826e728bcc5163f0829fdce0ea075b7028d5793e1cabc04431d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/19b6a7e90eea4826e728bcc5163f0829fdce0ea075b7028d5793e1cabc04431d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Sonja".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/19b6a7e90eea4826e728bcc5163f0829fdce0ea075b7028d5793e1cabc04431d> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/1dc9cb65f4a893dac574c61bad0da162384b272d408be3f3b8facb2312629aaf> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1dc9cb65f4a893dac574c61bad0da162384b272d408be3f3b8facb2312629aaf> a person:Person.
           <http://data.lblod.info/id/personen/1dc9cb65f4a893dac574c61bad0da162384b272d408be3f3b8facb2312629aaf> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1dc9cb65f4a893dac574c61bad0da162384b272d408be3f3b8facb2312629aaf> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Tom".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1dc9cb65f4a893dac574c61bad0da162384b272d408be3f3b8facb2312629aaf> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/5b6f5b74-f233-42fb-9195-b50ef3c946fc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5b6f5b74-f233-42fb-9195-b50ef3c946fc> a person:Person.
           <http://data.lblod.info/id/personen/5b6f5b74-f233-42fb-9195-b50ef3c946fc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5b6f5b74-f233-42fb-9195-b50ef3c946fc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Tina".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5b6f5b74-f233-42fb-9195-b50ef3c946fc> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/8c1d9a6e-76fc-4bd2-89de-7466b5cd1a58> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8c1d9a6e-76fc-4bd2-89de-7466b5cd1a58> a person:Person.
           <http://data.lblod.info/id/personen/8c1d9a6e-76fc-4bd2-89de-7466b5cd1a58> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8c1d9a6e-76fc-4bd2-89de-7466b5cd1a58> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Els".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8c1d9a6e-76fc-4bd2-89de-7466b5cd1a58> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/bc66df0f-4ebd-423f-b7f2-9682a9e7bab6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bc66df0f-4ebd-423f-b7f2-9682a9e7bab6> a person:Person.
           <http://data.lblod.info/id/personen/bc66df0f-4ebd-423f-b7f2-9682a9e7bab6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bc66df0f-4ebd-423f-b7f2-9682a9e7bab6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Kalbie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bc66df0f-4ebd-423f-b7f2-9682a9e7bab6> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/71c6a846-0d4e-441b-91d0-7a11e98f92bd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/71c6a846-0d4e-441b-91d0-7a11e98f92bd> a person:Person.
           <http://data.lblod.info/id/personen/71c6a846-0d4e-441b-91d0-7a11e98f92bd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/71c6a846-0d4e-441b-91d0-7a11e98f92bd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Alf".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/71c6a846-0d4e-441b-91d0-7a11e98f92bd> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f6582fa0-fed6-40e7-a5f7-4b9962ea594d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f6582fa0-fed6-40e7-a5f7-4b9962ea594d> a person:Person.
           <http://data.lblod.info/id/personen/f6582fa0-fed6-40e7-a5f7-4b9962ea594d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f6582fa0-fed6-40e7-a5f7-4b9962ea594d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Celine".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f6582fa0-fed6-40e7-a5f7-4b9962ea594d> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/0909aec1-19f6-4219-bda7-8a9edbed0ab1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0909aec1-19f6-4219-bda7-8a9edbed0ab1> a person:Person.
           <http://data.lblod.info/id/personen/0909aec1-19f6-4219-bda7-8a9edbed0ab1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0909aec1-19f6-4219-bda7-8a9edbed0ab1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Michael".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0909aec1-19f6-4219-bda7-8a9edbed0ab1> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/135e6a01-bc20-46b5-b785-34b9714e83a0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/135e6a01-bc20-46b5-b785-34b9714e83a0> a person:Person.
           <http://data.lblod.info/id/personen/135e6a01-bc20-46b5-b785-34b9714e83a0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/135e6a01-bc20-46b5-b785-34b9714e83a0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Sara".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/135e6a01-bc20-46b5-b785-34b9714e83a0> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/180c4f83-b433-4762-8963-19368786d1df> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/180c4f83-b433-4762-8963-19368786d1df> a person:Person.
           <http://data.lblod.info/id/personen/180c4f83-b433-4762-8963-19368786d1df> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/180c4f83-b433-4762-8963-19368786d1df> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Thomas".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/180c4f83-b433-4762-8963-19368786d1df> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/76bb2bac-8e42-46c1-9c6f-e85bd6fd70f7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/76bb2bac-8e42-46c1-9c6f-e85bd6fd70f7> a person:Person.
           <http://data.lblod.info/id/personen/76bb2bac-8e42-46c1-9c6f-e85bd6fd70f7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/76bb2bac-8e42-46c1-9c6f-e85bd6fd70f7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Nouchka".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/76bb2bac-8e42-46c1-9c6f-e85bd6fd70f7> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/929f7966-7feb-4659-9211-b27b9ea47de0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/929f7966-7feb-4659-9211-b27b9ea47de0> a person:Person.
           <http://data.lblod.info/id/personen/929f7966-7feb-4659-9211-b27b9ea47de0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/929f7966-7feb-4659-9211-b27b9ea47de0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Tamara".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/929f7966-7feb-4659-9211-b27b9ea47de0> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/eab66c85-5506-44e3-b051-28d91f8fd5d5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/eab66c85-5506-44e3-b051-28d91f8fd5d5> a person:Person.
           <http://data.lblod.info/id/personen/eab66c85-5506-44e3-b051-28d91f8fd5d5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/eab66c85-5506-44e3-b051-28d91f8fd5d5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Angelo".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/eab66c85-5506-44e3-b051-28d91f8fd5d5> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/69de218f-214c-434f-aa7c-e3be51c723d9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/69de218f-214c-434f-aa7c-e3be51c723d9> a person:Person.
           <http://data.lblod.info/id/personen/69de218f-214c-434f-aa7c-e3be51c723d9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/69de218f-214c-434f-aa7c-e3be51c723d9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Chris".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/69de218f-214c-434f-aa7c-e3be51c723d9> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/df3d36a5-4485-4b9b-9eb9-b9f323d2afa2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/df3d36a5-4485-4b9b-9eb9-b9f323d2afa2> a person:Person.
           <http://data.lblod.info/id/personen/df3d36a5-4485-4b9b-9eb9-b9f323d2afa2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/df3d36a5-4485-4b9b-9eb9-b9f323d2afa2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Robin".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/df3d36a5-4485-4b9b-9eb9-b9f323d2afa2> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/378b2ad4-f559-4869-ba38-d5c4ca5ca6e3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/378b2ad4-f559-4869-ba38-d5c4ca5ca6e3> a person:Person.
           <http://data.lblod.info/id/personen/378b2ad4-f559-4869-ba38-d5c4ca5ca6e3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/378b2ad4-f559-4869-ba38-d5c4ca5ca6e3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Reza".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/378b2ad4-f559-4869-ba38-d5c4ca5ca6e3> [] [].
          }
        }
     # finished voornamen-update-1081-210375db6a6848160966cb7c5aeecf1a8b0d75c2bb93e0f0e03001e306f62438 at 2018-12-27T15:07:14+00:00