# started voornamen-update-29296-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:49+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/59bf1e01-0338-4bd1-9f64-3ff11809dc98> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/59bf1e01-0338-4bd1-9f64-3ff11809dc98> a person:Person.
           <http://data.lblod.info/id/personen/59bf1e01-0338-4bd1-9f64-3ff11809dc98> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/59bf1e01-0338-4bd1-9f64-3ff11809dc98> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jeannine".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/59bf1e01-0338-4bd1-9f64-3ff11809dc98> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f8c4b240-aef2-43e3-83f9-5e470a7a5a83> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f8c4b240-aef2-43e3-83f9-5e470a7a5a83> a person:Person.
           <http://data.lblod.info/id/personen/f8c4b240-aef2-43e3-83f9-5e470a7a5a83> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f8c4b240-aef2-43e3-83f9-5e470a7a5a83> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Anita".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f8c4b240-aef2-43e3-83f9-5e470a7a5a83> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ebb375b9-5396-45cc-a9a5-375a5f2fbbf9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ebb375b9-5396-45cc-a9a5-375a5f2fbbf9> a person:Person.
           <http://data.lblod.info/id/personen/ebb375b9-5396-45cc-a9a5-375a5f2fbbf9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ebb375b9-5396-45cc-a9a5-375a5f2fbbf9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jeanine".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ebb375b9-5396-45cc-a9a5-375a5f2fbbf9> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ff9801ed-01e7-4631-b8ec-4f6b94729c48> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ff9801ed-01e7-4631-b8ec-4f6b94729c48> a person:Person.
           <http://data.lblod.info/id/personen/ff9801ed-01e7-4631-b8ec-4f6b94729c48> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ff9801ed-01e7-4631-b8ec-4f6b94729c48> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Rita".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ff9801ed-01e7-4631-b8ec-4f6b94729c48> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f5998417-091b-4c72-b1fc-efae8ac7cfe5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f5998417-091b-4c72-b1fc-efae8ac7cfe5> a person:Person.
           <http://data.lblod.info/id/personen/f5998417-091b-4c72-b1fc-efae8ac7cfe5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f5998417-091b-4c72-b1fc-efae8ac7cfe5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Raymonda".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f5998417-091b-4c72-b1fc-efae8ac7cfe5> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/084a8d2c-a86e-43a7-902a-e690a91d5e8c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/084a8d2c-a86e-43a7-902a-e690a91d5e8c> a person:Person.
           <http://data.lblod.info/id/personen/084a8d2c-a86e-43a7-902a-e690a91d5e8c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/084a8d2c-a86e-43a7-902a-e690a91d5e8c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Isabel".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/084a8d2c-a86e-43a7-902a-e690a91d5e8c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/bb4c90ed-822b-43d1-b70e-7f0103429481> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bb4c90ed-822b-43d1-b70e-7f0103429481> a person:Person.
           <http://data.lblod.info/id/personen/bb4c90ed-822b-43d1-b70e-7f0103429481> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bb4c90ed-822b-43d1-b70e-7f0103429481> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Kurt".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bb4c90ed-822b-43d1-b70e-7f0103429481> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/9bf8a2e5c4b7cd069da48d6a4d74763fbe43beae4dd64351949b47200790faca> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9bf8a2e5c4b7cd069da48d6a4d74763fbe43beae4dd64351949b47200790faca> a person:Person.
           <http://data.lblod.info/id/personen/9bf8a2e5c4b7cd069da48d6a4d74763fbe43beae4dd64351949b47200790faca> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9bf8a2e5c4b7cd069da48d6a4d74763fbe43beae4dd64351949b47200790faca> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Patrick".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9bf8a2e5c4b7cd069da48d6a4d74763fbe43beae4dd64351949b47200790faca> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/55208943-3007-4ea8-945f-63a4a05fedad> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/55208943-3007-4ea8-945f-63a4a05fedad> a person:Person.
           <http://data.lblod.info/id/personen/55208943-3007-4ea8-945f-63a4a05fedad> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/55208943-3007-4ea8-945f-63a4a05fedad> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Luc".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/55208943-3007-4ea8-945f-63a4a05fedad> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/c37f3d51-0085-40d4-bc13-84d0d4e82d64> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c37f3d51-0085-40d4-bc13-84d0d4e82d64> a person:Person.
           <http://data.lblod.info/id/personen/c37f3d51-0085-40d4-bc13-84d0d4e82d64> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c37f3d51-0085-40d4-bc13-84d0d4e82d64> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Katia".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c37f3d51-0085-40d4-bc13-84d0d4e82d64> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/32cf632cef38a7a46346fe34d3621f484f42f80acb2dc1af2912854a88638725> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/32cf632cef38a7a46346fe34d3621f484f42f80acb2dc1af2912854a88638725> a person:Person.
           <http://data.lblod.info/id/personen/32cf632cef38a7a46346fe34d3621f484f42f80acb2dc1af2912854a88638725> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/32cf632cef38a7a46346fe34d3621f484f42f80acb2dc1af2912854a88638725> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ria".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/32cf632cef38a7a46346fe34d3621f484f42f80acb2dc1af2912854a88638725> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/0c21eb12-382c-4e21-9763-f5822175d03d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0c21eb12-382c-4e21-9763-f5822175d03d> a person:Person.
           <http://data.lblod.info/id/personen/0c21eb12-382c-4e21-9763-f5822175d03d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0c21eb12-382c-4e21-9763-f5822175d03d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Myriam".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0c21eb12-382c-4e21-9763-f5822175d03d> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/aa177473ccf5603d8285dd637dd337a2d1c849e3f544ad56a12afcfa0c7a9233> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/aa177473ccf5603d8285dd637dd337a2d1c849e3f544ad56a12afcfa0c7a9233> a person:Person.
           <http://data.lblod.info/id/personen/aa177473ccf5603d8285dd637dd337a2d1c849e3f544ad56a12afcfa0c7a9233> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/aa177473ccf5603d8285dd637dd337a2d1c849e3f544ad56a12afcfa0c7a9233> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jürgen".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/aa177473ccf5603d8285dd637dd337a2d1c849e3f544ad56a12afcfa0c7a9233> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/17e0c2e6-59cf-47a4-bfb9-6faa3a3b5857> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/17e0c2e6-59cf-47a4-bfb9-6faa3a3b5857> a person:Person.
           <http://data.lblod.info/id/personen/17e0c2e6-59cf-47a4-bfb9-6faa3a3b5857> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/17e0c2e6-59cf-47a4-bfb9-6faa3a3b5857> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Agnes".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/17e0c2e6-59cf-47a4-bfb9-6faa3a3b5857> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/d71a574c-dfd5-4a4a-8730-92326f216f91> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d71a574c-dfd5-4a4a-8730-92326f216f91> a person:Person.
           <http://data.lblod.info/id/personen/d71a574c-dfd5-4a4a-8730-92326f216f91> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d71a574c-dfd5-4a4a-8730-92326f216f91> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Els".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d71a574c-dfd5-4a4a-8730-92326f216f91> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e300460b16740d4b8804bb250ea7d0d7ba6d8cb0b0c09da0253ce35b8bd586d8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e300460b16740d4b8804bb250ea7d0d7ba6d8cb0b0c09da0253ce35b8bd586d8> a person:Person.
           <http://data.lblod.info/id/personen/e300460b16740d4b8804bb250ea7d0d7ba6d8cb0b0c09da0253ce35b8bd586d8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e300460b16740d4b8804bb250ea7d0d7ba6d8cb0b0c09da0253ce35b8bd586d8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Niels".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e300460b16740d4b8804bb250ea7d0d7ba6d8cb0b0c09da0253ce35b8bd586d8> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/a9feb1e7-6848-4175-8241-a668a5a74d02> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a9feb1e7-6848-4175-8241-a668a5a74d02> a person:Person.
           <http://data.lblod.info/id/personen/a9feb1e7-6848-4175-8241-a668a5a74d02> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a9feb1e7-6848-4175-8241-a668a5a74d02> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Charlotte".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a9feb1e7-6848-4175-8241-a668a5a74d02> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e2641f7749b34dc33148187acbda452fdbc8626ef8856cac5e8fd08295197872> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e2641f7749b34dc33148187acbda452fdbc8626ef8856cac5e8fd08295197872> a person:Person.
           <http://data.lblod.info/id/personen/e2641f7749b34dc33148187acbda452fdbc8626ef8856cac5e8fd08295197872> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e2641f7749b34dc33148187acbda452fdbc8626ef8856cac5e8fd08295197872> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Viviane".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e2641f7749b34dc33148187acbda452fdbc8626ef8856cac5e8fd08295197872> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/a369985a-516e-47bd-a3e0-304cc90495f9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a369985a-516e-47bd-a3e0-304cc90495f9> a person:Person.
           <http://data.lblod.info/id/personen/a369985a-516e-47bd-a3e0-304cc90495f9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a369985a-516e-47bd-a3e0-304cc90495f9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Lesley".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a369985a-516e-47bd-a3e0-304cc90495f9> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/36066ef7-3393-42de-9628-f8a022cd1c20> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/36066ef7-3393-42de-9628-f8a022cd1c20> a person:Person.
           <http://data.lblod.info/id/personen/36066ef7-3393-42de-9628-f8a022cd1c20> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/36066ef7-3393-42de-9628-f8a022cd1c20> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Dirk".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/36066ef7-3393-42de-9628-f8a022cd1c20> [] [].
          }
        }
     # finished voornamen-update-29296-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:49+00:00