# started voornamen-update-2353-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:05:41+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/5054373b83809bc4b432bae2a76ceaa402c7f2972e2081e6e392ba8c6c4c06ea> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5054373b83809bc4b432bae2a76ceaa402c7f2972e2081e6e392ba8c6c4c06ea> a person:Person.
           <http://data.lblod.info/id/personen/5054373b83809bc4b432bae2a76ceaa402c7f2972e2081e6e392ba8c6c4c06ea> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5054373b83809bc4b432bae2a76ceaa402c7f2972e2081e6e392ba8c6c4c06ea> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Greet".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5054373b83809bc4b432bae2a76ceaa402c7f2972e2081e6e392ba8c6c4c06ea> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/02d39e90-1aea-434a-8579-7d44439a6396> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/02d39e90-1aea-434a-8579-7d44439a6396> a person:Person.
           <http://data.lblod.info/id/personen/02d39e90-1aea-434a-8579-7d44439a6396> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/02d39e90-1aea-434a-8579-7d44439a6396> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Gie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/02d39e90-1aea-434a-8579-7d44439a6396> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/7e440297b40ca125572a66a0ca687fba216710c7218069750e32f70874994fb6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7e440297b40ca125572a66a0ca687fba216710c7218069750e32f70874994fb6> a person:Person.
           <http://data.lblod.info/id/personen/7e440297b40ca125572a66a0ca687fba216710c7218069750e32f70874994fb6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7e440297b40ca125572a66a0ca687fba216710c7218069750e32f70874994fb6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Christiane".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7e440297b40ca125572a66a0ca687fba216710c7218069750e32f70874994fb6> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ffadc576083db90e8a7fecc5271b76619accc2b5e3a696d3a593f4b5987d658c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ffadc576083db90e8a7fecc5271b76619accc2b5e3a696d3a593f4b5987d658c> a person:Person.
           <http://data.lblod.info/id/personen/ffadc576083db90e8a7fecc5271b76619accc2b5e3a696d3a593f4b5987d658c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ffadc576083db90e8a7fecc5271b76619accc2b5e3a696d3a593f4b5987d658c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Monique".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ffadc576083db90e8a7fecc5271b76619accc2b5e3a696d3a593f4b5987d658c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2c73eaa2030fa02c65d405d6197f015f4354137b98d505ddb18ea59ed4fc64e4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2c73eaa2030fa02c65d405d6197f015f4354137b98d505ddb18ea59ed4fc64e4> a person:Person.
           <http://data.lblod.info/id/personen/2c73eaa2030fa02c65d405d6197f015f4354137b98d505ddb18ea59ed4fc64e4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2c73eaa2030fa02c65d405d6197f015f4354137b98d505ddb18ea59ed4fc64e4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Johan".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2c73eaa2030fa02c65d405d6197f015f4354137b98d505ddb18ea59ed4fc64e4> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/a83a06273b2e37f805f5f6f14a6b03c2679db5b017dfd24f61876188312ec508> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a83a06273b2e37f805f5f6f14a6b03c2679db5b017dfd24f61876188312ec508> a person:Person.
           <http://data.lblod.info/id/personen/a83a06273b2e37f805f5f6f14a6b03c2679db5b017dfd24f61876188312ec508> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a83a06273b2e37f805f5f6f14a6b03c2679db5b017dfd24f61876188312ec508> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Hans".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a83a06273b2e37f805f5f6f14a6b03c2679db5b017dfd24f61876188312ec508> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/da11f4b42bd0586184506018bb1f238b3e6535b43076262be7e5a70c0dd420d2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/da11f4b42bd0586184506018bb1f238b3e6535b43076262be7e5a70c0dd420d2> a person:Person.
           <http://data.lblod.info/id/personen/da11f4b42bd0586184506018bb1f238b3e6535b43076262be7e5a70c0dd420d2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/da11f4b42bd0586184506018bb1f238b3e6535b43076262be7e5a70c0dd420d2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jozef".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/da11f4b42bd0586184506018bb1f238b3e6535b43076262be7e5a70c0dd420d2> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/76b7dc42-99c3-4364-b7f4-de17114d7a95> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/76b7dc42-99c3-4364-b7f4-de17114d7a95> a person:Person.
           <http://data.lblod.info/id/personen/76b7dc42-99c3-4364-b7f4-de17114d7a95> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/76b7dc42-99c3-4364-b7f4-de17114d7a95> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Malvina".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/76b7dc42-99c3-4364-b7f4-de17114d7a95> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/0299e45a842584a71dd1f95a7838313e9ca47d9184acc874330f571e4eddb19c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0299e45a842584a71dd1f95a7838313e9ca47d9184acc874330f571e4eddb19c> a person:Person.
           <http://data.lblod.info/id/personen/0299e45a842584a71dd1f95a7838313e9ca47d9184acc874330f571e4eddb19c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0299e45a842584a71dd1f95a7838313e9ca47d9184acc874330f571e4eddb19c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marc".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0299e45a842584a71dd1f95a7838313e9ca47d9184acc874330f571e4eddb19c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/111d51e6106d3451dd269272a6dc56e1c0859e79d215b1d04dd99bba7b721e88> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/111d51e6106d3451dd269272a6dc56e1c0859e79d215b1d04dd99bba7b721e88> a person:Person.
           <http://data.lblod.info/id/personen/111d51e6106d3451dd269272a6dc56e1c0859e79d215b1d04dd99bba7b721e88> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/111d51e6106d3451dd269272a6dc56e1c0859e79d215b1d04dd99bba7b721e88> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Josée".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/111d51e6106d3451dd269272a6dc56e1c0859e79d215b1d04dd99bba7b721e88> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/295f239e2226c2f9bf5c4a6d4136685f2464a1b5293fe87e3cb2f558fd6cef97> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/295f239e2226c2f9bf5c4a6d4136685f2464a1b5293fe87e3cb2f558fd6cef97> a person:Person.
           <http://data.lblod.info/id/personen/295f239e2226c2f9bf5c4a6d4136685f2464a1b5293fe87e3cb2f558fd6cef97> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/295f239e2226c2f9bf5c4a6d4136685f2464a1b5293fe87e3cb2f558fd6cef97> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Dominique".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/295f239e2226c2f9bf5c4a6d4136685f2464a1b5293fe87e3cb2f558fd6cef97> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/feb736ee-bb35-47ed-8bf4-cb378f2184fb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/feb736ee-bb35-47ed-8bf4-cb378f2184fb> a person:Person.
           <http://data.lblod.info/id/personen/feb736ee-bb35-47ed-8bf4-cb378f2184fb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/feb736ee-bb35-47ed-8bf4-cb378f2184fb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Franky".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/feb736ee-bb35-47ed-8bf4-cb378f2184fb> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2720929a-60cf-4757-8b3e-b46a02200a54> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2720929a-60cf-4757-8b3e-b46a02200a54> a person:Person.
           <http://data.lblod.info/id/personen/2720929a-60cf-4757-8b3e-b46a02200a54> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2720929a-60cf-4757-8b3e-b46a02200a54> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Anne-Marie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2720929a-60cf-4757-8b3e-b46a02200a54> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/5930f631-24c9-44cf-b2f6-085fffe9239a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5930f631-24c9-44cf-b2f6-085fffe9239a> a person:Person.
           <http://data.lblod.info/id/personen/5930f631-24c9-44cf-b2f6-085fffe9239a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5930f631-24c9-44cf-b2f6-085fffe9239a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Patrick".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5930f631-24c9-44cf-b2f6-085fffe9239a> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/3c2f6dd4237ca5f89aa2b3d5e6b951601b43d0f354c65013e3c5e3c3cd996e3e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3c2f6dd4237ca5f89aa2b3d5e6b951601b43d0f354c65013e3c5e3c3cd996e3e> a person:Person.
           <http://data.lblod.info/id/personen/3c2f6dd4237ca5f89aa2b3d5e6b951601b43d0f354c65013e3c5e3c3cd996e3e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3c2f6dd4237ca5f89aa2b3d5e6b951601b43d0f354c65013e3c5e3c3cd996e3e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Luc".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3c2f6dd4237ca5f89aa2b3d5e6b951601b43d0f354c65013e3c5e3c3cd996e3e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f70ed0ad-4a9d-4ec8-82fb-f887b92b8b86> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f70ed0ad-4a9d-4ec8-82fb-f887b92b8b86> a person:Person.
           <http://data.lblod.info/id/personen/f70ed0ad-4a9d-4ec8-82fb-f887b92b8b86> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f70ed0ad-4a9d-4ec8-82fb-f887b92b8b86> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Sofie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f70ed0ad-4a9d-4ec8-82fb-f887b92b8b86> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/572b3124-b033-4301-92c8-df84e0dabf11> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/572b3124-b033-4301-92c8-df84e0dabf11> a person:Person.
           <http://data.lblod.info/id/personen/572b3124-b033-4301-92c8-df84e0dabf11> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/572b3124-b033-4301-92c8-df84e0dabf11> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Gino".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/572b3124-b033-4301-92c8-df84e0dabf11> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/716aa8eb-69bf-46c7-a66d-fa502cf0421e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/716aa8eb-69bf-46c7-a66d-fa502cf0421e> a person:Person.
           <http://data.lblod.info/id/personen/716aa8eb-69bf-46c7-a66d-fa502cf0421e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/716aa8eb-69bf-46c7-a66d-fa502cf0421e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Elke".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/716aa8eb-69bf-46c7-a66d-fa502cf0421e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/99b5e143-c107-42f3-8b96-a6598cb2acc4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/99b5e143-c107-42f3-8b96-a6598cb2acc4> a person:Person.
           <http://data.lblod.info/id/personen/99b5e143-c107-42f3-8b96-a6598cb2acc4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/99b5e143-c107-42f3-8b96-a6598cb2acc4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Laura".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/99b5e143-c107-42f3-8b96-a6598cb2acc4> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/5aad94e2-5d27-4483-8c01-4ba320f14ae0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5aad94e2-5d27-4483-8c01-4ba320f14ae0> a person:Person.
           <http://data.lblod.info/id/personen/5aad94e2-5d27-4483-8c01-4ba320f14ae0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5aad94e2-5d27-4483-8c01-4ba320f14ae0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Thomas".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5aad94e2-5d27-4483-8c01-4ba320f14ae0> [] [].
          }
        }
     # finished voornamen-update-2353-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:05:41+00:00