# started voornamen-update-5769-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:05:50+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/96a64c96-7db9-41f1-8cdc-b9d35041ff32> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/96a64c96-7db9-41f1-8cdc-b9d35041ff32> a person:Person.
           <http://data.lblod.info/id/personen/96a64c96-7db9-41f1-8cdc-b9d35041ff32> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/96a64c96-7db9-41f1-8cdc-b9d35041ff32> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Benny".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/96a64c96-7db9-41f1-8cdc-b9d35041ff32> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ed6cc5b5-721c-4314-a918-8e05e43e61df> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ed6cc5b5-721c-4314-a918-8e05e43e61df> a person:Person.
           <http://data.lblod.info/id/personen/ed6cc5b5-721c-4314-a918-8e05e43e61df> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ed6cc5b5-721c-4314-a918-8e05e43e61df> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Liesbeth".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ed6cc5b5-721c-4314-a918-8e05e43e61df> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/84f8abde-2890-4093-bb62-8bafd42c3809> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/84f8abde-2890-4093-bb62-8bafd42c3809> a person:Person.
           <http://data.lblod.info/id/personen/84f8abde-2890-4093-bb62-8bafd42c3809> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/84f8abde-2890-4093-bb62-8bafd42c3809> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marina".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/84f8abde-2890-4093-bb62-8bafd42c3809> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/0897c2c28ab4288f21da5e0c8c08215b285ab7d638d9d5f70c603ba5ab4bd4be> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0897c2c28ab4288f21da5e0c8c08215b285ab7d638d9d5f70c603ba5ab4bd4be> a person:Person.
           <http://data.lblod.info/id/personen/0897c2c28ab4288f21da5e0c8c08215b285ab7d638d9d5f70c603ba5ab4bd4be> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0897c2c28ab4288f21da5e0c8c08215b285ab7d638d9d5f70c603ba5ab4bd4be> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Guido".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0897c2c28ab4288f21da5e0c8c08215b285ab7d638d9d5f70c603ba5ab4bd4be> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/0ca67edf-68db-4ba4-8e4d-8f5500b59d01> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0ca67edf-68db-4ba4-8e4d-8f5500b59d01> a person:Person.
           <http://data.lblod.info/id/personen/0ca67edf-68db-4ba4-8e4d-8f5500b59d01> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0ca67edf-68db-4ba4-8e4d-8f5500b59d01> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Willy".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0ca67edf-68db-4ba4-8e4d-8f5500b59d01> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/4837627010d8f82b85799ead09837b26ace9c6acb22c8326eaeb7ebedec2fc0c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4837627010d8f82b85799ead09837b26ace9c6acb22c8326eaeb7ebedec2fc0c> a person:Person.
           <http://data.lblod.info/id/personen/4837627010d8f82b85799ead09837b26ace9c6acb22c8326eaeb7ebedec2fc0c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4837627010d8f82b85799ead09837b26ace9c6acb22c8326eaeb7ebedec2fc0c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Maria".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4837627010d8f82b85799ead09837b26ace9c6acb22c8326eaeb7ebedec2fc0c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/9addb2801a17d8661bab82ffbdac8d108f5ff1f9fbe451f57d708b004e0c7909> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9addb2801a17d8661bab82ffbdac8d108f5ff1f9fbe451f57d708b004e0c7909> a person:Person.
           <http://data.lblod.info/id/personen/9addb2801a17d8661bab82ffbdac8d108f5ff1f9fbe451f57d708b004e0c7909> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9addb2801a17d8661bab82ffbdac8d108f5ff1f9fbe451f57d708b004e0c7909> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Alex".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9addb2801a17d8661bab82ffbdac8d108f5ff1f9fbe451f57d708b004e0c7909> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/5adbba34-1a1c-49c5-968e-a7d308a81931> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5adbba34-1a1c-49c5-968e-a7d308a81931> a person:Person.
           <http://data.lblod.info/id/personen/5adbba34-1a1c-49c5-968e-a7d308a81931> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5adbba34-1a1c-49c5-968e-a7d308a81931> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marc".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5adbba34-1a1c-49c5-968e-a7d308a81931> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ee6a8782d25e4220c719b3931a0068ddf14d3ef6c7b8bd0415888b46b481ca04> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ee6a8782d25e4220c719b3931a0068ddf14d3ef6c7b8bd0415888b46b481ca04> a person:Person.
           <http://data.lblod.info/id/personen/ee6a8782d25e4220c719b3931a0068ddf14d3ef6c7b8bd0415888b46b481ca04> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ee6a8782d25e4220c719b3931a0068ddf14d3ef6c7b8bd0415888b46b481ca04> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Nele".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ee6a8782d25e4220c719b3931a0068ddf14d3ef6c7b8bd0415888b46b481ca04> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e23f00c19b9fe901a10ac73d4b57e8c1a4f0be4831a092afc3a033583f1366ec> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e23f00c19b9fe901a10ac73d4b57e8c1a4f0be4831a092afc3a033583f1366ec> a person:Person.
           <http://data.lblod.info/id/personen/e23f00c19b9fe901a10ac73d4b57e8c1a4f0be4831a092afc3a033583f1366ec> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e23f00c19b9fe901a10ac73d4b57e8c1a4f0be4831a092afc3a033583f1366ec> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Lydia".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e23f00c19b9fe901a10ac73d4b57e8c1a4f0be4831a092afc3a033583f1366ec> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/aa836cd6f3f3a16e6a215fab1bf34ecc1ec8570a517dda700af7c684a9c84a0e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/aa836cd6f3f3a16e6a215fab1bf34ecc1ec8570a517dda700af7c684a9c84a0e> a person:Person.
           <http://data.lblod.info/id/personen/aa836cd6f3f3a16e6a215fab1bf34ecc1ec8570a517dda700af7c684a9c84a0e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/aa836cd6f3f3a16e6a215fab1bf34ecc1ec8570a517dda700af7c684a9c84a0e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Brigitte".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/aa836cd6f3f3a16e6a215fab1bf34ecc1ec8570a517dda700af7c684a9c84a0e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/9c2727c7-f634-48ad-becb-23b6e9f916b2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9c2727c7-f634-48ad-becb-23b6e9f916b2> a person:Person.
           <http://data.lblod.info/id/personen/9c2727c7-f634-48ad-becb-23b6e9f916b2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9c2727c7-f634-48ad-becb-23b6e9f916b2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Gerry".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9c2727c7-f634-48ad-becb-23b6e9f916b2> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/d30ae986-90c4-4d01-91e8-786f64ee730a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d30ae986-90c4-4d01-91e8-786f64ee730a> a person:Person.
           <http://data.lblod.info/id/personen/d30ae986-90c4-4d01-91e8-786f64ee730a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d30ae986-90c4-4d01-91e8-786f64ee730a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Manuela".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d30ae986-90c4-4d01-91e8-786f64ee730a> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/699dc704-6767-455b-ba96-b09a4fd5660c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/699dc704-6767-455b-ba96-b09a4fd5660c> a person:Person.
           <http://data.lblod.info/id/personen/699dc704-6767-455b-ba96-b09a4fd5660c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/699dc704-6767-455b-ba96-b09a4fd5660c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Danny".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/699dc704-6767-455b-ba96-b09a4fd5660c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/b46191d2-8467-4ed1-96df-3b4bb5744101> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b46191d2-8467-4ed1-96df-3b4bb5744101> a person:Person.
           <http://data.lblod.info/id/personen/b46191d2-8467-4ed1-96df-3b4bb5744101> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b46191d2-8467-4ed1-96df-3b4bb5744101> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Johnny".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b46191d2-8467-4ed1-96df-3b4bb5744101> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ae8be2ab-bf6d-414e-aa87-18319ddde739> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ae8be2ab-bf6d-414e-aa87-18319ddde739> a person:Person.
           <http://data.lblod.info/id/personen/ae8be2ab-bf6d-414e-aa87-18319ddde739> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ae8be2ab-bf6d-414e-aa87-18319ddde739> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Frie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ae8be2ab-bf6d-414e-aa87-18319ddde739> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/1b5d1d89-e232-4644-8275-35aa5a36e2bc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1b5d1d89-e232-4644-8275-35aa5a36e2bc> a person:Person.
           <http://data.lblod.info/id/personen/1b5d1d89-e232-4644-8275-35aa5a36e2bc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1b5d1d89-e232-4644-8275-35aa5a36e2bc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Bart".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1b5d1d89-e232-4644-8275-35aa5a36e2bc> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/4661ce9b-15ac-4d7d-b105-a33b74e86ee6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4661ce9b-15ac-4d7d-b105-a33b74e86ee6> a person:Person.
           <http://data.lblod.info/id/personen/4661ce9b-15ac-4d7d-b105-a33b74e86ee6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4661ce9b-15ac-4d7d-b105-a33b74e86ee6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Bart".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4661ce9b-15ac-4d7d-b105-a33b74e86ee6> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/228441e8-5601-44d1-b9e7-99bae9b72f7c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/228441e8-5601-44d1-b9e7-99bae9b72f7c> a person:Person.
           <http://data.lblod.info/id/personen/228441e8-5601-44d1-b9e7-99bae9b72f7c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/228441e8-5601-44d1-b9e7-99bae9b72f7c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Stafke".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/228441e8-5601-44d1-b9e7-99bae9b72f7c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/c4aee07e-91df-4555-af22-785f9212093f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c4aee07e-91df-4555-af22-785f9212093f> a person:Person.
           <http://data.lblod.info/id/personen/c4aee07e-91df-4555-af22-785f9212093f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c4aee07e-91df-4555-af22-785f9212093f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Lut".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c4aee07e-91df-4555-af22-785f9212093f> [] [].
          }
        }
     # finished voornamen-update-5769-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:05:50+00:00