# started voornamen-update-30540-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:52+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/c8404b15-b32a-4574-9945-e296ceab87ae> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c8404b15-b32a-4574-9945-e296ceab87ae> a person:Person.
           <http://data.lblod.info/id/personen/c8404b15-b32a-4574-9945-e296ceab87ae> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c8404b15-b32a-4574-9945-e296ceab87ae> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jean".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c8404b15-b32a-4574-9945-e296ceab87ae> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/391c9d2e-62ac-4e6f-b178-c74b2f1e95cf> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/391c9d2e-62ac-4e6f-b178-c74b2f1e95cf> a person:Person.
           <http://data.lblod.info/id/personen/391c9d2e-62ac-4e6f-b178-c74b2f1e95cf> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/391c9d2e-62ac-4e6f-b178-c74b2f1e95cf> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Christel".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/391c9d2e-62ac-4e6f-b178-c74b2f1e95cf> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/1537be32-c005-45a4-af80-49f4b9a7e376> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1537be32-c005-45a4-af80-49f4b9a7e376> a person:Person.
           <http://data.lblod.info/id/personen/1537be32-c005-45a4-af80-49f4b9a7e376> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1537be32-c005-45a4-af80-49f4b9a7e376> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Rene".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1537be32-c005-45a4-af80-49f4b9a7e376> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/1cde91e0-1fde-4293-814a-afdf00dc7f38> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1cde91e0-1fde-4293-814a-afdf00dc7f38> a person:Person.
           <http://data.lblod.info/id/personen/1cde91e0-1fde-4293-814a-afdf00dc7f38> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1cde91e0-1fde-4293-814a-afdf00dc7f38> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jelle".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1cde91e0-1fde-4293-814a-afdf00dc7f38> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/bafc98c6-a930-41ff-9621-a98896c5972d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bafc98c6-a930-41ff-9621-a98896c5972d> a person:Person.
           <http://data.lblod.info/id/personen/bafc98c6-a930-41ff-9621-a98896c5972d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bafc98c6-a930-41ff-9621-a98896c5972d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Daniella".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bafc98c6-a930-41ff-9621-a98896c5972d> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/b4948fbb-a85f-4280-8946-181626ede03e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b4948fbb-a85f-4280-8946-181626ede03e> a person:Person.
           <http://data.lblod.info/id/personen/b4948fbb-a85f-4280-8946-181626ede03e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b4948fbb-a85f-4280-8946-181626ede03e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Francine".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b4948fbb-a85f-4280-8946-181626ede03e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/1b4b5bd0-b2c8-4ad1-ae2a-a798857719c7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1b4b5bd0-b2c8-4ad1-ae2a-a798857719c7> a person:Person.
           <http://data.lblod.info/id/personen/1b4b5bd0-b2c8-4ad1-ae2a-a798857719c7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1b4b5bd0-b2c8-4ad1-ae2a-a798857719c7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "David".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1b4b5bd0-b2c8-4ad1-ae2a-a798857719c7> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/c5af1771-d389-4997-bbf3-07b9f0b7ee70> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c5af1771-d389-4997-bbf3-07b9f0b7ee70> a person:Person.
           <http://data.lblod.info/id/personen/c5af1771-d389-4997-bbf3-07b9f0b7ee70> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c5af1771-d389-4997-bbf3-07b9f0b7ee70> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Sonja".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c5af1771-d389-4997-bbf3-07b9f0b7ee70> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/cf988138-7cc2-4d8a-89d7-badf0af5e3b7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cf988138-7cc2-4d8a-89d7-badf0af5e3b7> a person:Person.
           <http://data.lblod.info/id/personen/cf988138-7cc2-4d8a-89d7-badf0af5e3b7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cf988138-7cc2-4d8a-89d7-badf0af5e3b7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Elza".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cf988138-7cc2-4d8a-89d7-badf0af5e3b7> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/bcc188f169cad260badc2981e8dae05505973a8dee29ccab884b03fbb0a09199> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bcc188f169cad260badc2981e8dae05505973a8dee29ccab884b03fbb0a09199> a person:Person.
           <http://data.lblod.info/id/personen/bcc188f169cad260badc2981e8dae05505973a8dee29ccab884b03fbb0a09199> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bcc188f169cad260badc2981e8dae05505973a8dee29ccab884b03fbb0a09199> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jos".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bcc188f169cad260badc2981e8dae05505973a8dee29ccab884b03fbb0a09199> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/a562c70f36242793747432b7da56ef8fdb3e54555126ca7eb677ecf581f392df> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a562c70f36242793747432b7da56ef8fdb3e54555126ca7eb677ecf581f392df> a person:Person.
           <http://data.lblod.info/id/personen/a562c70f36242793747432b7da56ef8fdb3e54555126ca7eb677ecf581f392df> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a562c70f36242793747432b7da56ef8fdb3e54555126ca7eb677ecf581f392df> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Kris".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a562c70f36242793747432b7da56ef8fdb3e54555126ca7eb677ecf581f392df> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/23e7b6fafe73e18a1e2ea2385db2ef5bd54463d8092cfdbc9e75ccbd4cf98cb3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/23e7b6fafe73e18a1e2ea2385db2ef5bd54463d8092cfdbc9e75ccbd4cf98cb3> a person:Person.
           <http://data.lblod.info/id/personen/23e7b6fafe73e18a1e2ea2385db2ef5bd54463d8092cfdbc9e75ccbd4cf98cb3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/23e7b6fafe73e18a1e2ea2385db2ef5bd54463d8092cfdbc9e75ccbd4cf98cb3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Elsje".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/23e7b6fafe73e18a1e2ea2385db2ef5bd54463d8092cfdbc9e75ccbd4cf98cb3> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/17e5df6e-4602-461e-af5e-f029a43d44e8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/17e5df6e-4602-461e-af5e-f029a43d44e8> a person:Person.
           <http://data.lblod.info/id/personen/17e5df6e-4602-461e-af5e-f029a43d44e8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/17e5df6e-4602-461e-af5e-f029a43d44e8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Emilie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/17e5df6e-4602-461e-af5e-f029a43d44e8> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/707ded38-736a-42af-b510-9310870df289> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/707ded38-736a-42af-b510-9310870df289> a person:Person.
           <http://data.lblod.info/id/personen/707ded38-736a-42af-b510-9310870df289> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/707ded38-736a-42af-b510-9310870df289> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Bjorn".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/707ded38-736a-42af-b510-9310870df289> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/3b6fe8a7-22c8-4892-8f0e-7beb8adb921b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3b6fe8a7-22c8-4892-8f0e-7beb8adb921b> a person:Person.
           <http://data.lblod.info/id/personen/3b6fe8a7-22c8-4892-8f0e-7beb8adb921b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3b6fe8a7-22c8-4892-8f0e-7beb8adb921b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jo".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3b6fe8a7-22c8-4892-8f0e-7beb8adb921b> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ea41de46-b105-4c79-8a44-400896201f4a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ea41de46-b105-4c79-8a44-400896201f4a> a person:Person.
           <http://data.lblod.info/id/personen/ea41de46-b105-4c79-8a44-400896201f4a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ea41de46-b105-4c79-8a44-400896201f4a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Soraya".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ea41de46-b105-4c79-8a44-400896201f4a> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/8ca1df04-23af-4a9d-8627-97be42363f8f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8ca1df04-23af-4a9d-8627-97be42363f8f> a person:Person.
           <http://data.lblod.info/id/personen/8ca1df04-23af-4a9d-8627-97be42363f8f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8ca1df04-23af-4a9d-8627-97be42363f8f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Erik".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8ca1df04-23af-4a9d-8627-97be42363f8f> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/a40d4321-2c47-4dfd-be5b-733225817946> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a40d4321-2c47-4dfd-be5b-733225817946> a person:Person.
           <http://data.lblod.info/id/personen/a40d4321-2c47-4dfd-be5b-733225817946> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a40d4321-2c47-4dfd-be5b-733225817946> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Tim".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a40d4321-2c47-4dfd-be5b-733225817946> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f01ad204-ab45-498a-942b-0da8ad489e8d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f01ad204-ab45-498a-942b-0da8ad489e8d> a person:Person.
           <http://data.lblod.info/id/personen/f01ad204-ab45-498a-942b-0da8ad489e8d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f01ad204-ab45-498a-942b-0da8ad489e8d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Alain".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f01ad204-ab45-498a-942b-0da8ad489e8d> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/721fbf27-0ce7-4d2e-b739-f853ccf87102> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/721fbf27-0ce7-4d2e-b739-f853ccf87102> a person:Person.
           <http://data.lblod.info/id/personen/721fbf27-0ce7-4d2e-b739-f853ccf87102> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/721fbf27-0ce7-4d2e-b739-f853ccf87102> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ingrid".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/721fbf27-0ce7-4d2e-b739-f853ccf87102> [] [].
          }
        }
     # finished voornamen-update-30540-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:52+00:00