# started voornamen-update-28782-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:47+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/57831619d6338434515140f1455d27328f69604c9ee825cd74fc163b542aa73d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/57831619d6338434515140f1455d27328f69604c9ee825cd74fc163b542aa73d> a person:Person.
           <http://data.lblod.info/id/personen/57831619d6338434515140f1455d27328f69604c9ee825cd74fc163b542aa73d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/57831619d6338434515140f1455d27328f69604c9ee825cd74fc163b542aa73d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Paule".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/57831619d6338434515140f1455d27328f69604c9ee825cd74fc163b542aa73d> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/7245176d-fa90-47a4-acc5-8cf1e04e73f9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7245176d-fa90-47a4-acc5-8cf1e04e73f9> a person:Person.
           <http://data.lblod.info/id/personen/7245176d-fa90-47a4-acc5-8cf1e04e73f9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7245176d-fa90-47a4-acc5-8cf1e04e73f9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Albert".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7245176d-fa90-47a4-acc5-8cf1e04e73f9> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/57ec09ac-abef-4f9c-b9e7-596723070889> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/57ec09ac-abef-4f9c-b9e7-596723070889> a person:Person.
           <http://data.lblod.info/id/personen/57ec09ac-abef-4f9c-b9e7-596723070889> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/57ec09ac-abef-4f9c-b9e7-596723070889> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Agnelle".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/57ec09ac-abef-4f9c-b9e7-596723070889> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/8d3f39ba-0578-4f5e-981a-f3828ee44fd8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8d3f39ba-0578-4f5e-981a-f3828ee44fd8> a person:Person.
           <http://data.lblod.info/id/personen/8d3f39ba-0578-4f5e-981a-f3828ee44fd8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8d3f39ba-0578-4f5e-981a-f3828ee44fd8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Lucien".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8d3f39ba-0578-4f5e-981a-f3828ee44fd8> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/3d544ca618dd97919302dd56a99140f1c25ffc2923b901886bec0c946035cad0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3d544ca618dd97919302dd56a99140f1c25ffc2923b901886bec0c946035cad0> a person:Person.
           <http://data.lblod.info/id/personen/3d544ca618dd97919302dd56a99140f1c25ffc2923b901886bec0c946035cad0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3d544ca618dd97919302dd56a99140f1c25ffc2923b901886bec0c946035cad0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Bieke".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3d544ca618dd97919302dd56a99140f1c25ffc2923b901886bec0c946035cad0> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/d699cf63e4db5c308b786bcbc05c864b3855342120db4664a86bc9ad12755910> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d699cf63e4db5c308b786bcbc05c864b3855342120db4664a86bc9ad12755910> a person:Person.
           <http://data.lblod.info/id/personen/d699cf63e4db5c308b786bcbc05c864b3855342120db4664a86bc9ad12755910> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d699cf63e4db5c308b786bcbc05c864b3855342120db4664a86bc9ad12755910> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Rudy".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d699cf63e4db5c308b786bcbc05c864b3855342120db4664a86bc9ad12755910> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e7262ed6-4d7f-4006-8171-aa1982707f3b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e7262ed6-4d7f-4006-8171-aa1982707f3b> a person:Person.
           <http://data.lblod.info/id/personen/e7262ed6-4d7f-4006-8171-aa1982707f3b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e7262ed6-4d7f-4006-8171-aa1982707f3b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marc".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e7262ed6-4d7f-4006-8171-aa1982707f3b> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/36a4d5ff5e94af50a122d7d930f7ddaf1ba40ea03d1ccb14b407a6832c346747> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/36a4d5ff5e94af50a122d7d930f7ddaf1ba40ea03d1ccb14b407a6832c346747> a person:Person.
           <http://data.lblod.info/id/personen/36a4d5ff5e94af50a122d7d930f7ddaf1ba40ea03d1ccb14b407a6832c346747> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/36a4d5ff5e94af50a122d7d930f7ddaf1ba40ea03d1ccb14b407a6832c346747> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ireen".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/36a4d5ff5e94af50a122d7d930f7ddaf1ba40ea03d1ccb14b407a6832c346747> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/81f3c785-a618-47aa-95ac-0d42ad7a7f94> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/81f3c785-a618-47aa-95ac-0d42ad7a7f94> a person:Person.
           <http://data.lblod.info/id/personen/81f3c785-a618-47aa-95ac-0d42ad7a7f94> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/81f3c785-a618-47aa-95ac-0d42ad7a7f94> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Patrick".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/81f3c785-a618-47aa-95ac-0d42ad7a7f94> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/3084d381084301b29f45dc269a3068244b79ce0ad27e0382f922a3505892e14b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3084d381084301b29f45dc269a3068244b79ce0ad27e0382f922a3505892e14b> a person:Person.
           <http://data.lblod.info/id/personen/3084d381084301b29f45dc269a3068244b79ce0ad27e0382f922a3505892e14b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3084d381084301b29f45dc269a3068244b79ce0ad27e0382f922a3505892e14b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Peggy".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3084d381084301b29f45dc269a3068244b79ce0ad27e0382f922a3505892e14b> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/1d9789a2-84dc-4d0e-9ccc-a075f2b6c151> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1d9789a2-84dc-4d0e-9ccc-a075f2b6c151> a person:Person.
           <http://data.lblod.info/id/personen/1d9789a2-84dc-4d0e-9ccc-a075f2b6c151> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1d9789a2-84dc-4d0e-9ccc-a075f2b6c151> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Dominique".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1d9789a2-84dc-4d0e-9ccc-a075f2b6c151> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/974333df-ed9f-4895-a498-8352189f0921> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/974333df-ed9f-4895-a498-8352189f0921> a person:Person.
           <http://data.lblod.info/id/personen/974333df-ed9f-4895-a498-8352189f0921> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/974333df-ed9f-4895-a498-8352189f0921> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Natasja".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/974333df-ed9f-4895-a498-8352189f0921> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/8b66fee2-c168-4e65-98da-79658f8d5a69> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8b66fee2-c168-4e65-98da-79658f8d5a69> a person:Person.
           <http://data.lblod.info/id/personen/8b66fee2-c168-4e65-98da-79658f8d5a69> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8b66fee2-c168-4e65-98da-79658f8d5a69> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Diederik".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8b66fee2-c168-4e65-98da-79658f8d5a69> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/eb927edb10357af5bbc129237a33ba565f3b0668f2b125711820884bd0513411> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/eb927edb10357af5bbc129237a33ba565f3b0668f2b125711820884bd0513411> a person:Person.
           <http://data.lblod.info/id/personen/eb927edb10357af5bbc129237a33ba565f3b0668f2b125711820884bd0513411> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/eb927edb10357af5bbc129237a33ba565f3b0668f2b125711820884bd0513411> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marleen".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/eb927edb10357af5bbc129237a33ba565f3b0668f2b125711820884bd0513411> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/7b8232d8-ab4d-49c5-95aa-c74212860b4f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7b8232d8-ab4d-49c5-95aa-c74212860b4f> a person:Person.
           <http://data.lblod.info/id/personen/7b8232d8-ab4d-49c5-95aa-c74212860b4f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7b8232d8-ab4d-49c5-95aa-c74212860b4f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Steven".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7b8232d8-ab4d-49c5-95aa-c74212860b4f> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/4b3958fb-f4cc-4304-a80a-b6b18ab0761f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4b3958fb-f4cc-4304-a80a-b6b18ab0761f> a person:Person.
           <http://data.lblod.info/id/personen/4b3958fb-f4cc-4304-a80a-b6b18ab0761f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4b3958fb-f4cc-4304-a80a-b6b18ab0761f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Lieve".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4b3958fb-f4cc-4304-a80a-b6b18ab0761f> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/caf076fe-2466-4b0f-a33d-b122ff6dffbe> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/caf076fe-2466-4b0f-a33d-b122ff6dffbe> a person:Person.
           <http://data.lblod.info/id/personen/caf076fe-2466-4b0f-a33d-b122ff6dffbe> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/caf076fe-2466-4b0f-a33d-b122ff6dffbe> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Robin".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/caf076fe-2466-4b0f-a33d-b122ff6dffbe> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ac1b773c-72cf-4374-a3f1-43936935acb8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ac1b773c-72cf-4374-a3f1-43936935acb8> a person:Person.
           <http://data.lblod.info/id/personen/ac1b773c-72cf-4374-a3f1-43936935acb8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ac1b773c-72cf-4374-a3f1-43936935acb8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Lieve".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ac1b773c-72cf-4374-a3f1-43936935acb8> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/5449c940839f5b2947747b8b0b88079a1ce77e9bf9d85627bed6e4717b430c2f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5449c940839f5b2947747b8b0b88079a1ce77e9bf9d85627bed6e4717b430c2f> a person:Person.
           <http://data.lblod.info/id/personen/5449c940839f5b2947747b8b0b88079a1ce77e9bf9d85627bed6e4717b430c2f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5449c940839f5b2947747b8b0b88079a1ce77e9bf9d85627bed6e4717b430c2f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "An".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5449c940839f5b2947747b8b0b88079a1ce77e9bf9d85627bed6e4717b430c2f> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/cb4d15ab-88e5-4f52-984e-ebc5e4880b43> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cb4d15ab-88e5-4f52-984e-ebc5e4880b43> a person:Person.
           <http://data.lblod.info/id/personen/cb4d15ab-88e5-4f52-984e-ebc5e4880b43> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cb4d15ab-88e5-4f52-984e-ebc5e4880b43> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ruud".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cb4d15ab-88e5-4f52-984e-ebc5e4880b43> [] [].
          }
        }
     # finished voornamen-update-28782-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:47+00:00