# started voornamen-update-1483-2490de85e718ffa3e23344f4cd674bd5d9f40252833c8af6fb7fa3b82f44b008 at 2018-12-27T15:07:11+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/124d0d4a-32f3-40b9-a87d-27a69cf757ca> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/124d0d4a-32f3-40b9-a87d-27a69cf757ca> a person:Person.
           <http://data.lblod.info/id/personen/124d0d4a-32f3-40b9-a87d-27a69cf757ca> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/124d0d4a-32f3-40b9-a87d-27a69cf757ca> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Liesbet".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/124d0d4a-32f3-40b9-a87d-27a69cf757ca> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/72b28bb9850511bfad3d0a858604c36c93708c15f502c53126d843caee6f0c33> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/72b28bb9850511bfad3d0a858604c36c93708c15f502c53126d843caee6f0c33> a person:Person.
           <http://data.lblod.info/id/personen/72b28bb9850511bfad3d0a858604c36c93708c15f502c53126d843caee6f0c33> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/72b28bb9850511bfad3d0a858604c36c93708c15f502c53126d843caee6f0c33> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Maddy".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/72b28bb9850511bfad3d0a858604c36c93708c15f502c53126d843caee6f0c33> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/1a647878cf43b93e5bde9387a9308f054f8199f8286bd328916999006c226fcb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1a647878cf43b93e5bde9387a9308f054f8199f8286bd328916999006c226fcb> a person:Person.
           <http://data.lblod.info/id/personen/1a647878cf43b93e5bde9387a9308f054f8199f8286bd328916999006c226fcb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1a647878cf43b93e5bde9387a9308f054f8199f8286bd328916999006c226fcb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Dirk".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1a647878cf43b93e5bde9387a9308f054f8199f8286bd328916999006c226fcb> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/c8463e27-2a99-4fb6-8b76-8ceb8e330c47> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c8463e27-2a99-4fb6-8b76-8ceb8e330c47> a person:Person.
           <http://data.lblod.info/id/personen/c8463e27-2a99-4fb6-8b76-8ceb8e330c47> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c8463e27-2a99-4fb6-8b76-8ceb8e330c47> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Nathalie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c8463e27-2a99-4fb6-8b76-8ceb8e330c47> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/6957e3a85773cf83a7af52522a87496af074d844e9ea27d400b4f0e0c760dcb1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6957e3a85773cf83a7af52522a87496af074d844e9ea27d400b4f0e0c760dcb1> a person:Person.
           <http://data.lblod.info/id/personen/6957e3a85773cf83a7af52522a87496af074d844e9ea27d400b4f0e0c760dcb1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6957e3a85773cf83a7af52522a87496af074d844e9ea27d400b4f0e0c760dcb1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Tom".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6957e3a85773cf83a7af52522a87496af074d844e9ea27d400b4f0e0c760dcb1> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/1b1fec35-bc77-4206-9bf8-eeaf5fa51ec9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1b1fec35-bc77-4206-9bf8-eeaf5fa51ec9> a person:Person.
           <http://data.lblod.info/id/personen/1b1fec35-bc77-4206-9bf8-eeaf5fa51ec9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1b1fec35-bc77-4206-9bf8-eeaf5fa51ec9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Mathieu".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1b1fec35-bc77-4206-9bf8-eeaf5fa51ec9> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/7fec80b0-7fc7-4ec1-9cda-d57abe37521f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7fec80b0-7fc7-4ec1-9cda-d57abe37521f> a person:Person.
           <http://data.lblod.info/id/personen/7fec80b0-7fc7-4ec1-9cda-d57abe37521f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7fec80b0-7fc7-4ec1-9cda-d57abe37521f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Tessa".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7fec80b0-7fc7-4ec1-9cda-d57abe37521f> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/6b43f283-8af3-42ca-81d5-c149d8c639a5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6b43f283-8af3-42ca-81d5-c149d8c639a5> a person:Person.
           <http://data.lblod.info/id/personen/6b43f283-8af3-42ca-81d5-c149d8c639a5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6b43f283-8af3-42ca-81d5-c149d8c639a5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Katia".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6b43f283-8af3-42ca-81d5-c149d8c639a5> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/1a35f03f-2754-4ca9-b2e4-955e0c452ad8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1a35f03f-2754-4ca9-b2e4-955e0c452ad8> a person:Person.
           <http://data.lblod.info/id/personen/1a35f03f-2754-4ca9-b2e4-955e0c452ad8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1a35f03f-2754-4ca9-b2e4-955e0c452ad8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Zeen".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1a35f03f-2754-4ca9-b2e4-955e0c452ad8> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/03e5f59a-d0a6-4fa5-9f3f-510d289393e4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/03e5f59a-d0a6-4fa5-9f3f-510d289393e4> a person:Person.
           <http://data.lblod.info/id/personen/03e5f59a-d0a6-4fa5-9f3f-510d289393e4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/03e5f59a-d0a6-4fa5-9f3f-510d289393e4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Paul".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/03e5f59a-d0a6-4fa5-9f3f-510d289393e4> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e920745f-d33d-4cd4-bf08-dcf7082c07fc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e920745f-d33d-4cd4-bf08-dcf7082c07fc> a person:Person.
           <http://data.lblod.info/id/personen/e920745f-d33d-4cd4-bf08-dcf7082c07fc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e920745f-d33d-4cd4-bf08-dcf7082c07fc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ian".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e920745f-d33d-4cd4-bf08-dcf7082c07fc> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/15157274dec6c5046b09965fe7b4b23470b12d646a899383bb3ea39efc8562a3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/15157274dec6c5046b09965fe7b4b23470b12d646a899383bb3ea39efc8562a3> a person:Person.
           <http://data.lblod.info/id/personen/15157274dec6c5046b09965fe7b4b23470b12d646a899383bb3ea39efc8562a3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/15157274dec6c5046b09965fe7b4b23470b12d646a899383bb3ea39efc8562a3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Greet".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/15157274dec6c5046b09965fe7b4b23470b12d646a899383bb3ea39efc8562a3> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/4229482f267677e0bc722e9382fe14b790db4c00f006229588650646647a5128> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4229482f267677e0bc722e9382fe14b790db4c00f006229588650646647a5128> a person:Person.
           <http://data.lblod.info/id/personen/4229482f267677e0bc722e9382fe14b790db4c00f006229588650646647a5128> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4229482f267677e0bc722e9382fe14b790db4c00f006229588650646647a5128> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Gilbert".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4229482f267677e0bc722e9382fe14b790db4c00f006229588650646647a5128> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/10c4254a8d7935bbc0dd0ac6b98c459324568a3149e009bd11bc5835f2af9be7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/10c4254a8d7935bbc0dd0ac6b98c459324568a3149e009bd11bc5835f2af9be7> a person:Person.
           <http://data.lblod.info/id/personen/10c4254a8d7935bbc0dd0ac6b98c459324568a3149e009bd11bc5835f2af9be7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/10c4254a8d7935bbc0dd0ac6b98c459324568a3149e009bd11bc5835f2af9be7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Kristel".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/10c4254a8d7935bbc0dd0ac6b98c459324568a3149e009bd11bc5835f2af9be7> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/1f4c677ff3f39a2b7523f006bff9a2215df9022102befc07bed7f607c9b57492> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1f4c677ff3f39a2b7523f006bff9a2215df9022102befc07bed7f607c9b57492> a person:Person.
           <http://data.lblod.info/id/personen/1f4c677ff3f39a2b7523f006bff9a2215df9022102befc07bed7f607c9b57492> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1f4c677ff3f39a2b7523f006bff9a2215df9022102befc07bed7f607c9b57492> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Stef".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1f4c677ff3f39a2b7523f006bff9a2215df9022102befc07bed7f607c9b57492> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f9026b953798a6e539c15f96fe8ad768f8d8e59112f31063f2771d3feb7814e2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f9026b953798a6e539c15f96fe8ad768f8d8e59112f31063f2771d3feb7814e2> a person:Person.
           <http://data.lblod.info/id/personen/f9026b953798a6e539c15f96fe8ad768f8d8e59112f31063f2771d3feb7814e2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f9026b953798a6e539c15f96fe8ad768f8d8e59112f31063f2771d3feb7814e2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Julie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f9026b953798a6e539c15f96fe8ad768f8d8e59112f31063f2771d3feb7814e2> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/aa57a934c5a32d5bab3494d532cf2854df1e857b53cb98ae9ad8303ea3a5cb7f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/aa57a934c5a32d5bab3494d532cf2854df1e857b53cb98ae9ad8303ea3a5cb7f> a person:Person.
           <http://data.lblod.info/id/personen/aa57a934c5a32d5bab3494d532cf2854df1e857b53cb98ae9ad8303ea3a5cb7f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/aa57a934c5a32d5bab3494d532cf2854df1e857b53cb98ae9ad8303ea3a5cb7f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Steven".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/aa57a934c5a32d5bab3494d532cf2854df1e857b53cb98ae9ad8303ea3a5cb7f> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/af7118f87eb248dfc88196b76fdc9198b8c44f4f8ade3ea384c6f5ccea00959d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/af7118f87eb248dfc88196b76fdc9198b8c44f4f8ade3ea384c6f5ccea00959d> a person:Person.
           <http://data.lblod.info/id/personen/af7118f87eb248dfc88196b76fdc9198b8c44f4f8ade3ea384c6f5ccea00959d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/af7118f87eb248dfc88196b76fdc9198b8c44f4f8ade3ea384c6f5ccea00959d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Angèle".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/af7118f87eb248dfc88196b76fdc9198b8c44f4f8ade3ea384c6f5ccea00959d> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/7ccf5b2f6e4df83f20cbc77497fa32ced410851cfd730ec7f0fb48b6d68c1943> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7ccf5b2f6e4df83f20cbc77497fa32ced410851cfd730ec7f0fb48b6d68c1943> a person:Person.
           <http://data.lblod.info/id/personen/7ccf5b2f6e4df83f20cbc77497fa32ced410851cfd730ec7f0fb48b6d68c1943> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7ccf5b2f6e4df83f20cbc77497fa32ced410851cfd730ec7f0fb48b6d68c1943> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Lucienne".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7ccf5b2f6e4df83f20cbc77497fa32ced410851cfd730ec7f0fb48b6d68c1943> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/b317ccec1139a514c908da1381fab0db65d781e7eff014de847f1066897b5ddb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b317ccec1139a514c908da1381fab0db65d781e7eff014de847f1066897b5ddb> a person:Person.
           <http://data.lblod.info/id/personen/b317ccec1139a514c908da1381fab0db65d781e7eff014de847f1066897b5ddb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b317ccec1139a514c908da1381fab0db65d781e7eff014de847f1066897b5ddb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Luc".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b317ccec1139a514c908da1381fab0db65d781e7eff014de847f1066897b5ddb> [] [].
          }
        }
     # finished voornamen-update-1483-2490de85e718ffa3e23344f4cd674bd5d9f40252833c8af6fb7fa3b82f44b008 at 2018-12-27T15:07:11+00:00