# started voornamen-update-18976-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:22+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2881c071-da31-405e-ad6e-31547340ba41> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2881c071-da31-405e-ad6e-31547340ba41> a person:Person.
           <http://data.lblod.info/id/personen/2881c071-da31-405e-ad6e-31547340ba41> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2881c071-da31-405e-ad6e-31547340ba41> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Malika".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2881c071-da31-405e-ad6e-31547340ba41> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ced3f9a5-45ff-4328-b693-ac4ea972f3db> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ced3f9a5-45ff-4328-b693-ac4ea972f3db> a person:Person.
           <http://data.lblod.info/id/personen/ced3f9a5-45ff-4328-b693-ac4ea972f3db> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ced3f9a5-45ff-4328-b693-ac4ea972f3db> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Lorenzo".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ced3f9a5-45ff-4328-b693-ac4ea972f3db> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f1d8805a-2b73-43e1-9c98-e8af8ecdf5fc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f1d8805a-2b73-43e1-9c98-e8af8ecdf5fc> a person:Person.
           <http://data.lblod.info/id/personen/f1d8805a-2b73-43e1-9c98-e8af8ecdf5fc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f1d8805a-2b73-43e1-9c98-e8af8ecdf5fc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Genia".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f1d8805a-2b73-43e1-9c98-e8af8ecdf5fc> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ba1b5474-51c3-4e54-9f92-481db7dfbb57> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ba1b5474-51c3-4e54-9f92-481db7dfbb57> a person:Person.
           <http://data.lblod.info/id/personen/ba1b5474-51c3-4e54-9f92-481db7dfbb57> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ba1b5474-51c3-4e54-9f92-481db7dfbb57> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jean-Pierre".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ba1b5474-51c3-4e54-9f92-481db7dfbb57> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/94208b22-6b2b-419a-994d-63524b2c28c6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/94208b22-6b2b-419a-994d-63524b2c28c6> a person:Person.
           <http://data.lblod.info/id/personen/94208b22-6b2b-419a-994d-63524b2c28c6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/94208b22-6b2b-419a-994d-63524b2c28c6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Nathalie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/94208b22-6b2b-419a-994d-63524b2c28c6> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f5ffeaf3-ba30-4433-81b7-89e7420a7baa> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f5ffeaf3-ba30-4433-81b7-89e7420a7baa> a person:Person.
           <http://data.lblod.info/id/personen/f5ffeaf3-ba30-4433-81b7-89e7420a7baa> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f5ffeaf3-ba30-4433-81b7-89e7420a7baa> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ronald".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f5ffeaf3-ba30-4433-81b7-89e7420a7baa> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/45a76774-3201-4978-98d4-58a91f7a3845> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/45a76774-3201-4978-98d4-58a91f7a3845> a person:Person.
           <http://data.lblod.info/id/personen/45a76774-3201-4978-98d4-58a91f7a3845> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/45a76774-3201-4978-98d4-58a91f7a3845> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Steven".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/45a76774-3201-4978-98d4-58a91f7a3845> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/18be1d5d-5c8e-417c-813c-8ba8951e21dd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/18be1d5d-5c8e-417c-813c-8ba8951e21dd> a person:Person.
           <http://data.lblod.info/id/personen/18be1d5d-5c8e-417c-813c-8ba8951e21dd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/18be1d5d-5c8e-417c-813c-8ba8951e21dd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Virginie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/18be1d5d-5c8e-417c-813c-8ba8951e21dd> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/b1babb5fb6ae5c8a9e7a466ab0f2bb818a9eea269137f38eff7f94c9161c900e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b1babb5fb6ae5c8a9e7a466ab0f2bb818a9eea269137f38eff7f94c9161c900e> a person:Person.
           <http://data.lblod.info/id/personen/b1babb5fb6ae5c8a9e7a466ab0f2bb818a9eea269137f38eff7f94c9161c900e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b1babb5fb6ae5c8a9e7a466ab0f2bb818a9eea269137f38eff7f94c9161c900e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jean-Marie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b1babb5fb6ae5c8a9e7a466ab0f2bb818a9eea269137f38eff7f94c9161c900e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/6b11364c-6c9e-475a-8773-4819d42a647d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6b11364c-6c9e-475a-8773-4819d42a647d> a person:Person.
           <http://data.lblod.info/id/personen/6b11364c-6c9e-475a-8773-4819d42a647d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6b11364c-6c9e-475a-8773-4819d42a647d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Dominique".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6b11364c-6c9e-475a-8773-4819d42a647d> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/73682d67-6662-4b95-83e0-0d60c538e456> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/73682d67-6662-4b95-83e0-0d60c538e456> a person:Person.
           <http://data.lblod.info/id/personen/73682d67-6662-4b95-83e0-0d60c538e456> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/73682d67-6662-4b95-83e0-0d60c538e456> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Christine".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/73682d67-6662-4b95-83e0-0d60c538e456> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e1440326-3ccd-4e8b-b017-e051f68784ef> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e1440326-3ccd-4e8b-b017-e051f68784ef> a person:Person.
           <http://data.lblod.info/id/personen/e1440326-3ccd-4e8b-b017-e051f68784ef> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e1440326-3ccd-4e8b-b017-e051f68784ef> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Sharon".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e1440326-3ccd-4e8b-b017-e051f68784ef> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/b7d4ade9-a97f-4011-ae9e-dc743fcff0d0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b7d4ade9-a97f-4011-ae9e-dc743fcff0d0> a person:Person.
           <http://data.lblod.info/id/personen/b7d4ade9-a97f-4011-ae9e-dc743fcff0d0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b7d4ade9-a97f-4011-ae9e-dc743fcff0d0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Maxime".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b7d4ade9-a97f-4011-ae9e-dc743fcff0d0> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/6b60e70e-cf26-4fdc-960b-652b8ae2969b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6b60e70e-cf26-4fdc-960b-652b8ae2969b> a person:Person.
           <http://data.lblod.info/id/personen/6b60e70e-cf26-4fdc-960b-652b8ae2969b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6b60e70e-cf26-4fdc-960b-652b8ae2969b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Koen".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6b60e70e-cf26-4fdc-960b-652b8ae2969b> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/46a60aa4-8051-4e8a-9c68-6cfbd490e17a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/46a60aa4-8051-4e8a-9c68-6cfbd490e17a> a person:Person.
           <http://data.lblod.info/id/personen/46a60aa4-8051-4e8a-9c68-6cfbd490e17a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/46a60aa4-8051-4e8a-9c68-6cfbd490e17a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marleen".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/46a60aa4-8051-4e8a-9c68-6cfbd490e17a> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/83b4aa11-3aa3-4b60-b812-8aefef2aed3f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/83b4aa11-3aa3-4b60-b812-8aefef2aed3f> a person:Person.
           <http://data.lblod.info/id/personen/83b4aa11-3aa3-4b60-b812-8aefef2aed3f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/83b4aa11-3aa3-4b60-b812-8aefef2aed3f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ludovic".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/83b4aa11-3aa3-4b60-b812-8aefef2aed3f> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e6c9bd5e-fc65-4be9-8f59-8053c880ef86> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e6c9bd5e-fc65-4be9-8f59-8053c880ef86> a person:Person.
           <http://data.lblod.info/id/personen/e6c9bd5e-fc65-4be9-8f59-8053c880ef86> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e6c9bd5e-fc65-4be9-8f59-8053c880ef86> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Emiel".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e6c9bd5e-fc65-4be9-8f59-8053c880ef86> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/46df1897004172e2340a6c775ff4c39ebf207d290914f57bbe6660492b5f0522> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/46df1897004172e2340a6c775ff4c39ebf207d290914f57bbe6660492b5f0522> a person:Person.
           <http://data.lblod.info/id/personen/46df1897004172e2340a6c775ff4c39ebf207d290914f57bbe6660492b5f0522> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/46df1897004172e2340a6c775ff4c39ebf207d290914f57bbe6660492b5f0522> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Conny".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/46df1897004172e2340a6c775ff4c39ebf207d290914f57bbe6660492b5f0522> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/b224ec4e-20e3-42ad-96f9-32a3f0772bd6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b224ec4e-20e3-42ad-96f9-32a3f0772bd6> a person:Person.
           <http://data.lblod.info/id/personen/b224ec4e-20e3-42ad-96f9-32a3f0772bd6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b224ec4e-20e3-42ad-96f9-32a3f0772bd6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Frank".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b224ec4e-20e3-42ad-96f9-32a3f0772bd6> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/218614c8-3ce6-4cff-a692-e9bf3653a7d3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/218614c8-3ce6-4cff-a692-e9bf3653a7d3> a person:Person.
           <http://data.lblod.info/id/personen/218614c8-3ce6-4cff-a692-e9bf3653a7d3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/218614c8-3ce6-4cff-a692-e9bf3653a7d3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Annie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/218614c8-3ce6-4cff-a692-e9bf3653a7d3> [] [].
          }
        }
     # finished voornamen-update-18976-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:22+00:00