# started voornamen-update-29594-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:50+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e1a79f490addc1b14444ee457b162fe79ff1d4a7be68c65436af1c897b0b0299> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e1a79f490addc1b14444ee457b162fe79ff1d4a7be68c65436af1c897b0b0299> a person:Person.
           <http://data.lblod.info/id/personen/e1a79f490addc1b14444ee457b162fe79ff1d4a7be68c65436af1c897b0b0299> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e1a79f490addc1b14444ee457b162fe79ff1d4a7be68c65436af1c897b0b0299> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marnic".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e1a79f490addc1b14444ee457b162fe79ff1d4a7be68c65436af1c897b0b0299> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/a9946052304ef1e18b394d71964dde583109b27693ade951a8b685a703761a29> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a9946052304ef1e18b394d71964dde583109b27693ade951a8b685a703761a29> a person:Person.
           <http://data.lblod.info/id/personen/a9946052304ef1e18b394d71964dde583109b27693ade951a8b685a703761a29> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a9946052304ef1e18b394d71964dde583109b27693ade951a8b685a703761a29> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Carine".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a9946052304ef1e18b394d71964dde583109b27693ade951a8b685a703761a29> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/284d11adda36c33da03dda83111158c7dbdbe0ef97dc407b6f9092a17e140921> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/284d11adda36c33da03dda83111158c7dbdbe0ef97dc407b6f9092a17e140921> a person:Person.
           <http://data.lblod.info/id/personen/284d11adda36c33da03dda83111158c7dbdbe0ef97dc407b6f9092a17e140921> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/284d11adda36c33da03dda83111158c7dbdbe0ef97dc407b6f9092a17e140921> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Sybille".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/284d11adda36c33da03dda83111158c7dbdbe0ef97dc407b6f9092a17e140921> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/eab8b84e6815ee8d0b42baa1622107067a10ab4823eb341c8e95b0843efc22f8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/eab8b84e6815ee8d0b42baa1622107067a10ab4823eb341c8e95b0843efc22f8> a person:Person.
           <http://data.lblod.info/id/personen/eab8b84e6815ee8d0b42baa1622107067a10ab4823eb341c8e95b0843efc22f8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/eab8b84e6815ee8d0b42baa1622107067a10ab4823eb341c8e95b0843efc22f8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "John".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/eab8b84e6815ee8d0b42baa1622107067a10ab4823eb341c8e95b0843efc22f8> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/1118cba62da37399b0dfde7ecc0bbf3b88926f1adf24047f07ed3ada49302c3c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1118cba62da37399b0dfde7ecc0bbf3b88926f1adf24047f07ed3ada49302c3c> a person:Person.
           <http://data.lblod.info/id/personen/1118cba62da37399b0dfde7ecc0bbf3b88926f1adf24047f07ed3ada49302c3c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1118cba62da37399b0dfde7ecc0bbf3b88926f1adf24047f07ed3ada49302c3c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Franka".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1118cba62da37399b0dfde7ecc0bbf3b88926f1adf24047f07ed3ada49302c3c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2c0a79efdb39c333e3554d27341d3d609c7c5ad9157acc6b0166443d76b1d5d8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2c0a79efdb39c333e3554d27341d3d609c7c5ad9157acc6b0166443d76b1d5d8> a person:Person.
           <http://data.lblod.info/id/personen/2c0a79efdb39c333e3554d27341d3d609c7c5ad9157acc6b0166443d76b1d5d8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2c0a79efdb39c333e3554d27341d3d609c7c5ad9157acc6b0166443d76b1d5d8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Danny".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2c0a79efdb39c333e3554d27341d3d609c7c5ad9157acc6b0166443d76b1d5d8> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/efb398a3-a2f3-430a-a8e7-69f01b2c3acc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/efb398a3-a2f3-430a-a8e7-69f01b2c3acc> a person:Person.
           <http://data.lblod.info/id/personen/efb398a3-a2f3-430a-a8e7-69f01b2c3acc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/efb398a3-a2f3-430a-a8e7-69f01b2c3acc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Tineke".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/efb398a3-a2f3-430a-a8e7-69f01b2c3acc> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ebb90763-c163-4a1c-b977-6917dfbd217d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ebb90763-c163-4a1c-b977-6917dfbd217d> a person:Person.
           <http://data.lblod.info/id/personen/ebb90763-c163-4a1c-b977-6917dfbd217d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ebb90763-c163-4a1c-b977-6917dfbd217d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Kurt".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ebb90763-c163-4a1c-b977-6917dfbd217d> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/6e16b834-a787-4da3-897d-64387fd918d0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6e16b834-a787-4da3-897d-64387fd918d0> a person:Person.
           <http://data.lblod.info/id/personen/6e16b834-a787-4da3-897d-64387fd918d0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6e16b834-a787-4da3-897d-64387fd918d0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Robbin".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6e16b834-a787-4da3-897d-64387fd918d0> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/4fa1addf81a35210b85b91d5829bc43ee8d62c4c93d2e585b593b8148c1160a7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4fa1addf81a35210b85b91d5829bc43ee8d62c4c93d2e585b593b8148c1160a7> a person:Person.
           <http://data.lblod.info/id/personen/4fa1addf81a35210b85b91d5829bc43ee8d62c4c93d2e585b593b8148c1160a7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4fa1addf81a35210b85b91d5829bc43ee8d62c4c93d2e585b593b8148c1160a7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Hilde".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4fa1addf81a35210b85b91d5829bc43ee8d62c4c93d2e585b593b8148c1160a7> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/df56c36a-5a71-4314-8657-43876da2175b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/df56c36a-5a71-4314-8657-43876da2175b> a person:Person.
           <http://data.lblod.info/id/personen/df56c36a-5a71-4314-8657-43876da2175b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/df56c36a-5a71-4314-8657-43876da2175b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "David".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/df56c36a-5a71-4314-8657-43876da2175b> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/096c4acc-4074-40eb-8325-ecab16dd3f81> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/096c4acc-4074-40eb-8325-ecab16dd3f81> a person:Person.
           <http://data.lblod.info/id/personen/096c4acc-4074-40eb-8325-ecab16dd3f81> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/096c4acc-4074-40eb-8325-ecab16dd3f81> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Betül".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/096c4acc-4074-40eb-8325-ecab16dd3f81> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/3d76742a-6848-4c45-987a-a150397c0585> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3d76742a-6848-4c45-987a-a150397c0585> a person:Person.
           <http://data.lblod.info/id/personen/3d76742a-6848-4c45-987a-a150397c0585> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3d76742a-6848-4c45-987a-a150397c0585> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Koen".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3d76742a-6848-4c45-987a-a150397c0585> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/b1e59419-4a62-4be2-bf5c-873e978ed7bc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b1e59419-4a62-4be2-bf5c-873e978ed7bc> a person:Person.
           <http://data.lblod.info/id/personen/b1e59419-4a62-4be2-bf5c-873e978ed7bc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b1e59419-4a62-4be2-bf5c-873e978ed7bc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Anja".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b1e59419-4a62-4be2-bf5c-873e978ed7bc> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/0e53d79f-7d12-4559-9c10-89b8788ec717> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0e53d79f-7d12-4559-9c10-89b8788ec717> a person:Person.
           <http://data.lblod.info/id/personen/0e53d79f-7d12-4559-9c10-89b8788ec717> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0e53d79f-7d12-4559-9c10-89b8788ec717> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Emmily".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0e53d79f-7d12-4559-9c10-89b8788ec717> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/6335be6e-be96-48c2-9ccc-9d410bd3ac14> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6335be6e-be96-48c2-9ccc-9d410bd3ac14> a person:Person.
           <http://data.lblod.info/id/personen/6335be6e-be96-48c2-9ccc-9d410bd3ac14> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6335be6e-be96-48c2-9ccc-9d410bd3ac14> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ronny".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6335be6e-be96-48c2-9ccc-9d410bd3ac14> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f5a5ea7e-1587-4c54-a882-49980caba9c1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f5a5ea7e-1587-4c54-a882-49980caba9c1> a person:Person.
           <http://data.lblod.info/id/personen/f5a5ea7e-1587-4c54-a882-49980caba9c1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f5a5ea7e-1587-4c54-a882-49980caba9c1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jacques".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f5a5ea7e-1587-4c54-a882-49980caba9c1> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/1c9dd196-d5ea-4c1c-bb88-48e3c159e2bb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1c9dd196-d5ea-4c1c-bb88-48e3c159e2bb> a person:Person.
           <http://data.lblod.info/id/personen/1c9dd196-d5ea-4c1c-bb88-48e3c159e2bb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1c9dd196-d5ea-4c1c-bb88-48e3c159e2bb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Nancy".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1c9dd196-d5ea-4c1c-bb88-48e3c159e2bb> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f46605c4-b0dc-42f1-8065-773d261e0a57> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f46605c4-b0dc-42f1-8065-773d261e0a57> a person:Person.
           <http://data.lblod.info/id/personen/f46605c4-b0dc-42f1-8065-773d261e0a57> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f46605c4-b0dc-42f1-8065-773d261e0a57> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Erwin".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f46605c4-b0dc-42f1-8065-773d261e0a57> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/d21b39bc-202e-448e-82eb-6def4a21ea89> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d21b39bc-202e-448e-82eb-6def4a21ea89> a person:Person.
           <http://data.lblod.info/id/personen/d21b39bc-202e-448e-82eb-6def4a21ea89> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d21b39bc-202e-448e-82eb-6def4a21ea89> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marie-Kristine".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d21b39bc-202e-448e-82eb-6def4a21ea89> [] [].
          }
        }
     # finished voornamen-update-29594-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:50+00:00