# started voornamen-update-32555-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:57+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/c1bc7cae-66ee-4065-8820-caa54862658e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c1bc7cae-66ee-4065-8820-caa54862658e> a person:Person.
           <http://data.lblod.info/id/personen/c1bc7cae-66ee-4065-8820-caa54862658e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c1bc7cae-66ee-4065-8820-caa54862658e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Dirk".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c1bc7cae-66ee-4065-8820-caa54862658e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/67e95882-2314-4003-8fa2-deb456a0eef1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/67e95882-2314-4003-8fa2-deb456a0eef1> a person:Person.
           <http://data.lblod.info/id/personen/67e95882-2314-4003-8fa2-deb456a0eef1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/67e95882-2314-4003-8fa2-deb456a0eef1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Betty".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/67e95882-2314-4003-8fa2-deb456a0eef1> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/54485fdc-516a-43c8-8180-a1085194b23e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/54485fdc-516a-43c8-8180-a1085194b23e> a person:Person.
           <http://data.lblod.info/id/personen/54485fdc-516a-43c8-8180-a1085194b23e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/54485fdc-516a-43c8-8180-a1085194b23e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Willy".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/54485fdc-516a-43c8-8180-a1085194b23e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/61229e40-2c6e-4d76-a93b-83afeafc485f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/61229e40-2c6e-4d76-a93b-83afeafc485f> a person:Person.
           <http://data.lblod.info/id/personen/61229e40-2c6e-4d76-a93b-83afeafc485f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/61229e40-2c6e-4d76-a93b-83afeafc485f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Greta".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/61229e40-2c6e-4d76-a93b-83afeafc485f> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/00562c64-85e9-4a53-a68f-cda5601a7350> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/00562c64-85e9-4a53-a68f-cda5601a7350> a person:Person.
           <http://data.lblod.info/id/personen/00562c64-85e9-4a53-a68f-cda5601a7350> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/00562c64-85e9-4a53-a68f-cda5601a7350> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ives".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/00562c64-85e9-4a53-a68f-cda5601a7350> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e3d6b564-2afd-49a0-bee4-844c29417e49> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e3d6b564-2afd-49a0-bee4-844c29417e49> a person:Person.
           <http://data.lblod.info/id/personen/e3d6b564-2afd-49a0-bee4-844c29417e49> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e3d6b564-2afd-49a0-bee4-844c29417e49> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Juna".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e3d6b564-2afd-49a0-bee4-844c29417e49> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/84b3dde7-3b01-4f03-ab69-11bf5479af28> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/84b3dde7-3b01-4f03-ab69-11bf5479af28> a person:Person.
           <http://data.lblod.info/id/personen/84b3dde7-3b01-4f03-ab69-11bf5479af28> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/84b3dde7-3b01-4f03-ab69-11bf5479af28> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Claudia".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/84b3dde7-3b01-4f03-ab69-11bf5479af28> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/7b8f1d98-6fb7-482e-9eed-14044c87b9bb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7b8f1d98-6fb7-482e-9eed-14044c87b9bb> a person:Person.
           <http://data.lblod.info/id/personen/7b8f1d98-6fb7-482e-9eed-14044c87b9bb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7b8f1d98-6fb7-482e-9eed-14044c87b9bb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Luc".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7b8f1d98-6fb7-482e-9eed-14044c87b9bb> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/11f442fe-5ef4-4411-9ce0-850ddfe168a2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/11f442fe-5ef4-4411-9ce0-850ddfe168a2> a person:Person.
           <http://data.lblod.info/id/personen/11f442fe-5ef4-4411-9ce0-850ddfe168a2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/11f442fe-5ef4-4411-9ce0-850ddfe168a2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Nathalie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/11f442fe-5ef4-4411-9ce0-850ddfe168a2> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ada9a651-3e9d-420a-93bc-35c801ffa962> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ada9a651-3e9d-420a-93bc-35c801ffa962> a person:Person.
           <http://data.lblod.info/id/personen/ada9a651-3e9d-420a-93bc-35c801ffa962> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ada9a651-3e9d-420a-93bc-35c801ffa962> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Robby".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ada9a651-3e9d-420a-93bc-35c801ffa962> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/271b4f1f-7dbd-4f22-82aa-29710067f2f1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/271b4f1f-7dbd-4f22-82aa-29710067f2f1> a person:Person.
           <http://data.lblod.info/id/personen/271b4f1f-7dbd-4f22-82aa-29710067f2f1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/271b4f1f-7dbd-4f22-82aa-29710067f2f1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Stefanie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/271b4f1f-7dbd-4f22-82aa-29710067f2f1> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/215ae0329e3d073e105784ac8788e65d0fe81052f0c87cb09c615159db2acefb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/215ae0329e3d073e105784ac8788e65d0fe81052f0c87cb09c615159db2acefb> a person:Person.
           <http://data.lblod.info/id/personen/215ae0329e3d073e105784ac8788e65d0fe81052f0c87cb09c615159db2acefb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/215ae0329e3d073e105784ac8788e65d0fe81052f0c87cb09c615159db2acefb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Michaël".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/215ae0329e3d073e105784ac8788e65d0fe81052f0c87cb09c615159db2acefb> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/04c8fb7f-9efc-4d88-ac02-fed815f7e9f7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/04c8fb7f-9efc-4d88-ac02-fed815f7e9f7> a person:Person.
           <http://data.lblod.info/id/personen/04c8fb7f-9efc-4d88-ac02-fed815f7e9f7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/04c8fb7f-9efc-4d88-ac02-fed815f7e9f7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Viviane".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/04c8fb7f-9efc-4d88-ac02-fed815f7e9f7> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/8d098392-2659-4d79-930e-84611ab2c77d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8d098392-2659-4d79-930e-84611ab2c77d> a person:Person.
           <http://data.lblod.info/id/personen/8d098392-2659-4d79-930e-84611ab2c77d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8d098392-2659-4d79-930e-84611ab2c77d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Wannes".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8d098392-2659-4d79-930e-84611ab2c77d> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/43d8247c-3826-4819-b3ad-c1c9288df82f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/43d8247c-3826-4819-b3ad-c1c9288df82f> a person:Person.
           <http://data.lblod.info/id/personen/43d8247c-3826-4819-b3ad-c1c9288df82f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/43d8247c-3826-4819-b3ad-c1c9288df82f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Joris".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/43d8247c-3826-4819-b3ad-c1c9288df82f> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/3ff66097-935f-42ad-9a3f-6b7039f1b57d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3ff66097-935f-42ad-9a3f-6b7039f1b57d> a person:Person.
           <http://data.lblod.info/id/personen/3ff66097-935f-42ad-9a3f-6b7039f1b57d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3ff66097-935f-42ad-9a3f-6b7039f1b57d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Liliane".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3ff66097-935f-42ad-9a3f-6b7039f1b57d> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/303db819-81a9-46d9-840a-9159fe46b22d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/303db819-81a9-46d9-840a-9159fe46b22d> a person:Person.
           <http://data.lblod.info/id/personen/303db819-81a9-46d9-840a-9159fe46b22d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/303db819-81a9-46d9-840a-9159fe46b22d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Bea".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/303db819-81a9-46d9-840a-9159fe46b22d> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/3d44958b-0e7b-4ccf-b4c5-9a61554abec1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3d44958b-0e7b-4ccf-b4c5-9a61554abec1> a person:Person.
           <http://data.lblod.info/id/personen/3d44958b-0e7b-4ccf-b4c5-9a61554abec1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3d44958b-0e7b-4ccf-b4c5-9a61554abec1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Claude".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3d44958b-0e7b-4ccf-b4c5-9a61554abec1> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/15a9a9cb-5041-42b1-b0ae-75fbdce14c5e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/15a9a9cb-5041-42b1-b0ae-75fbdce14c5e> a person:Person.
           <http://data.lblod.info/id/personen/15a9a9cb-5041-42b1-b0ae-75fbdce14c5e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/15a9a9cb-5041-42b1-b0ae-75fbdce14c5e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Kurt".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/15a9a9cb-5041-42b1-b0ae-75fbdce14c5e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/9b45d9ca-d47b-41a1-9ecb-10183376a73c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9b45d9ca-d47b-41a1-9ecb-10183376a73c> a person:Person.
           <http://data.lblod.info/id/personen/9b45d9ca-d47b-41a1-9ecb-10183376a73c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9b45d9ca-d47b-41a1-9ecb-10183376a73c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Bruno".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9b45d9ca-d47b-41a1-9ecb-10183376a73c> [] [].
          }
        }
     # finished voornamen-update-32555-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:57+00:00