# started voornamen-update-26321-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:41+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/54a54c7a-be20-4e61-9d20-c2be7bc2209f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/54a54c7a-be20-4e61-9d20-c2be7bc2209f> a person:Person.
           <http://data.lblod.info/id/personen/54a54c7a-be20-4e61-9d20-c2be7bc2209f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/54a54c7a-be20-4e61-9d20-c2be7bc2209f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Claudine".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/54a54c7a-be20-4e61-9d20-c2be7bc2209f> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/a577795f-35bc-4770-8a68-0e95355e7d53> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a577795f-35bc-4770-8a68-0e95355e7d53> a person:Person.
           <http://data.lblod.info/id/personen/a577795f-35bc-4770-8a68-0e95355e7d53> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a577795f-35bc-4770-8a68-0e95355e7d53> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Piet".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a577795f-35bc-4770-8a68-0e95355e7d53> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/14231af5-d64d-4879-b941-0557d0d1100a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/14231af5-d64d-4879-b941-0557d0d1100a> a person:Person.
           <http://data.lblod.info/id/personen/14231af5-d64d-4879-b941-0557d0d1100a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/14231af5-d64d-4879-b941-0557d0d1100a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Casper".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/14231af5-d64d-4879-b941-0557d0d1100a> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/601592da-52a5-4c9c-baa9-637badc3ea16> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/601592da-52a5-4c9c-baa9-637badc3ea16> a person:Person.
           <http://data.lblod.info/id/personen/601592da-52a5-4c9c-baa9-637badc3ea16> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/601592da-52a5-4c9c-baa9-637badc3ea16> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Bart".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/601592da-52a5-4c9c-baa9-637badc3ea16> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/532e8263-fccd-4388-a7a3-ca70aeea178e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/532e8263-fccd-4388-a7a3-ca70aeea178e> a person:Person.
           <http://data.lblod.info/id/personen/532e8263-fccd-4388-a7a3-ca70aeea178e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/532e8263-fccd-4388-a7a3-ca70aeea178e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Geert".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/532e8263-fccd-4388-a7a3-ca70aeea178e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/705a80cc-26d7-4fcc-8b63-9774af37ff2b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/705a80cc-26d7-4fcc-8b63-9774af37ff2b> a person:Person.
           <http://data.lblod.info/id/personen/705a80cc-26d7-4fcc-8b63-9774af37ff2b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/705a80cc-26d7-4fcc-8b63-9774af37ff2b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Peter".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/705a80cc-26d7-4fcc-8b63-9774af37ff2b> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/8ad04309-13ea-461b-8b9b-5ab420f477d5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8ad04309-13ea-461b-8b9b-5ab420f477d5> a person:Person.
           <http://data.lblod.info/id/personen/8ad04309-13ea-461b-8b9b-5ab420f477d5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8ad04309-13ea-461b-8b9b-5ab420f477d5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Alain".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8ad04309-13ea-461b-8b9b-5ab420f477d5> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/6e975450-9197-4b32-a778-d5d16b39aa47> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6e975450-9197-4b32-a778-d5d16b39aa47> a person:Person.
           <http://data.lblod.info/id/personen/6e975450-9197-4b32-a778-d5d16b39aa47> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6e975450-9197-4b32-a778-d5d16b39aa47> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Nadine".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6e975450-9197-4b32-a778-d5d16b39aa47> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/662ba9de-af9a-488e-b4b2-23417695b3cc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/662ba9de-af9a-488e-b4b2-23417695b3cc> a person:Person.
           <http://data.lblod.info/id/personen/662ba9de-af9a-488e-b4b2-23417695b3cc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/662ba9de-af9a-488e-b4b2-23417695b3cc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Veerle".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/662ba9de-af9a-488e-b4b2-23417695b3cc> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/c5050da2-e87f-4d8e-8c11-2e9ece8d3f59> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c5050da2-e87f-4d8e-8c11-2e9ece8d3f59> a person:Person.
           <http://data.lblod.info/id/personen/c5050da2-e87f-4d8e-8c11-2e9ece8d3f59> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c5050da2-e87f-4d8e-8c11-2e9ece8d3f59> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jo".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c5050da2-e87f-4d8e-8c11-2e9ece8d3f59> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/38cbb649-15f8-4dc5-a87c-caf3d6ef8123> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/38cbb649-15f8-4dc5-a87c-caf3d6ef8123> a person:Person.
           <http://data.lblod.info/id/personen/38cbb649-15f8-4dc5-a87c-caf3d6ef8123> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/38cbb649-15f8-4dc5-a87c-caf3d6ef8123> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marie-Claire".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/38cbb649-15f8-4dc5-a87c-caf3d6ef8123> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/55a1fe7ad4c89c50523613c9df6507d5c4861c6fc10ca7e3490ddb810fcf12c2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/55a1fe7ad4c89c50523613c9df6507d5c4861c6fc10ca7e3490ddb810fcf12c2> a person:Person.
           <http://data.lblod.info/id/personen/55a1fe7ad4c89c50523613c9df6507d5c4861c6fc10ca7e3490ddb810fcf12c2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/55a1fe7ad4c89c50523613c9df6507d5c4861c6fc10ca7e3490ddb810fcf12c2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Niek".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/55a1fe7ad4c89c50523613c9df6507d5c4861c6fc10ca7e3490ddb810fcf12c2> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2f52bc81-1c31-47bf-9878-eda34115f73f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2f52bc81-1c31-47bf-9878-eda34115f73f> a person:Person.
           <http://data.lblod.info/id/personen/2f52bc81-1c31-47bf-9878-eda34115f73f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2f52bc81-1c31-47bf-9878-eda34115f73f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Dirk".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2f52bc81-1c31-47bf-9878-eda34115f73f> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/4b9e40bae4c84e037f4feb140aba03e5f5d0b6961915a34db43080f03b7c4100> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4b9e40bae4c84e037f4feb140aba03e5f5d0b6961915a34db43080f03b7c4100> a person:Person.
           <http://data.lblod.info/id/personen/4b9e40bae4c84e037f4feb140aba03e5f5d0b6961915a34db43080f03b7c4100> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4b9e40bae4c84e037f4feb140aba03e5f5d0b6961915a34db43080f03b7c4100> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Paul".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4b9e40bae4c84e037f4feb140aba03e5f5d0b6961915a34db43080f03b7c4100> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ef969e9da1468f53a1e4aa264df1a267f87b9b7f2f8738e23b19edbcb223999f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ef969e9da1468f53a1e4aa264df1a267f87b9b7f2f8738e23b19edbcb223999f> a person:Person.
           <http://data.lblod.info/id/personen/ef969e9da1468f53a1e4aa264df1a267f87b9b7f2f8738e23b19edbcb223999f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ef969e9da1468f53a1e4aa264df1a267f87b9b7f2f8738e23b19edbcb223999f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Veerle".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ef969e9da1468f53a1e4aa264df1a267f87b9b7f2f8738e23b19edbcb223999f> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/9655c82108f60b9b487a5cca320a544405d0f5a65597e66cabb6bbbb4cb3c4f3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9655c82108f60b9b487a5cca320a544405d0f5a65597e66cabb6bbbb4cb3c4f3> a person:Person.
           <http://data.lblod.info/id/personen/9655c82108f60b9b487a5cca320a544405d0f5a65597e66cabb6bbbb4cb3c4f3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9655c82108f60b9b487a5cca320a544405d0f5a65597e66cabb6bbbb4cb3c4f3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Hilde".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9655c82108f60b9b487a5cca320a544405d0f5a65597e66cabb6bbbb4cb3c4f3> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2aafed4e-f213-4bdf-8e03-73161463b264> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2aafed4e-f213-4bdf-8e03-73161463b264> a person:Person.
           <http://data.lblod.info/id/personen/2aafed4e-f213-4bdf-8e03-73161463b264> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2aafed4e-f213-4bdf-8e03-73161463b264> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Rebecca".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2aafed4e-f213-4bdf-8e03-73161463b264> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/885817d8e296591c63fa706e96617786ffb8c158cc3e27dc4465d45e00334709> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/885817d8e296591c63fa706e96617786ffb8c158cc3e27dc4465d45e00334709> a person:Person.
           <http://data.lblod.info/id/personen/885817d8e296591c63fa706e96617786ffb8c158cc3e27dc4465d45e00334709> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/885817d8e296591c63fa706e96617786ffb8c158cc3e27dc4465d45e00334709> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jezz".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/885817d8e296591c63fa706e96617786ffb8c158cc3e27dc4465d45e00334709> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/238ca145-91cc-4581-bb51-248d643e1518> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/238ca145-91cc-4581-bb51-248d643e1518> a person:Person.
           <http://data.lblod.info/id/personen/238ca145-91cc-4581-bb51-248d643e1518> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/238ca145-91cc-4581-bb51-248d643e1518> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Tonny".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/238ca145-91cc-4581-bb51-248d643e1518> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2271dd59-e9b8-4e7f-b285-2047d94ec1ca> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2271dd59-e9b8-4e7f-b285-2047d94ec1ca> a person:Person.
           <http://data.lblod.info/id/personen/2271dd59-e9b8-4e7f-b285-2047d94ec1ca> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2271dd59-e9b8-4e7f-b285-2047d94ec1ca> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Roland".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2271dd59-e9b8-4e7f-b285-2047d94ec1ca> [] [].
          }
        }
     # finished voornamen-update-26321-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:41+00:00