# started voornamen-update-18737-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:22+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2cbad312eb4b36789da9955213544fc7136f39cbf71f235a538d198c778667d2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2cbad312eb4b36789da9955213544fc7136f39cbf71f235a538d198c778667d2> a person:Person.
           <http://data.lblod.info/id/personen/2cbad312eb4b36789da9955213544fc7136f39cbf71f235a538d198c778667d2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2cbad312eb4b36789da9955213544fc7136f39cbf71f235a538d198c778667d2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Maja".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2cbad312eb4b36789da9955213544fc7136f39cbf71f235a538d198c778667d2> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/5c02f77ea921ea72e0471cae768071bae2c20eafc5cf703917e5dd58e714776e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5c02f77ea921ea72e0471cae768071bae2c20eafc5cf703917e5dd58e714776e> a person:Person.
           <http://data.lblod.info/id/personen/5c02f77ea921ea72e0471cae768071bae2c20eafc5cf703917e5dd58e714776e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5c02f77ea921ea72e0471cae768071bae2c20eafc5cf703917e5dd58e714776e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Geert".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5c02f77ea921ea72e0471cae768071bae2c20eafc5cf703917e5dd58e714776e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/a8d5b485-8b14-47ff-8c33-a39544db3b7b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a8d5b485-8b14-47ff-8c33-a39544db3b7b> a person:Person.
           <http://data.lblod.info/id/personen/a8d5b485-8b14-47ff-8c33-a39544db3b7b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a8d5b485-8b14-47ff-8c33-a39544db3b7b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Deborah".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a8d5b485-8b14-47ff-8c33-a39544db3b7b> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/97efbe03455a844bc3ba5703323b314b40bded368920ab618e3419839d19074d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/97efbe03455a844bc3ba5703323b314b40bded368920ab618e3419839d19074d> a person:Person.
           <http://data.lblod.info/id/personen/97efbe03455a844bc3ba5703323b314b40bded368920ab618e3419839d19074d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/97efbe03455a844bc3ba5703323b314b40bded368920ab618e3419839d19074d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Sara".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/97efbe03455a844bc3ba5703323b314b40bded368920ab618e3419839d19074d> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/27b9ea6158817b777f9220201cf84f129b4af85799604e023c410c0fb481ea30> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/27b9ea6158817b777f9220201cf84f129b4af85799604e023c410c0fb481ea30> a person:Person.
           <http://data.lblod.info/id/personen/27b9ea6158817b777f9220201cf84f129b4af85799604e023c410c0fb481ea30> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/27b9ea6158817b777f9220201cf84f129b4af85799604e023c410c0fb481ea30> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Pepijn".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/27b9ea6158817b777f9220201cf84f129b4af85799604e023c410c0fb481ea30> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/236aeab42b9503fa28462b1c15cfb5e113c9b100b735ea246babacd1422c5918> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/236aeab42b9503fa28462b1c15cfb5e113c9b100b735ea246babacd1422c5918> a person:Person.
           <http://data.lblod.info/id/personen/236aeab42b9503fa28462b1c15cfb5e113c9b100b735ea246babacd1422c5918> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/236aeab42b9503fa28462b1c15cfb5e113c9b100b735ea246babacd1422c5918> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "John".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/236aeab42b9503fa28462b1c15cfb5e113c9b100b735ea246babacd1422c5918> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/21a6727a-a2d6-4dda-a779-6fb973472d31> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/21a6727a-a2d6-4dda-a779-6fb973472d31> a person:Person.
           <http://data.lblod.info/id/personen/21a6727a-a2d6-4dda-a779-6fb973472d31> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/21a6727a-a2d6-4dda-a779-6fb973472d31> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marlies".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/21a6727a-a2d6-4dda-a779-6fb973472d31> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f2b6a1d7-116b-4faf-8d6c-92e3db9749d3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f2b6a1d7-116b-4faf-8d6c-92e3db9749d3> a person:Person.
           <http://data.lblod.info/id/personen/f2b6a1d7-116b-4faf-8d6c-92e3db9749d3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f2b6a1d7-116b-4faf-8d6c-92e3db9749d3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Gaetan".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f2b6a1d7-116b-4faf-8d6c-92e3db9749d3> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/01022cb9-aba3-414a-a45f-e1ea1c9ed508> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/01022cb9-aba3-414a-a45f-e1ea1c9ed508> a person:Person.
           <http://data.lblod.info/id/personen/01022cb9-aba3-414a-a45f-e1ea1c9ed508> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/01022cb9-aba3-414a-a45f-e1ea1c9ed508> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Yaron".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/01022cb9-aba3-414a-a45f-e1ea1c9ed508> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ce9003fc-2ddb-40ae-afb8-e1a558977707> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ce9003fc-2ddb-40ae-afb8-e1a558977707> a person:Person.
           <http://data.lblod.info/id/personen/ce9003fc-2ddb-40ae-afb8-e1a558977707> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ce9003fc-2ddb-40ae-afb8-e1a558977707> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Rani".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ce9003fc-2ddb-40ae-afb8-e1a558977707> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/53f0aeef-3250-4014-bfe8-65b0469d3a75> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/53f0aeef-3250-4014-bfe8-65b0469d3a75> a person:Person.
           <http://data.lblod.info/id/personen/53f0aeef-3250-4014-bfe8-65b0469d3a75> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/53f0aeef-3250-4014-bfe8-65b0469d3a75> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Henri".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/53f0aeef-3250-4014-bfe8-65b0469d3a75> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/16d39c34-ebfc-4f52-8b3b-df238777e06d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/16d39c34-ebfc-4f52-8b3b-df238777e06d> a person:Person.
           <http://data.lblod.info/id/personen/16d39c34-ebfc-4f52-8b3b-df238777e06d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/16d39c34-ebfc-4f52-8b3b-df238777e06d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Astrid".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/16d39c34-ebfc-4f52-8b3b-df238777e06d> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e7dfcdd8-53f8-493b-a7f0-e1932b7e378d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e7dfcdd8-53f8-493b-a7f0-e1932b7e378d> a person:Person.
           <http://data.lblod.info/id/personen/e7dfcdd8-53f8-493b-a7f0-e1932b7e378d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e7dfcdd8-53f8-493b-a7f0-e1932b7e378d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Anneke".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e7dfcdd8-53f8-493b-a7f0-e1932b7e378d> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/5dae94c4f863bd3339d2662661c96e677bde922c7267278224b00fe7fed32359> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5dae94c4f863bd3339d2662661c96e677bde922c7267278224b00fe7fed32359> a person:Person.
           <http://data.lblod.info/id/personen/5dae94c4f863bd3339d2662661c96e677bde922c7267278224b00fe7fed32359> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5dae94c4f863bd3339d2662661c96e677bde922c7267278224b00fe7fed32359> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Michel".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5dae94c4f863bd3339d2662661c96e677bde922c7267278224b00fe7fed32359> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/be658edd-ab5b-4aff-bf21-2967ee552347> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/be658edd-ab5b-4aff-bf21-2967ee552347> a person:Person.
           <http://data.lblod.info/id/personen/be658edd-ab5b-4aff-bf21-2967ee552347> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/be658edd-ab5b-4aff-bf21-2967ee552347> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Guido".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/be658edd-ab5b-4aff-bf21-2967ee552347> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/204589a5d3b09261f2b42550ff5a9d0246243d814d5a23996c57ae17ce10b6be> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/204589a5d3b09261f2b42550ff5a9d0246243d814d5a23996c57ae17ce10b6be> a person:Person.
           <http://data.lblod.info/id/personen/204589a5d3b09261f2b42550ff5a9d0246243d814d5a23996c57ae17ce10b6be> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/204589a5d3b09261f2b42550ff5a9d0246243d814d5a23996c57ae17ce10b6be> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Michelle".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/204589a5d3b09261f2b42550ff5a9d0246243d814d5a23996c57ae17ce10b6be> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/52734164-c3b7-41e9-b9df-6128b532f4e2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/52734164-c3b7-41e9-b9df-6128b532f4e2> a person:Person.
           <http://data.lblod.info/id/personen/52734164-c3b7-41e9-b9df-6128b532f4e2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/52734164-c3b7-41e9-b9df-6128b532f4e2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Dorothée".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/52734164-c3b7-41e9-b9df-6128b532f4e2> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2e14c1fc929aa70716b4422c52288471b67be634bfce042b7a92c9dabd2c5452> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2e14c1fc929aa70716b4422c52288471b67be634bfce042b7a92c9dabd2c5452> a person:Person.
           <http://data.lblod.info/id/personen/2e14c1fc929aa70716b4422c52288471b67be634bfce042b7a92c9dabd2c5452> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2e14c1fc929aa70716b4422c52288471b67be634bfce042b7a92c9dabd2c5452> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Bernard".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2e14c1fc929aa70716b4422c52288471b67be634bfce042b7a92c9dabd2c5452> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ba870dafad3d74bf9788d6639af98ab1ef9b0c9950b244ce367e331e1a7f0651> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ba870dafad3d74bf9788d6639af98ab1ef9b0c9950b244ce367e331e1a7f0651> a person:Person.
           <http://data.lblod.info/id/personen/ba870dafad3d74bf9788d6639af98ab1ef9b0c9950b244ce367e331e1a7f0651> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ba870dafad3d74bf9788d6639af98ab1ef9b0c9950b244ce367e331e1a7f0651> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Antoinette".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ba870dafad3d74bf9788d6639af98ab1ef9b0c9950b244ce367e331e1a7f0651> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/964d1929-a368-487d-8f86-34da4fe7eab4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/964d1929-a368-487d-8f86-34da4fe7eab4> a person:Person.
           <http://data.lblod.info/id/personen/964d1929-a368-487d-8f86-34da4fe7eab4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/964d1929-a368-487d-8f86-34da4fe7eab4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Roger".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/964d1929-a368-487d-8f86-34da4fe7eab4> [] [].
          }
        }
     # finished voornamen-update-18737-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:22+00:00