# started voornamen-update-23844-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:35+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/c82e548e-881a-438d-9c1d-9806b79f6883> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c82e548e-881a-438d-9c1d-9806b79f6883> a person:Person.
           <http://data.lblod.info/id/personen/c82e548e-881a-438d-9c1d-9806b79f6883> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c82e548e-881a-438d-9c1d-9806b79f6883> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Caroline".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c82e548e-881a-438d-9c1d-9806b79f6883> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/1b30f15b-b9ee-4cd2-9618-9c817eac551f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1b30f15b-b9ee-4cd2-9618-9c817eac551f> a person:Person.
           <http://data.lblod.info/id/personen/1b30f15b-b9ee-4cd2-9618-9c817eac551f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1b30f15b-b9ee-4cd2-9618-9c817eac551f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Benjamien".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1b30f15b-b9ee-4cd2-9618-9c817eac551f> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/64ecf6e5-59e8-4b31-ae92-14b865659f73> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/64ecf6e5-59e8-4b31-ae92-14b865659f73> a person:Person.
           <http://data.lblod.info/id/personen/64ecf6e5-59e8-4b31-ae92-14b865659f73> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/64ecf6e5-59e8-4b31-ae92-14b865659f73> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marc".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/64ecf6e5-59e8-4b31-ae92-14b865659f73> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/35c3830f-f393-495e-8631-72e19744c517> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/35c3830f-f393-495e-8631-72e19744c517> a person:Person.
           <http://data.lblod.info/id/personen/35c3830f-f393-495e-8631-72e19744c517> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/35c3830f-f393-495e-8631-72e19744c517> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Anja".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/35c3830f-f393-495e-8631-72e19744c517> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/07368c09-b4bc-45c7-b667-440ef0e990cb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/07368c09-b4bc-45c7-b667-440ef0e990cb> a person:Person.
           <http://data.lblod.info/id/personen/07368c09-b4bc-45c7-b667-440ef0e990cb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/07368c09-b4bc-45c7-b667-440ef0e990cb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Lionel".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/07368c09-b4bc-45c7-b667-440ef0e990cb> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/5762ff14-2d3a-4550-b3d3-8f0fe4875efa> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5762ff14-2d3a-4550-b3d3-8f0fe4875efa> a person:Person.
           <http://data.lblod.info/id/personen/5762ff14-2d3a-4550-b3d3-8f0fe4875efa> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5762ff14-2d3a-4550-b3d3-8f0fe4875efa> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Mimie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5762ff14-2d3a-4550-b3d3-8f0fe4875efa> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/50646816-eb44-4c04-af19-b6187747d51e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/50646816-eb44-4c04-af19-b6187747d51e> a person:Person.
           <http://data.lblod.info/id/personen/50646816-eb44-4c04-af19-b6187747d51e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/50646816-eb44-4c04-af19-b6187747d51e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marleen".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/50646816-eb44-4c04-af19-b6187747d51e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/8db8534c-3283-48c5-9ea3-f7d92e46fc27> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8db8534c-3283-48c5-9ea3-f7d92e46fc27> a person:Person.
           <http://data.lblod.info/id/personen/8db8534c-3283-48c5-9ea3-f7d92e46fc27> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8db8534c-3283-48c5-9ea3-f7d92e46fc27> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Guy".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8db8534c-3283-48c5-9ea3-f7d92e46fc27> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/c396f93e11eec435fb36465e1a9612058750c8d3877e69303ee9738023c7e257> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c396f93e11eec435fb36465e1a9612058750c8d3877e69303ee9738023c7e257> a person:Person.
           <http://data.lblod.info/id/personen/c396f93e11eec435fb36465e1a9612058750c8d3877e69303ee9738023c7e257> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c396f93e11eec435fb36465e1a9612058750c8d3877e69303ee9738023c7e257> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "François".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c396f93e11eec435fb36465e1a9612058750c8d3877e69303ee9738023c7e257> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/38cdac885ec8299162c5bcb8ce8d63d1a8c008e97a1fa5dbb42803e16f6fe811> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/38cdac885ec8299162c5bcb8ce8d63d1a8c008e97a1fa5dbb42803e16f6fe811> a person:Person.
           <http://data.lblod.info/id/personen/38cdac885ec8299162c5bcb8ce8d63d1a8c008e97a1fa5dbb42803e16f6fe811> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/38cdac885ec8299162c5bcb8ce8d63d1a8c008e97a1fa5dbb42803e16f6fe811> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Martine".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/38cdac885ec8299162c5bcb8ce8d63d1a8c008e97a1fa5dbb42803e16f6fe811> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f0719d63-dc14-4660-8b57-ec6058f67a6f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f0719d63-dc14-4660-8b57-ec6058f67a6f> a person:Person.
           <http://data.lblod.info/id/personen/f0719d63-dc14-4660-8b57-ec6058f67a6f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f0719d63-dc14-4660-8b57-ec6058f67a6f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Johnny".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f0719d63-dc14-4660-8b57-ec6058f67a6f> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/cadb47d08b301ec1e35d13298cec1b9e3a6b901a4468beaed04ccdc557958f07> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cadb47d08b301ec1e35d13298cec1b9e3a6b901a4468beaed04ccdc557958f07> a person:Person.
           <http://data.lblod.info/id/personen/cadb47d08b301ec1e35d13298cec1b9e3a6b901a4468beaed04ccdc557958f07> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cadb47d08b301ec1e35d13298cec1b9e3a6b901a4468beaed04ccdc557958f07> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Sabine".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cadb47d08b301ec1e35d13298cec1b9e3a6b901a4468beaed04ccdc557958f07> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/0497fac3-4c66-456d-afc2-4416ad93decf> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0497fac3-4c66-456d-afc2-4416ad93decf> a person:Person.
           <http://data.lblod.info/id/personen/0497fac3-4c66-456d-afc2-4416ad93decf> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0497fac3-4c66-456d-afc2-4416ad93decf> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Lucien".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0497fac3-4c66-456d-afc2-4416ad93decf> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/22435df5-1072-4e08-822c-548a69345335> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/22435df5-1072-4e08-822c-548a69345335> a person:Person.
           <http://data.lblod.info/id/personen/22435df5-1072-4e08-822c-548a69345335> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/22435df5-1072-4e08-822c-548a69345335> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Madeleine".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/22435df5-1072-4e08-822c-548a69345335> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e67ca01b-39f4-4667-ab91-c60b2410eace> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e67ca01b-39f4-4667-ab91-c60b2410eace> a person:Person.
           <http://data.lblod.info/id/personen/e67ca01b-39f4-4667-ab91-c60b2410eace> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e67ca01b-39f4-4667-ab91-c60b2410eace> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marc".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e67ca01b-39f4-4667-ab91-c60b2410eace> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/d8b6bfe9-5be9-4a06-ac55-83cb665f460a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d8b6bfe9-5be9-4a06-ac55-83cb665f460a> a person:Person.
           <http://data.lblod.info/id/personen/d8b6bfe9-5be9-4a06-ac55-83cb665f460a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d8b6bfe9-5be9-4a06-ac55-83cb665f460a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Rosita".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d8b6bfe9-5be9-4a06-ac55-83cb665f460a> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/3ee5b4cd-4894-4b73-ad0a-88abfaf12f2e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3ee5b4cd-4894-4b73-ad0a-88abfaf12f2e> a person:Person.
           <http://data.lblod.info/id/personen/3ee5b4cd-4894-4b73-ad0a-88abfaf12f2e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3ee5b4cd-4894-4b73-ad0a-88abfaf12f2e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Saskia".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3ee5b4cd-4894-4b73-ad0a-88abfaf12f2e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/b4b32240-886e-48f1-9528-b962079fa4a4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b4b32240-886e-48f1-9528-b962079fa4a4> a person:Person.
           <http://data.lblod.info/id/personen/b4b32240-886e-48f1-9528-b962079fa4a4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b4b32240-886e-48f1-9528-b962079fa4a4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Linda".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b4b32240-886e-48f1-9528-b962079fa4a4> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/5bf0fc79-1ce2-4654-bab6-fb5003b3affd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5bf0fc79-1ce2-4654-bab6-fb5003b3affd> a person:Person.
           <http://data.lblod.info/id/personen/5bf0fc79-1ce2-4654-bab6-fb5003b3affd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5bf0fc79-1ce2-4654-bab6-fb5003b3affd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "William".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5bf0fc79-1ce2-4654-bab6-fb5003b3affd> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f31d2ca4-5dc8-435f-b947-a76487f796a1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f31d2ca4-5dc8-435f-b947-a76487f796a1> a person:Person.
           <http://data.lblod.info/id/personen/f31d2ca4-5dc8-435f-b947-a76487f796a1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f31d2ca4-5dc8-435f-b947-a76487f796a1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Nancy".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f31d2ca4-5dc8-435f-b947-a76487f796a1> [] [].
          }
        }
     # finished voornamen-update-23844-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:35+00:00