# started voornamen-update-17635-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:19+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2ef44a11-04db-42bb-8409-b8d45e02210e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2ef44a11-04db-42bb-8409-b8d45e02210e> a person:Person.
           <http://data.lblod.info/id/personen/2ef44a11-04db-42bb-8409-b8d45e02210e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2ef44a11-04db-42bb-8409-b8d45e02210e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Stephan".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2ef44a11-04db-42bb-8409-b8d45e02210e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/7ae6c42e-f0da-43c5-9189-0a603ec93f8e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7ae6c42e-f0da-43c5-9189-0a603ec93f8e> a person:Person.
           <http://data.lblod.info/id/personen/7ae6c42e-f0da-43c5-9189-0a603ec93f8e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7ae6c42e-f0da-43c5-9189-0a603ec93f8e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Crist".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7ae6c42e-f0da-43c5-9189-0a603ec93f8e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/a49ffc3f-1063-4c4c-89fe-e8defbc4d3ad> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a49ffc3f-1063-4c4c-89fe-e8defbc4d3ad> a person:Person.
           <http://data.lblod.info/id/personen/a49ffc3f-1063-4c4c-89fe-e8defbc4d3ad> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a49ffc3f-1063-4c4c-89fe-e8defbc4d3ad> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Patty".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a49ffc3f-1063-4c4c-89fe-e8defbc4d3ad> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/efc7c6ae-480e-4597-8891-fd6abcede128> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/efc7c6ae-480e-4597-8891-fd6abcede128> a person:Person.
           <http://data.lblod.info/id/personen/efc7c6ae-480e-4597-8891-fd6abcede128> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/efc7c6ae-480e-4597-8891-fd6abcede128> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Stephanie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/efc7c6ae-480e-4597-8891-fd6abcede128> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/a652d16f4049f4b05a472f2d9481a05f18262e7747c122cac331a40c946e94b3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a652d16f4049f4b05a472f2d9481a05f18262e7747c122cac331a40c946e94b3> a person:Person.
           <http://data.lblod.info/id/personen/a652d16f4049f4b05a472f2d9481a05f18262e7747c122cac331a40c946e94b3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a652d16f4049f4b05a472f2d9481a05f18262e7747c122cac331a40c946e94b3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Kris".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a652d16f4049f4b05a472f2d9481a05f18262e7747c122cac331a40c946e94b3> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/201186b2dcf724f22b3be62e9cc598a8c0bcf8b5243ce994f2b520e545d62c6c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/201186b2dcf724f22b3be62e9cc598a8c0bcf8b5243ce994f2b520e545d62c6c> a person:Person.
           <http://data.lblod.info/id/personen/201186b2dcf724f22b3be62e9cc598a8c0bcf8b5243ce994f2b520e545d62c6c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/201186b2dcf724f22b3be62e9cc598a8c0bcf8b5243ce994f2b520e545d62c6c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Patrick".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/201186b2dcf724f22b3be62e9cc598a8c0bcf8b5243ce994f2b520e545d62c6c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/30cc6bf5-5bee-404d-8ca9-30092726956f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/30cc6bf5-5bee-404d-8ca9-30092726956f> a person:Person.
           <http://data.lblod.info/id/personen/30cc6bf5-5bee-404d-8ca9-30092726956f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/30cc6bf5-5bee-404d-8ca9-30092726956f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Sofie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/30cc6bf5-5bee-404d-8ca9-30092726956f> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/7c96e57c-0162-4998-ad96-41cc0ed23b23> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7c96e57c-0162-4998-ad96-41cc0ed23b23> a person:Person.
           <http://data.lblod.info/id/personen/7c96e57c-0162-4998-ad96-41cc0ed23b23> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7c96e57c-0162-4998-ad96-41cc0ed23b23> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Bolle".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7c96e57c-0162-4998-ad96-41cc0ed23b23> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/5d154f37-446c-48db-b39a-8ec732a0c918> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5d154f37-446c-48db-b39a-8ec732a0c918> a person:Person.
           <http://data.lblod.info/id/personen/5d154f37-446c-48db-b39a-8ec732a0c918> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5d154f37-446c-48db-b39a-8ec732a0c918> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jeannette".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5d154f37-446c-48db-b39a-8ec732a0c918> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ddfc0fc9-9245-417d-bd5f-3bb416122084> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ddfc0fc9-9245-417d-bd5f-3bb416122084> a person:Person.
           <http://data.lblod.info/id/personen/ddfc0fc9-9245-417d-bd5f-3bb416122084> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ddfc0fc9-9245-417d-bd5f-3bb416122084> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Vincent".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ddfc0fc9-9245-417d-bd5f-3bb416122084> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/38714d442ddb370ba9f637e55f8269b300d234c6eefb9ab7e0486b25c1cc9d06> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/38714d442ddb370ba9f637e55f8269b300d234c6eefb9ab7e0486b25c1cc9d06> a person:Person.
           <http://data.lblod.info/id/personen/38714d442ddb370ba9f637e55f8269b300d234c6eefb9ab7e0486b25c1cc9d06> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/38714d442ddb370ba9f637e55f8269b300d234c6eefb9ab7e0486b25c1cc9d06> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Pieter".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/38714d442ddb370ba9f637e55f8269b300d234c6eefb9ab7e0486b25c1cc9d06> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e37a5964-ddb7-46b2-b76e-ece6b7339a36> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e37a5964-ddb7-46b2-b76e-ece6b7339a36> a person:Person.
           <http://data.lblod.info/id/personen/e37a5964-ddb7-46b2-b76e-ece6b7339a36> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e37a5964-ddb7-46b2-b76e-ece6b7339a36> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Barbara".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e37a5964-ddb7-46b2-b76e-ece6b7339a36> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f4039c60-d5a7-4da7-b915-e27750eef897> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f4039c60-d5a7-4da7-b915-e27750eef897> a person:Person.
           <http://data.lblod.info/id/personen/f4039c60-d5a7-4da7-b915-e27750eef897> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f4039c60-d5a7-4da7-b915-e27750eef897> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Sofie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f4039c60-d5a7-4da7-b915-e27750eef897> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/18beb762-c4c9-42f7-87d4-388580aa6836> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/18beb762-c4c9-42f7-87d4-388580aa6836> a person:Person.
           <http://data.lblod.info/id/personen/18beb762-c4c9-42f7-87d4-388580aa6836> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/18beb762-c4c9-42f7-87d4-388580aa6836> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Nathalie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/18beb762-c4c9-42f7-87d4-388580aa6836> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/705a4bb2-b917-409c-9817-0b0ac483d2e9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/705a4bb2-b917-409c-9817-0b0ac483d2e9> a person:Person.
           <http://data.lblod.info/id/personen/705a4bb2-b917-409c-9817-0b0ac483d2e9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/705a4bb2-b917-409c-9817-0b0ac483d2e9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Michiel".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/705a4bb2-b917-409c-9817-0b0ac483d2e9> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/a9725dd83973b779e6ec3ca2939aa80eb04683856dece3e01adb73a07fbd8785> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a9725dd83973b779e6ec3ca2939aa80eb04683856dece3e01adb73a07fbd8785> a person:Person.
           <http://data.lblod.info/id/personen/a9725dd83973b779e6ec3ca2939aa80eb04683856dece3e01adb73a07fbd8785> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a9725dd83973b779e6ec3ca2939aa80eb04683856dece3e01adb73a07fbd8785> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Veerle".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a9725dd83973b779e6ec3ca2939aa80eb04683856dece3e01adb73a07fbd8785> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/c0f6f3e7-7400-46a4-941c-a95860a5e177> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c0f6f3e7-7400-46a4-941c-a95860a5e177> a person:Person.
           <http://data.lblod.info/id/personen/c0f6f3e7-7400-46a4-941c-a95860a5e177> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c0f6f3e7-7400-46a4-941c-a95860a5e177> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Freddy".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c0f6f3e7-7400-46a4-941c-a95860a5e177> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/4822df90-439f-4852-9632-ab7bfa9cd56c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4822df90-439f-4852-9632-ab7bfa9cd56c> a person:Person.
           <http://data.lblod.info/id/personen/4822df90-439f-4852-9632-ab7bfa9cd56c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4822df90-439f-4852-9632-ab7bfa9cd56c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Inge".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4822df90-439f-4852-9632-ab7bfa9cd56c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/15f549dc-96e9-43ce-92ca-18924cefb4ae> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/15f549dc-96e9-43ce-92ca-18924cefb4ae> a person:Person.
           <http://data.lblod.info/id/personen/15f549dc-96e9-43ce-92ca-18924cefb4ae> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/15f549dc-96e9-43ce-92ca-18924cefb4ae> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Juri".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/15f549dc-96e9-43ce-92ca-18924cefb4ae> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/20e0d99c-82d9-4cf4-8da6-d4cd79962fa3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/20e0d99c-82d9-4cf4-8da6-d4cd79962fa3> a person:Person.
           <http://data.lblod.info/id/personen/20e0d99c-82d9-4cf4-8da6-d4cd79962fa3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/20e0d99c-82d9-4cf4-8da6-d4cd79962fa3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Kelly".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/20e0d99c-82d9-4cf4-8da6-d4cd79962fa3> [] [].
          }
        }
     # finished voornamen-update-17635-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:19+00:00