# started voornamen-update-4518-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:05:46+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/8963fec4afd5ea83f37de68dcc9e944b15396c54ec0ca77aa498e764ec6cc0d5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8963fec4afd5ea83f37de68dcc9e944b15396c54ec0ca77aa498e764ec6cc0d5> a person:Person.
           <http://data.lblod.info/id/personen/8963fec4afd5ea83f37de68dcc9e944b15396c54ec0ca77aa498e764ec6cc0d5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8963fec4afd5ea83f37de68dcc9e944b15396c54ec0ca77aa498e764ec6cc0d5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Mirda".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8963fec4afd5ea83f37de68dcc9e944b15396c54ec0ca77aa498e764ec6cc0d5> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/7fba8649e7210cc4627037e2402effa52132280ad5cfc7b2e8c80cdf00fd5b5c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7fba8649e7210cc4627037e2402effa52132280ad5cfc7b2e8c80cdf00fd5b5c> a person:Person.
           <http://data.lblod.info/id/personen/7fba8649e7210cc4627037e2402effa52132280ad5cfc7b2e8c80cdf00fd5b5c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7fba8649e7210cc4627037e2402effa52132280ad5cfc7b2e8c80cdf00fd5b5c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Pieter".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7fba8649e7210cc4627037e2402effa52132280ad5cfc7b2e8c80cdf00fd5b5c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/6c8170a9-098d-46d1-aa04-1d6b4256c1b0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6c8170a9-098d-46d1-aa04-1d6b4256c1b0> a person:Person.
           <http://data.lblod.info/id/personen/6c8170a9-098d-46d1-aa04-1d6b4256c1b0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6c8170a9-098d-46d1-aa04-1d6b4256c1b0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marie-Christine".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6c8170a9-098d-46d1-aa04-1d6b4256c1b0> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/b6eba9fe-6456-40b5-810f-5073bff57f59> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b6eba9fe-6456-40b5-810f-5073bff57f59> a person:Person.
           <http://data.lblod.info/id/personen/b6eba9fe-6456-40b5-810f-5073bff57f59> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b6eba9fe-6456-40b5-810f-5073bff57f59> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Luc".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b6eba9fe-6456-40b5-810f-5073bff57f59> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/20920d19bf63a74f9e8f95b947531aabf3e18c09f80c62908e817dc9bc9a2375> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/20920d19bf63a74f9e8f95b947531aabf3e18c09f80c62908e817dc9bc9a2375> a person:Person.
           <http://data.lblod.info/id/personen/20920d19bf63a74f9e8f95b947531aabf3e18c09f80c62908e817dc9bc9a2375> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/20920d19bf63a74f9e8f95b947531aabf3e18c09f80c62908e817dc9bc9a2375> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Maria".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/20920d19bf63a74f9e8f95b947531aabf3e18c09f80c62908e817dc9bc9a2375> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/9f5eef118b0a2a7b88401dffe6d8bf2cf3687284e90b926fca8226b878bc00d5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9f5eef118b0a2a7b88401dffe6d8bf2cf3687284e90b926fca8226b878bc00d5> a person:Person.
           <http://data.lblod.info/id/personen/9f5eef118b0a2a7b88401dffe6d8bf2cf3687284e90b926fca8226b878bc00d5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9f5eef118b0a2a7b88401dffe6d8bf2cf3687284e90b926fca8226b878bc00d5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Hubert".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9f5eef118b0a2a7b88401dffe6d8bf2cf3687284e90b926fca8226b878bc00d5> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/7e00570accc225dec691bbac60dc22a09b9de05591f2727f481c9b7c37a5e79b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7e00570accc225dec691bbac60dc22a09b9de05591f2727f481c9b7c37a5e79b> a person:Person.
           <http://data.lblod.info/id/personen/7e00570accc225dec691bbac60dc22a09b9de05591f2727f481c9b7c37a5e79b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7e00570accc225dec691bbac60dc22a09b9de05591f2727f481c9b7c37a5e79b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Lies".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7e00570accc225dec691bbac60dc22a09b9de05591f2727f481c9b7c37a5e79b> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/35d095adbd951df547ae74d20067ecb1816f975d4da193c6ef7c98b03cb6312a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/35d095adbd951df547ae74d20067ecb1816f975d4da193c6ef7c98b03cb6312a> a person:Person.
           <http://data.lblod.info/id/personen/35d095adbd951df547ae74d20067ecb1816f975d4da193c6ef7c98b03cb6312a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/35d095adbd951df547ae74d20067ecb1816f975d4da193c6ef7c98b03cb6312a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Rudy".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/35d095adbd951df547ae74d20067ecb1816f975d4da193c6ef7c98b03cb6312a> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/99cba94e1200fe4947db4e656faf40891f4587f58c9dc0efa82a137ab2d1ae03> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/99cba94e1200fe4947db4e656faf40891f4587f58c9dc0efa82a137ab2d1ae03> a person:Person.
           <http://data.lblod.info/id/personen/99cba94e1200fe4947db4e656faf40891f4587f58c9dc0efa82a137ab2d1ae03> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/99cba94e1200fe4947db4e656faf40891f4587f58c9dc0efa82a137ab2d1ae03> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Wim".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/99cba94e1200fe4947db4e656faf40891f4587f58c9dc0efa82a137ab2d1ae03> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/bb93aeea-ff0c-4a1e-8730-bc457df16af3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bb93aeea-ff0c-4a1e-8730-bc457df16af3> a person:Person.
           <http://data.lblod.info/id/personen/bb93aeea-ff0c-4a1e-8730-bc457df16af3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bb93aeea-ff0c-4a1e-8730-bc457df16af3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Carl".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bb93aeea-ff0c-4a1e-8730-bc457df16af3> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f3b87a955a7d0fb1e7c7ed3fd922e9618b3541952f6809ceaacf486fc132cf1c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f3b87a955a7d0fb1e7c7ed3fd922e9618b3541952f6809ceaacf486fc132cf1c> a person:Person.
           <http://data.lblod.info/id/personen/f3b87a955a7d0fb1e7c7ed3fd922e9618b3541952f6809ceaacf486fc132cf1c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f3b87a955a7d0fb1e7c7ed3fd922e9618b3541952f6809ceaacf486fc132cf1c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Koen".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f3b87a955a7d0fb1e7c7ed3fd922e9618b3541952f6809ceaacf486fc132cf1c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/1cca5750c68f5676023dadc5e6e18477bc063b69f1fd0a27bcfaa347e7384205> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1cca5750c68f5676023dadc5e6e18477bc063b69f1fd0a27bcfaa347e7384205> a person:Person.
           <http://data.lblod.info/id/personen/1cca5750c68f5676023dadc5e6e18477bc063b69f1fd0a27bcfaa347e7384205> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1cca5750c68f5676023dadc5e6e18477bc063b69f1fd0a27bcfaa347e7384205> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Annemie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1cca5750c68f5676023dadc5e6e18477bc063b69f1fd0a27bcfaa347e7384205> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/b21671f459e165cd734313349f52d2da8cb6ff6f373f434f7d139c649f00eaf3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b21671f459e165cd734313349f52d2da8cb6ff6f373f434f7d139c649f00eaf3> a person:Person.
           <http://data.lblod.info/id/personen/b21671f459e165cd734313349f52d2da8cb6ff6f373f434f7d139c649f00eaf3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b21671f459e165cd734313349f52d2da8cb6ff6f373f434f7d139c649f00eaf3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jef".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b21671f459e165cd734313349f52d2da8cb6ff6f373f434f7d139c649f00eaf3> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f7bcc58e4625add41aaa8c03bd1283710f86233857cdb7ca61aef410ddcc65ab> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f7bcc58e4625add41aaa8c03bd1283710f86233857cdb7ca61aef410ddcc65ab> a person:Person.
           <http://data.lblod.info/id/personen/f7bcc58e4625add41aaa8c03bd1283710f86233857cdb7ca61aef410ddcc65ab> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f7bcc58e4625add41aaa8c03bd1283710f86233857cdb7ca61aef410ddcc65ab> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Chris".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f7bcc58e4625add41aaa8c03bd1283710f86233857cdb7ca61aef410ddcc65ab> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/88e24c1c53e8c2683ecc4d385a2bc10a7f154dd5e16b7296232e5ec82fa09665> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/88e24c1c53e8c2683ecc4d385a2bc10a7f154dd5e16b7296232e5ec82fa09665> a person:Person.
           <http://data.lblod.info/id/personen/88e24c1c53e8c2683ecc4d385a2bc10a7f154dd5e16b7296232e5ec82fa09665> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/88e24c1c53e8c2683ecc4d385a2bc10a7f154dd5e16b7296232e5ec82fa09665> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Swa".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/88e24c1c53e8c2683ecc4d385a2bc10a7f154dd5e16b7296232e5ec82fa09665> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/1f8bad63-0892-4f83-986c-7529fe086524> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1f8bad63-0892-4f83-986c-7529fe086524> a person:Person.
           <http://data.lblod.info/id/personen/1f8bad63-0892-4f83-986c-7529fe086524> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1f8bad63-0892-4f83-986c-7529fe086524> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Anneke".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1f8bad63-0892-4f83-986c-7529fe086524> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/b2ff0a28-ae22-4c65-9f90-4edc83f09ab0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b2ff0a28-ae22-4c65-9f90-4edc83f09ab0> a person:Person.
           <http://data.lblod.info/id/personen/b2ff0a28-ae22-4c65-9f90-4edc83f09ab0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b2ff0a28-ae22-4c65-9f90-4edc83f09ab0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Michel".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b2ff0a28-ae22-4c65-9f90-4edc83f09ab0> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/1dce7b5e-d00a-445a-9a2e-15e5ed90be05> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1dce7b5e-d00a-445a-9a2e-15e5ed90be05> a person:Person.
           <http://data.lblod.info/id/personen/1dce7b5e-d00a-445a-9a2e-15e5ed90be05> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1dce7b5e-d00a-445a-9a2e-15e5ed90be05> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Wim".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1dce7b5e-d00a-445a-9a2e-15e5ed90be05> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/16dd9a0b38ff0243437092879e1503d8f181ff5172efc1290849fe85770e4000> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/16dd9a0b38ff0243437092879e1503d8f181ff5172efc1290849fe85770e4000> a person:Person.
           <http://data.lblod.info/id/personen/16dd9a0b38ff0243437092879e1503d8f181ff5172efc1290849fe85770e4000> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/16dd9a0b38ff0243437092879e1503d8f181ff5172efc1290849fe85770e4000> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Christiane".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/16dd9a0b38ff0243437092879e1503d8f181ff5172efc1290849fe85770e4000> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/7dfed819468cd00ebbb3946afc75a404b5e2b10293c3656a684e1c58ed9ca148> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7dfed819468cd00ebbb3946afc75a404b5e2b10293c3656a684e1c58ed9ca148> a person:Person.
           <http://data.lblod.info/id/personen/7dfed819468cd00ebbb3946afc75a404b5e2b10293c3656a684e1c58ed9ca148> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7dfed819468cd00ebbb3946afc75a404b5e2b10293c3656a684e1c58ed9ca148> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Geert".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7dfed819468cd00ebbb3946afc75a404b5e2b10293c3656a684e1c58ed9ca148> [] [].
          }
        }
     # finished voornamen-update-4518-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:05:46+00:00