# started voornamen-update-34121-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:07:01+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/4ae4b4ae24260c31d5d64d38ee7b46a1a3e69d2a838a7556c7d9a227a34e1596> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4ae4b4ae24260c31d5d64d38ee7b46a1a3e69d2a838a7556c7d9a227a34e1596> a person:Person.
           <http://data.lblod.info/id/personen/4ae4b4ae24260c31d5d64d38ee7b46a1a3e69d2a838a7556c7d9a227a34e1596> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4ae4b4ae24260c31d5d64d38ee7b46a1a3e69d2a838a7556c7d9a227a34e1596> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Toos".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4ae4b4ae24260c31d5d64d38ee7b46a1a3e69d2a838a7556c7d9a227a34e1596> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/8249b064-c41b-419f-bf94-41cf01d25b17> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8249b064-c41b-419f-bf94-41cf01d25b17> a person:Person.
           <http://data.lblod.info/id/personen/8249b064-c41b-419f-bf94-41cf01d25b17> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8249b064-c41b-419f-bf94-41cf01d25b17> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Robert".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8249b064-c41b-419f-bf94-41cf01d25b17> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/727b0c53d27802dd0d09259dfc8dc5c3d943f6727900668de39f5b3e8becd91c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/727b0c53d27802dd0d09259dfc8dc5c3d943f6727900668de39f5b3e8becd91c> a person:Person.
           <http://data.lblod.info/id/personen/727b0c53d27802dd0d09259dfc8dc5c3d943f6727900668de39f5b3e8becd91c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/727b0c53d27802dd0d09259dfc8dc5c3d943f6727900668de39f5b3e8becd91c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Albert".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/727b0c53d27802dd0d09259dfc8dc5c3d943f6727900668de39f5b3e8becd91c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/abf7a568-a84b-4d55-ae7a-05c7ed2d528e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/abf7a568-a84b-4d55-ae7a-05c7ed2d528e> a person:Person.
           <http://data.lblod.info/id/personen/abf7a568-a84b-4d55-ae7a-05c7ed2d528e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/abf7a568-a84b-4d55-ae7a-05c7ed2d528e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jane".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/abf7a568-a84b-4d55-ae7a-05c7ed2d528e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/dc7f8a08fe306e1684bf23c00564bbca95d475184a51b8c7b67238a5cd614ad4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/dc7f8a08fe306e1684bf23c00564bbca95d475184a51b8c7b67238a5cd614ad4> a person:Person.
           <http://data.lblod.info/id/personen/dc7f8a08fe306e1684bf23c00564bbca95d475184a51b8c7b67238a5cd614ad4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/dc7f8a08fe306e1684bf23c00564bbca95d475184a51b8c7b67238a5cd614ad4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Bianca".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/dc7f8a08fe306e1684bf23c00564bbca95d475184a51b8c7b67238a5cd614ad4> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f81befbadf49aba0f73a0e37207ec64eb3cf77aa7ff9fd688022c0fada3d8e90> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f81befbadf49aba0f73a0e37207ec64eb3cf77aa7ff9fd688022c0fada3d8e90> a person:Person.
           <http://data.lblod.info/id/personen/f81befbadf49aba0f73a0e37207ec64eb3cf77aa7ff9fd688022c0fada3d8e90> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f81befbadf49aba0f73a0e37207ec64eb3cf77aa7ff9fd688022c0fada3d8e90> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Rita".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f81befbadf49aba0f73a0e37207ec64eb3cf77aa7ff9fd688022c0fada3d8e90> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/bf74e7c2780d730fd589d3136de27b43be1c790f5cc9826734681a688ccec9b9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bf74e7c2780d730fd589d3136de27b43be1c790f5cc9826734681a688ccec9b9> a person:Person.
           <http://data.lblod.info/id/personen/bf74e7c2780d730fd589d3136de27b43be1c790f5cc9826734681a688ccec9b9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bf74e7c2780d730fd589d3136de27b43be1c790f5cc9826734681a688ccec9b9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Stefan".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bf74e7c2780d730fd589d3136de27b43be1c790f5cc9826734681a688ccec9b9> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/0e04609e264828730002466b624ab28244cc4023220b54ac89cdaa8f9bd2e0c7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0e04609e264828730002466b624ab28244cc4023220b54ac89cdaa8f9bd2e0c7> a person:Person.
           <http://data.lblod.info/id/personen/0e04609e264828730002466b624ab28244cc4023220b54ac89cdaa8f9bd2e0c7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0e04609e264828730002466b624ab28244cc4023220b54ac89cdaa8f9bd2e0c7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Paul".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0e04609e264828730002466b624ab28244cc4023220b54ac89cdaa8f9bd2e0c7> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/9303258fb3828099142c7b46b43869bb9c3e1f15b90b05b531032fafc9c27de6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9303258fb3828099142c7b46b43869bb9c3e1f15b90b05b531032fafc9c27de6> a person:Person.
           <http://data.lblod.info/id/personen/9303258fb3828099142c7b46b43869bb9c3e1f15b90b05b531032fafc9c27de6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9303258fb3828099142c7b46b43869bb9c3e1f15b90b05b531032fafc9c27de6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Willy".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9303258fb3828099142c7b46b43869bb9c3e1f15b90b05b531032fafc9c27de6> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/1ae96107-5b40-43a7-9f31-faa71e2649c0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1ae96107-5b40-43a7-9f31-faa71e2649c0> a person:Person.
           <http://data.lblod.info/id/personen/1ae96107-5b40-43a7-9f31-faa71e2649c0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1ae96107-5b40-43a7-9f31-faa71e2649c0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ludo".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1ae96107-5b40-43a7-9f31-faa71e2649c0> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/52aab1b8feaa14929c571c8aad8d6a88c28392f5cedcf2dee6a09c136254b691> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/52aab1b8feaa14929c571c8aad8d6a88c28392f5cedcf2dee6a09c136254b691> a person:Person.
           <http://data.lblod.info/id/personen/52aab1b8feaa14929c571c8aad8d6a88c28392f5cedcf2dee6a09c136254b691> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/52aab1b8feaa14929c571c8aad8d6a88c28392f5cedcf2dee6a09c136254b691> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jos".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/52aab1b8feaa14929c571c8aad8d6a88c28392f5cedcf2dee6a09c136254b691> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/706cba03cf5fa919d4fb4d23cc4f725d6857b581a425f9f74d57e843dc4d18d5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/706cba03cf5fa919d4fb4d23cc4f725d6857b581a425f9f74d57e843dc4d18d5> a person:Person.
           <http://data.lblod.info/id/personen/706cba03cf5fa919d4fb4d23cc4f725d6857b581a425f9f74d57e843dc4d18d5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/706cba03cf5fa919d4fb4d23cc4f725d6857b581a425f9f74d57e843dc4d18d5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Johan".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/706cba03cf5fa919d4fb4d23cc4f725d6857b581a425f9f74d57e843dc4d18d5> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/1e3883cb0a03ae846969e8b7914eb4fe204a2ed8ee6ba08dfe1cffe2985e5453> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1e3883cb0a03ae846969e8b7914eb4fe204a2ed8ee6ba08dfe1cffe2985e5453> a person:Person.
           <http://data.lblod.info/id/personen/1e3883cb0a03ae846969e8b7914eb4fe204a2ed8ee6ba08dfe1cffe2985e5453> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1e3883cb0a03ae846969e8b7914eb4fe204a2ed8ee6ba08dfe1cffe2985e5453> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "José".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1e3883cb0a03ae846969e8b7914eb4fe204a2ed8ee6ba08dfe1cffe2985e5453> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f74e0c88629a50802b2dcafa79bf6d36ba0b47fcac601911ca16f14a66adf39d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f74e0c88629a50802b2dcafa79bf6d36ba0b47fcac601911ca16f14a66adf39d> a person:Person.
           <http://data.lblod.info/id/personen/f74e0c88629a50802b2dcafa79bf6d36ba0b47fcac601911ca16f14a66adf39d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f74e0c88629a50802b2dcafa79bf6d36ba0b47fcac601911ca16f14a66adf39d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jean".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f74e0c88629a50802b2dcafa79bf6d36ba0b47fcac601911ca16f14a66adf39d> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2d66b14fb60c4d91eb36e54361dfac0dcc407bd91e1b8165bf64786c2b5332c9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2d66b14fb60c4d91eb36e54361dfac0dcc407bd91e1b8165bf64786c2b5332c9> a person:Person.
           <http://data.lblod.info/id/personen/2d66b14fb60c4d91eb36e54361dfac0dcc407bd91e1b8165bf64786c2b5332c9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2d66b14fb60c4d91eb36e54361dfac0dcc407bd91e1b8165bf64786c2b5332c9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Veronique".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2d66b14fb60c4d91eb36e54361dfac0dcc407bd91e1b8165bf64786c2b5332c9> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/8273317e7a9509b903bc0b394d59e5fd918e34d0dbf841f117af422b0f837e8b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8273317e7a9509b903bc0b394d59e5fd918e34d0dbf841f117af422b0f837e8b> a person:Person.
           <http://data.lblod.info/id/personen/8273317e7a9509b903bc0b394d59e5fd918e34d0dbf841f117af422b0f837e8b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8273317e7a9509b903bc0b394d59e5fd918e34d0dbf841f117af422b0f837e8b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Theo".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8273317e7a9509b903bc0b394d59e5fd918e34d0dbf841f117af422b0f837e8b> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/0713cd90-a58d-4316-8b29-d3ca695cff5d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0713cd90-a58d-4316-8b29-d3ca695cff5d> a person:Person.
           <http://data.lblod.info/id/personen/0713cd90-a58d-4316-8b29-d3ca695cff5d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0713cd90-a58d-4316-8b29-d3ca695cff5d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ann".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0713cd90-a58d-4316-8b29-d3ca695cff5d> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/b405fa6d-a809-46e7-956d-6c7c82fe4bb2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b405fa6d-a809-46e7-956d-6c7c82fe4bb2> a person:Person.
           <http://data.lblod.info/id/personen/b405fa6d-a809-46e7-956d-6c7c82fe4bb2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b405fa6d-a809-46e7-956d-6c7c82fe4bb2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Hugo".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b405fa6d-a809-46e7-956d-6c7c82fe4bb2> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/60f4f7cd-79e3-4f15-bd04-b5ca706369ef> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/60f4f7cd-79e3-4f15-bd04-b5ca706369ef> a person:Person.
           <http://data.lblod.info/id/personen/60f4f7cd-79e3-4f15-bd04-b5ca706369ef> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/60f4f7cd-79e3-4f15-bd04-b5ca706369ef> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jolique".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/60f4f7cd-79e3-4f15-bd04-b5ca706369ef> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/4efc797c-206e-49bf-9b50-ab884016b05d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4efc797c-206e-49bf-9b50-ab884016b05d> a person:Person.
           <http://data.lblod.info/id/personen/4efc797c-206e-49bf-9b50-ab884016b05d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4efc797c-206e-49bf-9b50-ab884016b05d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Erwin".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4efc797c-206e-49bf-9b50-ab884016b05d> [] [].
          }
        }
     # finished voornamen-update-34121-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:07:01+00:00