# started voornamen-update-36490-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:07:07+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/041350bd-44df-4ebd-a908-8b93f12677e0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/041350bd-44df-4ebd-a908-8b93f12677e0> a person:Person.
           <http://data.lblod.info/id/personen/041350bd-44df-4ebd-a908-8b93f12677e0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/041350bd-44df-4ebd-a908-8b93f12677e0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Anja".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/041350bd-44df-4ebd-a908-8b93f12677e0> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/a797ded4-b5c2-414b-a5c1-a5300402b344> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a797ded4-b5c2-414b-a5c1-a5300402b344> a person:Person.
           <http://data.lblod.info/id/personen/a797ded4-b5c2-414b-a5c1-a5300402b344> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a797ded4-b5c2-414b-a5c1-a5300402b344> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Bart".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a797ded4-b5c2-414b-a5c1-a5300402b344> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/10a3ef31-f584-423f-a7e3-59f588640a64> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/10a3ef31-f584-423f-a7e3-59f588640a64> a person:Person.
           <http://data.lblod.info/id/personen/10a3ef31-f584-423f-a7e3-59f588640a64> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/10a3ef31-f584-423f-a7e3-59f588640a64> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Sofie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/10a3ef31-f584-423f-a7e3-59f588640a64> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/c5b40f38-7932-4a0e-8ccf-4e4bcacf748d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c5b40f38-7932-4a0e-8ccf-4e4bcacf748d> a person:Person.
           <http://data.lblod.info/id/personen/c5b40f38-7932-4a0e-8ccf-4e4bcacf748d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c5b40f38-7932-4a0e-8ccf-4e4bcacf748d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marijke".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c5b40f38-7932-4a0e-8ccf-4e4bcacf748d> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/77e521ff-185e-405e-8a49-279a2acee0d6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/77e521ff-185e-405e-8a49-279a2acee0d6> a person:Person.
           <http://data.lblod.info/id/personen/77e521ff-185e-405e-8a49-279a2acee0d6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/77e521ff-185e-405e-8a49-279a2acee0d6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Dirk".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/77e521ff-185e-405e-8a49-279a2acee0d6> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/58a887a4-e1ef-4cd1-bae4-1a3e68bc56f9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/58a887a4-e1ef-4cd1-bae4-1a3e68bc56f9> a person:Person.
           <http://data.lblod.info/id/personen/58a887a4-e1ef-4cd1-bae4-1a3e68bc56f9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/58a887a4-e1ef-4cd1-bae4-1a3e68bc56f9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Tinny".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/58a887a4-e1ef-4cd1-bae4-1a3e68bc56f9> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2348be53-d561-4d29-8da5-120dfdf2c334> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2348be53-d561-4d29-8da5-120dfdf2c334> a person:Person.
           <http://data.lblod.info/id/personen/2348be53-d561-4d29-8da5-120dfdf2c334> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2348be53-d561-4d29-8da5-120dfdf2c334> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Willy".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2348be53-d561-4d29-8da5-120dfdf2c334> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/093e13d3-a07e-4010-9114-5d5e7fc9013d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/093e13d3-a07e-4010-9114-5d5e7fc9013d> a person:Person.
           <http://data.lblod.info/id/personen/093e13d3-a07e-4010-9114-5d5e7fc9013d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/093e13d3-a07e-4010-9114-5d5e7fc9013d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Petra".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/093e13d3-a07e-4010-9114-5d5e7fc9013d> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/1e4bfb04-49f6-4ac3-af92-930ea79aa65c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1e4bfb04-49f6-4ac3-af92-930ea79aa65c> a person:Person.
           <http://data.lblod.info/id/personen/1e4bfb04-49f6-4ac3-af92-930ea79aa65c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1e4bfb04-49f6-4ac3-af92-930ea79aa65c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Raf".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1e4bfb04-49f6-4ac3-af92-930ea79aa65c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/81027feb6dd0433978df1e74843ed2be28507ba3bd10557a92f88f2680bacb50> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/81027feb6dd0433978df1e74843ed2be28507ba3bd10557a92f88f2680bacb50> a person:Person.
           <http://data.lblod.info/id/personen/81027feb6dd0433978df1e74843ed2be28507ba3bd10557a92f88f2680bacb50> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/81027feb6dd0433978df1e74843ed2be28507ba3bd10557a92f88f2680bacb50> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Elvire".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/81027feb6dd0433978df1e74843ed2be28507ba3bd10557a92f88f2680bacb50> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2e594ce730af0cf1a7bd439d0819883352da62a0f94a19b41f03e214baf28af1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2e594ce730af0cf1a7bd439d0819883352da62a0f94a19b41f03e214baf28af1> a person:Person.
           <http://data.lblod.info/id/personen/2e594ce730af0cf1a7bd439d0819883352da62a0f94a19b41f03e214baf28af1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2e594ce730af0cf1a7bd439d0819883352da62a0f94a19b41f03e214baf28af1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Costa".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2e594ce730af0cf1a7bd439d0819883352da62a0f94a19b41f03e214baf28af1> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/b7dee9823ae3cda8c19c369593d12c7b17f2ad5ff9eeba337ae99d2cf7529fe3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b7dee9823ae3cda8c19c369593d12c7b17f2ad5ff9eeba337ae99d2cf7529fe3> a person:Person.
           <http://data.lblod.info/id/personen/b7dee9823ae3cda8c19c369593d12c7b17f2ad5ff9eeba337ae99d2cf7529fe3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b7dee9823ae3cda8c19c369593d12c7b17f2ad5ff9eeba337ae99d2cf7529fe3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Patrick".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b7dee9823ae3cda8c19c369593d12c7b17f2ad5ff9eeba337ae99d2cf7529fe3> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ec009ba5-8690-4184-b160-37b8e395a3a7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ec009ba5-8690-4184-b160-37b8e395a3a7> a person:Person.
           <http://data.lblod.info/id/personen/ec009ba5-8690-4184-b160-37b8e395a3a7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ec009ba5-8690-4184-b160-37b8e395a3a7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Lorenza".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ec009ba5-8690-4184-b160-37b8e395a3a7> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/61b848ea-cc42-4e56-8799-bf9869f06655> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/61b848ea-cc42-4e56-8799-bf9869f06655> a person:Person.
           <http://data.lblod.info/id/personen/61b848ea-cc42-4e56-8799-bf9869f06655> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/61b848ea-cc42-4e56-8799-bf9869f06655> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Stef".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/61b848ea-cc42-4e56-8799-bf9869f06655> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/418b3afe-ea7b-440d-a255-216451645f06> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/418b3afe-ea7b-440d-a255-216451645f06> a person:Person.
           <http://data.lblod.info/id/personen/418b3afe-ea7b-440d-a255-216451645f06> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/418b3afe-ea7b-440d-a255-216451645f06> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Henny".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/418b3afe-ea7b-440d-a255-216451645f06> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/7a1b5ba5-5c86-4d0c-bcc2-d81745148fe6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7a1b5ba5-5c86-4d0c-bcc2-d81745148fe6> a person:Person.
           <http://data.lblod.info/id/personen/7a1b5ba5-5c86-4d0c-bcc2-d81745148fe6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7a1b5ba5-5c86-4d0c-bcc2-d81745148fe6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Roula".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7a1b5ba5-5c86-4d0c-bcc2-d81745148fe6> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/bbd77f1db48015700f6fd5a77ddfc0eb82f3f237fc5c7ca97e2f9f6fafadfa69> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bbd77f1db48015700f6fd5a77ddfc0eb82f3f237fc5c7ca97e2f9f6fafadfa69> a person:Person.
           <http://data.lblod.info/id/personen/bbd77f1db48015700f6fd5a77ddfc0eb82f3f237fc5c7ca97e2f9f6fafadfa69> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bbd77f1db48015700f6fd5a77ddfc0eb82f3f237fc5c7ca97e2f9f6fafadfa69> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Franky".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bbd77f1db48015700f6fd5a77ddfc0eb82f3f237fc5c7ca97e2f9f6fafadfa69> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/0a829c45-4706-4033-9a39-12fdf96fd29d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0a829c45-4706-4033-9a39-12fdf96fd29d> a person:Person.
           <http://data.lblod.info/id/personen/0a829c45-4706-4033-9a39-12fdf96fd29d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0a829c45-4706-4033-9a39-12fdf96fd29d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jessica".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0a829c45-4706-4033-9a39-12fdf96fd29d> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/42eb13a3-69dc-470d-ba8e-9742cb02ef8f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/42eb13a3-69dc-470d-ba8e-9742cb02ef8f> a person:Person.
           <http://data.lblod.info/id/personen/42eb13a3-69dc-470d-ba8e-9742cb02ef8f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/42eb13a3-69dc-470d-ba8e-9742cb02ef8f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Yolanda".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/42eb13a3-69dc-470d-ba8e-9742cb02ef8f> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/cb60150f-81a0-4e7a-a227-9fe33e7f6b19> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cb60150f-81a0-4e7a-a227-9fe33e7f6b19> a person:Person.
           <http://data.lblod.info/id/personen/cb60150f-81a0-4e7a-a227-9fe33e7f6b19> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cb60150f-81a0-4e7a-a227-9fe33e7f6b19> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Sarah".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cb60150f-81a0-4e7a-a227-9fe33e7f6b19> [] [].
          }
        }
     # finished voornamen-update-36490-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:07:07+00:00