# started voornamen-update-28052-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:45+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2ab21940-aa7a-4877-a6d3-90176897e68a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2ab21940-aa7a-4877-a6d3-90176897e68a> a person:Person.
           <http://data.lblod.info/id/personen/2ab21940-aa7a-4877-a6d3-90176897e68a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2ab21940-aa7a-4877-a6d3-90176897e68a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ann".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2ab21940-aa7a-4877-a6d3-90176897e68a> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f2411c0c-b866-464c-b2ae-0e829ea50cbd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f2411c0c-b866-464c-b2ae-0e829ea50cbd> a person:Person.
           <http://data.lblod.info/id/personen/f2411c0c-b866-464c-b2ae-0e829ea50cbd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f2411c0c-b866-464c-b2ae-0e829ea50cbd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Pierre".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f2411c0c-b866-464c-b2ae-0e829ea50cbd> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/6dcf81c4-2d38-48b0-b37e-b01e158ca13e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6dcf81c4-2d38-48b0-b37e-b01e158ca13e> a person:Person.
           <http://data.lblod.info/id/personen/6dcf81c4-2d38-48b0-b37e-b01e158ca13e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6dcf81c4-2d38-48b0-b37e-b01e158ca13e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Annemie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6dcf81c4-2d38-48b0-b37e-b01e158ca13e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/3aac8c50-3bc2-45c8-bde9-ee4514f0f7fd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3aac8c50-3bc2-45c8-bde9-ee4514f0f7fd> a person:Person.
           <http://data.lblod.info/id/personen/3aac8c50-3bc2-45c8-bde9-ee4514f0f7fd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3aac8c50-3bc2-45c8-bde9-ee4514f0f7fd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Olivier".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3aac8c50-3bc2-45c8-bde9-ee4514f0f7fd> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/4158f036-42f4-49c2-92fd-fa3037b96daf> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4158f036-42f4-49c2-92fd-fa3037b96daf> a person:Person.
           <http://data.lblod.info/id/personen/4158f036-42f4-49c2-92fd-fa3037b96daf> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4158f036-42f4-49c2-92fd-fa3037b96daf> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Robert".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4158f036-42f4-49c2-92fd-fa3037b96daf> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e1b468f8-5ece-45cd-818f-656e5663771f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e1b468f8-5ece-45cd-818f-656e5663771f> a person:Person.
           <http://data.lblod.info/id/personen/e1b468f8-5ece-45cd-818f-656e5663771f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e1b468f8-5ece-45cd-818f-656e5663771f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Véronique".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e1b468f8-5ece-45cd-818f-656e5663771f> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/118d4ed7-bd9a-4ffd-93db-dee4e59c88e6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/118d4ed7-bd9a-4ffd-93db-dee4e59c88e6> a person:Person.
           <http://data.lblod.info/id/personen/118d4ed7-bd9a-4ffd-93db-dee4e59c88e6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/118d4ed7-bd9a-4ffd-93db-dee4e59c88e6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Tatjana".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/118d4ed7-bd9a-4ffd-93db-dee4e59c88e6> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/0f6df435-8b92-4ed1-afe9-c25502bef6f2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0f6df435-8b92-4ed1-afe9-c25502bef6f2> a person:Person.
           <http://data.lblod.info/id/personen/0f6df435-8b92-4ed1-afe9-c25502bef6f2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0f6df435-8b92-4ed1-afe9-c25502bef6f2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Pascal".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0f6df435-8b92-4ed1-afe9-c25502bef6f2> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/5f01b23b-8cdf-4353-a45a-b37ede86d617> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5f01b23b-8cdf-4353-a45a-b37ede86d617> a person:Person.
           <http://data.lblod.info/id/personen/5f01b23b-8cdf-4353-a45a-b37ede86d617> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5f01b23b-8cdf-4353-a45a-b37ede86d617> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ingrid".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5f01b23b-8cdf-4353-a45a-b37ede86d617> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2384e0f1-3f75-40af-9eb3-19753d908fa3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2384e0f1-3f75-40af-9eb3-19753d908fa3> a person:Person.
           <http://data.lblod.info/id/personen/2384e0f1-3f75-40af-9eb3-19753d908fa3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2384e0f1-3f75-40af-9eb3-19753d908fa3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Elke".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2384e0f1-3f75-40af-9eb3-19753d908fa3> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/6f3d3c30-f3e3-4ca9-8ef4-558321728a62> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6f3d3c30-f3e3-4ca9-8ef4-558321728a62> a person:Person.
           <http://data.lblod.info/id/personen/6f3d3c30-f3e3-4ca9-8ef4-558321728a62> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6f3d3c30-f3e3-4ca9-8ef4-558321728a62> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Anne".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6f3d3c30-f3e3-4ca9-8ef4-558321728a62> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/d5b55493-c6c2-48a8-ae22-297e22319abd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d5b55493-c6c2-48a8-ae22-297e22319abd> a person:Person.
           <http://data.lblod.info/id/personen/d5b55493-c6c2-48a8-ae22-297e22319abd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d5b55493-c6c2-48a8-ae22-297e22319abd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Henk".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d5b55493-c6c2-48a8-ae22-297e22319abd> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2547df94-6864-4999-baf1-d489c3f233ed> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2547df94-6864-4999-baf1-d489c3f233ed> a person:Person.
           <http://data.lblod.info/id/personen/2547df94-6864-4999-baf1-d489c3f233ed> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2547df94-6864-4999-baf1-d489c3f233ed> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Noon".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2547df94-6864-4999-baf1-d489c3f233ed> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/302e1ffd-a26a-4c79-a2d0-ac8c4cf6a5c7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/302e1ffd-a26a-4c79-a2d0-ac8c4cf6a5c7> a person:Person.
           <http://data.lblod.info/id/personen/302e1ffd-a26a-4c79-a2d0-ac8c4cf6a5c7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/302e1ffd-a26a-4c79-a2d0-ac8c4cf6a5c7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jurgen".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/302e1ffd-a26a-4c79-a2d0-ac8c4cf6a5c7> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/92ac1361-ae8f-45f8-b862-e97c816b0acf> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/92ac1361-ae8f-45f8-b862-e97c816b0acf> a person:Person.
           <http://data.lblod.info/id/personen/92ac1361-ae8f-45f8-b862-e97c816b0acf> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/92ac1361-ae8f-45f8-b862-e97c816b0acf> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Sophie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/92ac1361-ae8f-45f8-b862-e97c816b0acf> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/25590dbb-bfc5-4620-a64a-fdff58d122c2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/25590dbb-bfc5-4620-a64a-fdff58d122c2> a person:Person.
           <http://data.lblod.info/id/personen/25590dbb-bfc5-4620-a64a-fdff58d122c2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/25590dbb-bfc5-4620-a64a-fdff58d122c2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Luc".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/25590dbb-bfc5-4620-a64a-fdff58d122c2> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2e6c841d-969f-4b5d-b845-6f7f966be044> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2e6c841d-969f-4b5d-b845-6f7f966be044> a person:Person.
           <http://data.lblod.info/id/personen/2e6c841d-969f-4b5d-b845-6f7f966be044> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2e6c841d-969f-4b5d-b845-6f7f966be044> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ingmar".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2e6c841d-969f-4b5d-b845-6f7f966be044> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/8c4817c7-ec9e-41f6-8c87-fc79ddf2f2ec> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8c4817c7-ec9e-41f6-8c87-fc79ddf2f2ec> a person:Person.
           <http://data.lblod.info/id/personen/8c4817c7-ec9e-41f6-8c87-fc79ddf2f2ec> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8c4817c7-ec9e-41f6-8c87-fc79ddf2f2ec> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Koen".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8c4817c7-ec9e-41f6-8c87-fc79ddf2f2ec> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/962851ab-d0b2-4280-a5da-bd12a3af7f76> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/962851ab-d0b2-4280-a5da-bd12a3af7f76> a person:Person.
           <http://data.lblod.info/id/personen/962851ab-d0b2-4280-a5da-bd12a3af7f76> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/962851ab-d0b2-4280-a5da-bd12a3af7f76> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Rosita".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/962851ab-d0b2-4280-a5da-bd12a3af7f76> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/78078f25-6390-4460-8b03-f115ab85f055> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/78078f25-6390-4460-8b03-f115ab85f055> a person:Person.
           <http://data.lblod.info/id/personen/78078f25-6390-4460-8b03-f115ab85f055> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/78078f25-6390-4460-8b03-f115ab85f055> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Sigrid".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/78078f25-6390-4460-8b03-f115ab85f055> [] [].
          }
        }
     # finished voornamen-update-28052-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:45+00:00