# started voornamen-update-704-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:05:37+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e5ffffe4b1e3034b45a20f73ec421aa6e5ededcae4201fbe28b869d7582362f4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e5ffffe4b1e3034b45a20f73ec421aa6e5ededcae4201fbe28b869d7582362f4> a person:Person.
           <http://data.lblod.info/id/personen/e5ffffe4b1e3034b45a20f73ec421aa6e5ededcae4201fbe28b869d7582362f4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e5ffffe4b1e3034b45a20f73ec421aa6e5ededcae4201fbe28b869d7582362f4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Greet".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e5ffffe4b1e3034b45a20f73ec421aa6e5ededcae4201fbe28b869d7582362f4> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e9628d17e4bae34ee3bf8fd7671e01a6e834d6f69e815c8692ac7e3e7852657c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e9628d17e4bae34ee3bf8fd7671e01a6e834d6f69e815c8692ac7e3e7852657c> a person:Person.
           <http://data.lblod.info/id/personen/e9628d17e4bae34ee3bf8fd7671e01a6e834d6f69e815c8692ac7e3e7852657c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e9628d17e4bae34ee3bf8fd7671e01a6e834d6f69e815c8692ac7e3e7852657c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Herman ".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e9628d17e4bae34ee3bf8fd7671e01a6e834d6f69e815c8692ac7e3e7852657c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/7fb03721de9dd4d42d8ef264c641922f05270141ede522a249f44de87f4b8b2f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7fb03721de9dd4d42d8ef264c641922f05270141ede522a249f44de87f4b8b2f> a person:Person.
           <http://data.lblod.info/id/personen/7fb03721de9dd4d42d8ef264c641922f05270141ede522a249f44de87f4b8b2f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7fb03721de9dd4d42d8ef264c641922f05270141ede522a249f44de87f4b8b2f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Wally".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7fb03721de9dd4d42d8ef264c641922f05270141ede522a249f44de87f4b8b2f> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ef96a199fb24261d3a1f10d6c6e42c459b62c3a918b4c815d1e8d03a324804dd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ef96a199fb24261d3a1f10d6c6e42c459b62c3a918b4c815d1e8d03a324804dd> a person:Person.
           <http://data.lblod.info/id/personen/ef96a199fb24261d3a1f10d6c6e42c459b62c3a918b4c815d1e8d03a324804dd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ef96a199fb24261d3a1f10d6c6e42c459b62c3a918b4c815d1e8d03a324804dd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Nele".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ef96a199fb24261d3a1f10d6c6e42c459b62c3a918b4c815d1e8d03a324804dd> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f874ab07853ac06cbabaf60d3807e22701792299a9b0f1b424727ea057e367b7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f874ab07853ac06cbabaf60d3807e22701792299a9b0f1b424727ea057e367b7> a person:Person.
           <http://data.lblod.info/id/personen/f874ab07853ac06cbabaf60d3807e22701792299a9b0f1b424727ea057e367b7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f874ab07853ac06cbabaf60d3807e22701792299a9b0f1b424727ea057e367b7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jan".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f874ab07853ac06cbabaf60d3807e22701792299a9b0f1b424727ea057e367b7> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/1a6ad17f-5ffd-4fa9-8f44-372351ebf903> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1a6ad17f-5ffd-4fa9-8f44-372351ebf903> a person:Person.
           <http://data.lblod.info/id/personen/1a6ad17f-5ffd-4fa9-8f44-372351ebf903> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1a6ad17f-5ffd-4fa9-8f44-372351ebf903> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jean".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1a6ad17f-5ffd-4fa9-8f44-372351ebf903> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/af03dcb3-c696-4228-b3de-b5d59a89c044> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/af03dcb3-c696-4228-b3de-b5d59a89c044> a person:Person.
           <http://data.lblod.info/id/personen/af03dcb3-c696-4228-b3de-b5d59a89c044> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/af03dcb3-c696-4228-b3de-b5d59a89c044> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Godelieve".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/af03dcb3-c696-4228-b3de-b5d59a89c044> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/76b8176bf41f127d8dfcfde6ac4f91376bf15de404826e4661b4d80ae4846317> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/76b8176bf41f127d8dfcfde6ac4f91376bf15de404826e4661b4d80ae4846317> a person:Person.
           <http://data.lblod.info/id/personen/76b8176bf41f127d8dfcfde6ac4f91376bf15de404826e4661b4d80ae4846317> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/76b8176bf41f127d8dfcfde6ac4f91376bf15de404826e4661b4d80ae4846317> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Mariette".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/76b8176bf41f127d8dfcfde6ac4f91376bf15de404826e4661b4d80ae4846317> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/1fe482e89cca763e00e7ceada72412b533f2ae08d2a638253cd20c43455a849b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1fe482e89cca763e00e7ceada72412b533f2ae08d2a638253cd20c43455a849b> a person:Person.
           <http://data.lblod.info/id/personen/1fe482e89cca763e00e7ceada72412b533f2ae08d2a638253cd20c43455a849b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1fe482e89cca763e00e7ceada72412b533f2ae08d2a638253cd20c43455a849b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Stine".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1fe482e89cca763e00e7ceada72412b533f2ae08d2a638253cd20c43455a849b> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/8ae04106-bb99-4d65-afb7-b1f6aafcddbd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8ae04106-bb99-4d65-afb7-b1f6aafcddbd> a person:Person.
           <http://data.lblod.info/id/personen/8ae04106-bb99-4d65-afb7-b1f6aafcddbd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8ae04106-bb99-4d65-afb7-b1f6aafcddbd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marleen".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8ae04106-bb99-4d65-afb7-b1f6aafcddbd> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/3330bf35962e783e18ecc1287303c549eeb7569010cae6b5a34e323e40952ac3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3330bf35962e783e18ecc1287303c549eeb7569010cae6b5a34e323e40952ac3> a person:Person.
           <http://data.lblod.info/id/personen/3330bf35962e783e18ecc1287303c549eeb7569010cae6b5a34e323e40952ac3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3330bf35962e783e18ecc1287303c549eeb7569010cae6b5a34e323e40952ac3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Tim".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3330bf35962e783e18ecc1287303c549eeb7569010cae6b5a34e323e40952ac3> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/004444613f6f17f7f2e2fb75d1666556698d3407129afd047ba74ced74612c76> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/004444613f6f17f7f2e2fb75d1666556698d3407129afd047ba74ced74612c76> a person:Person.
           <http://data.lblod.info/id/personen/004444613f6f17f7f2e2fb75d1666556698d3407129afd047ba74ced74612c76> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/004444613f6f17f7f2e2fb75d1666556698d3407129afd047ba74ced74612c76> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Stef".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/004444613f6f17f7f2e2fb75d1666556698d3407129afd047ba74ced74612c76> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/894297dad5c6239eb429cf1a86de9deae6ff7e3d22971044a624d507ec0296f5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/894297dad5c6239eb429cf1a86de9deae6ff7e3d22971044a624d507ec0296f5> a person:Person.
           <http://data.lblod.info/id/personen/894297dad5c6239eb429cf1a86de9deae6ff7e3d22971044a624d507ec0296f5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/894297dad5c6239eb429cf1a86de9deae6ff7e3d22971044a624d507ec0296f5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Annie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/894297dad5c6239eb429cf1a86de9deae6ff7e3d22971044a624d507ec0296f5> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/a3e80ff1-77bb-43e6-8f46-67c303b168a4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a3e80ff1-77bb-43e6-8f46-67c303b168a4> a person:Person.
           <http://data.lblod.info/id/personen/a3e80ff1-77bb-43e6-8f46-67c303b168a4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a3e80ff1-77bb-43e6-8f46-67c303b168a4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jef".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a3e80ff1-77bb-43e6-8f46-67c303b168a4> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/1559daf7-515b-4ed5-b2a6-b13791db5f29> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1559daf7-515b-4ed5-b2a6-b13791db5f29> a person:Person.
           <http://data.lblod.info/id/personen/1559daf7-515b-4ed5-b2a6-b13791db5f29> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1559daf7-515b-4ed5-b2a6-b13791db5f29> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ferre".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1559daf7-515b-4ed5-b2a6-b13791db5f29> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/3f31c865f6c1c5399a9af5bac7bb1dea1b97be17225e430a75cb0caff2e260a1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3f31c865f6c1c5399a9af5bac7bb1dea1b97be17225e430a75cb0caff2e260a1> a person:Person.
           <http://data.lblod.info/id/personen/3f31c865f6c1c5399a9af5bac7bb1dea1b97be17225e430a75cb0caff2e260a1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3f31c865f6c1c5399a9af5bac7bb1dea1b97be17225e430a75cb0caff2e260a1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Joris".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3f31c865f6c1c5399a9af5bac7bb1dea1b97be17225e430a75cb0caff2e260a1> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/867c71e1e1964057f5fddf36152243eb1f7252848b877025567079841fd0ad56> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/867c71e1e1964057f5fddf36152243eb1f7252848b877025567079841fd0ad56> a person:Person.
           <http://data.lblod.info/id/personen/867c71e1e1964057f5fddf36152243eb1f7252848b877025567079841fd0ad56> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/867c71e1e1964057f5fddf36152243eb1f7252848b877025567079841fd0ad56> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Lieve".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/867c71e1e1964057f5fddf36152243eb1f7252848b877025567079841fd0ad56> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/390c3469a589453ebd3558b6bff963ae3770e5a2fa5b1c9db6788f95787c944e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/390c3469a589453ebd3558b6bff963ae3770e5a2fa5b1c9db6788f95787c944e> a person:Person.
           <http://data.lblod.info/id/personen/390c3469a589453ebd3558b6bff963ae3770e5a2fa5b1c9db6788f95787c944e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/390c3469a589453ebd3558b6bff963ae3770e5a2fa5b1c9db6788f95787c944e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jo".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/390c3469a589453ebd3558b6bff963ae3770e5a2fa5b1c9db6788f95787c944e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/7e683f2a-ff5d-4de6-9160-1b753a62103e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7e683f2a-ff5d-4de6-9160-1b753a62103e> a person:Person.
           <http://data.lblod.info/id/personen/7e683f2a-ff5d-4de6-9160-1b753a62103e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7e683f2a-ff5d-4de6-9160-1b753a62103e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jenny".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7e683f2a-ff5d-4de6-9160-1b753a62103e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2fa63c9a6e08d52c5f5c98529cbbebd1d46cba708dc35c916b5d3cd46ff4c5aa> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2fa63c9a6e08d52c5f5c98529cbbebd1d46cba708dc35c916b5d3cd46ff4c5aa> a person:Person.
           <http://data.lblod.info/id/personen/2fa63c9a6e08d52c5f5c98529cbbebd1d46cba708dc35c916b5d3cd46ff4c5aa> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2fa63c9a6e08d52c5f5c98529cbbebd1d46cba708dc35c916b5d3cd46ff4c5aa> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ria".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2fa63c9a6e08d52c5f5c98529cbbebd1d46cba708dc35c916b5d3cd46ff4c5aa> [] [].
          }
        }
     # finished voornamen-update-704-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:05:37+00:00