# started voornamen-update-8515-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:05:56+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/69f40bff-dae3-4f10-9327-ec5bf716e523> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/69f40bff-dae3-4f10-9327-ec5bf716e523> a person:Person.
           <http://data.lblod.info/id/personen/69f40bff-dae3-4f10-9327-ec5bf716e523> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/69f40bff-dae3-4f10-9327-ec5bf716e523> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Kaat".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/69f40bff-dae3-4f10-9327-ec5bf716e523> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/a7110aca-da93-4f26-805f-bd925897dad4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a7110aca-da93-4f26-805f-bd925897dad4> a person:Person.
           <http://data.lblod.info/id/personen/a7110aca-da93-4f26-805f-bd925897dad4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a7110aca-da93-4f26-805f-bd925897dad4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ann".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a7110aca-da93-4f26-805f-bd925897dad4> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/8995722cd261e2f98ef42d2615ec6abcc0037393f5e971113ec3c38d1836618e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8995722cd261e2f98ef42d2615ec6abcc0037393f5e971113ec3c38d1836618e> a person:Person.
           <http://data.lblod.info/id/personen/8995722cd261e2f98ef42d2615ec6abcc0037393f5e971113ec3c38d1836618e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8995722cd261e2f98ef42d2615ec6abcc0037393f5e971113ec3c38d1836618e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jef".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8995722cd261e2f98ef42d2615ec6abcc0037393f5e971113ec3c38d1836618e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/39c8f34d-3de8-42e5-9f2c-4eb7a75cb68a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/39c8f34d-3de8-42e5-9f2c-4eb7a75cb68a> a person:Person.
           <http://data.lblod.info/id/personen/39c8f34d-3de8-42e5-9f2c-4eb7a75cb68a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/39c8f34d-3de8-42e5-9f2c-4eb7a75cb68a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Koen".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/39c8f34d-3de8-42e5-9f2c-4eb7a75cb68a> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/fa1e680ebb3787b67b318b2913e937e3ad9e1ee660f904aa28278ea2acd4b9a9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/fa1e680ebb3787b67b318b2913e937e3ad9e1ee660f904aa28278ea2acd4b9a9> a person:Person.
           <http://data.lblod.info/id/personen/fa1e680ebb3787b67b318b2913e937e3ad9e1ee660f904aa28278ea2acd4b9a9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/fa1e680ebb3787b67b318b2913e937e3ad9e1ee660f904aa28278ea2acd4b9a9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ward".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/fa1e680ebb3787b67b318b2913e937e3ad9e1ee660f904aa28278ea2acd4b9a9> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/1a6058f5-f533-4e24-84c8-47bf0c14fd6b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1a6058f5-f533-4e24-84c8-47bf0c14fd6b> a person:Person.
           <http://data.lblod.info/id/personen/1a6058f5-f533-4e24-84c8-47bf0c14fd6b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1a6058f5-f533-4e24-84c8-47bf0c14fd6b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Hilde".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1a6058f5-f533-4e24-84c8-47bf0c14fd6b> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/af6d79d1-dd4a-4a50-9e79-a03b57d84013> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/af6d79d1-dd4a-4a50-9e79-a03b57d84013> a person:Person.
           <http://data.lblod.info/id/personen/af6d79d1-dd4a-4a50-9e79-a03b57d84013> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/af6d79d1-dd4a-4a50-9e79-a03b57d84013> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Nele".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/af6d79d1-dd4a-4a50-9e79-a03b57d84013> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/b39359206d141d89ec76118326b42d6ca63f879da9d0b32c8de0ef68aea1d5c6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b39359206d141d89ec76118326b42d6ca63f879da9d0b32c8de0ef68aea1d5c6> a person:Person.
           <http://data.lblod.info/id/personen/b39359206d141d89ec76118326b42d6ca63f879da9d0b32c8de0ef68aea1d5c6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b39359206d141d89ec76118326b42d6ca63f879da9d0b32c8de0ef68aea1d5c6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jan".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b39359206d141d89ec76118326b42d6ca63f879da9d0b32c8de0ef68aea1d5c6> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2e595a43-62b5-443f-9e75-d56477a52be0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2e595a43-62b5-443f-9e75-d56477a52be0> a person:Person.
           <http://data.lblod.info/id/personen/2e595a43-62b5-443f-9e75-d56477a52be0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2e595a43-62b5-443f-9e75-d56477a52be0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Chris".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2e595a43-62b5-443f-9e75-d56477a52be0> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ae6948fd-e055-4420-96c4-34173f5d901c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ae6948fd-e055-4420-96c4-34173f5d901c> a person:Person.
           <http://data.lblod.info/id/personen/ae6948fd-e055-4420-96c4-34173f5d901c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ae6948fd-e055-4420-96c4-34173f5d901c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Laura".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ae6948fd-e055-4420-96c4-34173f5d901c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/3537fa05-4925-4148-b657-a927a6e5976e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3537fa05-4925-4148-b657-a927a6e5976e> a person:Person.
           <http://data.lblod.info/id/personen/3537fa05-4925-4148-b657-a927a6e5976e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3537fa05-4925-4148-b657-a927a6e5976e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Gilbert".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3537fa05-4925-4148-b657-a927a6e5976e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/441bf57d-73bd-4003-bb91-754f4f5136dd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/441bf57d-73bd-4003-bb91-754f4f5136dd> a person:Person.
           <http://data.lblod.info/id/personen/441bf57d-73bd-4003-bb91-754f4f5136dd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/441bf57d-73bd-4003-bb91-754f4f5136dd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Els".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/441bf57d-73bd-4003-bb91-754f4f5136dd> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/dceb41f3-8073-4073-b7a9-02610a0bfed7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/dceb41f3-8073-4073-b7a9-02610a0bfed7> a person:Person.
           <http://data.lblod.info/id/personen/dceb41f3-8073-4073-b7a9-02610a0bfed7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/dceb41f3-8073-4073-b7a9-02610a0bfed7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Luc".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/dceb41f3-8073-4073-b7a9-02610a0bfed7> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f5a42925-f5c1-4447-ab9e-93d5f118e43e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f5a42925-f5c1-4447-ab9e-93d5f118e43e> a person:Person.
           <http://data.lblod.info/id/personen/f5a42925-f5c1-4447-ab9e-93d5f118e43e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f5a42925-f5c1-4447-ab9e-93d5f118e43e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Nan".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f5a42925-f5c1-4447-ab9e-93d5f118e43e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/44cad4bbe96d15b22bdb6d1d65d39e56d3a68c6fbf58e7b1827b9b7b239ce9b4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/44cad4bbe96d15b22bdb6d1d65d39e56d3a68c6fbf58e7b1827b9b7b239ce9b4> a person:Person.
           <http://data.lblod.info/id/personen/44cad4bbe96d15b22bdb6d1d65d39e56d3a68c6fbf58e7b1827b9b7b239ce9b4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/44cad4bbe96d15b22bdb6d1d65d39e56d3a68c6fbf58e7b1827b9b7b239ce9b4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "René".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/44cad4bbe96d15b22bdb6d1d65d39e56d3a68c6fbf58e7b1827b9b7b239ce9b4> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/def88745-00d6-4a28-9c10-f05cbcbb39f8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/def88745-00d6-4a28-9c10-f05cbcbb39f8> a person:Person.
           <http://data.lblod.info/id/personen/def88745-00d6-4a28-9c10-f05cbcbb39f8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/def88745-00d6-4a28-9c10-f05cbcbb39f8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Annick".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/def88745-00d6-4a28-9c10-f05cbcbb39f8> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ef86883e-8760-4085-808b-2a18768fe4ca> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ef86883e-8760-4085-808b-2a18768fe4ca> a person:Person.
           <http://data.lblod.info/id/personen/ef86883e-8760-4085-808b-2a18768fe4ca> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ef86883e-8760-4085-808b-2a18768fe4ca> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Paul".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ef86883e-8760-4085-808b-2a18768fe4ca> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e20480b7-bfbb-4fc3-980a-76453ff63865> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e20480b7-bfbb-4fc3-980a-76453ff63865> a person:Person.
           <http://data.lblod.info/id/personen/e20480b7-bfbb-4fc3-980a-76453ff63865> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e20480b7-bfbb-4fc3-980a-76453ff63865> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Kim".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e20480b7-bfbb-4fc3-980a-76453ff63865> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/84c2aefd2664bf86a45ac375cc5993be315f3a5bef0be716504784ca31a419cc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/84c2aefd2664bf86a45ac375cc5993be315f3a5bef0be716504784ca31a419cc> a person:Person.
           <http://data.lblod.info/id/personen/84c2aefd2664bf86a45ac375cc5993be315f3a5bef0be716504784ca31a419cc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/84c2aefd2664bf86a45ac375cc5993be315f3a5bef0be716504784ca31a419cc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Lu".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/84c2aefd2664bf86a45ac375cc5993be315f3a5bef0be716504784ca31a419cc> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/3aeb4baf-7951-4ed8-9cce-588dc6e4fd58> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3aeb4baf-7951-4ed8-9cce-588dc6e4fd58> a person:Person.
           <http://data.lblod.info/id/personen/3aeb4baf-7951-4ed8-9cce-588dc6e4fd58> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3aeb4baf-7951-4ed8-9cce-588dc6e4fd58> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Paul".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3aeb4baf-7951-4ed8-9cce-588dc6e4fd58> [] [].
          }
        }
     # finished voornamen-update-8515-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:05:56+00:00