# started voornamen-update-33387-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:59+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/a481ec0e-9b28-463c-8f24-61e4f690cf8c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a481ec0e-9b28-463c-8f24-61e4f690cf8c> a person:Person.
           <http://data.lblod.info/id/personen/a481ec0e-9b28-463c-8f24-61e4f690cf8c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a481ec0e-9b28-463c-8f24-61e4f690cf8c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Zinio".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a481ec0e-9b28-463c-8f24-61e4f690cf8c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/b88e2e7c33bbeb2f0ca0b1621c6cc1230f339b22fa40bbb2a4b4abdc8a82effc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b88e2e7c33bbeb2f0ca0b1621c6cc1230f339b22fa40bbb2a4b4abdc8a82effc> a person:Person.
           <http://data.lblod.info/id/personen/b88e2e7c33bbeb2f0ca0b1621c6cc1230f339b22fa40bbb2a4b4abdc8a82effc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b88e2e7c33bbeb2f0ca0b1621c6cc1230f339b22fa40bbb2a4b4abdc8a82effc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Conny".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b88e2e7c33bbeb2f0ca0b1621c6cc1230f339b22fa40bbb2a4b4abdc8a82effc> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/6b098534-ebf0-413f-8d88-eb1b10b76dd1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6b098534-ebf0-413f-8d88-eb1b10b76dd1> a person:Person.
           <http://data.lblod.info/id/personen/6b098534-ebf0-413f-8d88-eb1b10b76dd1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6b098534-ebf0-413f-8d88-eb1b10b76dd1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Renny".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6b098534-ebf0-413f-8d88-eb1b10b76dd1> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e484211ac65e4e485c426f1061fc0951a6a7b8a6f7f004dc643da10646f1792b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e484211ac65e4e485c426f1061fc0951a6a7b8a6f7f004dc643da10646f1792b> a person:Person.
           <http://data.lblod.info/id/personen/e484211ac65e4e485c426f1061fc0951a6a7b8a6f7f004dc643da10646f1792b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e484211ac65e4e485c426f1061fc0951a6a7b8a6f7f004dc643da10646f1792b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marleen".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e484211ac65e4e485c426f1061fc0951a6a7b8a6f7f004dc643da10646f1792b> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/826f0291-19fc-4214-b035-a0e8fddd8ba6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/826f0291-19fc-4214-b035-a0e8fddd8ba6> a person:Person.
           <http://data.lblod.info/id/personen/826f0291-19fc-4214-b035-a0e8fddd8ba6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/826f0291-19fc-4214-b035-a0e8fddd8ba6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Peter".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/826f0291-19fc-4214-b035-a0e8fddd8ba6> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/0015b5783624117747db9635848f24bfa11c75fdf8f0a33906309f5c1471e56a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0015b5783624117747db9635848f24bfa11c75fdf8f0a33906309f5c1471e56a> a person:Person.
           <http://data.lblod.info/id/personen/0015b5783624117747db9635848f24bfa11c75fdf8f0a33906309f5c1471e56a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0015b5783624117747db9635848f24bfa11c75fdf8f0a33906309f5c1471e56a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Serge".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0015b5783624117747db9635848f24bfa11c75fdf8f0a33906309f5c1471e56a> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/02e5d2e6-c93e-4f99-8cd2-e17c08ad028d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/02e5d2e6-c93e-4f99-8cd2-e17c08ad028d> a person:Person.
           <http://data.lblod.info/id/personen/02e5d2e6-c93e-4f99-8cd2-e17c08ad028d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/02e5d2e6-c93e-4f99-8cd2-e17c08ad028d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Cis".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/02e5d2e6-c93e-4f99-8cd2-e17c08ad028d> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/d302c1d1-2003-400c-8219-d78739ad0de8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d302c1d1-2003-400c-8219-d78739ad0de8> a person:Person.
           <http://data.lblod.info/id/personen/d302c1d1-2003-400c-8219-d78739ad0de8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d302c1d1-2003-400c-8219-d78739ad0de8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Dirk".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d302c1d1-2003-400c-8219-d78739ad0de8> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/55b2d874-7729-42f8-b39b-61fcc336e800> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/55b2d874-7729-42f8-b39b-61fcc336e800> a person:Person.
           <http://data.lblod.info/id/personen/55b2d874-7729-42f8-b39b-61fcc336e800> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/55b2d874-7729-42f8-b39b-61fcc336e800> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Peter".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/55b2d874-7729-42f8-b39b-61fcc336e800> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/88fd5f63-b236-44d6-a974-e2709d20b4bc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/88fd5f63-b236-44d6-a974-e2709d20b4bc> a person:Person.
           <http://data.lblod.info/id/personen/88fd5f63-b236-44d6-a974-e2709d20b4bc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/88fd5f63-b236-44d6-a974-e2709d20b4bc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Sonja".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/88fd5f63-b236-44d6-a974-e2709d20b4bc> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/85cb3c045c161d007446d2305703a0c02071a798d3a7f1a23e84786d8eab8d36> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/85cb3c045c161d007446d2305703a0c02071a798d3a7f1a23e84786d8eab8d36> a person:Person.
           <http://data.lblod.info/id/personen/85cb3c045c161d007446d2305703a0c02071a798d3a7f1a23e84786d8eab8d36> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/85cb3c045c161d007446d2305703a0c02071a798d3a7f1a23e84786d8eab8d36> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Serge".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/85cb3c045c161d007446d2305703a0c02071a798d3a7f1a23e84786d8eab8d36> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/9c314013e1fac589eed490e8f4b45811b9a8ab19009668d8e1b48fac9b69e390> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9c314013e1fac589eed490e8f4b45811b9a8ab19009668d8e1b48fac9b69e390> a person:Person.
           <http://data.lblod.info/id/personen/9c314013e1fac589eed490e8f4b45811b9a8ab19009668d8e1b48fac9b69e390> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9c314013e1fac589eed490e8f4b45811b9a8ab19009668d8e1b48fac9b69e390> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Martine".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9c314013e1fac589eed490e8f4b45811b9a8ab19009668d8e1b48fac9b69e390> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/b410c213-b5bc-466c-aa1a-8be9f247a4d3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b410c213-b5bc-466c-aa1a-8be9f247a4d3> a person:Person.
           <http://data.lblod.info/id/personen/b410c213-b5bc-466c-aa1a-8be9f247a4d3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b410c213-b5bc-466c-aa1a-8be9f247a4d3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Kelly".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b410c213-b5bc-466c-aa1a-8be9f247a4d3> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/04ee2d75-65f4-4bcd-b0dd-75635bcc8496> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/04ee2d75-65f4-4bcd-b0dd-75635bcc8496> a person:Person.
           <http://data.lblod.info/id/personen/04ee2d75-65f4-4bcd-b0dd-75635bcc8496> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/04ee2d75-65f4-4bcd-b0dd-75635bcc8496> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jef".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/04ee2d75-65f4-4bcd-b0dd-75635bcc8496> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/a156ca60-dfe7-49a4-bd7a-babd30476ee1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a156ca60-dfe7-49a4-bd7a-babd30476ee1> a person:Person.
           <http://data.lblod.info/id/personen/a156ca60-dfe7-49a4-bd7a-babd30476ee1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a156ca60-dfe7-49a4-bd7a-babd30476ee1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Josette".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a156ca60-dfe7-49a4-bd7a-babd30476ee1> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/efe02410-d226-44da-83c8-c4113e5b02aa> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/efe02410-d226-44da-83c8-c4113e5b02aa> a person:Person.
           <http://data.lblod.info/id/personen/efe02410-d226-44da-83c8-c4113e5b02aa> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/efe02410-d226-44da-83c8-c4113e5b02aa> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Theo".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/efe02410-d226-44da-83c8-c4113e5b02aa> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/cda0b3c6-4870-4214-b75a-5be58fe747f3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cda0b3c6-4870-4214-b75a-5be58fe747f3> a person:Person.
           <http://data.lblod.info/id/personen/cda0b3c6-4870-4214-b75a-5be58fe747f3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cda0b3c6-4870-4214-b75a-5be58fe747f3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Xenia".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cda0b3c6-4870-4214-b75a-5be58fe747f3> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/d843d7c069abf9dc576dcb8f0cef5ab8c119a09cac931de1d8e22ad6e46b34c7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d843d7c069abf9dc576dcb8f0cef5ab8c119a09cac931de1d8e22ad6e46b34c7> a person:Person.
           <http://data.lblod.info/id/personen/d843d7c069abf9dc576dcb8f0cef5ab8c119a09cac931de1d8e22ad6e46b34c7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d843d7c069abf9dc576dcb8f0cef5ab8c119a09cac931de1d8e22ad6e46b34c7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Pol".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d843d7c069abf9dc576dcb8f0cef5ab8c119a09cac931de1d8e22ad6e46b34c7> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/50807df2-aa00-47fa-9bb7-6f0da1183113> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/50807df2-aa00-47fa-9bb7-6f0da1183113> a person:Person.
           <http://data.lblod.info/id/personen/50807df2-aa00-47fa-9bb7-6f0da1183113> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/50807df2-aa00-47fa-9bb7-6f0da1183113> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Yannick".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/50807df2-aa00-47fa-9bb7-6f0da1183113> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/588b60be-956d-4a87-a844-4c465bf47d0b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/588b60be-956d-4a87-a844-4c465bf47d0b> a person:Person.
           <http://data.lblod.info/id/personen/588b60be-956d-4a87-a844-4c465bf47d0b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/588b60be-956d-4a87-a844-4c465bf47d0b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jeremy".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/588b60be-956d-4a87-a844-4c465bf47d0b> [] [].
          }
        }
     # finished voornamen-update-33387-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:59+00:00