# started voornamen-update-19133-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:23+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/8de77fe9-6411-4875-ad82-f33258aa0228> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8de77fe9-6411-4875-ad82-f33258aa0228> a person:Person.
           <http://data.lblod.info/id/personen/8de77fe9-6411-4875-ad82-f33258aa0228> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8de77fe9-6411-4875-ad82-f33258aa0228> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Claudine".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8de77fe9-6411-4875-ad82-f33258aa0228> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/526c3588-c358-4421-ac78-ef327ea86a28> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/526c3588-c358-4421-ac78-ef327ea86a28> a person:Person.
           <http://data.lblod.info/id/personen/526c3588-c358-4421-ac78-ef327ea86a28> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/526c3588-c358-4421-ac78-ef327ea86a28> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Evelyne".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/526c3588-c358-4421-ac78-ef327ea86a28> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/87d68880-3a20-42db-ac39-bafc01db6e28> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/87d68880-3a20-42db-ac39-bafc01db6e28> a person:Person.
           <http://data.lblod.info/id/personen/87d68880-3a20-42db-ac39-bafc01db6e28> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/87d68880-3a20-42db-ac39-bafc01db6e28> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Françoise".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/87d68880-3a20-42db-ac39-bafc01db6e28> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/03d40039-f698-4e97-a671-4974ff791181> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/03d40039-f698-4e97-a671-4974ff791181> a person:Person.
           <http://data.lblod.info/id/personen/03d40039-f698-4e97-a671-4974ff791181> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/03d40039-f698-4e97-a671-4974ff791181> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Nathan".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/03d40039-f698-4e97-a671-4974ff791181> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/3053e85e-ee0f-4978-9a29-daae07030b88> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3053e85e-ee0f-4978-9a29-daae07030b88> a person:Person.
           <http://data.lblod.info/id/personen/3053e85e-ee0f-4978-9a29-daae07030b88> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3053e85e-ee0f-4978-9a29-daae07030b88> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marianne".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3053e85e-ee0f-4978-9a29-daae07030b88> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/7f4b9144-83ba-45d8-b4d9-8778dce2a348> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7f4b9144-83ba-45d8-b4d9-8778dce2a348> a person:Person.
           <http://data.lblod.info/id/personen/7f4b9144-83ba-45d8-b4d9-8778dce2a348> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7f4b9144-83ba-45d8-b4d9-8778dce2a348> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Johan".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7f4b9144-83ba-45d8-b4d9-8778dce2a348> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/d6f9f350-0a87-4562-b8a9-083124df4e1c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d6f9f350-0a87-4562-b8a9-083124df4e1c> a person:Person.
           <http://data.lblod.info/id/personen/d6f9f350-0a87-4562-b8a9-083124df4e1c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d6f9f350-0a87-4562-b8a9-083124df4e1c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Erwin".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d6f9f350-0a87-4562-b8a9-083124df4e1c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/4f3b7490-8a5d-4988-abeb-ca42dec0377d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4f3b7490-8a5d-4988-abeb-ca42dec0377d> a person:Person.
           <http://data.lblod.info/id/personen/4f3b7490-8a5d-4988-abeb-ca42dec0377d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4f3b7490-8a5d-4988-abeb-ca42dec0377d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Raymond".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4f3b7490-8a5d-4988-abeb-ca42dec0377d> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/d5cea7f5-eb73-4357-bec6-e90f58792929> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d5cea7f5-eb73-4357-bec6-e90f58792929> a person:Person.
           <http://data.lblod.info/id/personen/d5cea7f5-eb73-4357-bec6-e90f58792929> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d5cea7f5-eb73-4357-bec6-e90f58792929> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Sylvie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d5cea7f5-eb73-4357-bec6-e90f58792929> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e6042c3c-7deb-41d4-836e-65b59e2ba3a5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e6042c3c-7deb-41d4-836e-65b59e2ba3a5> a person:Person.
           <http://data.lblod.info/id/personen/e6042c3c-7deb-41d4-836e-65b59e2ba3a5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e6042c3c-7deb-41d4-836e-65b59e2ba3a5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Anitza".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e6042c3c-7deb-41d4-836e-65b59e2ba3a5> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/5e597660-43e8-49b4-b572-f85c1330836c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5e597660-43e8-49b4-b572-f85c1330836c> a person:Person.
           <http://data.lblod.info/id/personen/5e597660-43e8-49b4-b572-f85c1330836c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5e597660-43e8-49b4-b572-f85c1330836c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Lieve".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5e597660-43e8-49b4-b572-f85c1330836c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/bccc6fbeeefe3b182d4dac2311f78518a59d1b13a526776571e80ed3b6650d56> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bccc6fbeeefe3b182d4dac2311f78518a59d1b13a526776571e80ed3b6650d56> a person:Person.
           <http://data.lblod.info/id/personen/bccc6fbeeefe3b182d4dac2311f78518a59d1b13a526776571e80ed3b6650d56> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bccc6fbeeefe3b182d4dac2311f78518a59d1b13a526776571e80ed3b6650d56> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Chris".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bccc6fbeeefe3b182d4dac2311f78518a59d1b13a526776571e80ed3b6650d56> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/40df587a7e34ea0faa953c538b8b52fde9f07ebc41071aada263cae169c2b6c5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/40df587a7e34ea0faa953c538b8b52fde9f07ebc41071aada263cae169c2b6c5> a person:Person.
           <http://data.lblod.info/id/personen/40df587a7e34ea0faa953c538b8b52fde9f07ebc41071aada263cae169c2b6c5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/40df587a7e34ea0faa953c538b8b52fde9f07ebc41071aada263cae169c2b6c5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Bieke".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/40df587a7e34ea0faa953c538b8b52fde9f07ebc41071aada263cae169c2b6c5> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/9fd8684d-0449-418e-ac20-4c4d98c94866> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9fd8684d-0449-418e-ac20-4c4d98c94866> a person:Person.
           <http://data.lblod.info/id/personen/9fd8684d-0449-418e-ac20-4c4d98c94866> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9fd8684d-0449-418e-ac20-4c4d98c94866> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marjan".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9fd8684d-0449-418e-ac20-4c4d98c94866> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/314f098f-f727-4023-b55e-a86fb6ed8066> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/314f098f-f727-4023-b55e-a86fb6ed8066> a person:Person.
           <http://data.lblod.info/id/personen/314f098f-f727-4023-b55e-a86fb6ed8066> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/314f098f-f727-4023-b55e-a86fb6ed8066> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Cindy".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/314f098f-f727-4023-b55e-a86fb6ed8066> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/7db9c7d8-cefc-4b37-ab95-0de5479f649a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7db9c7d8-cefc-4b37-ab95-0de5479f649a> a person:Person.
           <http://data.lblod.info/id/personen/7db9c7d8-cefc-4b37-ab95-0de5479f649a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7db9c7d8-cefc-4b37-ab95-0de5479f649a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Joachim".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7db9c7d8-cefc-4b37-ab95-0de5479f649a> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/4fbef865-c1fa-41d2-a79e-33ee3ef71334> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4fbef865-c1fa-41d2-a79e-33ee3ef71334> a person:Person.
           <http://data.lblod.info/id/personen/4fbef865-c1fa-41d2-a79e-33ee3ef71334> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4fbef865-c1fa-41d2-a79e-33ee3ef71334> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jolien".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4fbef865-c1fa-41d2-a79e-33ee3ef71334> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/548ebece-eff0-4c54-8716-74dcc5656a64> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/548ebece-eff0-4c54-8716-74dcc5656a64> a person:Person.
           <http://data.lblod.info/id/personen/548ebece-eff0-4c54-8716-74dcc5656a64> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/548ebece-eff0-4c54-8716-74dcc5656a64> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Caroline".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/548ebece-eff0-4c54-8716-74dcc5656a64> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/d9331325d8344bc7b4911f6d5f22967e2b82adbfcdbaf835cb48503b357b8476> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d9331325d8344bc7b4911f6d5f22967e2b82adbfcdbaf835cb48503b357b8476> a person:Person.
           <http://data.lblod.info/id/personen/d9331325d8344bc7b4911f6d5f22967e2b82adbfcdbaf835cb48503b357b8476> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d9331325d8344bc7b4911f6d5f22967e2b82adbfcdbaf835cb48503b357b8476> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Mireille".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d9331325d8344bc7b4911f6d5f22967e2b82adbfcdbaf835cb48503b357b8476> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/a53f9bd8-f2b0-4177-9ca7-5a1f6cd76764> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a53f9bd8-f2b0-4177-9ca7-5a1f6cd76764> a person:Person.
           <http://data.lblod.info/id/personen/a53f9bd8-f2b0-4177-9ca7-5a1f6cd76764> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a53f9bd8-f2b0-4177-9ca7-5a1f6cd76764> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Lisa".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a53f9bd8-f2b0-4177-9ca7-5a1f6cd76764> [] [].
          }
        }
     # finished voornamen-update-19133-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:23+00:00