# started voornamen-update-912-2490de85e718ffa3e23344f4cd674bd5d9f40252833c8af6fb7fa3b82f44b008 at 2018-12-27T15:07:10+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/0a52fc1b-b349-4612-86ac-5a51a2b73919> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0a52fc1b-b349-4612-86ac-5a51a2b73919> a person:Person.
           <http://data.lblod.info/id/personen/0a52fc1b-b349-4612-86ac-5a51a2b73919> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0a52fc1b-b349-4612-86ac-5a51a2b73919> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Myriam".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0a52fc1b-b349-4612-86ac-5a51a2b73919> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/751be8f2-dda8-4314-8e6c-87adbdffe7c0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/751be8f2-dda8-4314-8e6c-87adbdffe7c0> a person:Person.
           <http://data.lblod.info/id/personen/751be8f2-dda8-4314-8e6c-87adbdffe7c0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/751be8f2-dda8-4314-8e6c-87adbdffe7c0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Werner".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/751be8f2-dda8-4314-8e6c-87adbdffe7c0> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/81e25aed-9a5f-42f9-997f-f6f64cefbdcb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/81e25aed-9a5f-42f9-997f-f6f64cefbdcb> a person:Person.
           <http://data.lblod.info/id/personen/81e25aed-9a5f-42f9-997f-f6f64cefbdcb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/81e25aed-9a5f-42f9-997f-f6f64cefbdcb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Stephanie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/81e25aed-9a5f-42f9-997f-f6f64cefbdcb> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/bc4ccb48d27ec4be8112d344e2fcfdaa95a673cd8f0eaed8e72d2bd282bcad41> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bc4ccb48d27ec4be8112d344e2fcfdaa95a673cd8f0eaed8e72d2bd282bcad41> a person:Person.
           <http://data.lblod.info/id/personen/bc4ccb48d27ec4be8112d344e2fcfdaa95a673cd8f0eaed8e72d2bd282bcad41> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bc4ccb48d27ec4be8112d344e2fcfdaa95a673cd8f0eaed8e72d2bd282bcad41> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Freddy".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bc4ccb48d27ec4be8112d344e2fcfdaa95a673cd8f0eaed8e72d2bd282bcad41> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/aa3f9a28-8290-43af-9f67-429233365094> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/aa3f9a28-8290-43af-9f67-429233365094> a person:Person.
           <http://data.lblod.info/id/personen/aa3f9a28-8290-43af-9f67-429233365094> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/aa3f9a28-8290-43af-9f67-429233365094> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Sofie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/aa3f9a28-8290-43af-9f67-429233365094> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/39736307-017b-4d27-947b-14aa32de0a7e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/39736307-017b-4d27-947b-14aa32de0a7e> a person:Person.
           <http://data.lblod.info/id/personen/39736307-017b-4d27-947b-14aa32de0a7e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/39736307-017b-4d27-947b-14aa32de0a7e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ina".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/39736307-017b-4d27-947b-14aa32de0a7e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/a4038819-fcd1-4ac2-8b43-1deea50733d7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a4038819-fcd1-4ac2-8b43-1deea50733d7> a person:Person.
           <http://data.lblod.info/id/personen/a4038819-fcd1-4ac2-8b43-1deea50733d7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a4038819-fcd1-4ac2-8b43-1deea50733d7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Wiske".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a4038819-fcd1-4ac2-8b43-1deea50733d7> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/bfcddf8b9f40bc1bed4c27f3735f1c3f3490b5fd24cd6f2b29a4cad9a8d05061> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bfcddf8b9f40bc1bed4c27f3735f1c3f3490b5fd24cd6f2b29a4cad9a8d05061> a person:Person.
           <http://data.lblod.info/id/personen/bfcddf8b9f40bc1bed4c27f3735f1c3f3490b5fd24cd6f2b29a4cad9a8d05061> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bfcddf8b9f40bc1bed4c27f3735f1c3f3490b5fd24cd6f2b29a4cad9a8d05061> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ludo".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bfcddf8b9f40bc1bed4c27f3735f1c3f3490b5fd24cd6f2b29a4cad9a8d05061> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/c26c031b-cf96-4dce-8ec7-09c33cb4cf55> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c26c031b-cf96-4dce-8ec7-09c33cb4cf55> a person:Person.
           <http://data.lblod.info/id/personen/c26c031b-cf96-4dce-8ec7-09c33cb4cf55> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c26c031b-cf96-4dce-8ec7-09c33cb4cf55> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Agnes".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c26c031b-cf96-4dce-8ec7-09c33cb4cf55> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/215027d2-0b3a-4675-9bd8-2617196a0111> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/215027d2-0b3a-4675-9bd8-2617196a0111> a person:Person.
           <http://data.lblod.info/id/personen/215027d2-0b3a-4675-9bd8-2617196a0111> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/215027d2-0b3a-4675-9bd8-2617196a0111> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Hugo".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/215027d2-0b3a-4675-9bd8-2617196a0111> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/08c7a0b9-cd76-4097-8ed3-37a35e6f25d5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/08c7a0b9-cd76-4097-8ed3-37a35e6f25d5> a person:Person.
           <http://data.lblod.info/id/personen/08c7a0b9-cd76-4097-8ed3-37a35e6f25d5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/08c7a0b9-cd76-4097-8ed3-37a35e6f25d5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jarkko".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/08c7a0b9-cd76-4097-8ed3-37a35e6f25d5> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/39e72f5c-587e-45af-8de3-b149aee65df1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/39e72f5c-587e-45af-8de3-b149aee65df1> a person:Person.
           <http://data.lblod.info/id/personen/39e72f5c-587e-45af-8de3-b149aee65df1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/39e72f5c-587e-45af-8de3-b149aee65df1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Raymond".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/39e72f5c-587e-45af-8de3-b149aee65df1> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/64c41478-b692-484b-adb6-a2f9d2f34124> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/64c41478-b692-484b-adb6-a2f9d2f34124> a person:Person.
           <http://data.lblod.info/id/personen/64c41478-b692-484b-adb6-a2f9d2f34124> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/64c41478-b692-484b-adb6-a2f9d2f34124> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Liliana".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/64c41478-b692-484b-adb6-a2f9d2f34124> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/463196ad-63af-46e8-9621-a6b37d56e98b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/463196ad-63af-46e8-9621-a6b37d56e98b> a person:Person.
           <http://data.lblod.info/id/personen/463196ad-63af-46e8-9621-a6b37d56e98b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/463196ad-63af-46e8-9621-a6b37d56e98b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "René".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/463196ad-63af-46e8-9621-a6b37d56e98b> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/3574233f-71e1-4673-9552-8b64b101b680> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3574233f-71e1-4673-9552-8b64b101b680> a person:Person.
           <http://data.lblod.info/id/personen/3574233f-71e1-4673-9552-8b64b101b680> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3574233f-71e1-4673-9552-8b64b101b680> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Raf".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3574233f-71e1-4673-9552-8b64b101b680> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/996b4bc9-1026-4f63-9470-afc359108f8c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/996b4bc9-1026-4f63-9470-afc359108f8c> a person:Person.
           <http://data.lblod.info/id/personen/996b4bc9-1026-4f63-9470-afc359108f8c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/996b4bc9-1026-4f63-9470-afc359108f8c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Erwin".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/996b4bc9-1026-4f63-9470-afc359108f8c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/8034092d-567e-4ea3-b8b9-8e9417e9932b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8034092d-567e-4ea3-b8b9-8e9417e9932b> a person:Person.
           <http://data.lblod.info/id/personen/8034092d-567e-4ea3-b8b9-8e9417e9932b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8034092d-567e-4ea3-b8b9-8e9417e9932b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Bernard".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8034092d-567e-4ea3-b8b9-8e9417e9932b> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e82f5f17cfbebc9cc77b832c9b81e1bd9a0be24ce56c639cb9c5ce12325f4c18> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e82f5f17cfbebc9cc77b832c9b81e1bd9a0be24ce56c639cb9c5ce12325f4c18> a person:Person.
           <http://data.lblod.info/id/personen/e82f5f17cfbebc9cc77b832c9b81e1bd9a0be24ce56c639cb9c5ce12325f4c18> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e82f5f17cfbebc9cc77b832c9b81e1bd9a0be24ce56c639cb9c5ce12325f4c18> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Bert".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e82f5f17cfbebc9cc77b832c9b81e1bd9a0be24ce56c639cb9c5ce12325f4c18> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/805b7c79da0ba9eca029821c638d45560053c1a32edd2d758b58febfe277eacb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/805b7c79da0ba9eca029821c638d45560053c1a32edd2d758b58febfe277eacb> a person:Person.
           <http://data.lblod.info/id/personen/805b7c79da0ba9eca029821c638d45560053c1a32edd2d758b58febfe277eacb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/805b7c79da0ba9eca029821c638d45560053c1a32edd2d758b58febfe277eacb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Guido".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/805b7c79da0ba9eca029821c638d45560053c1a32edd2d758b58febfe277eacb> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/b341dcb3-f783-4a7a-b8aa-f16ab2794537> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b341dcb3-f783-4a7a-b8aa-f16ab2794537> a person:Person.
           <http://data.lblod.info/id/personen/b341dcb3-f783-4a7a-b8aa-f16ab2794537> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b341dcb3-f783-4a7a-b8aa-f16ab2794537> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Lotte".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b341dcb3-f783-4a7a-b8aa-f16ab2794537> [] [].
          }
        }
     # finished voornamen-update-912-2490de85e718ffa3e23344f4cd674bd5d9f40252833c8af6fb7fa3b82f44b008 at 2018-12-27T15:07:10+00:00