# started voornamen-update-9187-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:05:58+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/77bddcfc-8ce8-46e9-9588-f145b62275c4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/77bddcfc-8ce8-46e9-9588-f145b62275c4> a person:Person.
           <http://data.lblod.info/id/personen/77bddcfc-8ce8-46e9-9588-f145b62275c4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/77bddcfc-8ce8-46e9-9588-f145b62275c4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Wouter".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/77bddcfc-8ce8-46e9-9588-f145b62275c4> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/c47eb611-f3e2-46eb-aac5-c291e669620f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c47eb611-f3e2-46eb-aac5-c291e669620f> a person:Person.
           <http://data.lblod.info/id/personen/c47eb611-f3e2-46eb-aac5-c291e669620f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c47eb611-f3e2-46eb-aac5-c291e669620f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Lieve".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c47eb611-f3e2-46eb-aac5-c291e669620f> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/a7ac931a195f0e9a789a5077f506d23915aaa80d870a1c30e24f2b0a9a2547c4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a7ac931a195f0e9a789a5077f506d23915aaa80d870a1c30e24f2b0a9a2547c4> a person:Person.
           <http://data.lblod.info/id/personen/a7ac931a195f0e9a789a5077f506d23915aaa80d870a1c30e24f2b0a9a2547c4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a7ac931a195f0e9a789a5077f506d23915aaa80d870a1c30e24f2b0a9a2547c4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Kris".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a7ac931a195f0e9a789a5077f506d23915aaa80d870a1c30e24f2b0a9a2547c4> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/aef9ec61-08ae-4b0c-9e22-71b0d4347c76> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/aef9ec61-08ae-4b0c-9e22-71b0d4347c76> a person:Person.
           <http://data.lblod.info/id/personen/aef9ec61-08ae-4b0c-9e22-71b0d4347c76> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/aef9ec61-08ae-4b0c-9e22-71b0d4347c76> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "An".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/aef9ec61-08ae-4b0c-9e22-71b0d4347c76> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/0976cbfc2899e5dfcf3c66d165e28c1dadc5f0882225cfbb4b2c0729d8c920a2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0976cbfc2899e5dfcf3c66d165e28c1dadc5f0882225cfbb4b2c0729d8c920a2> a person:Person.
           <http://data.lblod.info/id/personen/0976cbfc2899e5dfcf3c66d165e28c1dadc5f0882225cfbb4b2c0729d8c920a2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0976cbfc2899e5dfcf3c66d165e28c1dadc5f0882225cfbb4b2c0729d8c920a2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jos".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0976cbfc2899e5dfcf3c66d165e28c1dadc5f0882225cfbb4b2c0729d8c920a2> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/3fe26f671082492c5126df6e691f75b2426fad7079327631c04b882110369bc4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3fe26f671082492c5126df6e691f75b2426fad7079327631c04b882110369bc4> a person:Person.
           <http://data.lblod.info/id/personen/3fe26f671082492c5126df6e691f75b2426fad7079327631c04b882110369bc4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3fe26f671082492c5126df6e691f75b2426fad7079327631c04b882110369bc4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Rita".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3fe26f671082492c5126df6e691f75b2426fad7079327631c04b882110369bc4> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/77aa976837df1a07e570a92c1cdd7f5f6790b4b04014ed79c634f26745b8fb32> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/77aa976837df1a07e570a92c1cdd7f5f6790b4b04014ed79c634f26745b8fb32> a person:Person.
           <http://data.lblod.info/id/personen/77aa976837df1a07e570a92c1cdd7f5f6790b4b04014ed79c634f26745b8fb32> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/77aa976837df1a07e570a92c1cdd7f5f6790b4b04014ed79c634f26745b8fb32> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Inge".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/77aa976837df1a07e570a92c1cdd7f5f6790b4b04014ed79c634f26745b8fb32> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/8c7ee8bb516cd4790c4ca8f35e430c602a6f3b479c8abd2134261a2623d0ed20> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8c7ee8bb516cd4790c4ca8f35e430c602a6f3b479c8abd2134261a2623d0ed20> a person:Person.
           <http://data.lblod.info/id/personen/8c7ee8bb516cd4790c4ca8f35e430c602a6f3b479c8abd2134261a2623d0ed20> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8c7ee8bb516cd4790c4ca8f35e430c602a6f3b479c8abd2134261a2623d0ed20> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Peter".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8c7ee8bb516cd4790c4ca8f35e430c602a6f3b479c8abd2134261a2623d0ed20> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/a62211d3-e74c-4f28-99ec-7a7894a66cb0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a62211d3-e74c-4f28-99ec-7a7894a66cb0> a person:Person.
           <http://data.lblod.info/id/personen/a62211d3-e74c-4f28-99ec-7a7894a66cb0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a62211d3-e74c-4f28-99ec-7a7894a66cb0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Diane".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a62211d3-e74c-4f28-99ec-7a7894a66cb0> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2e3fe95fb0073a7a22fe5da7643ad61523e80e2af1e7d22ef71e24a5d5953ad6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2e3fe95fb0073a7a22fe5da7643ad61523e80e2af1e7d22ef71e24a5d5953ad6> a person:Person.
           <http://data.lblod.info/id/personen/2e3fe95fb0073a7a22fe5da7643ad61523e80e2af1e7d22ef71e24a5d5953ad6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2e3fe95fb0073a7a22fe5da7643ad61523e80e2af1e7d22ef71e24a5d5953ad6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Denis".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2e3fe95fb0073a7a22fe5da7643ad61523e80e2af1e7d22ef71e24a5d5953ad6> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/b581df207c3040eacf45b92b488b80a02bc69ec3ff3234bf2dfc180711971f15> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b581df207c3040eacf45b92b488b80a02bc69ec3ff3234bf2dfc180711971f15> a person:Person.
           <http://data.lblod.info/id/personen/b581df207c3040eacf45b92b488b80a02bc69ec3ff3234bf2dfc180711971f15> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b581df207c3040eacf45b92b488b80a02bc69ec3ff3234bf2dfc180711971f15> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Diane".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b581df207c3040eacf45b92b488b80a02bc69ec3ff3234bf2dfc180711971f15> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/a4bd120201104d6b0e0886121ab4133ba11e9cea8b848b3e25864def0e71b0c2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a4bd120201104d6b0e0886121ab4133ba11e9cea8b848b3e25864def0e71b0c2> a person:Person.
           <http://data.lblod.info/id/personen/a4bd120201104d6b0e0886121ab4133ba11e9cea8b848b3e25864def0e71b0c2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a4bd120201104d6b0e0886121ab4133ba11e9cea8b848b3e25864def0e71b0c2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Denis".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a4bd120201104d6b0e0886121ab4133ba11e9cea8b848b3e25864def0e71b0c2> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/4f8f3065a5320568f769dc820b111468bf0324c0e03e7fb323eb9abe10a1a4f6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4f8f3065a5320568f769dc820b111468bf0324c0e03e7fb323eb9abe10a1a4f6> a person:Person.
           <http://data.lblod.info/id/personen/4f8f3065a5320568f769dc820b111468bf0324c0e03e7fb323eb9abe10a1a4f6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4f8f3065a5320568f769dc820b111468bf0324c0e03e7fb323eb9abe10a1a4f6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Chris".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4f8f3065a5320568f769dc820b111468bf0324c0e03e7fb323eb9abe10a1a4f6> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/7a5de06e93ccb9d439f48f25196848a6aabca2bc04a4d1cbe06e86134fd7d3e8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7a5de06e93ccb9d439f48f25196848a6aabca2bc04a4d1cbe06e86134fd7d3e8> a person:Person.
           <http://data.lblod.info/id/personen/7a5de06e93ccb9d439f48f25196848a6aabca2bc04a4d1cbe06e86134fd7d3e8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7a5de06e93ccb9d439f48f25196848a6aabca2bc04a4d1cbe06e86134fd7d3e8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Fons".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7a5de06e93ccb9d439f48f25196848a6aabca2bc04a4d1cbe06e86134fd7d3e8> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f72b01c599a908a8ac1b765aeab93d9859f5d790b1148128aea9da99dec5c085> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f72b01c599a908a8ac1b765aeab93d9859f5d790b1148128aea9da99dec5c085> a person:Person.
           <http://data.lblod.info/id/personen/f72b01c599a908a8ac1b765aeab93d9859f5d790b1148128aea9da99dec5c085> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f72b01c599a908a8ac1b765aeab93d9859f5d790b1148128aea9da99dec5c085> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Rita".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f72b01c599a908a8ac1b765aeab93d9859f5d790b1148128aea9da99dec5c085> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/41510d4662d158062ae1f8ac7236d4417bac57f332e70182aaa840ea2ae46a29> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/41510d4662d158062ae1f8ac7236d4417bac57f332e70182aaa840ea2ae46a29> a person:Person.
           <http://data.lblod.info/id/personen/41510d4662d158062ae1f8ac7236d4417bac57f332e70182aaa840ea2ae46a29> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/41510d4662d158062ae1f8ac7236d4417bac57f332e70182aaa840ea2ae46a29> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Flor".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/41510d4662d158062ae1f8ac7236d4417bac57f332e70182aaa840ea2ae46a29> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/9945da07f778c2a6520b9159c0ca595794a895f599e04424461afcee1fbe4337> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9945da07f778c2a6520b9159c0ca595794a895f599e04424461afcee1fbe4337> a person:Person.
           <http://data.lblod.info/id/personen/9945da07f778c2a6520b9159c0ca595794a895f599e04424461afcee1fbe4337> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9945da07f778c2a6520b9159c0ca595794a895f599e04424461afcee1fbe4337> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Nancy".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9945da07f778c2a6520b9159c0ca595794a895f599e04424461afcee1fbe4337> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/b447b39622788ca988b7c5888e8802d38d83adba1ef207ce2a5e89763c1e83e8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b447b39622788ca988b7c5888e8802d38d83adba1ef207ce2a5e89763c1e83e8> a person:Person.
           <http://data.lblod.info/id/personen/b447b39622788ca988b7c5888e8802d38d83adba1ef207ce2a5e89763c1e83e8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b447b39622788ca988b7c5888e8802d38d83adba1ef207ce2a5e89763c1e83e8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Fik".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b447b39622788ca988b7c5888e8802d38d83adba1ef207ce2a5e89763c1e83e8> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/8620c08208be916359040efe9decbe52e17fde62278dd542f0b891693bec8143> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8620c08208be916359040efe9decbe52e17fde62278dd542f0b891693bec8143> a person:Person.
           <http://data.lblod.info/id/personen/8620c08208be916359040efe9decbe52e17fde62278dd542f0b891693bec8143> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8620c08208be916359040efe9decbe52e17fde62278dd542f0b891693bec8143> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Emma".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8620c08208be916359040efe9decbe52e17fde62278dd542f0b891693bec8143> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/09f122ec-f7fd-4c8b-a148-4b2fafab041f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/09f122ec-f7fd-4c8b-a148-4b2fafab041f> a person:Person.
           <http://data.lblod.info/id/personen/09f122ec-f7fd-4c8b-a148-4b2fafab041f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/09f122ec-f7fd-4c8b-a148-4b2fafab041f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marc".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/09f122ec-f7fd-4c8b-a148-4b2fafab041f> [] [].
          }
        }
     # finished voornamen-update-9187-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:05:58+00:00