# started voornamen-update-22243-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:30+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/9758a486765aebb00c3f48a5c7e14a443968ca598022bb58ed1de86ac225379c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9758a486765aebb00c3f48a5c7e14a443968ca598022bb58ed1de86ac225379c> a person:Person.
           <http://data.lblod.info/id/personen/9758a486765aebb00c3f48a5c7e14a443968ca598022bb58ed1de86ac225379c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9758a486765aebb00c3f48a5c7e14a443968ca598022bb58ed1de86ac225379c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Henk".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9758a486765aebb00c3f48a5c7e14a443968ca598022bb58ed1de86ac225379c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ffb892bc3dfb9ba8895902afac51e4a8dd1d2935c0711d2784a913938e2970f0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ffb892bc3dfb9ba8895902afac51e4a8dd1d2935c0711d2784a913938e2970f0> a person:Person.
           <http://data.lblod.info/id/personen/ffb892bc3dfb9ba8895902afac51e4a8dd1d2935c0711d2784a913938e2970f0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ffb892bc3dfb9ba8895902afac51e4a8dd1d2935c0711d2784a913938e2970f0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Hilde".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ffb892bc3dfb9ba8895902afac51e4a8dd1d2935c0711d2784a913938e2970f0> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/99ee3a78-09a2-4083-a4be-741408526d95> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/99ee3a78-09a2-4083-a4be-741408526d95> a person:Person.
           <http://data.lblod.info/id/personen/99ee3a78-09a2-4083-a4be-741408526d95> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/99ee3a78-09a2-4083-a4be-741408526d95> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Filiep".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/99ee3a78-09a2-4083-a4be-741408526d95> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/d08442be-537a-475e-b269-a2828320b51e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d08442be-537a-475e-b269-a2828320b51e> a person:Person.
           <http://data.lblod.info/id/personen/d08442be-537a-475e-b269-a2828320b51e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d08442be-537a-475e-b269-a2828320b51e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "David".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d08442be-537a-475e-b269-a2828320b51e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/5947685c-6136-45c3-a98d-a1fbe74177a5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5947685c-6136-45c3-a98d-a1fbe74177a5> a person:Person.
           <http://data.lblod.info/id/personen/5947685c-6136-45c3-a98d-a1fbe74177a5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5947685c-6136-45c3-a98d-a1fbe74177a5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Aäron".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5947685c-6136-45c3-a98d-a1fbe74177a5> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/5beac9c4-e957-4c68-bd1a-16c9891ab775> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5beac9c4-e957-4c68-bd1a-16c9891ab775> a person:Person.
           <http://data.lblod.info/id/personen/5beac9c4-e957-4c68-bd1a-16c9891ab775> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5beac9c4-e957-4c68-bd1a-16c9891ab775> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marc".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5beac9c4-e957-4c68-bd1a-16c9891ab775> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ca9ba189-c3c3-4abb-89ca-fce7ec407b91> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ca9ba189-c3c3-4abb-89ca-fce7ec407b91> a person:Person.
           <http://data.lblod.info/id/personen/ca9ba189-c3c3-4abb-89ca-fce7ec407b91> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ca9ba189-c3c3-4abb-89ca-fce7ec407b91> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Alexander".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ca9ba189-c3c3-4abb-89ca-fce7ec407b91> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/b51c8826-d8d1-434f-83fd-840b8d6e4ec2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b51c8826-d8d1-434f-83fd-840b8d6e4ec2> a person:Person.
           <http://data.lblod.info/id/personen/b51c8826-d8d1-434f-83fd-840b8d6e4ec2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b51c8826-d8d1-434f-83fd-840b8d6e4ec2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Kathy".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b51c8826-d8d1-434f-83fd-840b8d6e4ec2> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2513f226-777c-49eb-9f63-460b2047209a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2513f226-777c-49eb-9f63-460b2047209a> a person:Person.
           <http://data.lblod.info/id/personen/2513f226-777c-49eb-9f63-460b2047209a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2513f226-777c-49eb-9f63-460b2047209a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Peter".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2513f226-777c-49eb-9f63-460b2047209a> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/5ec5c048-7313-42a5-a663-ac491e08b69c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5ec5c048-7313-42a5-a663-ac491e08b69c> a person:Person.
           <http://data.lblod.info/id/personen/5ec5c048-7313-42a5-a663-ac491e08b69c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5ec5c048-7313-42a5-a663-ac491e08b69c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Reinhilde".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5ec5c048-7313-42a5-a663-ac491e08b69c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/5aeb0a5f-a0d4-43fb-864f-d08a4d09ca36> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5aeb0a5f-a0d4-43fb-864f-d08a4d09ca36> a person:Person.
           <http://data.lblod.info/id/personen/5aeb0a5f-a0d4-43fb-864f-d08a4d09ca36> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5aeb0a5f-a0d4-43fb-864f-d08a4d09ca36> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marie Claire".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5aeb0a5f-a0d4-43fb-864f-d08a4d09ca36> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ac1d5385-db6f-4c01-8fa2-4646c9a8e190> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ac1d5385-db6f-4c01-8fa2-4646c9a8e190> a person:Person.
           <http://data.lblod.info/id/personen/ac1d5385-db6f-4c01-8fa2-4646c9a8e190> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ac1d5385-db6f-4c01-8fa2-4646c9a8e190> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Kries".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ac1d5385-db6f-4c01-8fa2-4646c9a8e190> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/fe23da22-a315-4462-afd7-33c4491adcba> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/fe23da22-a315-4462-afd7-33c4491adcba> a person:Person.
           <http://data.lblod.info/id/personen/fe23da22-a315-4462-afd7-33c4491adcba> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/fe23da22-a315-4462-afd7-33c4491adcba> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jan".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/fe23da22-a315-4462-afd7-33c4491adcba> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/24288614199282906233e322cba2dcbbca38e4aee79015d47bf09a05cf9e6629> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/24288614199282906233e322cba2dcbbca38e4aee79015d47bf09a05cf9e6629> a person:Person.
           <http://data.lblod.info/id/personen/24288614199282906233e322cba2dcbbca38e4aee79015d47bf09a05cf9e6629> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/24288614199282906233e322cba2dcbbca38e4aee79015d47bf09a05cf9e6629> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Erika".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/24288614199282906233e322cba2dcbbca38e4aee79015d47bf09a05cf9e6629> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f7cea08979d4bce829de9daa68502d0662a8ac94b4dc7e64566400d5fd2d62dc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f7cea08979d4bce829de9daa68502d0662a8ac94b4dc7e64566400d5fd2d62dc> a person:Person.
           <http://data.lblod.info/id/personen/f7cea08979d4bce829de9daa68502d0662a8ac94b4dc7e64566400d5fd2d62dc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f7cea08979d4bce829de9daa68502d0662a8ac94b4dc7e64566400d5fd2d62dc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marie Louise".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f7cea08979d4bce829de9daa68502d0662a8ac94b4dc7e64566400d5fd2d62dc> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2ce650a4-dc1e-4c2d-b400-8d1e745ac4fa> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2ce650a4-dc1e-4c2d-b400-8d1e745ac4fa> a person:Person.
           <http://data.lblod.info/id/personen/2ce650a4-dc1e-4c2d-b400-8d1e745ac4fa> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2ce650a4-dc1e-4c2d-b400-8d1e745ac4fa> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Evelyne".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2ce650a4-dc1e-4c2d-b400-8d1e745ac4fa> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/9aed0f31-104b-4435-8d13-f46a5222b1a9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9aed0f31-104b-4435-8d13-f46a5222b1a9> a person:Person.
           <http://data.lblod.info/id/personen/9aed0f31-104b-4435-8d13-f46a5222b1a9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9aed0f31-104b-4435-8d13-f46a5222b1a9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Lisa".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9aed0f31-104b-4435-8d13-f46a5222b1a9> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/8a438482-aff8-4f1f-a737-0250da0c32cd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8a438482-aff8-4f1f-a737-0250da0c32cd> a person:Person.
           <http://data.lblod.info/id/personen/8a438482-aff8-4f1f-a737-0250da0c32cd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8a438482-aff8-4f1f-a737-0250da0c32cd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Virginie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8a438482-aff8-4f1f-a737-0250da0c32cd> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/eb479abe-da8d-4b19-a4a7-589fccdf11a3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/eb479abe-da8d-4b19-a4a7-589fccdf11a3> a person:Person.
           <http://data.lblod.info/id/personen/eb479abe-da8d-4b19-a4a7-589fccdf11a3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/eb479abe-da8d-4b19-a4a7-589fccdf11a3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ria".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/eb479abe-da8d-4b19-a4a7-589fccdf11a3> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/b8b72392-b5b4-4998-aa50-00627ec3b718> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b8b72392-b5b4-4998-aa50-00627ec3b718> a person:Person.
           <http://data.lblod.info/id/personen/b8b72392-b5b4-4998-aa50-00627ec3b718> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b8b72392-b5b4-4998-aa50-00627ec3b718> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Rebecca".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b8b72392-b5b4-4998-aa50-00627ec3b718> [] [].
          }
        }
     # finished voornamen-update-22243-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:30+00:00