# started voornamen-update-26144-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:40+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/62fb37ef497558785fa7af515c4b33f5cbfe7fd975b888213c1f96478f2f9282> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/62fb37ef497558785fa7af515c4b33f5cbfe7fd975b888213c1f96478f2f9282> a person:Person.
           <http://data.lblod.info/id/personen/62fb37ef497558785fa7af515c4b33f5cbfe7fd975b888213c1f96478f2f9282> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/62fb37ef497558785fa7af515c4b33f5cbfe7fd975b888213c1f96478f2f9282> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Raf".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/62fb37ef497558785fa7af515c4b33f5cbfe7fd975b888213c1f96478f2f9282> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/cf18063e0f477ea3f2fc54f52a0f3f27d1108903f3c4801ae5c98cb837fcf821> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cf18063e0f477ea3f2fc54f52a0f3f27d1108903f3c4801ae5c98cb837fcf821> a person:Person.
           <http://data.lblod.info/id/personen/cf18063e0f477ea3f2fc54f52a0f3f27d1108903f3c4801ae5c98cb837fcf821> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cf18063e0f477ea3f2fc54f52a0f3f27d1108903f3c4801ae5c98cb837fcf821> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "çoiken".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cf18063e0f477ea3f2fc54f52a0f3f27d1108903f3c4801ae5c98cb837fcf821> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/131d95a3-b215-46cf-b67a-5066e1f1f6fa> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/131d95a3-b215-46cf-b67a-5066e1f1f6fa> a person:Person.
           <http://data.lblod.info/id/personen/131d95a3-b215-46cf-b67a-5066e1f1f6fa> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/131d95a3-b215-46cf-b67a-5066e1f1f6fa> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "René".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/131d95a3-b215-46cf-b67a-5066e1f1f6fa> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/1b5c04e4-b51b-4d8d-aca6-de44d8e0911c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1b5c04e4-b51b-4d8d-aca6-de44d8e0911c> a person:Person.
           <http://data.lblod.info/id/personen/1b5c04e4-b51b-4d8d-aca6-de44d8e0911c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1b5c04e4-b51b-4d8d-aca6-de44d8e0911c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Alain".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1b5c04e4-b51b-4d8d-aca6-de44d8e0911c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/46b15b45-bd60-4eb0-a87c-8c9642db3515> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/46b15b45-bd60-4eb0-a87c-8c9642db3515> a person:Person.
           <http://data.lblod.info/id/personen/46b15b45-bd60-4eb0-a87c-8c9642db3515> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/46b15b45-bd60-4eb0-a87c-8c9642db3515> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jordi".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/46b15b45-bd60-4eb0-a87c-8c9642db3515> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/46976365d45a5d90a89aca99c347b8833ee8c0e807980e5a4caff60daa4e08f0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/46976365d45a5d90a89aca99c347b8833ee8c0e807980e5a4caff60daa4e08f0> a person:Person.
           <http://data.lblod.info/id/personen/46976365d45a5d90a89aca99c347b8833ee8c0e807980e5a4caff60daa4e08f0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/46976365d45a5d90a89aca99c347b8833ee8c0e807980e5a4caff60daa4e08f0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marianne".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/46976365d45a5d90a89aca99c347b8833ee8c0e807980e5a4caff60daa4e08f0> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/48916be1-f8e7-4c58-b760-3295805f5637> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/48916be1-f8e7-4c58-b760-3295805f5637> a person:Person.
           <http://data.lblod.info/id/personen/48916be1-f8e7-4c58-b760-3295805f5637> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/48916be1-f8e7-4c58-b760-3295805f5637> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Werner".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/48916be1-f8e7-4c58-b760-3295805f5637> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/6c515b00-1bc5-4479-9fd2-f2cece27e124> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6c515b00-1bc5-4479-9fd2-f2cece27e124> a person:Person.
           <http://data.lblod.info/id/personen/6c515b00-1bc5-4479-9fd2-f2cece27e124> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6c515b00-1bc5-4479-9fd2-f2cece27e124> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Paul".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6c515b00-1bc5-4479-9fd2-f2cece27e124> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/afe744ab-c142-4d24-ae4c-38be03500677> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/afe744ab-c142-4d24-ae4c-38be03500677> a person:Person.
           <http://data.lblod.info/id/personen/afe744ab-c142-4d24-ae4c-38be03500677> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/afe744ab-c142-4d24-ae4c-38be03500677> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Olivier".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/afe744ab-c142-4d24-ae4c-38be03500677> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e4a76a0a-18b8-41e2-986b-087a536b7283> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e4a76a0a-18b8-41e2-986b-087a536b7283> a person:Person.
           <http://data.lblod.info/id/personen/e4a76a0a-18b8-41e2-986b-087a536b7283> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e4a76a0a-18b8-41e2-986b-087a536b7283> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Bart".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e4a76a0a-18b8-41e2-986b-087a536b7283> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/93c51025-6a2c-4ec4-8192-a61ea19223a3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/93c51025-6a2c-4ec4-8192-a61ea19223a3> a person:Person.
           <http://data.lblod.info/id/personen/93c51025-6a2c-4ec4-8192-a61ea19223a3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/93c51025-6a2c-4ec4-8192-a61ea19223a3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Catherine".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/93c51025-6a2c-4ec4-8192-a61ea19223a3> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2c9c06b4-3c37-453f-9d27-86d617483253> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2c9c06b4-3c37-453f-9d27-86d617483253> a person:Person.
           <http://data.lblod.info/id/personen/2c9c06b4-3c37-453f-9d27-86d617483253> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2c9c06b4-3c37-453f-9d27-86d617483253> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Guy".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2c9c06b4-3c37-453f-9d27-86d617483253> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/b1ea3979-ceb4-45b3-a900-328cf60ec2e2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b1ea3979-ceb4-45b3-a900-328cf60ec2e2> a person:Person.
           <http://data.lblod.info/id/personen/b1ea3979-ceb4-45b3-a900-328cf60ec2e2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b1ea3979-ceb4-45b3-a900-328cf60ec2e2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Anoesjka".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b1ea3979-ceb4-45b3-a900-328cf60ec2e2> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/fbfc4f4f8fda49ed8ad790d6fc73ff4d061e44d4b54da55b32e8203f998a0d6c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/fbfc4f4f8fda49ed8ad790d6fc73ff4d061e44d4b54da55b32e8203f998a0d6c> a person:Person.
           <http://data.lblod.info/id/personen/fbfc4f4f8fda49ed8ad790d6fc73ff4d061e44d4b54da55b32e8203f998a0d6c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/fbfc4f4f8fda49ed8ad790d6fc73ff4d061e44d4b54da55b32e8203f998a0d6c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Vincent".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/fbfc4f4f8fda49ed8ad790d6fc73ff4d061e44d4b54da55b32e8203f998a0d6c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/eae7f9b295ad09a526cfce7df17262ea2f80e5dc1233fbaa1520c82bb5f2af0a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/eae7f9b295ad09a526cfce7df17262ea2f80e5dc1233fbaa1520c82bb5f2af0a> a person:Person.
           <http://data.lblod.info/id/personen/eae7f9b295ad09a526cfce7df17262ea2f80e5dc1233fbaa1520c82bb5f2af0a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/eae7f9b295ad09a526cfce7df17262ea2f80e5dc1233fbaa1520c82bb5f2af0a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Rita".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/eae7f9b295ad09a526cfce7df17262ea2f80e5dc1233fbaa1520c82bb5f2af0a> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/82e447ff-05ca-442c-a9f2-a5a74abb5007> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/82e447ff-05ca-442c-a9f2-a5a74abb5007> a person:Person.
           <http://data.lblod.info/id/personen/82e447ff-05ca-442c-a9f2-a5a74abb5007> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/82e447ff-05ca-442c-a9f2-a5a74abb5007> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Sheryl".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/82e447ff-05ca-442c-a9f2-a5a74abb5007> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/81e772e9-d2bf-4063-9bee-eea47069b53e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/81e772e9-d2bf-4063-9bee-eea47069b53e> a person:Person.
           <http://data.lblod.info/id/personen/81e772e9-d2bf-4063-9bee-eea47069b53e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/81e772e9-d2bf-4063-9bee-eea47069b53e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Rudy".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/81e772e9-d2bf-4063-9bee-eea47069b53e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/a036f900-fd7b-45a4-a78c-c8e9746d807f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a036f900-fd7b-45a4-a78c-c8e9746d807f> a person:Person.
           <http://data.lblod.info/id/personen/a036f900-fd7b-45a4-a78c-c8e9746d807f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a036f900-fd7b-45a4-a78c-c8e9746d807f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Vera".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a036f900-fd7b-45a4-a78c-c8e9746d807f> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ed9f6278-8e8b-43a4-87f5-d156622c8fe7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ed9f6278-8e8b-43a4-87f5-d156622c8fe7> a person:Person.
           <http://data.lblod.info/id/personen/ed9f6278-8e8b-43a4-87f5-d156622c8fe7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ed9f6278-8e8b-43a4-87f5-d156622c8fe7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Gerrit".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ed9f6278-8e8b-43a4-87f5-d156622c8fe7> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/cc04cdd2d6ece419130e03182944122f045b8bb9730bacb3857ba644c9639354> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cc04cdd2d6ece419130e03182944122f045b8bb9730bacb3857ba644c9639354> a person:Person.
           <http://data.lblod.info/id/personen/cc04cdd2d6ece419130e03182944122f045b8bb9730bacb3857ba644c9639354> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cc04cdd2d6ece419130e03182944122f045b8bb9730bacb3857ba644c9639354> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Sofie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cc04cdd2d6ece419130e03182944122f045b8bb9730bacb3857ba644c9639354> [] [].
          }
        }
     # finished voornamen-update-26144-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:40+00:00