# started voornamen-update-19898-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:25+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/6ea11833-a43b-4213-99a8-7c6278eb1184> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6ea11833-a43b-4213-99a8-7c6278eb1184> a person:Person.
           <http://data.lblod.info/id/personen/6ea11833-a43b-4213-99a8-7c6278eb1184> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6ea11833-a43b-4213-99a8-7c6278eb1184> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Fleur".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6ea11833-a43b-4213-99a8-7c6278eb1184> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/05e18b91-0283-4f4d-8b72-a289f3866a1e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/05e18b91-0283-4f4d-8b72-a289f3866a1e> a person:Person.
           <http://data.lblod.info/id/personen/05e18b91-0283-4f4d-8b72-a289f3866a1e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/05e18b91-0283-4f4d-8b72-a289f3866a1e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Nick".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/05e18b91-0283-4f4d-8b72-a289f3866a1e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/8584bbc0-2e57-421a-ad6a-4f84bf42e79b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8584bbc0-2e57-421a-ad6a-4f84bf42e79b> a person:Person.
           <http://data.lblod.info/id/personen/8584bbc0-2e57-421a-ad6a-4f84bf42e79b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8584bbc0-2e57-421a-ad6a-4f84bf42e79b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Virginie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8584bbc0-2e57-421a-ad6a-4f84bf42e79b> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/38d978c2-3fbd-4916-af0c-2c9508495ea1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/38d978c2-3fbd-4916-af0c-2c9508495ea1> a person:Person.
           <http://data.lblod.info/id/personen/38d978c2-3fbd-4916-af0c-2c9508495ea1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/38d978c2-3fbd-4916-af0c-2c9508495ea1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "David".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/38d978c2-3fbd-4916-af0c-2c9508495ea1> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/cb93296987e4cd38373300803c28b742d61b080f9edf0c1927564a1717cbf366> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cb93296987e4cd38373300803c28b742d61b080f9edf0c1927564a1717cbf366> a person:Person.
           <http://data.lblod.info/id/personen/cb93296987e4cd38373300803c28b742d61b080f9edf0c1927564a1717cbf366> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cb93296987e4cd38373300803c28b742d61b080f9edf0c1927564a1717cbf366> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marniek".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cb93296987e4cd38373300803c28b742d61b080f9edf0c1927564a1717cbf366> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/5b886470-84c4-4cbf-acb0-ed1e10cb919c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5b886470-84c4-4cbf-acb0-ed1e10cb919c> a person:Person.
           <http://data.lblod.info/id/personen/5b886470-84c4-4cbf-acb0-ed1e10cb919c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5b886470-84c4-4cbf-acb0-ed1e10cb919c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Dominique".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5b886470-84c4-4cbf-acb0-ed1e10cb919c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/abb5e004-7e2b-409d-9901-3d616b56136d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/abb5e004-7e2b-409d-9901-3d616b56136d> a person:Person.
           <http://data.lblod.info/id/personen/abb5e004-7e2b-409d-9901-3d616b56136d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/abb5e004-7e2b-409d-9901-3d616b56136d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Carl".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/abb5e004-7e2b-409d-9901-3d616b56136d> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/1a9dd926-c6b4-4bec-9d8e-8cb1d9593d73> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1a9dd926-c6b4-4bec-9d8e-8cb1d9593d73> a person:Person.
           <http://data.lblod.info/id/personen/1a9dd926-c6b4-4bec-9d8e-8cb1d9593d73> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1a9dd926-c6b4-4bec-9d8e-8cb1d9593d73> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Geert".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1a9dd926-c6b4-4bec-9d8e-8cb1d9593d73> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/6168fcdf-6ed6-44c1-bdcf-d0ed76d8285e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6168fcdf-6ed6-44c1-bdcf-d0ed76d8285e> a person:Person.
           <http://data.lblod.info/id/personen/6168fcdf-6ed6-44c1-bdcf-d0ed76d8285e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6168fcdf-6ed6-44c1-bdcf-d0ed76d8285e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Johnny".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6168fcdf-6ed6-44c1-bdcf-d0ed76d8285e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/5419b8c7c197079458a01e9251bd61009d631417f9725f599dde959739e70344> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5419b8c7c197079458a01e9251bd61009d631417f9725f599dde959739e70344> a person:Person.
           <http://data.lblod.info/id/personen/5419b8c7c197079458a01e9251bd61009d631417f9725f599dde959739e70344> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5419b8c7c197079458a01e9251bd61009d631417f9725f599dde959739e70344> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jan".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5419b8c7c197079458a01e9251bd61009d631417f9725f599dde959739e70344> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/0ec8c216-0053-48f6-a66c-8457ee0cd793> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0ec8c216-0053-48f6-a66c-8457ee0cd793> a person:Person.
           <http://data.lblod.info/id/personen/0ec8c216-0053-48f6-a66c-8457ee0cd793> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0ec8c216-0053-48f6-a66c-8457ee0cd793> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Johanna".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0ec8c216-0053-48f6-a66c-8457ee0cd793> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2087bf62-2552-4d11-891f-e551a8573d97> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2087bf62-2552-4d11-891f-e551a8573d97> a person:Person.
           <http://data.lblod.info/id/personen/2087bf62-2552-4d11-891f-e551a8573d97> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2087bf62-2552-4d11-891f-e551a8573d97> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Geert".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2087bf62-2552-4d11-891f-e551a8573d97> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/eb2dadf7-f203-44ba-bd61-0aa824884412> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/eb2dadf7-f203-44ba-bd61-0aa824884412> a person:Person.
           <http://data.lblod.info/id/personen/eb2dadf7-f203-44ba-bd61-0aa824884412> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/eb2dadf7-f203-44ba-bd61-0aa824884412> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Géry".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/eb2dadf7-f203-44ba-bd61-0aa824884412> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/daeb821e-2011-40b7-958a-04b0734f4dab> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/daeb821e-2011-40b7-958a-04b0734f4dab> a person:Person.
           <http://data.lblod.info/id/personen/daeb821e-2011-40b7-958a-04b0734f4dab> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/daeb821e-2011-40b7-958a-04b0734f4dab> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Anita".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/daeb821e-2011-40b7-958a-04b0734f4dab> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/4342a523-50e4-48bf-aedc-a88d87c9cf35> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4342a523-50e4-48bf-aedc-a88d87c9cf35> a person:Person.
           <http://data.lblod.info/id/personen/4342a523-50e4-48bf-aedc-a88d87c9cf35> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4342a523-50e4-48bf-aedc-a88d87c9cf35> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Pieter".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4342a523-50e4-48bf-aedc-a88d87c9cf35> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/d022b8ed-af27-4794-b8a7-b88f8d9a2134> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d022b8ed-af27-4794-b8a7-b88f8d9a2134> a person:Person.
           <http://data.lblod.info/id/personen/d022b8ed-af27-4794-b8a7-b88f8d9a2134> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d022b8ed-af27-4794-b8a7-b88f8d9a2134> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Stephanie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d022b8ed-af27-4794-b8a7-b88f8d9a2134> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/518681ea-0954-412f-a430-06a62fd994e1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/518681ea-0954-412f-a430-06a62fd994e1> a person:Person.
           <http://data.lblod.info/id/personen/518681ea-0954-412f-a430-06a62fd994e1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/518681ea-0954-412f-a430-06a62fd994e1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Andy".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/518681ea-0954-412f-a430-06a62fd994e1> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e62ae7dd-cf6c-4e27-84e2-e81a7ef3b5f9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e62ae7dd-cf6c-4e27-84e2-e81a7ef3b5f9> a person:Person.
           <http://data.lblod.info/id/personen/e62ae7dd-cf6c-4e27-84e2-e81a7ef3b5f9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e62ae7dd-cf6c-4e27-84e2-e81a7ef3b5f9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Cindy".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e62ae7dd-cf6c-4e27-84e2-e81a7ef3b5f9> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/30aefccb-e9df-4139-b677-a8c7d45676f5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/30aefccb-e9df-4139-b677-a8c7d45676f5> a person:Person.
           <http://data.lblod.info/id/personen/30aefccb-e9df-4139-b677-a8c7d45676f5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/30aefccb-e9df-4139-b677-a8c7d45676f5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Andy".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/30aefccb-e9df-4139-b677-a8c7d45676f5> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/71aa052d-a90a-4743-9ee8-ecd7db365429> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/71aa052d-a90a-4743-9ee8-ecd7db365429> a person:Person.
           <http://data.lblod.info/id/personen/71aa052d-a90a-4743-9ee8-ecd7db365429> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/71aa052d-a90a-4743-9ee8-ecd7db365429> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Fabienne".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/71aa052d-a90a-4743-9ee8-ecd7db365429> [] [].
          }
        }
     # finished voornamen-update-19898-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:25+00:00