# started voornamen-update-12156-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:05+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/aa8bc3c2-654a-43f3-8272-672ee41df6a8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/aa8bc3c2-654a-43f3-8272-672ee41df6a8> a person:Person.
           <http://data.lblod.info/id/personen/aa8bc3c2-654a-43f3-8272-672ee41df6a8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/aa8bc3c2-654a-43f3-8272-672ee41df6a8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Bas".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/aa8bc3c2-654a-43f3-8272-672ee41df6a8> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/58d1b28e-ea18-40eb-954c-de99f2f359e0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/58d1b28e-ea18-40eb-954c-de99f2f359e0> a person:Person.
           <http://data.lblod.info/id/personen/58d1b28e-ea18-40eb-954c-de99f2f359e0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/58d1b28e-ea18-40eb-954c-de99f2f359e0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Stijn".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/58d1b28e-ea18-40eb-954c-de99f2f359e0> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/a85e8120-00ae-45ea-9cbc-ba0c9af7da04> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a85e8120-00ae-45ea-9cbc-ba0c9af7da04> a person:Person.
           <http://data.lblod.info/id/personen/a85e8120-00ae-45ea-9cbc-ba0c9af7da04> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a85e8120-00ae-45ea-9cbc-ba0c9af7da04> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Greta".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a85e8120-00ae-45ea-9cbc-ba0c9af7da04> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/bb6b9a7b-5c7c-40bf-b414-102c5aa709de> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bb6b9a7b-5c7c-40bf-b414-102c5aa709de> a person:Person.
           <http://data.lblod.info/id/personen/bb6b9a7b-5c7c-40bf-b414-102c5aa709de> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bb6b9a7b-5c7c-40bf-b414-102c5aa709de> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Gino".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bb6b9a7b-5c7c-40bf-b414-102c5aa709de> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/395f6fd9-3bac-4530-9171-b5dec658b19e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/395f6fd9-3bac-4530-9171-b5dec658b19e> a person:Person.
           <http://data.lblod.info/id/personen/395f6fd9-3bac-4530-9171-b5dec658b19e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/395f6fd9-3bac-4530-9171-b5dec658b19e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "An".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/395f6fd9-3bac-4530-9171-b5dec658b19e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/23fe4716-7e05-45e6-8ba9-dc38cde9c137> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/23fe4716-7e05-45e6-8ba9-dc38cde9c137> a person:Person.
           <http://data.lblod.info/id/personen/23fe4716-7e05-45e6-8ba9-dc38cde9c137> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/23fe4716-7e05-45e6-8ba9-dc38cde9c137> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Lina".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/23fe4716-7e05-45e6-8ba9-dc38cde9c137> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/97961e39-ef78-4ed8-9563-d7cb5b9e4dbd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/97961e39-ef78-4ed8-9563-d7cb5b9e4dbd> a person:Person.
           <http://data.lblod.info/id/personen/97961e39-ef78-4ed8-9563-d7cb5b9e4dbd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/97961e39-ef78-4ed8-9563-d7cb5b9e4dbd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Kelly".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/97961e39-ef78-4ed8-9563-d7cb5b9e4dbd> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/b35043be-1dca-4ab0-837f-00a4c70c63a0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b35043be-1dca-4ab0-837f-00a4c70c63a0> a person:Person.
           <http://data.lblod.info/id/personen/b35043be-1dca-4ab0-837f-00a4c70c63a0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b35043be-1dca-4ab0-837f-00a4c70c63a0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Freddy".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b35043be-1dca-4ab0-837f-00a4c70c63a0> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f540a462d4da9583b9bb070fa77134138245e71cddd301075eaeacd2a72b99f7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f540a462d4da9583b9bb070fa77134138245e71cddd301075eaeacd2a72b99f7> a person:Person.
           <http://data.lblod.info/id/personen/f540a462d4da9583b9bb070fa77134138245e71cddd301075eaeacd2a72b99f7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f540a462d4da9583b9bb070fa77134138245e71cddd301075eaeacd2a72b99f7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jacques".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f540a462d4da9583b9bb070fa77134138245e71cddd301075eaeacd2a72b99f7> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/29fc4e71-ed49-4cd5-9763-c46f6497b2ea> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/29fc4e71-ed49-4cd5-9763-c46f6497b2ea> a person:Person.
           <http://data.lblod.info/id/personen/29fc4e71-ed49-4cd5-9763-c46f6497b2ea> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/29fc4e71-ed49-4cd5-9763-c46f6497b2ea> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ivo".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/29fc4e71-ed49-4cd5-9763-c46f6497b2ea> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/fea4f171bc0ea3594d6da1655636b6abcb6889e696fc73cad0f62ecf2ddf2bbd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/fea4f171bc0ea3594d6da1655636b6abcb6889e696fc73cad0f62ecf2ddf2bbd> a person:Person.
           <http://data.lblod.info/id/personen/fea4f171bc0ea3594d6da1655636b6abcb6889e696fc73cad0f62ecf2ddf2bbd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/fea4f171bc0ea3594d6da1655636b6abcb6889e696fc73cad0f62ecf2ddf2bbd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Houari".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/fea4f171bc0ea3594d6da1655636b6abcb6889e696fc73cad0f62ecf2ddf2bbd> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/d6ab2a3e-6663-4819-8407-55d8aada9c05> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d6ab2a3e-6663-4819-8407-55d8aada9c05> a person:Person.
           <http://data.lblod.info/id/personen/d6ab2a3e-6663-4819-8407-55d8aada9c05> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d6ab2a3e-6663-4819-8407-55d8aada9c05> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Melissa".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d6ab2a3e-6663-4819-8407-55d8aada9c05> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/cc6e5b73-3d7a-421e-85d9-0b8de071f92b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cc6e5b73-3d7a-421e-85d9-0b8de071f92b> a person:Person.
           <http://data.lblod.info/id/personen/cc6e5b73-3d7a-421e-85d9-0b8de071f92b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cc6e5b73-3d7a-421e-85d9-0b8de071f92b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "François".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cc6e5b73-3d7a-421e-85d9-0b8de071f92b> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/cbe4c833-8e61-4e73-a795-e93b31966369> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cbe4c833-8e61-4e73-a795-e93b31966369> a person:Person.
           <http://data.lblod.info/id/personen/cbe4c833-8e61-4e73-a795-e93b31966369> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cbe4c833-8e61-4e73-a795-e93b31966369> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marc".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cbe4c833-8e61-4e73-a795-e93b31966369> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/fa9a0aa6-df25-41ca-a9bc-ef19a8282459> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/fa9a0aa6-df25-41ca-a9bc-ef19a8282459> a person:Person.
           <http://data.lblod.info/id/personen/fa9a0aa6-df25-41ca-a9bc-ef19a8282459> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/fa9a0aa6-df25-41ca-a9bc-ef19a8282459> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Aimen".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/fa9a0aa6-df25-41ca-a9bc-ef19a8282459> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/335b41b6-eb6b-43aa-b62c-1981b5c171e2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/335b41b6-eb6b-43aa-b62c-1981b5c171e2> a person:Person.
           <http://data.lblod.info/id/personen/335b41b6-eb6b-43aa-b62c-1981b5c171e2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/335b41b6-eb6b-43aa-b62c-1981b5c171e2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Barbara".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/335b41b6-eb6b-43aa-b62c-1981b5c171e2> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/6c96a4b2-bc24-4871-ac47-f80ea7cdd120> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6c96a4b2-bc24-4871-ac47-f80ea7cdd120> a person:Person.
           <http://data.lblod.info/id/personen/6c96a4b2-bc24-4871-ac47-f80ea7cdd120> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6c96a4b2-bc24-4871-ac47-f80ea7cdd120> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "David".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6c96a4b2-bc24-4871-ac47-f80ea7cdd120> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/cb8f9231b84a36243c84d837925dd249eb9a8e8731e9cb24f079af0fd1512360> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cb8f9231b84a36243c84d837925dd249eb9a8e8731e9cb24f079af0fd1512360> a person:Person.
           <http://data.lblod.info/id/personen/cb8f9231b84a36243c84d837925dd249eb9a8e8731e9cb24f079af0fd1512360> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cb8f9231b84a36243c84d837925dd249eb9a8e8731e9cb24f079af0fd1512360> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ingrid".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cb8f9231b84a36243c84d837925dd249eb9a8e8731e9cb24f079af0fd1512360> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/0c2bc6c768c98996c525e24e34b623ad5d78d5eecdeedc2fe5fbf6c6b63e901e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0c2bc6c768c98996c525e24e34b623ad5d78d5eecdeedc2fe5fbf6c6b63e901e> a person:Person.
           <http://data.lblod.info/id/personen/0c2bc6c768c98996c525e24e34b623ad5d78d5eecdeedc2fe5fbf6c6b63e901e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0c2bc6c768c98996c525e24e34b623ad5d78d5eecdeedc2fe5fbf6c6b63e901e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Eric".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0c2bc6c768c98996c525e24e34b623ad5d78d5eecdeedc2fe5fbf6c6b63e901e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/b40af7ac-c2ef-4b63-a7cf-19da56762e30> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b40af7ac-c2ef-4b63-a7cf-19da56762e30> a person:Person.
           <http://data.lblod.info/id/personen/b40af7ac-c2ef-4b63-a7cf-19da56762e30> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b40af7ac-c2ef-4b63-a7cf-19da56762e30> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Catia".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b40af7ac-c2ef-4b63-a7cf-19da56762e30> [] [].
          }
        }
     # finished voornamen-update-12156-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:05+00:00