# started voornamen-update-698-2490de85e718ffa3e23344f4cd674bd5d9f40252833c8af6fb7fa3b82f44b008 at 2018-12-27T15:07:09+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/4b85cf9b-de76-403d-8f8a-4af1c6be39d1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4b85cf9b-de76-403d-8f8a-4af1c6be39d1> a person:Person.
           <http://data.lblod.info/id/personen/4b85cf9b-de76-403d-8f8a-4af1c6be39d1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4b85cf9b-de76-403d-8f8a-4af1c6be39d1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Robert".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4b85cf9b-de76-403d-8f8a-4af1c6be39d1> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/b87bb79e-fe40-4229-921f-1165cb43c1d2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b87bb79e-fe40-4229-921f-1165cb43c1d2> a person:Person.
           <http://data.lblod.info/id/personen/b87bb79e-fe40-4229-921f-1165cb43c1d2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b87bb79e-fe40-4229-921f-1165cb43c1d2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Veronique".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b87bb79e-fe40-4229-921f-1165cb43c1d2> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/c82c305c-fa06-489a-92d1-3b88c5544c47> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c82c305c-fa06-489a-92d1-3b88c5544c47> a person:Person.
           <http://data.lblod.info/id/personen/c82c305c-fa06-489a-92d1-3b88c5544c47> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c82c305c-fa06-489a-92d1-3b88c5544c47> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Irene".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c82c305c-fa06-489a-92d1-3b88c5544c47> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/bdcc8ec6-13a7-4c64-9547-774600d084e1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bdcc8ec6-13a7-4c64-9547-774600d084e1> a person:Person.
           <http://data.lblod.info/id/personen/bdcc8ec6-13a7-4c64-9547-774600d084e1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bdcc8ec6-13a7-4c64-9547-774600d084e1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Mascha".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bdcc8ec6-13a7-4c64-9547-774600d084e1> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/c896a939-835b-4669-a94e-75709a4dd734> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c896a939-835b-4669-a94e-75709a4dd734> a person:Person.
           <http://data.lblod.info/id/personen/c896a939-835b-4669-a94e-75709a4dd734> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c896a939-835b-4669-a94e-75709a4dd734> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Alain".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c896a939-835b-4669-a94e-75709a4dd734> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e46f7ba6-f92d-4373-9ec2-65fd3c2b02a1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e46f7ba6-f92d-4373-9ec2-65fd3c2b02a1> a person:Person.
           <http://data.lblod.info/id/personen/e46f7ba6-f92d-4373-9ec2-65fd3c2b02a1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e46f7ba6-f92d-4373-9ec2-65fd3c2b02a1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Filip".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e46f7ba6-f92d-4373-9ec2-65fd3c2b02a1> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/fe053d13-68e1-46fe-a7cf-6f97f9555f27> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/fe053d13-68e1-46fe-a7cf-6f97f9555f27> a person:Person.
           <http://data.lblod.info/id/personen/fe053d13-68e1-46fe-a7cf-6f97f9555f27> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/fe053d13-68e1-46fe-a7cf-6f97f9555f27> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Sonja".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/fe053d13-68e1-46fe-a7cf-6f97f9555f27> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/df673c96-c2f8-4532-95c3-2fb89b850c75> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/df673c96-c2f8-4532-95c3-2fb89b850c75> a person:Person.
           <http://data.lblod.info/id/personen/df673c96-c2f8-4532-95c3-2fb89b850c75> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/df673c96-c2f8-4532-95c3-2fb89b850c75> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Xander".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/df673c96-c2f8-4532-95c3-2fb89b850c75> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/1d351c53-06e1-4a7d-b0c0-0096cd2ea897> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1d351c53-06e1-4a7d-b0c0-0096cd2ea897> a person:Person.
           <http://data.lblod.info/id/personen/1d351c53-06e1-4a7d-b0c0-0096cd2ea897> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1d351c53-06e1-4a7d-b0c0-0096cd2ea897> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Peggy".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1d351c53-06e1-4a7d-b0c0-0096cd2ea897> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/915543be-3fa6-4dde-939d-6a7469b82167> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/915543be-3fa6-4dde-939d-6a7469b82167> a person:Person.
           <http://data.lblod.info/id/personen/915543be-3fa6-4dde-939d-6a7469b82167> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/915543be-3fa6-4dde-939d-6a7469b82167> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Wout".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/915543be-3fa6-4dde-939d-6a7469b82167> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2616b1a4-10de-458c-af3e-422ec0ce47db> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2616b1a4-10de-458c-af3e-422ec0ce47db> a person:Person.
           <http://data.lblod.info/id/personen/2616b1a4-10de-458c-af3e-422ec0ce47db> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2616b1a4-10de-458c-af3e-422ec0ce47db> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Viviane".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2616b1a4-10de-458c-af3e-422ec0ce47db> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/1aef3aee-67b0-4d74-b09d-70ddb5c65469> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1aef3aee-67b0-4d74-b09d-70ddb5c65469> a person:Person.
           <http://data.lblod.info/id/personen/1aef3aee-67b0-4d74-b09d-70ddb5c65469> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1aef3aee-67b0-4d74-b09d-70ddb5c65469> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jorg".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1aef3aee-67b0-4d74-b09d-70ddb5c65469> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/c1935cd0-0d72-4497-b990-0f43dfe511f3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c1935cd0-0d72-4497-b990-0f43dfe511f3> a person:Person.
           <http://data.lblod.info/id/personen/c1935cd0-0d72-4497-b990-0f43dfe511f3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c1935cd0-0d72-4497-b990-0f43dfe511f3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Greg".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c1935cd0-0d72-4497-b990-0f43dfe511f3> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/1c4fcafa-9897-469f-bb44-94bcc5d5c2d6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1c4fcafa-9897-469f-bb44-94bcc5d5c2d6> a person:Person.
           <http://data.lblod.info/id/personen/1c4fcafa-9897-469f-bb44-94bcc5d5c2d6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1c4fcafa-9897-469f-bb44-94bcc5d5c2d6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ellen".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1c4fcafa-9897-469f-bb44-94bcc5d5c2d6> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e64546b991e04b685d35766e4a5b93b143c739a2d5b45615f0a164842279db50> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e64546b991e04b685d35766e4a5b93b143c739a2d5b45615f0a164842279db50> a person:Person.
           <http://data.lblod.info/id/personen/e64546b991e04b685d35766e4a5b93b143c739a2d5b45615f0a164842279db50> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e64546b991e04b685d35766e4a5b93b143c739a2d5b45615f0a164842279db50> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Koen".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e64546b991e04b685d35766e4a5b93b143c739a2d5b45615f0a164842279db50> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/a69a5120fe95e6f06c027c728fe5c32fa8b12b1cceeca5f7ea5b0a97a2e601e2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a69a5120fe95e6f06c027c728fe5c32fa8b12b1cceeca5f7ea5b0a97a2e601e2> a person:Person.
           <http://data.lblod.info/id/personen/a69a5120fe95e6f06c027c728fe5c32fa8b12b1cceeca5f7ea5b0a97a2e601e2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a69a5120fe95e6f06c027c728fe5c32fa8b12b1cceeca5f7ea5b0a97a2e601e2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Mia".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a69a5120fe95e6f06c027c728fe5c32fa8b12b1cceeca5f7ea5b0a97a2e601e2> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/47ed0993-3c8a-44fb-aee3-41ec1ae95038> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/47ed0993-3c8a-44fb-aee3-41ec1ae95038> a person:Person.
           <http://data.lblod.info/id/personen/47ed0993-3c8a-44fb-aee3-41ec1ae95038> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/47ed0993-3c8a-44fb-aee3-41ec1ae95038> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Lina".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/47ed0993-3c8a-44fb-aee3-41ec1ae95038> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/64b61391-9aeb-415c-89b6-f667518580bd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/64b61391-9aeb-415c-89b6-f667518580bd> a person:Person.
           <http://data.lblod.info/id/personen/64b61391-9aeb-415c-89b6-f667518580bd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/64b61391-9aeb-415c-89b6-f667518580bd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Rit".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/64b61391-9aeb-415c-89b6-f667518580bd> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/952aeda00528e2c6f2c13ed0f9e4212c9476feea2a36c58802e00f2ddd4d2f6a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/952aeda00528e2c6f2c13ed0f9e4212c9476feea2a36c58802e00f2ddd4d2f6a> a person:Person.
           <http://data.lblod.info/id/personen/952aeda00528e2c6f2c13ed0f9e4212c9476feea2a36c58802e00f2ddd4d2f6a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/952aeda00528e2c6f2c13ed0f9e4212c9476feea2a36c58802e00f2ddd4d2f6a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Willy".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/952aeda00528e2c6f2c13ed0f9e4212c9476feea2a36c58802e00f2ddd4d2f6a> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/76f2fee2fcbebf6f6f486abd22359403f0a6804bde70c6615a0e1b19868b21de> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/76f2fee2fcbebf6f6f486abd22359403f0a6804bde70c6615a0e1b19868b21de> a person:Person.
           <http://data.lblod.info/id/personen/76f2fee2fcbebf6f6f486abd22359403f0a6804bde70c6615a0e1b19868b21de> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/76f2fee2fcbebf6f6f486abd22359403f0a6804bde70c6615a0e1b19868b21de> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Gina".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/76f2fee2fcbebf6f6f486abd22359403f0a6804bde70c6615a0e1b19868b21de> [] [].
          }
        }
     # finished voornamen-update-698-2490de85e718ffa3e23344f4cd674bd5d9f40252833c8af6fb7fa3b82f44b008 at 2018-12-27T15:07:09+00:00