# started voornamen-update-17258-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:18+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/6710f735-a00b-4ade-bbed-91d4dcabafe6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6710f735-a00b-4ade-bbed-91d4dcabafe6> a person:Person.
           <http://data.lblod.info/id/personen/6710f735-a00b-4ade-bbed-91d4dcabafe6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6710f735-a00b-4ade-bbed-91d4dcabafe6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Lieveke".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6710f735-a00b-4ade-bbed-91d4dcabafe6> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/328b52d2-bdbb-440f-b71f-2251c12c6cd9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/328b52d2-bdbb-440f-b71f-2251c12c6cd9> a person:Person.
           <http://data.lblod.info/id/personen/328b52d2-bdbb-440f-b71f-2251c12c6cd9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/328b52d2-bdbb-440f-b71f-2251c12c6cd9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Wout".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/328b52d2-bdbb-440f-b71f-2251c12c6cd9> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/be95693b-ce23-496b-991f-9cf544d24ad8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/be95693b-ce23-496b-991f-9cf544d24ad8> a person:Person.
           <http://data.lblod.info/id/personen/be95693b-ce23-496b-991f-9cf544d24ad8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/be95693b-ce23-496b-991f-9cf544d24ad8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Diya".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/be95693b-ce23-496b-991f-9cf544d24ad8> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/34f729c2-eaf7-49c4-a0dc-39f52986143a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/34f729c2-eaf7-49c4-a0dc-39f52986143a> a person:Person.
           <http://data.lblod.info/id/personen/34f729c2-eaf7-49c4-a0dc-39f52986143a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/34f729c2-eaf7-49c4-a0dc-39f52986143a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Martine".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/34f729c2-eaf7-49c4-a0dc-39f52986143a> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/df82e97f-f76f-4213-8cf8-67a76648486c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/df82e97f-f76f-4213-8cf8-67a76648486c> a person:Person.
           <http://data.lblod.info/id/personen/df82e97f-f76f-4213-8cf8-67a76648486c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/df82e97f-f76f-4213-8cf8-67a76648486c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Eva".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/df82e97f-f76f-4213-8cf8-67a76648486c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ffe65c09-ccd4-4c04-bf2f-6f37b8d30a63> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ffe65c09-ccd4-4c04-bf2f-6f37b8d30a63> a person:Person.
           <http://data.lblod.info/id/personen/ffe65c09-ccd4-4c04-bf2f-6f37b8d30a63> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ffe65c09-ccd4-4c04-bf2f-6f37b8d30a63> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Christine".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ffe65c09-ccd4-4c04-bf2f-6f37b8d30a63> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f75cb542-154b-49cf-af6c-69cc4dfff766> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f75cb542-154b-49cf-af6c-69cc4dfff766> a person:Person.
           <http://data.lblod.info/id/personen/f75cb542-154b-49cf-af6c-69cc4dfff766> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f75cb542-154b-49cf-af6c-69cc4dfff766> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Joke".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f75cb542-154b-49cf-af6c-69cc4dfff766> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/49860aca-eda2-42a4-9a9b-0abbcce233f1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/49860aca-eda2-42a4-9a9b-0abbcce233f1> a person:Person.
           <http://data.lblod.info/id/personen/49860aca-eda2-42a4-9a9b-0abbcce233f1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/49860aca-eda2-42a4-9a9b-0abbcce233f1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ann".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/49860aca-eda2-42a4-9a9b-0abbcce233f1> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/9162b9b0-96b4-49d2-822d-b43205469103> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9162b9b0-96b4-49d2-822d-b43205469103> a person:Person.
           <http://data.lblod.info/id/personen/9162b9b0-96b4-49d2-822d-b43205469103> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9162b9b0-96b4-49d2-822d-b43205469103> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ramina".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9162b9b0-96b4-49d2-822d-b43205469103> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/85ecab5d-40f4-41ae-b107-632efa97cd99> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/85ecab5d-40f4-41ae-b107-632efa97cd99> a person:Person.
           <http://data.lblod.info/id/personen/85ecab5d-40f4-41ae-b107-632efa97cd99> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/85ecab5d-40f4-41ae-b107-632efa97cd99> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Febe".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/85ecab5d-40f4-41ae-b107-632efa97cd99> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/a5c04f6b-106c-454f-b382-3e139fff5793> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a5c04f6b-106c-454f-b382-3e139fff5793> a person:Person.
           <http://data.lblod.info/id/personen/a5c04f6b-106c-454f-b382-3e139fff5793> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a5c04f6b-106c-454f-b382-3e139fff5793> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Björn".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a5c04f6b-106c-454f-b382-3e139fff5793> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/04bdfc08-e792-4ef3-ab08-1ab1e3baa73b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/04bdfc08-e792-4ef3-ab08-1ab1e3baa73b> a person:Person.
           <http://data.lblod.info/id/personen/04bdfc08-e792-4ef3-ab08-1ab1e3baa73b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/04bdfc08-e792-4ef3-ab08-1ab1e3baa73b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marc".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/04bdfc08-e792-4ef3-ab08-1ab1e3baa73b> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/46344137-25f2-4ed1-aee5-0269d3762dff> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/46344137-25f2-4ed1-aee5-0269d3762dff> a person:Person.
           <http://data.lblod.info/id/personen/46344137-25f2-4ed1-aee5-0269d3762dff> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/46344137-25f2-4ed1-aee5-0269d3762dff> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Chris".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/46344137-25f2-4ed1-aee5-0269d3762dff> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/98a6ff3c-6372-45e9-ac40-7a1882b7d0d9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/98a6ff3c-6372-45e9-ac40-7a1882b7d0d9> a person:Person.
           <http://data.lblod.info/id/personen/98a6ff3c-6372-45e9-ac40-7a1882b7d0d9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/98a6ff3c-6372-45e9-ac40-7a1882b7d0d9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Tim".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/98a6ff3c-6372-45e9-ac40-7a1882b7d0d9> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/152240e1-179f-4747-8bc8-26481fd72317> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/152240e1-179f-4747-8bc8-26481fd72317> a person:Person.
           <http://data.lblod.info/id/personen/152240e1-179f-4747-8bc8-26481fd72317> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/152240e1-179f-4747-8bc8-26481fd72317> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Francis".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/152240e1-179f-4747-8bc8-26481fd72317> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/75b9e4d1-2c28-4eeb-8819-ec03499814ed> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/75b9e4d1-2c28-4eeb-8819-ec03499814ed> a person:Person.
           <http://data.lblod.info/id/personen/75b9e4d1-2c28-4eeb-8819-ec03499814ed> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/75b9e4d1-2c28-4eeb-8819-ec03499814ed> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Tristan".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/75b9e4d1-2c28-4eeb-8819-ec03499814ed> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/95c69004-44fb-4bc0-a82a-3e7be2833e8a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/95c69004-44fb-4bc0-a82a-3e7be2833e8a> a person:Person.
           <http://data.lblod.info/id/personen/95c69004-44fb-4bc0-a82a-3e7be2833e8a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/95c69004-44fb-4bc0-a82a-3e7be2833e8a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Chantal".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/95c69004-44fb-4bc0-a82a-3e7be2833e8a> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/13137943-470d-473f-81c2-e0e9632659b1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/13137943-470d-473f-81c2-e0e9632659b1> a person:Person.
           <http://data.lblod.info/id/personen/13137943-470d-473f-81c2-e0e9632659b1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/13137943-470d-473f-81c2-e0e9632659b1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Nancy".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/13137943-470d-473f-81c2-e0e9632659b1> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/9d4d0cda21c3f1be6547b05a2bf82804c28d516526f1067f2108ba01ec5b59c8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9d4d0cda21c3f1be6547b05a2bf82804c28d516526f1067f2108ba01ec5b59c8> a person:Person.
           <http://data.lblod.info/id/personen/9d4d0cda21c3f1be6547b05a2bf82804c28d516526f1067f2108ba01ec5b59c8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9d4d0cda21c3f1be6547b05a2bf82804c28d516526f1067f2108ba01ec5b59c8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marleen".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9d4d0cda21c3f1be6547b05a2bf82804c28d516526f1067f2108ba01ec5b59c8> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/30441fdf-2e56-4749-aaf1-f09699b75ea2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/30441fdf-2e56-4749-aaf1-f09699b75ea2> a person:Person.
           <http://data.lblod.info/id/personen/30441fdf-2e56-4749-aaf1-f09699b75ea2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/30441fdf-2e56-4749-aaf1-f09699b75ea2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Luc".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/30441fdf-2e56-4749-aaf1-f09699b75ea2> [] [].
          }
        }
     # finished voornamen-update-17258-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:18+00:00