# started voornamen-update-16185-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:15+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e1c3702852b0be8c9856863a9fc44efb8b701280c3e7adae919718a9d29c37cd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e1c3702852b0be8c9856863a9fc44efb8b701280c3e7adae919718a9d29c37cd> a person:Person.
           <http://data.lblod.info/id/personen/e1c3702852b0be8c9856863a9fc44efb8b701280c3e7adae919718a9d29c37cd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e1c3702852b0be8c9856863a9fc44efb8b701280c3e7adae919718a9d29c37cd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Nicole".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e1c3702852b0be8c9856863a9fc44efb8b701280c3e7adae919718a9d29c37cd> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/c1036850afef13a10b01dc06624524b3d6a58abc77862af1745ce0fddd62d24d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c1036850afef13a10b01dc06624524b3d6a58abc77862af1745ce0fddd62d24d> a person:Person.
           <http://data.lblod.info/id/personen/c1036850afef13a10b01dc06624524b3d6a58abc77862af1745ce0fddd62d24d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c1036850afef13a10b01dc06624524b3d6a58abc77862af1745ce0fddd62d24d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Maurice".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c1036850afef13a10b01dc06624524b3d6a58abc77862af1745ce0fddd62d24d> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/c36fded4-528c-4a1b-877c-7a3df9ebc593> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c36fded4-528c-4a1b-877c-7a3df9ebc593> a person:Person.
           <http://data.lblod.info/id/personen/c36fded4-528c-4a1b-877c-7a3df9ebc593> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c36fded4-528c-4a1b-877c-7a3df9ebc593> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Niko".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c36fded4-528c-4a1b-877c-7a3df9ebc593> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/5343f28b-4c7c-4c33-87d5-6c46f37c6c6c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5343f28b-4c7c-4c33-87d5-6c46f37c6c6c> a person:Person.
           <http://data.lblod.info/id/personen/5343f28b-4c7c-4c33-87d5-6c46f37c6c6c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5343f28b-4c7c-4c33-87d5-6c46f37c6c6c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marie José".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5343f28b-4c7c-4c33-87d5-6c46f37c6c6c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/beca60ab-0746-4d01-a3ff-b2065a9a1494> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/beca60ab-0746-4d01-a3ff-b2065a9a1494> a person:Person.
           <http://data.lblod.info/id/personen/beca60ab-0746-4d01-a3ff-b2065a9a1494> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/beca60ab-0746-4d01-a3ff-b2065a9a1494> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Gwenny".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/beca60ab-0746-4d01-a3ff-b2065a9a1494> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/c9c52ba0-54b5-421d-8420-159ed4570d99> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c9c52ba0-54b5-421d-8420-159ed4570d99> a person:Person.
           <http://data.lblod.info/id/personen/c9c52ba0-54b5-421d-8420-159ed4570d99> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c9c52ba0-54b5-421d-8420-159ed4570d99> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "David".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c9c52ba0-54b5-421d-8420-159ed4570d99> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/b260b442-3464-41df-a9ac-308f9d076fd7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b260b442-3464-41df-a9ac-308f9d076fd7> a person:Person.
           <http://data.lblod.info/id/personen/b260b442-3464-41df-a9ac-308f9d076fd7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b260b442-3464-41df-a9ac-308f9d076fd7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Werner".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b260b442-3464-41df-a9ac-308f9d076fd7> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e917d73e-adc5-42b6-82c4-5105375eee20> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e917d73e-adc5-42b6-82c4-5105375eee20> a person:Person.
           <http://data.lblod.info/id/personen/e917d73e-adc5-42b6-82c4-5105375eee20> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e917d73e-adc5-42b6-82c4-5105375eee20> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Lorenzo".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e917d73e-adc5-42b6-82c4-5105375eee20> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f3ca9ea3-4953-415f-9dd1-78f727c1363c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f3ca9ea3-4953-415f-9dd1-78f727c1363c> a person:Person.
           <http://data.lblod.info/id/personen/f3ca9ea3-4953-415f-9dd1-78f727c1363c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f3ca9ea3-4953-415f-9dd1-78f727c1363c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Joëlla".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f3ca9ea3-4953-415f-9dd1-78f727c1363c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/d2006880-1a0d-4e13-a322-e2668d29061e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d2006880-1a0d-4e13-a322-e2668d29061e> a person:Person.
           <http://data.lblod.info/id/personen/d2006880-1a0d-4e13-a322-e2668d29061e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d2006880-1a0d-4e13-a322-e2668d29061e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ciska".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d2006880-1a0d-4e13-a322-e2668d29061e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/038b2752973a98ef29f656146a4cb84c836d669c945213f4d13673dee69dce46> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/038b2752973a98ef29f656146a4cb84c836d669c945213f4d13673dee69dce46> a person:Person.
           <http://data.lblod.info/id/personen/038b2752973a98ef29f656146a4cb84c836d669c945213f4d13673dee69dce46> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/038b2752973a98ef29f656146a4cb84c836d669c945213f4d13673dee69dce46> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Greet".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/038b2752973a98ef29f656146a4cb84c836d669c945213f4d13673dee69dce46> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/287d2a10-cedd-4263-8d27-f3ac7829e624> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/287d2a10-cedd-4263-8d27-f3ac7829e624> a person:Person.
           <http://data.lblod.info/id/personen/287d2a10-cedd-4263-8d27-f3ac7829e624> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/287d2a10-cedd-4263-8d27-f3ac7829e624> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Shirley".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/287d2a10-cedd-4263-8d27-f3ac7829e624> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/594d6c62-4efa-49b2-b550-d84a95b834fd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/594d6c62-4efa-49b2-b550-d84a95b834fd> a person:Person.
           <http://data.lblod.info/id/personen/594d6c62-4efa-49b2-b550-d84a95b834fd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/594d6c62-4efa-49b2-b550-d84a95b834fd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Armand".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/594d6c62-4efa-49b2-b550-d84a95b834fd> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ba318750-0508-49a6-a32f-2367e865e197> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ba318750-0508-49a6-a32f-2367e865e197> a person:Person.
           <http://data.lblod.info/id/personen/ba318750-0508-49a6-a32f-2367e865e197> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ba318750-0508-49a6-a32f-2367e865e197> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Freddy".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ba318750-0508-49a6-a32f-2367e865e197> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/aa6e4b409925fa5e35602844c9bdac4394e91a713701d7fec0104281e81513b9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/aa6e4b409925fa5e35602844c9bdac4394e91a713701d7fec0104281e81513b9> a person:Person.
           <http://data.lblod.info/id/personen/aa6e4b409925fa5e35602844c9bdac4394e91a713701d7fec0104281e81513b9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/aa6e4b409925fa5e35602844c9bdac4394e91a713701d7fec0104281e81513b9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Benny".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/aa6e4b409925fa5e35602844c9bdac4394e91a713701d7fec0104281e81513b9> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/459d1363b40159961fba4195399c0b8e86f6d9f519b180c06242fe9a326b2b24> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/459d1363b40159961fba4195399c0b8e86f6d9f519b180c06242fe9a326b2b24> a person:Person.
           <http://data.lblod.info/id/personen/459d1363b40159961fba4195399c0b8e86f6d9f519b180c06242fe9a326b2b24> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/459d1363b40159961fba4195399c0b8e86f6d9f519b180c06242fe9a326b2b24> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Eddy".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/459d1363b40159961fba4195399c0b8e86f6d9f519b180c06242fe9a326b2b24> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/7dd17f42500fabf275c230bd03f66f6757c2111c079606c62e52ff8ea52b3815> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7dd17f42500fabf275c230bd03f66f6757c2111c079606c62e52ff8ea52b3815> a person:Person.
           <http://data.lblod.info/id/personen/7dd17f42500fabf275c230bd03f66f6757c2111c079606c62e52ff8ea52b3815> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7dd17f42500fabf275c230bd03f66f6757c2111c079606c62e52ff8ea52b3815> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ketty".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7dd17f42500fabf275c230bd03f66f6757c2111c079606c62e52ff8ea52b3815> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/c0e50597-86e4-47bf-9866-6165b676faf9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c0e50597-86e4-47bf-9866-6165b676faf9> a person:Person.
           <http://data.lblod.info/id/personen/c0e50597-86e4-47bf-9866-6165b676faf9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c0e50597-86e4-47bf-9866-6165b676faf9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Rudi".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c0e50597-86e4-47bf-9866-6165b676faf9> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/aa425590d3a3ae8287fa62f2cf83c3e8e942da4beb189ecb8cbb0ccb6ab39aff> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/aa425590d3a3ae8287fa62f2cf83c3e8e942da4beb189ecb8cbb0ccb6ab39aff> a person:Person.
           <http://data.lblod.info/id/personen/aa425590d3a3ae8287fa62f2cf83c3e8e942da4beb189ecb8cbb0ccb6ab39aff> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/aa425590d3a3ae8287fa62f2cf83c3e8e942da4beb189ecb8cbb0ccb6ab39aff> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Inge".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/aa425590d3a3ae8287fa62f2cf83c3e8e942da4beb189ecb8cbb0ccb6ab39aff> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/fe5c6d59b4c3e0d9b749d15abfbf900f28f97a66385ecfd633dc33d1122a3e55> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/fe5c6d59b4c3e0d9b749d15abfbf900f28f97a66385ecfd633dc33d1122a3e55> a person:Person.
           <http://data.lblod.info/id/personen/fe5c6d59b4c3e0d9b749d15abfbf900f28f97a66385ecfd633dc33d1122a3e55> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/fe5c6d59b4c3e0d9b749d15abfbf900f28f97a66385ecfd633dc33d1122a3e55> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Laurence".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/fe5c6d59b4c3e0d9b749d15abfbf900f28f97a66385ecfd633dc33d1122a3e55> [] [].
          }
        }
     # finished voornamen-update-16185-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:15+00:00