# started voornamen-update-26834-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:42+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/16b4f282-d1b9-48b8-9e9e-cc56a83e18b7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/16b4f282-d1b9-48b8-9e9e-cc56a83e18b7> a person:Person.
           <http://data.lblod.info/id/personen/16b4f282-d1b9-48b8-9e9e-cc56a83e18b7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/16b4f282-d1b9-48b8-9e9e-cc56a83e18b7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Fleur".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/16b4f282-d1b9-48b8-9e9e-cc56a83e18b7> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/301e002c-c737-465f-aaef-a7ed260c2e05> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/301e002c-c737-465f-aaef-a7ed260c2e05> a person:Person.
           <http://data.lblod.info/id/personen/301e002c-c737-465f-aaef-a7ed260c2e05> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/301e002c-c737-465f-aaef-a7ed260c2e05> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Mátyás".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/301e002c-c737-465f-aaef-a7ed260c2e05> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/9c10a255-bf99-46a8-aba5-7847306b3887> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9c10a255-bf99-46a8-aba5-7847306b3887> a person:Person.
           <http://data.lblod.info/id/personen/9c10a255-bf99-46a8-aba5-7847306b3887> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9c10a255-bf99-46a8-aba5-7847306b3887> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Tom".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9c10a255-bf99-46a8-aba5-7847306b3887> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/9a6557df-1a0c-4efe-9d4f-78e995e8d342> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9a6557df-1a0c-4efe-9d4f-78e995e8d342> a person:Person.
           <http://data.lblod.info/id/personen/9a6557df-1a0c-4efe-9d4f-78e995e8d342> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9a6557df-1a0c-4efe-9d4f-78e995e8d342> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Femke".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9a6557df-1a0c-4efe-9d4f-78e995e8d342> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/93c9e007-183d-4929-a31c-3ccfd883de5b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/93c9e007-183d-4929-a31c-3ccfd883de5b> a person:Person.
           <http://data.lblod.info/id/personen/93c9e007-183d-4929-a31c-3ccfd883de5b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/93c9e007-183d-4929-a31c-3ccfd883de5b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Anita".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/93c9e007-183d-4929-a31c-3ccfd883de5b> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/8b2e4a18-c6b5-4e29-9989-39b5eb0994fa> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8b2e4a18-c6b5-4e29-9989-39b5eb0994fa> a person:Person.
           <http://data.lblod.info/id/personen/8b2e4a18-c6b5-4e29-9989-39b5eb0994fa> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8b2e4a18-c6b5-4e29-9989-39b5eb0994fa> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Frank".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8b2e4a18-c6b5-4e29-9989-39b5eb0994fa> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/1f24ff33-0f91-49e2-845a-21adec64613c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1f24ff33-0f91-49e2-845a-21adec64613c> a person:Person.
           <http://data.lblod.info/id/personen/1f24ff33-0f91-49e2-845a-21adec64613c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1f24ff33-0f91-49e2-845a-21adec64613c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Petra".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1f24ff33-0f91-49e2-845a-21adec64613c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e74e6b79-989f-4fbc-b893-9b363a0792ac> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e74e6b79-989f-4fbc-b893-9b363a0792ac> a person:Person.
           <http://data.lblod.info/id/personen/e74e6b79-989f-4fbc-b893-9b363a0792ac> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e74e6b79-989f-4fbc-b893-9b363a0792ac> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Amourie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e74e6b79-989f-4fbc-b893-9b363a0792ac> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/7cd8d78a-3bb9-4af9-b051-d0bdbabbf8ed> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7cd8d78a-3bb9-4af9-b051-d0bdbabbf8ed> a person:Person.
           <http://data.lblod.info/id/personen/7cd8d78a-3bb9-4af9-b051-d0bdbabbf8ed> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7cd8d78a-3bb9-4af9-b051-d0bdbabbf8ed> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Gert".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7cd8d78a-3bb9-4af9-b051-d0bdbabbf8ed> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/24d3cc98-a4e0-4606-8649-5bdcca14d856> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/24d3cc98-a4e0-4606-8649-5bdcca14d856> a person:Person.
           <http://data.lblod.info/id/personen/24d3cc98-a4e0-4606-8649-5bdcca14d856> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/24d3cc98-a4e0-4606-8649-5bdcca14d856> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Carl".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/24d3cc98-a4e0-4606-8649-5bdcca14d856> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/3513bcdc-aa16-46f4-b9e8-4b8246118c93> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3513bcdc-aa16-46f4-b9e8-4b8246118c93> a person:Person.
           <http://data.lblod.info/id/personen/3513bcdc-aa16-46f4-b9e8-4b8246118c93> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3513bcdc-aa16-46f4-b9e8-4b8246118c93> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marijke".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3513bcdc-aa16-46f4-b9e8-4b8246118c93> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/b39b54bd-3a33-4fb0-88f3-94634ff59c48> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b39b54bd-3a33-4fb0-88f3-94634ff59c48> a person:Person.
           <http://data.lblod.info/id/personen/b39b54bd-3a33-4fb0-88f3-94634ff59c48> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b39b54bd-3a33-4fb0-88f3-94634ff59c48> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Christine".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b39b54bd-3a33-4fb0-88f3-94634ff59c48> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/9c2594d8-491b-4f3d-ab53-43c7efc8296e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9c2594d8-491b-4f3d-ab53-43c7efc8296e> a person:Person.
           <http://data.lblod.info/id/personen/9c2594d8-491b-4f3d-ab53-43c7efc8296e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9c2594d8-491b-4f3d-ab53-43c7efc8296e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Magda".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9c2594d8-491b-4f3d-ab53-43c7efc8296e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/7026f12f330e6f80670591dfbd8507744808db3987ef72b050368bb4c06587fe> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7026f12f330e6f80670591dfbd8507744808db3987ef72b050368bb4c06587fe> a person:Person.
           <http://data.lblod.info/id/personen/7026f12f330e6f80670591dfbd8507744808db3987ef72b050368bb4c06587fe> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7026f12f330e6f80670591dfbd8507744808db3987ef72b050368bb4c06587fe> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Karel".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7026f12f330e6f80670591dfbd8507744808db3987ef72b050368bb4c06587fe> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/da0980efd5268f92a474cd4e313ebb880f1c62ed611cb88069d57e9237b2eafb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/da0980efd5268f92a474cd4e313ebb880f1c62ed611cb88069d57e9237b2eafb> a person:Person.
           <http://data.lblod.info/id/personen/da0980efd5268f92a474cd4e313ebb880f1c62ed611cb88069d57e9237b2eafb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/da0980efd5268f92a474cd4e313ebb880f1c62ed611cb88069d57e9237b2eafb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Rita".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/da0980efd5268f92a474cd4e313ebb880f1c62ed611cb88069d57e9237b2eafb> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/67773389-70aa-4c4d-8456-05bc13858ae9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/67773389-70aa-4c4d-8456-05bc13858ae9> a person:Person.
           <http://data.lblod.info/id/personen/67773389-70aa-4c4d-8456-05bc13858ae9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/67773389-70aa-4c4d-8456-05bc13858ae9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Godelieve".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/67773389-70aa-4c4d-8456-05bc13858ae9> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/34034ca7-a48b-4f1a-b796-bb3004d28a79> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/34034ca7-a48b-4f1a-b796-bb3004d28a79> a person:Person.
           <http://data.lblod.info/id/personen/34034ca7-a48b-4f1a-b796-bb3004d28a79> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/34034ca7-a48b-4f1a-b796-bb3004d28a79> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Paul".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/34034ca7-a48b-4f1a-b796-bb3004d28a79> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/be4171d6-735f-4475-9fab-a6d47543a29b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/be4171d6-735f-4475-9fab-a6d47543a29b> a person:Person.
           <http://data.lblod.info/id/personen/be4171d6-735f-4475-9fab-a6d47543a29b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/be4171d6-735f-4475-9fab-a6d47543a29b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jan".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/be4171d6-735f-4475-9fab-a6d47543a29b> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/0268b188-1feb-4fe8-a211-9db52091572e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0268b188-1feb-4fe8-a211-9db52091572e> a person:Person.
           <http://data.lblod.info/id/personen/0268b188-1feb-4fe8-a211-9db52091572e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0268b188-1feb-4fe8-a211-9db52091572e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Kevin".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0268b188-1feb-4fe8-a211-9db52091572e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/a91ed289-c0c0-4965-9399-7d73bd5fcc79> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a91ed289-c0c0-4965-9399-7d73bd5fcc79> a person:Person.
           <http://data.lblod.info/id/personen/a91ed289-c0c0-4965-9399-7d73bd5fcc79> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a91ed289-c0c0-4965-9399-7d73bd5fcc79> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Isabelle".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a91ed289-c0c0-4965-9399-7d73bd5fcc79> [] [].
          }
        }
     # finished voornamen-update-26834-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:42+00:00