# started voornamen-update-235-210375db6a6848160966cb7c5aeecf1a8b0d75c2bb93e0f0e03001e306f62438 at 2018-12-27T15:07:12+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/9d098907-aafc-4b8a-b0b5-56d668007084> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9d098907-aafc-4b8a-b0b5-56d668007084> a person:Person.
           <http://data.lblod.info/id/personen/9d098907-aafc-4b8a-b0b5-56d668007084> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9d098907-aafc-4b8a-b0b5-56d668007084> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Erwin".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9d098907-aafc-4b8a-b0b5-56d668007084> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e1bf75a3a14e3b586c447b8f8b0f0687b690b41f9a3952b60c004ce491896d4e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e1bf75a3a14e3b586c447b8f8b0f0687b690b41f9a3952b60c004ce491896d4e> a person:Person.
           <http://data.lblod.info/id/personen/e1bf75a3a14e3b586c447b8f8b0f0687b690b41f9a3952b60c004ce491896d4e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e1bf75a3a14e3b586c447b8f8b0f0687b690b41f9a3952b60c004ce491896d4e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Lili".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e1bf75a3a14e3b586c447b8f8b0f0687b690b41f9a3952b60c004ce491896d4e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/710f72ba574e9a8724720c559360835109feda8f887f0bbc6a7399fa8c85eb64> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/710f72ba574e9a8724720c559360835109feda8f887f0bbc6a7399fa8c85eb64> a person:Person.
           <http://data.lblod.info/id/personen/710f72ba574e9a8724720c559360835109feda8f887f0bbc6a7399fa8c85eb64> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/710f72ba574e9a8724720c559360835109feda8f887f0bbc6a7399fa8c85eb64> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Mieke".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/710f72ba574e9a8724720c559360835109feda8f887f0bbc6a7399fa8c85eb64> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2d6c7f68-faef-4a1e-a540-d67984e10834> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2d6c7f68-faef-4a1e-a540-d67984e10834> a person:Person.
           <http://data.lblod.info/id/personen/2d6c7f68-faef-4a1e-a540-d67984e10834> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2d6c7f68-faef-4a1e-a540-d67984e10834> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Rina".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2d6c7f68-faef-4a1e-a540-d67984e10834> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f7944201-4c77-44f7-ba38-e750fd5ae11f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f7944201-4c77-44f7-ba38-e750fd5ae11f> a person:Person.
           <http://data.lblod.info/id/personen/f7944201-4c77-44f7-ba38-e750fd5ae11f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f7944201-4c77-44f7-ba38-e750fd5ae11f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Anjes".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f7944201-4c77-44f7-ba38-e750fd5ae11f> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/84e2ddb927ad7c16570ab33e00fdf0dbad56ca5f662768f135db043f682557e1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/84e2ddb927ad7c16570ab33e00fdf0dbad56ca5f662768f135db043f682557e1> a person:Person.
           <http://data.lblod.info/id/personen/84e2ddb927ad7c16570ab33e00fdf0dbad56ca5f662768f135db043f682557e1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/84e2ddb927ad7c16570ab33e00fdf0dbad56ca5f662768f135db043f682557e1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Koen".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/84e2ddb927ad7c16570ab33e00fdf0dbad56ca5f662768f135db043f682557e1> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f4c18624422dedbc68b89262e9c9fc9574baefa25ee833ff78ddc0049128f9c2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f4c18624422dedbc68b89262e9c9fc9574baefa25ee833ff78ddc0049128f9c2> a person:Person.
           <http://data.lblod.info/id/personen/f4c18624422dedbc68b89262e9c9fc9574baefa25ee833ff78ddc0049128f9c2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f4c18624422dedbc68b89262e9c9fc9574baefa25ee833ff78ddc0049128f9c2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Wim".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f4c18624422dedbc68b89262e9c9fc9574baefa25ee833ff78ddc0049128f9c2> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/7ff08693-7fe3-4100-8949-1d9ce55c0b7f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7ff08693-7fe3-4100-8949-1d9ce55c0b7f> a person:Person.
           <http://data.lblod.info/id/personen/7ff08693-7fe3-4100-8949-1d9ce55c0b7f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7ff08693-7fe3-4100-8949-1d9ce55c0b7f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Mieke".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7ff08693-7fe3-4100-8949-1d9ce55c0b7f> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ea0ac42d18ad8d4bc4e8e8182856b75d6819b4644a77637ee069d44af10bb303> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ea0ac42d18ad8d4bc4e8e8182856b75d6819b4644a77637ee069d44af10bb303> a person:Person.
           <http://data.lblod.info/id/personen/ea0ac42d18ad8d4bc4e8e8182856b75d6819b4644a77637ee069d44af10bb303> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ea0ac42d18ad8d4bc4e8e8182856b75d6819b4644a77637ee069d44af10bb303> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Koen".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ea0ac42d18ad8d4bc4e8e8182856b75d6819b4644a77637ee069d44af10bb303> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f5e3d2a408e2498a6ad7d6548cce764bdefba801a4d1d4084b28aea8e93a8bed> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f5e3d2a408e2498a6ad7d6548cce764bdefba801a4d1d4084b28aea8e93a8bed> a person:Person.
           <http://data.lblod.info/id/personen/f5e3d2a408e2498a6ad7d6548cce764bdefba801a4d1d4084b28aea8e93a8bed> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f5e3d2a408e2498a6ad7d6548cce764bdefba801a4d1d4084b28aea8e93a8bed> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Bart".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f5e3d2a408e2498a6ad7d6548cce764bdefba801a4d1d4084b28aea8e93a8bed> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/c45effb9-d698-4ab2-a4c9-944b8e6f07dc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c45effb9-d698-4ab2-a4c9-944b8e6f07dc> a person:Person.
           <http://data.lblod.info/id/personen/c45effb9-d698-4ab2-a4c9-944b8e6f07dc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c45effb9-d698-4ab2-a4c9-944b8e6f07dc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Martine".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c45effb9-d698-4ab2-a4c9-944b8e6f07dc> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/3eec4ec39ae02523c86b17c20917a0315d45a1d6946454dc54c1260ec48eeeae> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3eec4ec39ae02523c86b17c20917a0315d45a1d6946454dc54c1260ec48eeeae> a person:Person.
           <http://data.lblod.info/id/personen/3eec4ec39ae02523c86b17c20917a0315d45a1d6946454dc54c1260ec48eeeae> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3eec4ec39ae02523c86b17c20917a0315d45a1d6946454dc54c1260ec48eeeae> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Bart".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3eec4ec39ae02523c86b17c20917a0315d45a1d6946454dc54c1260ec48eeeae> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/bdde6c8c-a791-45bd-b4fb-b8344ab652d6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bdde6c8c-a791-45bd-b4fb-b8344ab652d6> a person:Person.
           <http://data.lblod.info/id/personen/bdde6c8c-a791-45bd-b4fb-b8344ab652d6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bdde6c8c-a791-45bd-b4fb-b8344ab652d6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Yves".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bdde6c8c-a791-45bd-b4fb-b8344ab652d6> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/0b0dcef47f9cad0191fa50571e6619772e94af5b1ddb64fd7ed4e782e9cc1eb4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0b0dcef47f9cad0191fa50571e6619772e94af5b1ddb64fd7ed4e782e9cc1eb4> a person:Person.
           <http://data.lblod.info/id/personen/0b0dcef47f9cad0191fa50571e6619772e94af5b1ddb64fd7ed4e782e9cc1eb4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0b0dcef47f9cad0191fa50571e6619772e94af5b1ddb64fd7ed4e782e9cc1eb4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Willy".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0b0dcef47f9cad0191fa50571e6619772e94af5b1ddb64fd7ed4e782e9cc1eb4> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/c7d0aba6-ff55-4cd1-8071-5ccc35592672> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c7d0aba6-ff55-4cd1-8071-5ccc35592672> a person:Person.
           <http://data.lblod.info/id/personen/c7d0aba6-ff55-4cd1-8071-5ccc35592672> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c7d0aba6-ff55-4cd1-8071-5ccc35592672> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marc".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c7d0aba6-ff55-4cd1-8071-5ccc35592672> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/99cba94e1200fe4947db4e656faf40891f4587f58c9dc0efa82a137ab2d1ae03> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/99cba94e1200fe4947db4e656faf40891f4587f58c9dc0efa82a137ab2d1ae03> a person:Person.
           <http://data.lblod.info/id/personen/99cba94e1200fe4947db4e656faf40891f4587f58c9dc0efa82a137ab2d1ae03> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/99cba94e1200fe4947db4e656faf40891f4587f58c9dc0efa82a137ab2d1ae03> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Wim".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/99cba94e1200fe4947db4e656faf40891f4587f58c9dc0efa82a137ab2d1ae03> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/b21671f459e165cd734313349f52d2da8cb6ff6f373f434f7d139c649f00eaf3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b21671f459e165cd734313349f52d2da8cb6ff6f373f434f7d139c649f00eaf3> a person:Person.
           <http://data.lblod.info/id/personen/b21671f459e165cd734313349f52d2da8cb6ff6f373f434f7d139c649f00eaf3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b21671f459e165cd734313349f52d2da8cb6ff6f373f434f7d139c649f00eaf3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jef".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b21671f459e165cd734313349f52d2da8cb6ff6f373f434f7d139c649f00eaf3> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/88e24c1c53e8c2683ecc4d385a2bc10a7f154dd5e16b7296232e5ec82fa09665> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/88e24c1c53e8c2683ecc4d385a2bc10a7f154dd5e16b7296232e5ec82fa09665> a person:Person.
           <http://data.lblod.info/id/personen/88e24c1c53e8c2683ecc4d385a2bc10a7f154dd5e16b7296232e5ec82fa09665> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/88e24c1c53e8c2683ecc4d385a2bc10a7f154dd5e16b7296232e5ec82fa09665> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Swa".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/88e24c1c53e8c2683ecc4d385a2bc10a7f154dd5e16b7296232e5ec82fa09665> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/6c2c887d61c74db67b86bcbefb09021e35c7522eb670121d22a4364e2acff6c0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6c2c887d61c74db67b86bcbefb09021e35c7522eb670121d22a4364e2acff6c0> a person:Person.
           <http://data.lblod.info/id/personen/6c2c887d61c74db67b86bcbefb09021e35c7522eb670121d22a4364e2acff6c0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6c2c887d61c74db67b86bcbefb09021e35c7522eb670121d22a4364e2acff6c0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Fella".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6c2c887d61c74db67b86bcbefb09021e35c7522eb670121d22a4364e2acff6c0> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f1b04468a62d942a885e00e5054c9c1766498affed962aa27f7546f32eb7ce59> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f1b04468a62d942a885e00e5054c9c1766498affed962aa27f7546f32eb7ce59> a person:Person.
           <http://data.lblod.info/id/personen/f1b04468a62d942a885e00e5054c9c1766498affed962aa27f7546f32eb7ce59> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f1b04468a62d942a885e00e5054c9c1766498affed962aa27f7546f32eb7ce59> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Albert".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f1b04468a62d942a885e00e5054c9c1766498affed962aa27f7546f32eb7ce59> [] [].
          }
        }
     # finished voornamen-update-235-210375db6a6848160966cb7c5aeecf1a8b0d75c2bb93e0f0e03001e306f62438 at 2018-12-27T15:07:12+00:00