# started voornamen-update-25289-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:38+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/7277587a-ad23-419d-aab8-aa85d40d58f8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7277587a-ad23-419d-aab8-aa85d40d58f8> a person:Person.
           <http://data.lblod.info/id/personen/7277587a-ad23-419d-aab8-aa85d40d58f8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7277587a-ad23-419d-aab8-aa85d40d58f8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ann".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7277587a-ad23-419d-aab8-aa85d40d58f8> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/75eb1b29-57a9-445a-a42d-a49d906fce4c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/75eb1b29-57a9-445a-a42d-a49d906fce4c> a person:Person.
           <http://data.lblod.info/id/personen/75eb1b29-57a9-445a-a42d-a49d906fce4c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/75eb1b29-57a9-445a-a42d-a49d906fce4c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Stefanie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/75eb1b29-57a9-445a-a42d-a49d906fce4c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/5a1714ab-edbb-4c58-ba7c-99eda58f5bf4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5a1714ab-edbb-4c58-ba7c-99eda58f5bf4> a person:Person.
           <http://data.lblod.info/id/personen/5a1714ab-edbb-4c58-ba7c-99eda58f5bf4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5a1714ab-edbb-4c58-ba7c-99eda58f5bf4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Albert".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5a1714ab-edbb-4c58-ba7c-99eda58f5bf4> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/63be295a-0567-4eb7-bfe2-ca3c6e66fd5d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/63be295a-0567-4eb7-bfe2-ca3c6e66fd5d> a person:Person.
           <http://data.lblod.info/id/personen/63be295a-0567-4eb7-bfe2-ca3c6e66fd5d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/63be295a-0567-4eb7-bfe2-ca3c6e66fd5d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Freek".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/63be295a-0567-4eb7-bfe2-ca3c6e66fd5d> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ff69319e-1680-41a5-a340-68d8f434c5cc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ff69319e-1680-41a5-a340-68d8f434c5cc> a person:Person.
           <http://data.lblod.info/id/personen/ff69319e-1680-41a5-a340-68d8f434c5cc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ff69319e-1680-41a5-a340-68d8f434c5cc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Hector".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ff69319e-1680-41a5-a340-68d8f434c5cc> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/0093ac10-a33c-475c-824d-2e13bb36b84e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0093ac10-a33c-475c-824d-2e13bb36b84e> a person:Person.
           <http://data.lblod.info/id/personen/0093ac10-a33c-475c-824d-2e13bb36b84e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0093ac10-a33c-475c-824d-2e13bb36b84e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Bart".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0093ac10-a33c-475c-824d-2e13bb36b84e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/b653b98a-4792-49db-ab67-759c304c6ac6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b653b98a-4792-49db-ab67-759c304c6ac6> a person:Person.
           <http://data.lblod.info/id/personen/b653b98a-4792-49db-ab67-759c304c6ac6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b653b98a-4792-49db-ab67-759c304c6ac6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Eric".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b653b98a-4792-49db-ab67-759c304c6ac6> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/beae7bbb-aa35-410b-8836-f7c223ef5720> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/beae7bbb-aa35-410b-8836-f7c223ef5720> a person:Person.
           <http://data.lblod.info/id/personen/beae7bbb-aa35-410b-8836-f7c223ef5720> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/beae7bbb-aa35-410b-8836-f7c223ef5720> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Filip".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/beae7bbb-aa35-410b-8836-f7c223ef5720> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e68f4e2c-f722-4533-8d8b-1be0665e01e2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e68f4e2c-f722-4533-8d8b-1be0665e01e2> a person:Person.
           <http://data.lblod.info/id/personen/e68f4e2c-f722-4533-8d8b-1be0665e01e2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e68f4e2c-f722-4533-8d8b-1be0665e01e2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Peter".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e68f4e2c-f722-4533-8d8b-1be0665e01e2> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f7a7c144-2951-4be7-9ed4-a78987f3ac2f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f7a7c144-2951-4be7-9ed4-a78987f3ac2f> a person:Person.
           <http://data.lblod.info/id/personen/f7a7c144-2951-4be7-9ed4-a78987f3ac2f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f7a7c144-2951-4be7-9ed4-a78987f3ac2f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Isabel".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f7a7c144-2951-4be7-9ed4-a78987f3ac2f> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/8f848777-b641-4789-a040-7069ff6ec118> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8f848777-b641-4789-a040-7069ff6ec118> a person:Person.
           <http://data.lblod.info/id/personen/8f848777-b641-4789-a040-7069ff6ec118> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8f848777-b641-4789-a040-7069ff6ec118> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Nelly".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8f848777-b641-4789-a040-7069ff6ec118> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/0bb1ffd0-cf02-42df-9eeb-f349cf14cdc1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0bb1ffd0-cf02-42df-9eeb-f349cf14cdc1> a person:Person.
           <http://data.lblod.info/id/personen/0bb1ffd0-cf02-42df-9eeb-f349cf14cdc1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0bb1ffd0-cf02-42df-9eeb-f349cf14cdc1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Antoine".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0bb1ffd0-cf02-42df-9eeb-f349cf14cdc1> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/807fdd46-7ed2-4eb8-86bd-b3452956fefb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/807fdd46-7ed2-4eb8-86bd-b3452956fefb> a person:Person.
           <http://data.lblod.info/id/personen/807fdd46-7ed2-4eb8-86bd-b3452956fefb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/807fdd46-7ed2-4eb8-86bd-b3452956fefb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Roos".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/807fdd46-7ed2-4eb8-86bd-b3452956fefb> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/c2da21f59087a1ac22baea3e913880c44f3ed5329a223525bf246aa007d3fa79> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c2da21f59087a1ac22baea3e913880c44f3ed5329a223525bf246aa007d3fa79> a person:Person.
           <http://data.lblod.info/id/personen/c2da21f59087a1ac22baea3e913880c44f3ed5329a223525bf246aa007d3fa79> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c2da21f59087a1ac22baea3e913880c44f3ed5329a223525bf246aa007d3fa79> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Paul".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c2da21f59087a1ac22baea3e913880c44f3ed5329a223525bf246aa007d3fa79> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ad2b9ef503cd7e25964b4e986c7aa579a7d821883f4a925afeac3f9702e6c986> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ad2b9ef503cd7e25964b4e986c7aa579a7d821883f4a925afeac3f9702e6c986> a person:Person.
           <http://data.lblod.info/id/personen/ad2b9ef503cd7e25964b4e986c7aa579a7d821883f4a925afeac3f9702e6c986> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ad2b9ef503cd7e25964b4e986c7aa579a7d821883f4a925afeac3f9702e6c986> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Mia".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ad2b9ef503cd7e25964b4e986c7aa579a7d821883f4a925afeac3f9702e6c986> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/874de950-9f0c-42f6-8e2a-237c2e67b648> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/874de950-9f0c-42f6-8e2a-237c2e67b648> a person:Person.
           <http://data.lblod.info/id/personen/874de950-9f0c-42f6-8e2a-237c2e67b648> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/874de950-9f0c-42f6-8e2a-237c2e67b648> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Theo".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/874de950-9f0c-42f6-8e2a-237c2e67b648> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/3d5fcd77-fde6-43d2-8400-00fdddaa5e71> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3d5fcd77-fde6-43d2-8400-00fdddaa5e71> a person:Person.
           <http://data.lblod.info/id/personen/3d5fcd77-fde6-43d2-8400-00fdddaa5e71> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3d5fcd77-fde6-43d2-8400-00fdddaa5e71> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Sarah".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3d5fcd77-fde6-43d2-8400-00fdddaa5e71> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/42028f7a-8c20-4b8d-b489-60b11f6af7bf> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/42028f7a-8c20-4b8d-b489-60b11f6af7bf> a person:Person.
           <http://data.lblod.info/id/personen/42028f7a-8c20-4b8d-b489-60b11f6af7bf> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/42028f7a-8c20-4b8d-b489-60b11f6af7bf> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "André".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/42028f7a-8c20-4b8d-b489-60b11f6af7bf> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/a47512f4ba8e0e74830e16641cf00f0d51d128b9f092a2913a71703e7264be1c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a47512f4ba8e0e74830e16641cf00f0d51d128b9f092a2913a71703e7264be1c> a person:Person.
           <http://data.lblod.info/id/personen/a47512f4ba8e0e74830e16641cf00f0d51d128b9f092a2913a71703e7264be1c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a47512f4ba8e0e74830e16641cf00f0d51d128b9f092a2913a71703e7264be1c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Wendy".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a47512f4ba8e0e74830e16641cf00f0d51d128b9f092a2913a71703e7264be1c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/71c91272-d292-4432-9641-715060405580> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/71c91272-d292-4432-9641-715060405580> a person:Person.
           <http://data.lblod.info/id/personen/71c91272-d292-4432-9641-715060405580> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/71c91272-d292-4432-9641-715060405580> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Lieve".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/71c91272-d292-4432-9641-715060405580> [] [].
          }
        }
     # finished voornamen-update-25289-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:38+00:00