# started voornamen-update-6762-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:05:52+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/0b7286a4-dcc4-46d8-9870-fa6d731b7f2d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0b7286a4-dcc4-46d8-9870-fa6d731b7f2d> a person:Person.
           <http://data.lblod.info/id/personen/0b7286a4-dcc4-46d8-9870-fa6d731b7f2d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0b7286a4-dcc4-46d8-9870-fa6d731b7f2d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Hilda".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0b7286a4-dcc4-46d8-9870-fa6d731b7f2d> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/4ca750e2-4266-46f0-82b7-7aa3204cc8dd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4ca750e2-4266-46f0-82b7-7aa3204cc8dd> a person:Person.
           <http://data.lblod.info/id/personen/4ca750e2-4266-46f0-82b7-7aa3204cc8dd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4ca750e2-4266-46f0-82b7-7aa3204cc8dd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Thomas".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4ca750e2-4266-46f0-82b7-7aa3204cc8dd> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/6eb18062281e867b4abf769bb320315cfdca5056dd2f387b80286e865923ab6a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6eb18062281e867b4abf769bb320315cfdca5056dd2f387b80286e865923ab6a> a person:Person.
           <http://data.lblod.info/id/personen/6eb18062281e867b4abf769bb320315cfdca5056dd2f387b80286e865923ab6a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6eb18062281e867b4abf769bb320315cfdca5056dd2f387b80286e865923ab6a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Hilda".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6eb18062281e867b4abf769bb320315cfdca5056dd2f387b80286e865923ab6a> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2e11e5bb-a3fa-4a2e-8a9b-26e998f8c94d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2e11e5bb-a3fa-4a2e-8a9b-26e998f8c94d> a person:Person.
           <http://data.lblod.info/id/personen/2e11e5bb-a3fa-4a2e-8a9b-26e998f8c94d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2e11e5bb-a3fa-4a2e-8a9b-26e998f8c94d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Annie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2e11e5bb-a3fa-4a2e-8a9b-26e998f8c94d> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/c15e54b0f2ed271a463ef998d78a563bd942c27bb6fac50b4bfa2d3bb9c26adb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c15e54b0f2ed271a463ef998d78a563bd942c27bb6fac50b4bfa2d3bb9c26adb> a person:Person.
           <http://data.lblod.info/id/personen/c15e54b0f2ed271a463ef998d78a563bd942c27bb6fac50b4bfa2d3bb9c26adb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c15e54b0f2ed271a463ef998d78a563bd942c27bb6fac50b4bfa2d3bb9c26adb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marie-Ange".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c15e54b0f2ed271a463ef998d78a563bd942c27bb6fac50b4bfa2d3bb9c26adb> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/39a832ad-2365-48b5-b591-4b292434e82a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/39a832ad-2365-48b5-b591-4b292434e82a> a person:Person.
           <http://data.lblod.info/id/personen/39a832ad-2365-48b5-b591-4b292434e82a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/39a832ad-2365-48b5-b591-4b292434e82a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jos".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/39a832ad-2365-48b5-b591-4b292434e82a> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/96cced996b5638a3b065c304255d669ba471a56a8598a8daa41329dfaf19f976> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/96cced996b5638a3b065c304255d669ba471a56a8598a8daa41329dfaf19f976> a person:Person.
           <http://data.lblod.info/id/personen/96cced996b5638a3b065c304255d669ba471a56a8598a8daa41329dfaf19f976> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/96cced996b5638a3b065c304255d669ba471a56a8598a8daa41329dfaf19f976> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Nand".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/96cced996b5638a3b065c304255d669ba471a56a8598a8daa41329dfaf19f976> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f6481cbe110d56deffe5ffac623b10cde778b3cf7903a6f9f97835b52b1a74a5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f6481cbe110d56deffe5ffac623b10cde778b3cf7903a6f9f97835b52b1a74a5> a person:Person.
           <http://data.lblod.info/id/personen/f6481cbe110d56deffe5ffac623b10cde778b3cf7903a6f9f97835b52b1a74a5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f6481cbe110d56deffe5ffac623b10cde778b3cf7903a6f9f97835b52b1a74a5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Piet".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f6481cbe110d56deffe5ffac623b10cde778b3cf7903a6f9f97835b52b1a74a5> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/aa3c86a9-2027-4f18-9ebd-cd139a15bf02> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/aa3c86a9-2027-4f18-9ebd-cd139a15bf02> a person:Person.
           <http://data.lblod.info/id/personen/aa3c86a9-2027-4f18-9ebd-cd139a15bf02> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/aa3c86a9-2027-4f18-9ebd-cd139a15bf02> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Irina".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/aa3c86a9-2027-4f18-9ebd-cd139a15bf02> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/559cc1823516519c06d9270d1e7186b495acece3a2b9aeaddd0fb11689704a45> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/559cc1823516519c06d9270d1e7186b495acece3a2b9aeaddd0fb11689704a45> a person:Person.
           <http://data.lblod.info/id/personen/559cc1823516519c06d9270d1e7186b495acece3a2b9aeaddd0fb11689704a45> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/559cc1823516519c06d9270d1e7186b495acece3a2b9aeaddd0fb11689704a45> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jasmine".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/559cc1823516519c06d9270d1e7186b495acece3a2b9aeaddd0fb11689704a45> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/6a130cb29599f4c5220e9b6f856df904eb97aa781867eeed6cb8c25df0e7c263> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6a130cb29599f4c5220e9b6f856df904eb97aa781867eeed6cb8c25df0e7c263> a person:Person.
           <http://data.lblod.info/id/personen/6a130cb29599f4c5220e9b6f856df904eb97aa781867eeed6cb8c25df0e7c263> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6a130cb29599f4c5220e9b6f856df904eb97aa781867eeed6cb8c25df0e7c263> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Lies".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6a130cb29599f4c5220e9b6f856df904eb97aa781867eeed6cb8c25df0e7c263> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/a6100724-302e-4fbe-bd76-be9df2996ff4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a6100724-302e-4fbe-bd76-be9df2996ff4> a person:Person.
           <http://data.lblod.info/id/personen/a6100724-302e-4fbe-bd76-be9df2996ff4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a6100724-302e-4fbe-bd76-be9df2996ff4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Wouter".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a6100724-302e-4fbe-bd76-be9df2996ff4> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e8f80eea-01ce-4353-9f72-d2e0c8775f54> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e8f80eea-01ce-4353-9f72-d2e0c8775f54> a person:Person.
           <http://data.lblod.info/id/personen/e8f80eea-01ce-4353-9f72-d2e0c8775f54> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e8f80eea-01ce-4353-9f72-d2e0c8775f54> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ruben".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e8f80eea-01ce-4353-9f72-d2e0c8775f54> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/adb7f9a4-07b3-46ae-af30-e8440d0597fb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/adb7f9a4-07b3-46ae-af30-e8440d0597fb> a person:Person.
           <http://data.lblod.info/id/personen/adb7f9a4-07b3-46ae-af30-e8440d0597fb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/adb7f9a4-07b3-46ae-af30-e8440d0597fb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Josée".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/adb7f9a4-07b3-46ae-af30-e8440d0597fb> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/b11228c261122a616f98df10353eb9df1da6716eda89514b302a406eaf4a3f2e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b11228c261122a616f98df10353eb9df1da6716eda89514b302a406eaf4a3f2e> a person:Person.
           <http://data.lblod.info/id/personen/b11228c261122a616f98df10353eb9df1da6716eda89514b302a406eaf4a3f2e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b11228c261122a616f98df10353eb9df1da6716eda89514b302a406eaf4a3f2e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Piet".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b11228c261122a616f98df10353eb9df1da6716eda89514b302a406eaf4a3f2e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/97cdd00c8d9b55b1c3d5ae3f24f324a049dc6d8bc20f8435032343e72981b4ee> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/97cdd00c8d9b55b1c3d5ae3f24f324a049dc6d8bc20f8435032343e72981b4ee> a person:Person.
           <http://data.lblod.info/id/personen/97cdd00c8d9b55b1c3d5ae3f24f324a049dc6d8bc20f8435032343e72981b4ee> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/97cdd00c8d9b55b1c3d5ae3f24f324a049dc6d8bc20f8435032343e72981b4ee> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Anne".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/97cdd00c8d9b55b1c3d5ae3f24f324a049dc6d8bc20f8435032343e72981b4ee> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/aca3678a10fd8ef170ccf03ea9a0a0acb57c6aaa428c483113271e06a922f32e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/aca3678a10fd8ef170ccf03ea9a0a0acb57c6aaa428c483113271e06a922f32e> a person:Person.
           <http://data.lblod.info/id/personen/aca3678a10fd8ef170ccf03ea9a0a0acb57c6aaa428c483113271e06a922f32e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/aca3678a10fd8ef170ccf03ea9a0a0acb57c6aaa428c483113271e06a922f32e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Frans".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/aca3678a10fd8ef170ccf03ea9a0a0acb57c6aaa428c483113271e06a922f32e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/66f8b3da749bccc2ab6034c2d3a8cc6f29e7f595079b24f0b86bf22860abed5c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/66f8b3da749bccc2ab6034c2d3a8cc6f29e7f595079b24f0b86bf22860abed5c> a person:Person.
           <http://data.lblod.info/id/personen/66f8b3da749bccc2ab6034c2d3a8cc6f29e7f595079b24f0b86bf22860abed5c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/66f8b3da749bccc2ab6034c2d3a8cc6f29e7f595079b24f0b86bf22860abed5c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Annemarie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/66f8b3da749bccc2ab6034c2d3a8cc6f29e7f595079b24f0b86bf22860abed5c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/755dde5a1b12e9dde3f3aacd86970fc486b8742c7d3f45e533662fd8fe636d96> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/755dde5a1b12e9dde3f3aacd86970fc486b8742c7d3f45e533662fd8fe636d96> a person:Person.
           <http://data.lblod.info/id/personen/755dde5a1b12e9dde3f3aacd86970fc486b8742c7d3f45e533662fd8fe636d96> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/755dde5a1b12e9dde3f3aacd86970fc486b8742c7d3f45e533662fd8fe636d96> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jacqueline".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/755dde5a1b12e9dde3f3aacd86970fc486b8742c7d3f45e533662fd8fe636d96> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/df3a07697d1e7e3b046416403db85fd0598c4796d13c62127656d167a36d79d2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/df3a07697d1e7e3b046416403db85fd0598c4796d13c62127656d167a36d79d2> a person:Person.
           <http://data.lblod.info/id/personen/df3a07697d1e7e3b046416403db85fd0598c4796d13c62127656d167a36d79d2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/df3a07697d1e7e3b046416403db85fd0598c4796d13c62127656d167a36d79d2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jan".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/df3a07697d1e7e3b046416403db85fd0598c4796d13c62127656d167a36d79d2> [] [].
          }
        }
     # finished voornamen-update-6762-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:05:52+00:00