# started voornamen-update-10403-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:01+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/5e344eab-fd96-48c7-8230-ade3241c9bbe> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5e344eab-fd96-48c7-8230-ade3241c9bbe> a person:Person.
           <http://data.lblod.info/id/personen/5e344eab-fd96-48c7-8230-ade3241c9bbe> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5e344eab-fd96-48c7-8230-ade3241c9bbe> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Sven".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5e344eab-fd96-48c7-8230-ade3241c9bbe> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/c8bdc6e0-5a8e-4c69-b9a5-cbfbd81fd56d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c8bdc6e0-5a8e-4c69-b9a5-cbfbd81fd56d> a person:Person.
           <http://data.lblod.info/id/personen/c8bdc6e0-5a8e-4c69-b9a5-cbfbd81fd56d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c8bdc6e0-5a8e-4c69-b9a5-cbfbd81fd56d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jan".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c8bdc6e0-5a8e-4c69-b9a5-cbfbd81fd56d> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e05d9774-4ef5-4c57-8366-34ed3b105c4a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e05d9774-4ef5-4c57-8366-34ed3b105c4a> a person:Person.
           <http://data.lblod.info/id/personen/e05d9774-4ef5-4c57-8366-34ed3b105c4a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e05d9774-4ef5-4c57-8366-34ed3b105c4a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marc".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e05d9774-4ef5-4c57-8366-34ed3b105c4a> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/42aa85240f6b8bd7e81d0717b6c25776e2c333ce1b4591aa1a58ea1c29552468> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/42aa85240f6b8bd7e81d0717b6c25776e2c333ce1b4591aa1a58ea1c29552468> a person:Person.
           <http://data.lblod.info/id/personen/42aa85240f6b8bd7e81d0717b6c25776e2c333ce1b4591aa1a58ea1c29552468> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/42aa85240f6b8bd7e81d0717b6c25776e2c333ce1b4591aa1a58ea1c29552468> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Sien".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/42aa85240f6b8bd7e81d0717b6c25776e2c333ce1b4591aa1a58ea1c29552468> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e6862186-e382-4f47-a464-59425b47c645> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e6862186-e382-4f47-a464-59425b47c645> a person:Person.
           <http://data.lblod.info/id/personen/e6862186-e382-4f47-a464-59425b47c645> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e6862186-e382-4f47-a464-59425b47c645> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Walter".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e6862186-e382-4f47-a464-59425b47c645> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/4d5b80e9-c06f-421c-a07f-0999723e5a5c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4d5b80e9-c06f-421c-a07f-0999723e5a5c> a person:Person.
           <http://data.lblod.info/id/personen/4d5b80e9-c06f-421c-a07f-0999723e5a5c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4d5b80e9-c06f-421c-a07f-0999723e5a5c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Bruno".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4d5b80e9-c06f-421c-a07f-0999723e5a5c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ed04c829-37e6-4de9-a957-2f0fa6032657> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ed04c829-37e6-4de9-a957-2f0fa6032657> a person:Person.
           <http://data.lblod.info/id/personen/ed04c829-37e6-4de9-a957-2f0fa6032657> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ed04c829-37e6-4de9-a957-2f0fa6032657> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Lydy".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ed04c829-37e6-4de9-a957-2f0fa6032657> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e9a8ac8b-e507-4b48-9c09-87a48639f938> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e9a8ac8b-e507-4b48-9c09-87a48639f938> a person:Person.
           <http://data.lblod.info/id/personen/e9a8ac8b-e507-4b48-9c09-87a48639f938> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e9a8ac8b-e507-4b48-9c09-87a48639f938> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Miguel".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e9a8ac8b-e507-4b48-9c09-87a48639f938> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/74c2ed8b-b6ea-49df-9666-79760236c150> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/74c2ed8b-b6ea-49df-9666-79760236c150> a person:Person.
           <http://data.lblod.info/id/personen/74c2ed8b-b6ea-49df-9666-79760236c150> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/74c2ed8b-b6ea-49df-9666-79760236c150> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Nathalie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/74c2ed8b-b6ea-49df-9666-79760236c150> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e5d4a7c3f0f36aea5fc43e78656f2c2e254465833c25fc2e0002ae688d93d726> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e5d4a7c3f0f36aea5fc43e78656f2c2e254465833c25fc2e0002ae688d93d726> a person:Person.
           <http://data.lblod.info/id/personen/e5d4a7c3f0f36aea5fc43e78656f2c2e254465833c25fc2e0002ae688d93d726> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e5d4a7c3f0f36aea5fc43e78656f2c2e254465833c25fc2e0002ae688d93d726> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Franske".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e5d4a7c3f0f36aea5fc43e78656f2c2e254465833c25fc2e0002ae688d93d726> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/b268475d284124cdeb49438e78f7ab5651b8203d326a9096bba797f2aff5a35f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b268475d284124cdeb49438e78f7ab5651b8203d326a9096bba797f2aff5a35f> a person:Person.
           <http://data.lblod.info/id/personen/b268475d284124cdeb49438e78f7ab5651b8203d326a9096bba797f2aff5a35f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b268475d284124cdeb49438e78f7ab5651b8203d326a9096bba797f2aff5a35f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Nicky".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b268475d284124cdeb49438e78f7ab5651b8203d326a9096bba797f2aff5a35f> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/05d0ffe93aa976bcd46efdf5693ef300404ae3e219a5c2ddf140b757780f30f8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/05d0ffe93aa976bcd46efdf5693ef300404ae3e219a5c2ddf140b757780f30f8> a person:Person.
           <http://data.lblod.info/id/personen/05d0ffe93aa976bcd46efdf5693ef300404ae3e219a5c2ddf140b757780f30f8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/05d0ffe93aa976bcd46efdf5693ef300404ae3e219a5c2ddf140b757780f30f8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Fred".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/05d0ffe93aa976bcd46efdf5693ef300404ae3e219a5c2ddf140b757780f30f8> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/bba2fc8675fc511fee29bae96c5612a1bbe1d7a6121efc8f2e25eeabf7f442f0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bba2fc8675fc511fee29bae96c5612a1bbe1d7a6121efc8f2e25eeabf7f442f0> a person:Person.
           <http://data.lblod.info/id/personen/bba2fc8675fc511fee29bae96c5612a1bbe1d7a6121efc8f2e25eeabf7f442f0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bba2fc8675fc511fee29bae96c5612a1bbe1d7a6121efc8f2e25eeabf7f442f0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Christel".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bba2fc8675fc511fee29bae96c5612a1bbe1d7a6121efc8f2e25eeabf7f442f0> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/426e4ff8-f0cb-462a-82fb-531131d6c6ec> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/426e4ff8-f0cb-462a-82fb-531131d6c6ec> a person:Person.
           <http://data.lblod.info/id/personen/426e4ff8-f0cb-462a-82fb-531131d6c6ec> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/426e4ff8-f0cb-462a-82fb-531131d6c6ec> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Thomas".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/426e4ff8-f0cb-462a-82fb-531131d6c6ec> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/4ab37abe-fb50-4c6e-8ff3-3f8509be453b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4ab37abe-fb50-4c6e-8ff3-3f8509be453b> a person:Person.
           <http://data.lblod.info/id/personen/4ab37abe-fb50-4c6e-8ff3-3f8509be453b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4ab37abe-fb50-4c6e-8ff3-3f8509be453b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Leen".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4ab37abe-fb50-4c6e-8ff3-3f8509be453b> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/3d5cb8c6-b0a6-487c-90a6-4181798bdb5f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3d5cb8c6-b0a6-487c-90a6-4181798bdb5f> a person:Person.
           <http://data.lblod.info/id/personen/3d5cb8c6-b0a6-487c-90a6-4181798bdb5f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3d5cb8c6-b0a6-487c-90a6-4181798bdb5f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Dick".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3d5cb8c6-b0a6-487c-90a6-4181798bdb5f> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/8ca15e3474470001cb4e6aba94b08809fe12b80f4f0607c3d2c19ec6f8850011> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8ca15e3474470001cb4e6aba94b08809fe12b80f4f0607c3d2c19ec6f8850011> a person:Person.
           <http://data.lblod.info/id/personen/8ca15e3474470001cb4e6aba94b08809fe12b80f4f0607c3d2c19ec6f8850011> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8ca15e3474470001cb4e6aba94b08809fe12b80f4f0607c3d2c19ec6f8850011> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Lies".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8ca15e3474470001cb4e6aba94b08809fe12b80f4f0607c3d2c19ec6f8850011> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/a5694152-e61e-46eb-aa5d-03de1ffe51ff> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a5694152-e61e-46eb-aa5d-03de1ffe51ff> a person:Person.
           <http://data.lblod.info/id/personen/a5694152-e61e-46eb-aa5d-03de1ffe51ff> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a5694152-e61e-46eb-aa5d-03de1ffe51ff> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jolien".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a5694152-e61e-46eb-aa5d-03de1ffe51ff> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/15e7b4a2-7958-45dc-8607-964dead06716> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/15e7b4a2-7958-45dc-8607-964dead06716> a person:Person.
           <http://data.lblod.info/id/personen/15e7b4a2-7958-45dc-8607-964dead06716> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/15e7b4a2-7958-45dc-8607-964dead06716> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Damien".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/15e7b4a2-7958-45dc-8607-964dead06716> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/d010f079-2798-4174-b737-fdd6e7037545> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d010f079-2798-4174-b737-fdd6e7037545> a person:Person.
           <http://data.lblod.info/id/personen/d010f079-2798-4174-b737-fdd6e7037545> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d010f079-2798-4174-b737-fdd6e7037545> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Annick".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d010f079-2798-4174-b737-fdd6e7037545> [] [].
          }
        }
     # finished voornamen-update-10403-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:01+00:00