# started voornamen-update-5087-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:05:48+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f083e45fd40e1b431e4cdbd8eda44a19620eb85621368dea992a2d8bea4d826d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f083e45fd40e1b431e4cdbd8eda44a19620eb85621368dea992a2d8bea4d826d> a person:Person.
           <http://data.lblod.info/id/personen/f083e45fd40e1b431e4cdbd8eda44a19620eb85621368dea992a2d8bea4d826d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f083e45fd40e1b431e4cdbd8eda44a19620eb85621368dea992a2d8bea4d826d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Annie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f083e45fd40e1b431e4cdbd8eda44a19620eb85621368dea992a2d8bea4d826d> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/334b3018-4ee9-430b-a335-43f25c5929ec> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/334b3018-4ee9-430b-a335-43f25c5929ec> a person:Person.
           <http://data.lblod.info/id/personen/334b3018-4ee9-430b-a335-43f25c5929ec> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/334b3018-4ee9-430b-a335-43f25c5929ec> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marc".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/334b3018-4ee9-430b-a335-43f25c5929ec> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ac4de2360d695eb7ff6f82fed3c7027612e8c77f76c8678c61e23d69999621a7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ac4de2360d695eb7ff6f82fed3c7027612e8c77f76c8678c61e23d69999621a7> a person:Person.
           <http://data.lblod.info/id/personen/ac4de2360d695eb7ff6f82fed3c7027612e8c77f76c8678c61e23d69999621a7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ac4de2360d695eb7ff6f82fed3c7027612e8c77f76c8678c61e23d69999621a7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Sofie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ac4de2360d695eb7ff6f82fed3c7027612e8c77f76c8678c61e23d69999621a7> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/60efff8f-7025-4ba3-8b86-cb1bf07268cb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/60efff8f-7025-4ba3-8b86-cb1bf07268cb> a person:Person.
           <http://data.lblod.info/id/personen/60efff8f-7025-4ba3-8b86-cb1bf07268cb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/60efff8f-7025-4ba3-8b86-cb1bf07268cb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Gerda".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/60efff8f-7025-4ba3-8b86-cb1bf07268cb> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/3570bf9a8c9eced3bb3e80b558dd4d3f5a9fcec69a5a3af96dac44fd8b31c419> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3570bf9a8c9eced3bb3e80b558dd4d3f5a9fcec69a5a3af96dac44fd8b31c419> a person:Person.
           <http://data.lblod.info/id/personen/3570bf9a8c9eced3bb3e80b558dd4d3f5a9fcec69a5a3af96dac44fd8b31c419> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3570bf9a8c9eced3bb3e80b558dd4d3f5a9fcec69a5a3af96dac44fd8b31c419> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Lutgarde".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3570bf9a8c9eced3bb3e80b558dd4d3f5a9fcec69a5a3af96dac44fd8b31c419> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/604732f8-8626-41d1-ada8-241999340622> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/604732f8-8626-41d1-ada8-241999340622> a person:Person.
           <http://data.lblod.info/id/personen/604732f8-8626-41d1-ada8-241999340622> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/604732f8-8626-41d1-ada8-241999340622> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Benny".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/604732f8-8626-41d1-ada8-241999340622> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/d8074971-5b50-4664-96b6-a5af9a97804d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d8074971-5b50-4664-96b6-a5af9a97804d> a person:Person.
           <http://data.lblod.info/id/personen/d8074971-5b50-4664-96b6-a5af9a97804d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d8074971-5b50-4664-96b6-a5af9a97804d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Linda".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d8074971-5b50-4664-96b6-a5af9a97804d> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/0a655c46-3aff-420f-aeaf-7b64bad49841> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0a655c46-3aff-420f-aeaf-7b64bad49841> a person:Person.
           <http://data.lblod.info/id/personen/0a655c46-3aff-420f-aeaf-7b64bad49841> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0a655c46-3aff-420f-aeaf-7b64bad49841> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marina".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0a655c46-3aff-420f-aeaf-7b64bad49841> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/3344ee72-d878-432d-aecb-40e0a212fe71> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3344ee72-d878-432d-aecb-40e0a212fe71> a person:Person.
           <http://data.lblod.info/id/personen/3344ee72-d878-432d-aecb-40e0a212fe71> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3344ee72-d878-432d-aecb-40e0a212fe71> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Celle".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3344ee72-d878-432d-aecb-40e0a212fe71> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/8c334486-e1bf-4786-ad1f-563ee7f85293> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8c334486-e1bf-4786-ad1f-563ee7f85293> a person:Person.
           <http://data.lblod.info/id/personen/8c334486-e1bf-4786-ad1f-563ee7f85293> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8c334486-e1bf-4786-ad1f-563ee7f85293> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Bruno".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8c334486-e1bf-4786-ad1f-563ee7f85293> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/9577030f-4a76-4ad0-bfcd-6854f4118fc1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9577030f-4a76-4ad0-bfcd-6854f4118fc1> a person:Person.
           <http://data.lblod.info/id/personen/9577030f-4a76-4ad0-bfcd-6854f4118fc1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9577030f-4a76-4ad0-bfcd-6854f4118fc1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Dirk".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9577030f-4a76-4ad0-bfcd-6854f4118fc1> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/78df358b882bcf5fc2cfa29a803c5009a00c27ed4e1046cdd3939831807524e8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/78df358b882bcf5fc2cfa29a803c5009a00c27ed4e1046cdd3939831807524e8> a person:Person.
           <http://data.lblod.info/id/personen/78df358b882bcf5fc2cfa29a803c5009a00c27ed4e1046cdd3939831807524e8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/78df358b882bcf5fc2cfa29a803c5009a00c27ed4e1046cdd3939831807524e8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Geert".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/78df358b882bcf5fc2cfa29a803c5009a00c27ed4e1046cdd3939831807524e8> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/7116586c-98fe-42e1-8b13-1c0a0995f0bc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7116586c-98fe-42e1-8b13-1c0a0995f0bc> a person:Person.
           <http://data.lblod.info/id/personen/7116586c-98fe-42e1-8b13-1c0a0995f0bc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7116586c-98fe-42e1-8b13-1c0a0995f0bc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Gilbert".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7116586c-98fe-42e1-8b13-1c0a0995f0bc> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/d83af656f3051626a690f63c75ad4e6c46183f0b5b572ac06e974b1f6cc5864e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d83af656f3051626a690f63c75ad4e6c46183f0b5b572ac06e974b1f6cc5864e> a person:Person.
           <http://data.lblod.info/id/personen/d83af656f3051626a690f63c75ad4e6c46183f0b5b572ac06e974b1f6cc5864e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d83af656f3051626a690f63c75ad4e6c46183f0b5b572ac06e974b1f6cc5864e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jozef".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d83af656f3051626a690f63c75ad4e6c46183f0b5b572ac06e974b1f6cc5864e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/093e3435-7657-4a49-b84b-b368cc63a6f0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/093e3435-7657-4a49-b84b-b368cc63a6f0> a person:Person.
           <http://data.lblod.info/id/personen/093e3435-7657-4a49-b84b-b368cc63a6f0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/093e3435-7657-4a49-b84b-b368cc63a6f0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Kurt Fonne".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/093e3435-7657-4a49-b84b-b368cc63a6f0> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/aeed23ab-c782-4fe7-940d-99cf26f93b7a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/aeed23ab-c782-4fe7-940d-99cf26f93b7a> a person:Person.
           <http://data.lblod.info/id/personen/aeed23ab-c782-4fe7-940d-99cf26f93b7a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/aeed23ab-c782-4fe7-940d-99cf26f93b7a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marc".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/aeed23ab-c782-4fe7-940d-99cf26f93b7a> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/9e296eb2-70ff-468a-8e55-62e1d8f00252> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9e296eb2-70ff-468a-8e55-62e1d8f00252> a person:Person.
           <http://data.lblod.info/id/personen/9e296eb2-70ff-468a-8e55-62e1d8f00252> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9e296eb2-70ff-468a-8e55-62e1d8f00252> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Gisèle".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9e296eb2-70ff-468a-8e55-62e1d8f00252> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/76c1ab02-18cc-4ec6-ad23-c10fa3ca9447> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/76c1ab02-18cc-4ec6-ad23-c10fa3ca9447> a person:Person.
           <http://data.lblod.info/id/personen/76c1ab02-18cc-4ec6-ad23-c10fa3ca9447> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/76c1ab02-18cc-4ec6-ad23-c10fa3ca9447> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Adam".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/76c1ab02-18cc-4ec6-ad23-c10fa3ca9447> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/dea785e3-fd08-4340-88c5-38b7a7fe0b95> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/dea785e3-fd08-4340-88c5-38b7a7fe0b95> a person:Person.
           <http://data.lblod.info/id/personen/dea785e3-fd08-4340-88c5-38b7a7fe0b95> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/dea785e3-fd08-4340-88c5-38b7a7fe0b95> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jari".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/dea785e3-fd08-4340-88c5-38b7a7fe0b95> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f77725e7-14ef-47a5-bba8-711e44271ddc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f77725e7-14ef-47a5-bba8-711e44271ddc> a person:Person.
           <http://data.lblod.info/id/personen/f77725e7-14ef-47a5-bba8-711e44271ddc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f77725e7-14ef-47a5-bba8-711e44271ddc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Kurt".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f77725e7-14ef-47a5-bba8-711e44271ddc> [] [].
          }
        }
     # finished voornamen-update-5087-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:05:48+00:00