# started voornamen-update-28563-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:46+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/6c84b744-8fca-49b6-977f-006cbf1aa3f3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6c84b744-8fca-49b6-977f-006cbf1aa3f3> a person:Person.
           <http://data.lblod.info/id/personen/6c84b744-8fca-49b6-977f-006cbf1aa3f3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6c84b744-8fca-49b6-977f-006cbf1aa3f3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Johan".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6c84b744-8fca-49b6-977f-006cbf1aa3f3> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f127d98a-eed0-4897-89c7-e47227b422e7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f127d98a-eed0-4897-89c7-e47227b422e7> a person:Person.
           <http://data.lblod.info/id/personen/f127d98a-eed0-4897-89c7-e47227b422e7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f127d98a-eed0-4897-89c7-e47227b422e7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Martine".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f127d98a-eed0-4897-89c7-e47227b422e7> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/b09a982c46db6cab2de3122dfedb3e9c6bb81e4e7afa6401d7d6845e76813784> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b09a982c46db6cab2de3122dfedb3e9c6bb81e4e7afa6401d7d6845e76813784> a person:Person.
           <http://data.lblod.info/id/personen/b09a982c46db6cab2de3122dfedb3e9c6bb81e4e7afa6401d7d6845e76813784> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b09a982c46db6cab2de3122dfedb3e9c6bb81e4e7afa6401d7d6845e76813784> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Inge".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b09a982c46db6cab2de3122dfedb3e9c6bb81e4e7afa6401d7d6845e76813784> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/574c2381-f357-4a8f-97aa-cda2c03e3adf> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/574c2381-f357-4a8f-97aa-cda2c03e3adf> a person:Person.
           <http://data.lblod.info/id/personen/574c2381-f357-4a8f-97aa-cda2c03e3adf> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/574c2381-f357-4a8f-97aa-cda2c03e3adf> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Tibbe".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/574c2381-f357-4a8f-97aa-cda2c03e3adf> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2eb4424f-0b52-4acf-afa6-e2ff22f597b8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2eb4424f-0b52-4acf-afa6-e2ff22f597b8> a person:Person.
           <http://data.lblod.info/id/personen/2eb4424f-0b52-4acf-afa6-e2ff22f597b8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2eb4424f-0b52-4acf-afa6-e2ff22f597b8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Katrien".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2eb4424f-0b52-4acf-afa6-e2ff22f597b8> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/4d44e8ac-4cf7-4844-8e61-4489f9cdcee5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4d44e8ac-4cf7-4844-8e61-4489f9cdcee5> a person:Person.
           <http://data.lblod.info/id/personen/4d44e8ac-4cf7-4844-8e61-4489f9cdcee5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4d44e8ac-4cf7-4844-8e61-4489f9cdcee5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Véronique".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4d44e8ac-4cf7-4844-8e61-4489f9cdcee5> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2941961a-5d52-4346-b424-2696a1c4ea97> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2941961a-5d52-4346-b424-2696a1c4ea97> a person:Person.
           <http://data.lblod.info/id/personen/2941961a-5d52-4346-b424-2696a1c4ea97> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2941961a-5d52-4346-b424-2696a1c4ea97> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Katleen".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2941961a-5d52-4346-b424-2696a1c4ea97> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/45a2a454-8df2-4923-8352-3908900bdc4b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/45a2a454-8df2-4923-8352-3908900bdc4b> a person:Person.
           <http://data.lblod.info/id/personen/45a2a454-8df2-4923-8352-3908900bdc4b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/45a2a454-8df2-4923-8352-3908900bdc4b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Annelie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/45a2a454-8df2-4923-8352-3908900bdc4b> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/b6bd095a-3852-4d21-b79e-4525634e5f7c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b6bd095a-3852-4d21-b79e-4525634e5f7c> a person:Person.
           <http://data.lblod.info/id/personen/b6bd095a-3852-4d21-b79e-4525634e5f7c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b6bd095a-3852-4d21-b79e-4525634e5f7c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Peter".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b6bd095a-3852-4d21-b79e-4525634e5f7c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/04a5f85f-3cc2-4224-8106-cc5c16f3be2a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/04a5f85f-3cc2-4224-8106-cc5c16f3be2a> a person:Person.
           <http://data.lblod.info/id/personen/04a5f85f-3cc2-4224-8106-cc5c16f3be2a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/04a5f85f-3cc2-4224-8106-cc5c16f3be2a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Seline".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/04a5f85f-3cc2-4224-8106-cc5c16f3be2a> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/70e6df8cf695fa5470f59ed71a7c958735356269fe83a59e0a779086f383aafe> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/70e6df8cf695fa5470f59ed71a7c958735356269fe83a59e0a779086f383aafe> a person:Person.
           <http://data.lblod.info/id/personen/70e6df8cf695fa5470f59ed71a7c958735356269fe83a59e0a779086f383aafe> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/70e6df8cf695fa5470f59ed71a7c958735356269fe83a59e0a779086f383aafe> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Vince".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/70e6df8cf695fa5470f59ed71a7c958735356269fe83a59e0a779086f383aafe> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f4d8b96d-78ba-412d-8b8b-b5ead6c61ebc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f4d8b96d-78ba-412d-8b8b-b5ead6c61ebc> a person:Person.
           <http://data.lblod.info/id/personen/f4d8b96d-78ba-412d-8b8b-b5ead6c61ebc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f4d8b96d-78ba-412d-8b8b-b5ead6c61ebc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Chris".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f4d8b96d-78ba-412d-8b8b-b5ead6c61ebc> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/c22dfff6caea760d97bb1e5b54df530c3e2c8f3a97d559910a6a665d104616ed> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c22dfff6caea760d97bb1e5b54df530c3e2c8f3a97d559910a6a665d104616ed> a person:Person.
           <http://data.lblod.info/id/personen/c22dfff6caea760d97bb1e5b54df530c3e2c8f3a97d559910a6a665d104616ed> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c22dfff6caea760d97bb1e5b54df530c3e2c8f3a97d559910a6a665d104616ed> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Peter".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c22dfff6caea760d97bb1e5b54df530c3e2c8f3a97d559910a6a665d104616ed> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/02ffe64e8a353ddc1ec684d022459097243400ab483108049680e5f19423c76e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/02ffe64e8a353ddc1ec684d022459097243400ab483108049680e5f19423c76e> a person:Person.
           <http://data.lblod.info/id/personen/02ffe64e8a353ddc1ec684d022459097243400ab483108049680e5f19423c76e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/02ffe64e8a353ddc1ec684d022459097243400ab483108049680e5f19423c76e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Filip".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/02ffe64e8a353ddc1ec684d022459097243400ab483108049680e5f19423c76e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/c2a461e21ee86be5bb073c9b13fdfdc251d5fd0689d1d5564ea0668fef3ede9b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c2a461e21ee86be5bb073c9b13fdfdc251d5fd0689d1d5564ea0668fef3ede9b> a person:Person.
           <http://data.lblod.info/id/personen/c2a461e21ee86be5bb073c9b13fdfdc251d5fd0689d1d5564ea0668fef3ede9b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c2a461e21ee86be5bb073c9b13fdfdc251d5fd0689d1d5564ea0668fef3ede9b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Walter".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c2a461e21ee86be5bb073c9b13fdfdc251d5fd0689d1d5564ea0668fef3ede9b> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/6b04eb50-268c-46c2-9202-fcf005c62263> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6b04eb50-268c-46c2-9202-fcf005c62263> a person:Person.
           <http://data.lblod.info/id/personen/6b04eb50-268c-46c2-9202-fcf005c62263> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6b04eb50-268c-46c2-9202-fcf005c62263> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Lien".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6b04eb50-268c-46c2-9202-fcf005c62263> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/44f03c996e74139d2a732c09f6bdf3310d12ef10f3bd9360e08b637f42ef82dc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/44f03c996e74139d2a732c09f6bdf3310d12ef10f3bd9360e08b637f42ef82dc> a person:Person.
           <http://data.lblod.info/id/personen/44f03c996e74139d2a732c09f6bdf3310d12ef10f3bd9360e08b637f42ef82dc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/44f03c996e74139d2a732c09f6bdf3310d12ef10f3bd9360e08b637f42ef82dc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ann".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/44f03c996e74139d2a732c09f6bdf3310d12ef10f3bd9360e08b637f42ef82dc> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e1e9468c-5aa9-4007-ab89-9d7656e3c73f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e1e9468c-5aa9-4007-ab89-9d7656e3c73f> a person:Person.
           <http://data.lblod.info/id/personen/e1e9468c-5aa9-4007-ab89-9d7656e3c73f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e1e9468c-5aa9-4007-ab89-9d7656e3c73f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Chris".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e1e9468c-5aa9-4007-ab89-9d7656e3c73f> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/a2afafcd69ef6aafcf6e07cdb89aa23311c5c8c4e4932e88c675c7d51f0b528c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a2afafcd69ef6aafcf6e07cdb89aa23311c5c8c4e4932e88c675c7d51f0b528c> a person:Person.
           <http://data.lblod.info/id/personen/a2afafcd69ef6aafcf6e07cdb89aa23311c5c8c4e4932e88c675c7d51f0b528c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a2afafcd69ef6aafcf6e07cdb89aa23311c5c8c4e4932e88c675c7d51f0b528c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Christel".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a2afafcd69ef6aafcf6e07cdb89aa23311c5c8c4e4932e88c675c7d51f0b528c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/4ab1a3d7-7336-4f1a-bc21-8c7d91970265> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4ab1a3d7-7336-4f1a-bc21-8c7d91970265> a person:Person.
           <http://data.lblod.info/id/personen/4ab1a3d7-7336-4f1a-bc21-8c7d91970265> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4ab1a3d7-7336-4f1a-bc21-8c7d91970265> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Luc".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4ab1a3d7-7336-4f1a-bc21-8c7d91970265> [] [].
          }
        }
     # finished voornamen-update-28563-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:46+00:00