# started voornamen-update-1240-210375db6a6848160966cb7c5aeecf1a8b0d75c2bb93e0f0e03001e306f62438 at 2018-12-27T15:07:15+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/abc2a540-c6ca-4221-81c0-80e9f3ca59a5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/abc2a540-c6ca-4221-81c0-80e9f3ca59a5> a person:Person.
           <http://data.lblod.info/id/personen/abc2a540-c6ca-4221-81c0-80e9f3ca59a5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/abc2a540-c6ca-4221-81c0-80e9f3ca59a5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Andrès".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/abc2a540-c6ca-4221-81c0-80e9f3ca59a5> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/061a0891-a3a9-468b-81bc-f21e7c82e7d2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/061a0891-a3a9-468b-81bc-f21e7c82e7d2> a person:Person.
           <http://data.lblod.info/id/personen/061a0891-a3a9-468b-81bc-f21e7c82e7d2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/061a0891-a3a9-468b-81bc-f21e7c82e7d2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Els".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/061a0891-a3a9-468b-81bc-f21e7c82e7d2> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/506aa4bc-8af3-426c-9f83-8c593e2e51d7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/506aa4bc-8af3-426c-9f83-8c593e2e51d7> a person:Person.
           <http://data.lblod.info/id/personen/506aa4bc-8af3-426c-9f83-8c593e2e51d7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/506aa4bc-8af3-426c-9f83-8c593e2e51d7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Rita".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/506aa4bc-8af3-426c-9f83-8c593e2e51d7> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/671fd96e-5183-4e3c-afd4-ab97c112418c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/671fd96e-5183-4e3c-afd4-ab97c112418c> a person:Person.
           <http://data.lblod.info/id/personen/671fd96e-5183-4e3c-afd4-ab97c112418c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/671fd96e-5183-4e3c-afd4-ab97c112418c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ruben".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/671fd96e-5183-4e3c-afd4-ab97c112418c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/bc638536-6302-45ce-a6b2-b84efdd80cac> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bc638536-6302-45ce-a6b2-b84efdd80cac> a person:Person.
           <http://data.lblod.info/id/personen/bc638536-6302-45ce-a6b2-b84efdd80cac> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bc638536-6302-45ce-a6b2-b84efdd80cac> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Stefan".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bc638536-6302-45ce-a6b2-b84efdd80cac> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/279f3fc7-372e-4aec-bfc4-12a0d62a87d1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/279f3fc7-372e-4aec-bfc4-12a0d62a87d1> a person:Person.
           <http://data.lblod.info/id/personen/279f3fc7-372e-4aec-bfc4-12a0d62a87d1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/279f3fc7-372e-4aec-bfc4-12a0d62a87d1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Peter".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/279f3fc7-372e-4aec-bfc4-12a0d62a87d1> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/098849ba4af32ee589029ff409d1589f319cdedfc09d720dec335521c6e8276e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/098849ba4af32ee589029ff409d1589f319cdedfc09d720dec335521c6e8276e> a person:Person.
           <http://data.lblod.info/id/personen/098849ba4af32ee589029ff409d1589f319cdedfc09d720dec335521c6e8276e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/098849ba4af32ee589029ff409d1589f319cdedfc09d720dec335521c6e8276e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ann".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/098849ba4af32ee589029ff409d1589f319cdedfc09d720dec335521c6e8276e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2c0461f44126226db0fa6772e1c6bb30ec6ae3c18b7768e78140ec9109a3a5f1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2c0461f44126226db0fa6772e1c6bb30ec6ae3c18b7768e78140ec9109a3a5f1> a person:Person.
           <http://data.lblod.info/id/personen/2c0461f44126226db0fa6772e1c6bb30ec6ae3c18b7768e78140ec9109a3a5f1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2c0461f44126226db0fa6772e1c6bb30ec6ae3c18b7768e78140ec9109a3a5f1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Katleen".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2c0461f44126226db0fa6772e1c6bb30ec6ae3c18b7768e78140ec9109a3a5f1> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/489c2e15111f1d13ae0219403aaa64fe280b6481d97396faa0e9b8cf5c79f924> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/489c2e15111f1d13ae0219403aaa64fe280b6481d97396faa0e9b8cf5c79f924> a person:Person.
           <http://data.lblod.info/id/personen/489c2e15111f1d13ae0219403aaa64fe280b6481d97396faa0e9b8cf5c79f924> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/489c2e15111f1d13ae0219403aaa64fe280b6481d97396faa0e9b8cf5c79f924> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Bart".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/489c2e15111f1d13ae0219403aaa64fe280b6481d97396faa0e9b8cf5c79f924> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/bd63f15c11b1dae672fa8d5c9dd00afedbcf72165ad4e54724df3e0cd050bda2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bd63f15c11b1dae672fa8d5c9dd00afedbcf72165ad4e54724df3e0cd050bda2> a person:Person.
           <http://data.lblod.info/id/personen/bd63f15c11b1dae672fa8d5c9dd00afedbcf72165ad4e54724df3e0cd050bda2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bd63f15c11b1dae672fa8d5c9dd00afedbcf72165ad4e54724df3e0cd050bda2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Anne".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bd63f15c11b1dae672fa8d5c9dd00afedbcf72165ad4e54724df3e0cd050bda2> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/bffe4fc3d40621d56d0f0ca7954714d2d2756d30bd50eea865ddef2efcb190dd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bffe4fc3d40621d56d0f0ca7954714d2d2756d30bd50eea865ddef2efcb190dd> a person:Person.
           <http://data.lblod.info/id/personen/bffe4fc3d40621d56d0f0ca7954714d2d2756d30bd50eea865ddef2efcb190dd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bffe4fc3d40621d56d0f0ca7954714d2d2756d30bd50eea865ddef2efcb190dd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Giani".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bffe4fc3d40621d56d0f0ca7954714d2d2756d30bd50eea865ddef2efcb190dd> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/04eb0b69a6c8f6bc17a7f2943d18209c448807b1ef7be0153a7b80822d2c06a0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/04eb0b69a6c8f6bc17a7f2943d18209c448807b1ef7be0153a7b80822d2c06a0> a person:Person.
           <http://data.lblod.info/id/personen/04eb0b69a6c8f6bc17a7f2943d18209c448807b1ef7be0153a7b80822d2c06a0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/04eb0b69a6c8f6bc17a7f2943d18209c448807b1ef7be0153a7b80822d2c06a0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jo".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/04eb0b69a6c8f6bc17a7f2943d18209c448807b1ef7be0153a7b80822d2c06a0> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/a5ab2c85-ba0b-4ae3-a8e0-16b74de41bda> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a5ab2c85-ba0b-4ae3-a8e0-16b74de41bda> a person:Person.
           <http://data.lblod.info/id/personen/a5ab2c85-ba0b-4ae3-a8e0-16b74de41bda> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a5ab2c85-ba0b-4ae3-a8e0-16b74de41bda> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Katrien".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a5ab2c85-ba0b-4ae3-a8e0-16b74de41bda> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/3304c5f3-42ce-4466-8e9e-461d31bd83a9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3304c5f3-42ce-4466-8e9e-461d31bd83a9> a person:Person.
           <http://data.lblod.info/id/personen/3304c5f3-42ce-4466-8e9e-461d31bd83a9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3304c5f3-42ce-4466-8e9e-461d31bd83a9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Bruno".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3304c5f3-42ce-4466-8e9e-461d31bd83a9> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/77846ea6-217f-4d21-84b5-9f88406b5205> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/77846ea6-217f-4d21-84b5-9f88406b5205> a person:Person.
           <http://data.lblod.info/id/personen/77846ea6-217f-4d21-84b5-9f88406b5205> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/77846ea6-217f-4d21-84b5-9f88406b5205> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Nele".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/77846ea6-217f-4d21-84b5-9f88406b5205> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ba89b364-e858-4a01-9cbf-07d30e501df3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ba89b364-e858-4a01-9cbf-07d30e501df3> a person:Person.
           <http://data.lblod.info/id/personen/ba89b364-e858-4a01-9cbf-07d30e501df3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ba89b364-e858-4a01-9cbf-07d30e501df3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Vie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ba89b364-e858-4a01-9cbf-07d30e501df3> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/d61e063f-d7ea-4a8c-b6b7-ebf7afa338a7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d61e063f-d7ea-4a8c-b6b7-ebf7afa338a7> a person:Person.
           <http://data.lblod.info/id/personen/d61e063f-d7ea-4a8c-b6b7-ebf7afa338a7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d61e063f-d7ea-4a8c-b6b7-ebf7afa338a7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Lieven".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d61e063f-d7ea-4a8c-b6b7-ebf7afa338a7> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/3e23e451-5be8-49e4-b1ef-3e30d22257dc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3e23e451-5be8-49e4-b1ef-3e30d22257dc> a person:Person.
           <http://data.lblod.info/id/personen/3e23e451-5be8-49e4-b1ef-3e30d22257dc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3e23e451-5be8-49e4-b1ef-3e30d22257dc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Katelijne".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3e23e451-5be8-49e4-b1ef-3e30d22257dc> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/1e6d0936-2e87-4ed6-b5b8-9f53a42e37e3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1e6d0936-2e87-4ed6-b5b8-9f53a42e37e3> a person:Person.
           <http://data.lblod.info/id/personen/1e6d0936-2e87-4ed6-b5b8-9f53a42e37e3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1e6d0936-2e87-4ed6-b5b8-9f53a42e37e3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Raf".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1e6d0936-2e87-4ed6-b5b8-9f53a42e37e3> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/49e1fa99-8ee2-4bfc-bf95-d40708796ea0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/49e1fa99-8ee2-4bfc-bf95-d40708796ea0> a person:Person.
           <http://data.lblod.info/id/personen/49e1fa99-8ee2-4bfc-bf95-d40708796ea0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/49e1fa99-8ee2-4bfc-bf95-d40708796ea0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marij".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/49e1fa99-8ee2-4bfc-bf95-d40708796ea0> [] [].
          }
        }
     # finished voornamen-update-1240-210375db6a6848160966cb7c5aeecf1a8b0d75c2bb93e0f0e03001e306f62438 at 2018-12-27T15:07:15+00:00