# started voornamen-update-24697-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:37+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/d715108d-fb87-4d2a-9e30-803102ee01f8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d715108d-fb87-4d2a-9e30-803102ee01f8> a person:Person.
           <http://data.lblod.info/id/personen/d715108d-fb87-4d2a-9e30-803102ee01f8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d715108d-fb87-4d2a-9e30-803102ee01f8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Lieve".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d715108d-fb87-4d2a-9e30-803102ee01f8> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ab78f32b-d6d4-4269-a448-ff3dbdfb73e7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ab78f32b-d6d4-4269-a448-ff3dbdfb73e7> a person:Person.
           <http://data.lblod.info/id/personen/ab78f32b-d6d4-4269-a448-ff3dbdfb73e7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ab78f32b-d6d4-4269-a448-ff3dbdfb73e7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Guy".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ab78f32b-d6d4-4269-a448-ff3dbdfb73e7> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e4dab959-58ef-425b-9770-25338dbfcfda> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e4dab959-58ef-425b-9770-25338dbfcfda> a person:Person.
           <http://data.lblod.info/id/personen/e4dab959-58ef-425b-9770-25338dbfcfda> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e4dab959-58ef-425b-9770-25338dbfcfda> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Gudrun".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e4dab959-58ef-425b-9770-25338dbfcfda> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/85d2dba0-9bd7-4827-a797-b02f384fcc15> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/85d2dba0-9bd7-4827-a797-b02f384fcc15> a person:Person.
           <http://data.lblod.info/id/personen/85d2dba0-9bd7-4827-a797-b02f384fcc15> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/85d2dba0-9bd7-4827-a797-b02f384fcc15> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Bernard".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/85d2dba0-9bd7-4827-a797-b02f384fcc15> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/a63c9eed-140b-41ed-889c-e77a24d13122> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a63c9eed-140b-41ed-889c-e77a24d13122> a person:Person.
           <http://data.lblod.info/id/personen/a63c9eed-140b-41ed-889c-e77a24d13122> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a63c9eed-140b-41ed-889c-e77a24d13122> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ingeborg".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a63c9eed-140b-41ed-889c-e77a24d13122> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/7af189b8-8b9c-4747-8109-d0c914bb0774> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7af189b8-8b9c-4747-8109-d0c914bb0774> a person:Person.
           <http://data.lblod.info/id/personen/7af189b8-8b9c-4747-8109-d0c914bb0774> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7af189b8-8b9c-4747-8109-d0c914bb0774> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Pascal".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7af189b8-8b9c-4747-8109-d0c914bb0774> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/8943d8d557536ba73869ec30c1826429754f1feb0d1ddcbb0d64e56cb7d471f3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8943d8d557536ba73869ec30c1826429754f1feb0d1ddcbb0d64e56cb7d471f3> a person:Person.
           <http://data.lblod.info/id/personen/8943d8d557536ba73869ec30c1826429754f1feb0d1ddcbb0d64e56cb7d471f3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8943d8d557536ba73869ec30c1826429754f1feb0d1ddcbb0d64e56cb7d471f3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Lieve".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8943d8d557536ba73869ec30c1826429754f1feb0d1ddcbb0d64e56cb7d471f3> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/6043fe3d-eea7-4f12-aafb-671c85156838> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6043fe3d-eea7-4f12-aafb-671c85156838> a person:Person.
           <http://data.lblod.info/id/personen/6043fe3d-eea7-4f12-aafb-671c85156838> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6043fe3d-eea7-4f12-aafb-671c85156838> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Steven".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6043fe3d-eea7-4f12-aafb-671c85156838> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/cc1b45ea-6fa8-4eba-b80a-0fd78cec9d5b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cc1b45ea-6fa8-4eba-b80a-0fd78cec9d5b> a person:Person.
           <http://data.lblod.info/id/personen/cc1b45ea-6fa8-4eba-b80a-0fd78cec9d5b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cc1b45ea-6fa8-4eba-b80a-0fd78cec9d5b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Winnie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cc1b45ea-6fa8-4eba-b80a-0fd78cec9d5b> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e238d722-023b-44a3-abc0-9e28e4784149> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e238d722-023b-44a3-abc0-9e28e4784149> a person:Person.
           <http://data.lblod.info/id/personen/e238d722-023b-44a3-abc0-9e28e4784149> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e238d722-023b-44a3-abc0-9e28e4784149> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ingeborg".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e238d722-023b-44a3-abc0-9e28e4784149> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/9bfe3382-d45c-4adb-bfd3-0fa138ca8553> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9bfe3382-d45c-4adb-bfd3-0fa138ca8553> a person:Person.
           <http://data.lblod.info/id/personen/9bfe3382-d45c-4adb-bfd3-0fa138ca8553> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9bfe3382-d45c-4adb-bfd3-0fa138ca8553> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Rudi".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9bfe3382-d45c-4adb-bfd3-0fa138ca8553> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2c3d3b24-f770-4f81-9971-c852c7d511dc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2c3d3b24-f770-4f81-9971-c852c7d511dc> a person:Person.
           <http://data.lblod.info/id/personen/2c3d3b24-f770-4f81-9971-c852c7d511dc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2c3d3b24-f770-4f81-9971-c852c7d511dc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Lieve".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2c3d3b24-f770-4f81-9971-c852c7d511dc> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ecef25cb-1ae3-4e6c-875c-9afa7f42e3aa> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ecef25cb-1ae3-4e6c-875c-9afa7f42e3aa> a person:Person.
           <http://data.lblod.info/id/personen/ecef25cb-1ae3-4e6c-875c-9afa7f42e3aa> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ecef25cb-1ae3-4e6c-875c-9afa7f42e3aa> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Raf".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ecef25cb-1ae3-4e6c-875c-9afa7f42e3aa> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/7b5dc5f0-afed-463c-894f-6110c5745164> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7b5dc5f0-afed-463c-894f-6110c5745164> a person:Person.
           <http://data.lblod.info/id/personen/7b5dc5f0-afed-463c-894f-6110c5745164> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7b5dc5f0-afed-463c-894f-6110c5745164> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Rita".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7b5dc5f0-afed-463c-894f-6110c5745164> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/bade6d32-c398-457d-96ca-ddf8a3f3caf9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bade6d32-c398-457d-96ca-ddf8a3f3caf9> a person:Person.
           <http://data.lblod.info/id/personen/bade6d32-c398-457d-96ca-ddf8a3f3caf9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bade6d32-c398-457d-96ca-ddf8a3f3caf9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Eddy".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bade6d32-c398-457d-96ca-ddf8a3f3caf9> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/a522a4ecd1ac65395dd959c745d65ea2d3d72e2a9c6ac62e3faa19857a63c7ed> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a522a4ecd1ac65395dd959c745d65ea2d3d72e2a9c6ac62e3faa19857a63c7ed> a person:Person.
           <http://data.lblod.info/id/personen/a522a4ecd1ac65395dd959c745d65ea2d3d72e2a9c6ac62e3faa19857a63c7ed> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a522a4ecd1ac65395dd959c745d65ea2d3d72e2a9c6ac62e3faa19857a63c7ed> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Sai".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a522a4ecd1ac65395dd959c745d65ea2d3d72e2a9c6ac62e3faa19857a63c7ed> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/b21c3881-1618-4614-94af-494beed4fd92> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b21c3881-1618-4614-94af-494beed4fd92> a person:Person.
           <http://data.lblod.info/id/personen/b21c3881-1618-4614-94af-494beed4fd92> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b21c3881-1618-4614-94af-494beed4fd92> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Simonne".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b21c3881-1618-4614-94af-494beed4fd92> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/b32b4115-c839-40a0-beb1-9a647bb1f4e8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b32b4115-c839-40a0-beb1-9a647bb1f4e8> a person:Person.
           <http://data.lblod.info/id/personen/b32b4115-c839-40a0-beb1-9a647bb1f4e8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b32b4115-c839-40a0-beb1-9a647bb1f4e8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Guido".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b32b4115-c839-40a0-beb1-9a647bb1f4e8> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/9b002244-b72e-4590-871f-5bf531ebab46> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9b002244-b72e-4590-871f-5bf531ebab46> a person:Person.
           <http://data.lblod.info/id/personen/9b002244-b72e-4590-871f-5bf531ebab46> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9b002244-b72e-4590-871f-5bf531ebab46> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Joris".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9b002244-b72e-4590-871f-5bf531ebab46> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/a2b1838f-96c6-4c9e-a662-79e33ed0c02c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a2b1838f-96c6-4c9e-a662-79e33ed0c02c> a person:Person.
           <http://data.lblod.info/id/personen/a2b1838f-96c6-4c9e-a662-79e33ed0c02c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a2b1838f-96c6-4c9e-a662-79e33ed0c02c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Katinka".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a2b1838f-96c6-4c9e-a662-79e33ed0c02c> [] [].
          }
        }
     # finished voornamen-update-24697-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:37+00:00