# started voornamen-update-32914-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:58+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/099b9e6f-5ec3-4e0c-b8b9-9c249895935c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/099b9e6f-5ec3-4e0c-b8b9-9c249895935c> a person:Person.
           <http://data.lblod.info/id/personen/099b9e6f-5ec3-4e0c-b8b9-9c249895935c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/099b9e6f-5ec3-4e0c-b8b9-9c249895935c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Heidi".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/099b9e6f-5ec3-4e0c-b8b9-9c249895935c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/54d6a71f-3449-4ee7-9c6d-91efabe7476f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/54d6a71f-3449-4ee7-9c6d-91efabe7476f> a person:Person.
           <http://data.lblod.info/id/personen/54d6a71f-3449-4ee7-9c6d-91efabe7476f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/54d6a71f-3449-4ee7-9c6d-91efabe7476f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Axel".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/54d6a71f-3449-4ee7-9c6d-91efabe7476f> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/0c87fb0e-622c-4ad3-9cd6-cadac5ce32fc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0c87fb0e-622c-4ad3-9cd6-cadac5ce32fc> a person:Person.
           <http://data.lblod.info/id/personen/0c87fb0e-622c-4ad3-9cd6-cadac5ce32fc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0c87fb0e-622c-4ad3-9cd6-cadac5ce32fc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Chelsea".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0c87fb0e-622c-4ad3-9cd6-cadac5ce32fc> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/53dbf1bd-9c72-43eb-a87c-82a189f2ffbe> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/53dbf1bd-9c72-43eb-a87c-82a189f2ffbe> a person:Person.
           <http://data.lblod.info/id/personen/53dbf1bd-9c72-43eb-a87c-82a189f2ffbe> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/53dbf1bd-9c72-43eb-a87c-82a189f2ffbe> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Brenda".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/53dbf1bd-9c72-43eb-a87c-82a189f2ffbe> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/888985c8-5fa4-420d-b618-cd3b78c89ae7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/888985c8-5fa4-420d-b618-cd3b78c89ae7> a person:Person.
           <http://data.lblod.info/id/personen/888985c8-5fa4-420d-b618-cd3b78c89ae7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/888985c8-5fa4-420d-b618-cd3b78c89ae7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ghislain".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/888985c8-5fa4-420d-b618-cd3b78c89ae7> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/9b24a76a-1cbf-4dd8-beb4-c59b630257ca> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9b24a76a-1cbf-4dd8-beb4-c59b630257ca> a person:Person.
           <http://data.lblod.info/id/personen/9b24a76a-1cbf-4dd8-beb4-c59b630257ca> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9b24a76a-1cbf-4dd8-beb4-c59b630257ca> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Monique".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9b24a76a-1cbf-4dd8-beb4-c59b630257ca> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/81406b84-316e-4c25-89cf-160f049db627> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/81406b84-316e-4c25-89cf-160f049db627> a person:Person.
           <http://data.lblod.info/id/personen/81406b84-316e-4c25-89cf-160f049db627> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/81406b84-316e-4c25-89cf-160f049db627> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Johan".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/81406b84-316e-4c25-89cf-160f049db627> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f36965eda7452b80e72c3508e948e3bb7d1e4f06c358697c0ff5460f09ea11a4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f36965eda7452b80e72c3508e948e3bb7d1e4f06c358697c0ff5460f09ea11a4> a person:Person.
           <http://data.lblod.info/id/personen/f36965eda7452b80e72c3508e948e3bb7d1e4f06c358697c0ff5460f09ea11a4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f36965eda7452b80e72c3508e948e3bb7d1e4f06c358697c0ff5460f09ea11a4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Andre".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f36965eda7452b80e72c3508e948e3bb7d1e4f06c358697c0ff5460f09ea11a4> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/9a485257-c68d-472d-8a13-47aa68d5c7c6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9a485257-c68d-472d-8a13-47aa68d5c7c6> a person:Person.
           <http://data.lblod.info/id/personen/9a485257-c68d-472d-8a13-47aa68d5c7c6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9a485257-c68d-472d-8a13-47aa68d5c7c6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Hanne".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9a485257-c68d-472d-8a13-47aa68d5c7c6> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2830320e-4d92-4436-a4b5-d0483c0f3c5a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2830320e-4d92-4436-a4b5-d0483c0f3c5a> a person:Person.
           <http://data.lblod.info/id/personen/2830320e-4d92-4436-a4b5-d0483c0f3c5a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2830320e-4d92-4436-a4b5-d0483c0f3c5a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Elke".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2830320e-4d92-4436-a4b5-d0483c0f3c5a> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/07d164a1-a8e0-4b1e-9c43-4f2678c6cd5a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/07d164a1-a8e0-4b1e-9c43-4f2678c6cd5a> a person:Person.
           <http://data.lblod.info/id/personen/07d164a1-a8e0-4b1e-9c43-4f2678c6cd5a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/07d164a1-a8e0-4b1e-9c43-4f2678c6cd5a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Peter".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/07d164a1-a8e0-4b1e-9c43-4f2678c6cd5a> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/808d0d51-e7b1-4d01-8aa7-484dc9ed7e1b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/808d0d51-e7b1-4d01-8aa7-484dc9ed7e1b> a person:Person.
           <http://data.lblod.info/id/personen/808d0d51-e7b1-4d01-8aa7-484dc9ed7e1b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/808d0d51-e7b1-4d01-8aa7-484dc9ed7e1b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Astrid".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/808d0d51-e7b1-4d01-8aa7-484dc9ed7e1b> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/63a3a437a5c1ffe3307c95ec627bed9c6ab28675298551a3740b833530ff3902> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/63a3a437a5c1ffe3307c95ec627bed9c6ab28675298551a3740b833530ff3902> a person:Person.
           <http://data.lblod.info/id/personen/63a3a437a5c1ffe3307c95ec627bed9c6ab28675298551a3740b833530ff3902> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/63a3a437a5c1ffe3307c95ec627bed9c6ab28675298551a3740b833530ff3902> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Anita".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/63a3a437a5c1ffe3307c95ec627bed9c6ab28675298551a3740b833530ff3902> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/80788546-5589-4740-87a1-c59822c1083b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/80788546-5589-4740-87a1-c59822c1083b> a person:Person.
           <http://data.lblod.info/id/personen/80788546-5589-4740-87a1-c59822c1083b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/80788546-5589-4740-87a1-c59822c1083b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Miet".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/80788546-5589-4740-87a1-c59822c1083b> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/c5fa8529-157d-4f53-b557-6fdbeb9b298c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c5fa8529-157d-4f53-b557-6fdbeb9b298c> a person:Person.
           <http://data.lblod.info/id/personen/c5fa8529-157d-4f53-b557-6fdbeb9b298c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c5fa8529-157d-4f53-b557-6fdbeb9b298c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Katrien".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c5fa8529-157d-4f53-b557-6fdbeb9b298c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/3f476c28-9a6e-46a1-8682-b865388e49aa> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3f476c28-9a6e-46a1-8682-b865388e49aa> a person:Person.
           <http://data.lblod.info/id/personen/3f476c28-9a6e-46a1-8682-b865388e49aa> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3f476c28-9a6e-46a1-8682-b865388e49aa> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Roland".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3f476c28-9a6e-46a1-8682-b865388e49aa> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/3f439e18-ee5e-453e-992d-8c0118b0b9d0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3f439e18-ee5e-453e-992d-8c0118b0b9d0> a person:Person.
           <http://data.lblod.info/id/personen/3f439e18-ee5e-453e-992d-8c0118b0b9d0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3f439e18-ee5e-453e-992d-8c0118b0b9d0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Andy".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3f439e18-ee5e-453e-992d-8c0118b0b9d0> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/7a525bbd95aa50d913cfab2a745fc2e2509bff6a5aba752bd0dbef08018600b8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7a525bbd95aa50d913cfab2a745fc2e2509bff6a5aba752bd0dbef08018600b8> a person:Person.
           <http://data.lblod.info/id/personen/7a525bbd95aa50d913cfab2a745fc2e2509bff6a5aba752bd0dbef08018600b8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7a525bbd95aa50d913cfab2a745fc2e2509bff6a5aba752bd0dbef08018600b8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jaak".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7a525bbd95aa50d913cfab2a745fc2e2509bff6a5aba752bd0dbef08018600b8> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e3111ac1-0f74-406d-b02f-9f9345fea038> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e3111ac1-0f74-406d-b02f-9f9345fea038> a person:Person.
           <http://data.lblod.info/id/personen/e3111ac1-0f74-406d-b02f-9f9345fea038> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e3111ac1-0f74-406d-b02f-9f9345fea038> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Cynthia".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e3111ac1-0f74-406d-b02f-9f9345fea038> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/7b41fd77-f37a-4ab0-878a-748ccedff2ab> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7b41fd77-f37a-4ab0-878a-748ccedff2ab> a person:Person.
           <http://data.lblod.info/id/personen/7b41fd77-f37a-4ab0-878a-748ccedff2ab> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7b41fd77-f37a-4ab0-878a-748ccedff2ab> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Frank".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7b41fd77-f37a-4ab0-878a-748ccedff2ab> [] [].
          }
        }
     # finished voornamen-update-32914-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:58+00:00