# started voornamen-update-10923-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:02+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f75a07c3-6176-4640-8c80-178cca5e71c8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f75a07c3-6176-4640-8c80-178cca5e71c8> a person:Person.
           <http://data.lblod.info/id/personen/f75a07c3-6176-4640-8c80-178cca5e71c8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f75a07c3-6176-4640-8c80-178cca5e71c8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jimmy".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f75a07c3-6176-4640-8c80-178cca5e71c8> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ddeacbff-40d1-4ba7-a257-f24411217818> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ddeacbff-40d1-4ba7-a257-f24411217818> a person:Person.
           <http://data.lblod.info/id/personen/ddeacbff-40d1-4ba7-a257-f24411217818> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ddeacbff-40d1-4ba7-a257-f24411217818> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Els".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ddeacbff-40d1-4ba7-a257-f24411217818> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/82a62acd-6dfb-4fa3-9d03-09c4839b4d32> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/82a62acd-6dfb-4fa3-9d03-09c4839b4d32> a person:Person.
           <http://data.lblod.info/id/personen/82a62acd-6dfb-4fa3-9d03-09c4839b4d32> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/82a62acd-6dfb-4fa3-9d03-09c4839b4d32> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Koen".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/82a62acd-6dfb-4fa3-9d03-09c4839b4d32> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/cabbef95-6413-4804-a8c7-75adda51c09f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cabbef95-6413-4804-a8c7-75adda51c09f> a person:Person.
           <http://data.lblod.info/id/personen/cabbef95-6413-4804-a8c7-75adda51c09f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cabbef95-6413-4804-a8c7-75adda51c09f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ilsy".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cabbef95-6413-4804-a8c7-75adda51c09f> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/5a63c201-b079-451f-83b9-f9fc30e0ed3b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5a63c201-b079-451f-83b9-f9fc30e0ed3b> a person:Person.
           <http://data.lblod.info/id/personen/5a63c201-b079-451f-83b9-f9fc30e0ed3b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5a63c201-b079-451f-83b9-f9fc30e0ed3b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Martine".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5a63c201-b079-451f-83b9-f9fc30e0ed3b> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/bd82414c-8fc0-4fcb-a7f9-5e5d5d82cf08> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bd82414c-8fc0-4fcb-a7f9-5e5d5d82cf08> a person:Person.
           <http://data.lblod.info/id/personen/bd82414c-8fc0-4fcb-a7f9-5e5d5d82cf08> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bd82414c-8fc0-4fcb-a7f9-5e5d5d82cf08> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Nicky".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bd82414c-8fc0-4fcb-a7f9-5e5d5d82cf08> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/a302ba566d09ab028fb6cbafc8b3512860b4a4bb8f11fb2eb686aa0a2f4843c7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a302ba566d09ab028fb6cbafc8b3512860b4a4bb8f11fb2eb686aa0a2f4843c7> a person:Person.
           <http://data.lblod.info/id/personen/a302ba566d09ab028fb6cbafc8b3512860b4a4bb8f11fb2eb686aa0a2f4843c7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a302ba566d09ab028fb6cbafc8b3512860b4a4bb8f11fb2eb686aa0a2f4843c7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marie Louise".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a302ba566d09ab028fb6cbafc8b3512860b4a4bb8f11fb2eb686aa0a2f4843c7> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/d92426e81682dc1b21200d72d80016ee3097a11a16a9d6b096cc7b14fae030aa> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d92426e81682dc1b21200d72d80016ee3097a11a16a9d6b096cc7b14fae030aa> a person:Person.
           <http://data.lblod.info/id/personen/d92426e81682dc1b21200d72d80016ee3097a11a16a9d6b096cc7b14fae030aa> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d92426e81682dc1b21200d72d80016ee3097a11a16a9d6b096cc7b14fae030aa> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Agnes".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d92426e81682dc1b21200d72d80016ee3097a11a16a9d6b096cc7b14fae030aa> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/25423243-92ca-484d-83bc-98a3d840ea91> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/25423243-92ca-484d-83bc-98a3d840ea91> a person:Person.
           <http://data.lblod.info/id/personen/25423243-92ca-484d-83bc-98a3d840ea91> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/25423243-92ca-484d-83bc-98a3d840ea91> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Yves".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/25423243-92ca-484d-83bc-98a3d840ea91> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/4f787e41-29d7-4937-ab63-b9783bd209d2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4f787e41-29d7-4937-ab63-b9783bd209d2> a person:Person.
           <http://data.lblod.info/id/personen/4f787e41-29d7-4937-ab63-b9783bd209d2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4f787e41-29d7-4937-ab63-b9783bd209d2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Rita".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4f787e41-29d7-4937-ab63-b9783bd209d2> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ccb7811f-592c-4d67-917b-103698e7da2a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ccb7811f-592c-4d67-917b-103698e7da2a> a person:Person.
           <http://data.lblod.info/id/personen/ccb7811f-592c-4d67-917b-103698e7da2a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ccb7811f-592c-4d67-917b-103698e7da2a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Micheline".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ccb7811f-592c-4d67-917b-103698e7da2a> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/15c958b4-99e4-4cb2-940d-1f3599a5c2c3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/15c958b4-99e4-4cb2-940d-1f3599a5c2c3> a person:Person.
           <http://data.lblod.info/id/personen/15c958b4-99e4-4cb2-940d-1f3599a5c2c3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/15c958b4-99e4-4cb2-940d-1f3599a5c2c3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Danny".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/15c958b4-99e4-4cb2-940d-1f3599a5c2c3> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/3f98cb62eb115ccd25d27047aa83a5593e4c934561b3b1b08450e8d4c527c562> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3f98cb62eb115ccd25d27047aa83a5593e4c934561b3b1b08450e8d4c527c562> a person:Person.
           <http://data.lblod.info/id/personen/3f98cb62eb115ccd25d27047aa83a5593e4c934561b3b1b08450e8d4c527c562> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3f98cb62eb115ccd25d27047aa83a5593e4c934561b3b1b08450e8d4c527c562> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marc".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3f98cb62eb115ccd25d27047aa83a5593e4c934561b3b1b08450e8d4c527c562> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/6015b8d8809345a944fb29bddf1a463c04d700da490b4b04dce9ef710a5bfc28> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6015b8d8809345a944fb29bddf1a463c04d700da490b4b04dce9ef710a5bfc28> a person:Person.
           <http://data.lblod.info/id/personen/6015b8d8809345a944fb29bddf1a463c04d700da490b4b04dce9ef710a5bfc28> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6015b8d8809345a944fb29bddf1a463c04d700da490b4b04dce9ef710a5bfc28> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Maurice".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6015b8d8809345a944fb29bddf1a463c04d700da490b4b04dce9ef710a5bfc28> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/6a42eb4ba607b2f3ae9cf5c95f567ac4f7a7be0c7da2772e111e8018b57afb04> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6a42eb4ba607b2f3ae9cf5c95f567ac4f7a7be0c7da2772e111e8018b57afb04> a person:Person.
           <http://data.lblod.info/id/personen/6a42eb4ba607b2f3ae9cf5c95f567ac4f7a7be0c7da2772e111e8018b57afb04> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6a42eb4ba607b2f3ae9cf5c95f567ac4f7a7be0c7da2772e111e8018b57afb04> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Piet".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6a42eb4ba607b2f3ae9cf5c95f567ac4f7a7be0c7da2772e111e8018b57afb04> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/a570e42a-0a3f-405a-ba3a-74818fbaa3f5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a570e42a-0a3f-405a-ba3a-74818fbaa3f5> a person:Person.
           <http://data.lblod.info/id/personen/a570e42a-0a3f-405a-ba3a-74818fbaa3f5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a570e42a-0a3f-405a-ba3a-74818fbaa3f5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ann".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a570e42a-0a3f-405a-ba3a-74818fbaa3f5> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/d9b94ed3-2b1f-4c20-89fe-ce9f48393cfc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d9b94ed3-2b1f-4c20-89fe-ce9f48393cfc> a person:Person.
           <http://data.lblod.info/id/personen/d9b94ed3-2b1f-4c20-89fe-ce9f48393cfc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d9b94ed3-2b1f-4c20-89fe-ce9f48393cfc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Carine".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d9b94ed3-2b1f-4c20-89fe-ce9f48393cfc> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/4b492b44-8d30-4852-82b9-72358b7af17e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4b492b44-8d30-4852-82b9-72358b7af17e> a person:Person.
           <http://data.lblod.info/id/personen/4b492b44-8d30-4852-82b9-72358b7af17e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4b492b44-8d30-4852-82b9-72358b7af17e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Veerle".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4b492b44-8d30-4852-82b9-72358b7af17e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f48df694-d7e7-44cf-a729-49e8653adbb4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f48df694-d7e7-44cf-a729-49e8653adbb4> a person:Person.
           <http://data.lblod.info/id/personen/f48df694-d7e7-44cf-a729-49e8653adbb4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f48df694-d7e7-44cf-a729-49e8653adbb4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Geert".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f48df694-d7e7-44cf-a729-49e8653adbb4> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/349c7f54-9a9d-4572-adb8-486f8cccf0ec> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/349c7f54-9a9d-4572-adb8-486f8cccf0ec> a person:Person.
           <http://data.lblod.info/id/personen/349c7f54-9a9d-4572-adb8-486f8cccf0ec> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/349c7f54-9a9d-4572-adb8-486f8cccf0ec> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Heywood".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/349c7f54-9a9d-4572-adb8-486f8cccf0ec> [] [].
          }
        }
     # finished voornamen-update-10923-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:02+00:00