# started voornamen-update-22081-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:30+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/64c299701f938ee5812fa614c8073bce1842ea531db8db1b719a70cab32d8712> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/64c299701f938ee5812fa614c8073bce1842ea531db8db1b719a70cab32d8712> a person:Person.
           <http://data.lblod.info/id/personen/64c299701f938ee5812fa614c8073bce1842ea531db8db1b719a70cab32d8712> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/64c299701f938ee5812fa614c8073bce1842ea531db8db1b719a70cab32d8712> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Rik".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/64c299701f938ee5812fa614c8073bce1842ea531db8db1b719a70cab32d8712> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e1acf658-b105-446c-a39b-e645821c6cfb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e1acf658-b105-446c-a39b-e645821c6cfb> a person:Person.
           <http://data.lblod.info/id/personen/e1acf658-b105-446c-a39b-e645821c6cfb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e1acf658-b105-446c-a39b-e645821c6cfb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Emiel".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e1acf658-b105-446c-a39b-e645821c6cfb> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/d9957ba9e7480711b272a120933bbf1a7828b2167d1e3bb0edd26d92638b0cb2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d9957ba9e7480711b272a120933bbf1a7828b2167d1e3bb0edd26d92638b0cb2> a person:Person.
           <http://data.lblod.info/id/personen/d9957ba9e7480711b272a120933bbf1a7828b2167d1e3bb0edd26d92638b0cb2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d9957ba9e7480711b272a120933bbf1a7828b2167d1e3bb0edd26d92638b0cb2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Dominique".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d9957ba9e7480711b272a120933bbf1a7828b2167d1e3bb0edd26d92638b0cb2> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/02c0da8c565c5cba16a28f24e719ae1682331fd500622e00f77d5c6253d4ea59> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/02c0da8c565c5cba16a28f24e719ae1682331fd500622e00f77d5c6253d4ea59> a person:Person.
           <http://data.lblod.info/id/personen/02c0da8c565c5cba16a28f24e719ae1682331fd500622e00f77d5c6253d4ea59> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/02c0da8c565c5cba16a28f24e719ae1682331fd500622e00f77d5c6253d4ea59> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jurgen".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/02c0da8c565c5cba16a28f24e719ae1682331fd500622e00f77d5c6253d4ea59> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/aa1e747f-1996-48b7-8017-efb88e922f7c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/aa1e747f-1996-48b7-8017-efb88e922f7c> a person:Person.
           <http://data.lblod.info/id/personen/aa1e747f-1996-48b7-8017-efb88e922f7c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/aa1e747f-1996-48b7-8017-efb88e922f7c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Dorine".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/aa1e747f-1996-48b7-8017-efb88e922f7c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/1119dc7b-d671-4af9-9f1b-bfdc8db6f3dc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1119dc7b-d671-4af9-9f1b-bfdc8db6f3dc> a person:Person.
           <http://data.lblod.info/id/personen/1119dc7b-d671-4af9-9f1b-bfdc8db6f3dc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1119dc7b-d671-4af9-9f1b-bfdc8db6f3dc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Sophie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1119dc7b-d671-4af9-9f1b-bfdc8db6f3dc> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/7fe207f0-10d2-4844-95c8-b008f413cc36> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7fe207f0-10d2-4844-95c8-b008f413cc36> a person:Person.
           <http://data.lblod.info/id/personen/7fe207f0-10d2-4844-95c8-b008f413cc36> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7fe207f0-10d2-4844-95c8-b008f413cc36> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Quicky Nico".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7fe207f0-10d2-4844-95c8-b008f413cc36> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ac5cd63c-693b-4d43-a2f4-63d1d9b447e2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ac5cd63c-693b-4d43-a2f4-63d1d9b447e2> a person:Person.
           <http://data.lblod.info/id/personen/ac5cd63c-693b-4d43-a2f4-63d1d9b447e2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ac5cd63c-693b-4d43-a2f4-63d1d9b447e2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jurgen".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ac5cd63c-693b-4d43-a2f4-63d1d9b447e2> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/5f45a15c-3782-4129-98a3-cf3d7ba9ec61> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5f45a15c-3782-4129-98a3-cf3d7ba9ec61> a person:Person.
           <http://data.lblod.info/id/personen/5f45a15c-3782-4129-98a3-cf3d7ba9ec61> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5f45a15c-3782-4129-98a3-cf3d7ba9ec61> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Sébastien".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5f45a15c-3782-4129-98a3-cf3d7ba9ec61> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/66fc85d8-4a35-4ce9-b1ad-2b779db2b765> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/66fc85d8-4a35-4ce9-b1ad-2b779db2b765> a person:Person.
           <http://data.lblod.info/id/personen/66fc85d8-4a35-4ce9-b1ad-2b779db2b765> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/66fc85d8-4a35-4ce9-b1ad-2b779db2b765> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Mireille".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/66fc85d8-4a35-4ce9-b1ad-2b779db2b765> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/0dd312ac-b868-4007-a635-171b23e706a8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0dd312ac-b868-4007-a635-171b23e706a8> a person:Person.
           <http://data.lblod.info/id/personen/0dd312ac-b868-4007-a635-171b23e706a8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0dd312ac-b868-4007-a635-171b23e706a8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Dya".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0dd312ac-b868-4007-a635-171b23e706a8> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/776a5146-9fe7-4b5c-be5d-824347f6673d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/776a5146-9fe7-4b5c-be5d-824347f6673d> a person:Person.
           <http://data.lblod.info/id/personen/776a5146-9fe7-4b5c-be5d-824347f6673d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/776a5146-9fe7-4b5c-be5d-824347f6673d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Nele".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/776a5146-9fe7-4b5c-be5d-824347f6673d> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/04b73817-bb39-447d-b2a9-55c76ab815a9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/04b73817-bb39-447d-b2a9-55c76ab815a9> a person:Person.
           <http://data.lblod.info/id/personen/04b73817-bb39-447d-b2a9-55c76ab815a9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/04b73817-bb39-447d-b2a9-55c76ab815a9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Stefaan".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/04b73817-bb39-447d-b2a9-55c76ab815a9> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ddb367dd-c947-4c2a-82cd-f6ba4c0efde7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ddb367dd-c947-4c2a-82cd-f6ba4c0efde7> a person:Person.
           <http://data.lblod.info/id/personen/ddb367dd-c947-4c2a-82cd-f6ba4c0efde7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ddb367dd-c947-4c2a-82cd-f6ba4c0efde7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Stefan".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ddb367dd-c947-4c2a-82cd-f6ba4c0efde7> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/7147ca10-9d61-4826-8982-b09fe98cdae2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7147ca10-9d61-4826-8982-b09fe98cdae2> a person:Person.
           <http://data.lblod.info/id/personen/7147ca10-9d61-4826-8982-b09fe98cdae2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7147ca10-9d61-4826-8982-b09fe98cdae2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Stephan".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7147ca10-9d61-4826-8982-b09fe98cdae2> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/d6bc7059-aafa-4372-b81d-dff9dbe34a07> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d6bc7059-aafa-4372-b81d-dff9dbe34a07> a person:Person.
           <http://data.lblod.info/id/personen/d6bc7059-aafa-4372-b81d-dff9dbe34a07> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d6bc7059-aafa-4372-b81d-dff9dbe34a07> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Joyce".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d6bc7059-aafa-4372-b81d-dff9dbe34a07> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/3b9466dc-4d8b-45f7-a0f7-81993550d445> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3b9466dc-4d8b-45f7-a0f7-81993550d445> a person:Person.
           <http://data.lblod.info/id/personen/3b9466dc-4d8b-45f7-a0f7-81993550d445> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3b9466dc-4d8b-45f7-a0f7-81993550d445> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Lander".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3b9466dc-4d8b-45f7-a0f7-81993550d445> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/58c2e81d-2d77-40a1-b64c-cef3cfaac506> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/58c2e81d-2d77-40a1-b64c-cef3cfaac506> a person:Person.
           <http://data.lblod.info/id/personen/58c2e81d-2d77-40a1-b64c-cef3cfaac506> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/58c2e81d-2d77-40a1-b64c-cef3cfaac506> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Axelle".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/58c2e81d-2d77-40a1-b64c-cef3cfaac506> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/d056365e-f4b9-499e-be43-84b4de9de4f0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d056365e-f4b9-499e-be43-84b4de9de4f0> a person:Person.
           <http://data.lblod.info/id/personen/d056365e-f4b9-499e-be43-84b4de9de4f0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d056365e-f4b9-499e-be43-84b4de9de4f0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jari".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d056365e-f4b9-499e-be43-84b4de9de4f0> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/d531a7be-507a-4a5f-bc9c-ad58190a9e05> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d531a7be-507a-4a5f-bc9c-ad58190a9e05> a person:Person.
           <http://data.lblod.info/id/personen/d531a7be-507a-4a5f-bc9c-ad58190a9e05> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d531a7be-507a-4a5f-bc9c-ad58190a9e05> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Robin".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d531a7be-507a-4a5f-bc9c-ad58190a9e05> [] [].
          }
        }
     # finished voornamen-update-22081-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:30+00:00