# started voornamen-update-18180-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:20+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f428b65dcf5b9c243fa73228b03c7e8ced04cf4c2ad2ebbee58daf8afaa1e5ef> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f428b65dcf5b9c243fa73228b03c7e8ced04cf4c2ad2ebbee58daf8afaa1e5ef> a person:Person.
           <http://data.lblod.info/id/personen/f428b65dcf5b9c243fa73228b03c7e8ced04cf4c2ad2ebbee58daf8afaa1e5ef> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f428b65dcf5b9c243fa73228b03c7e8ced04cf4c2ad2ebbee58daf8afaa1e5ef> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Odette".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f428b65dcf5b9c243fa73228b03c7e8ced04cf4c2ad2ebbee58daf8afaa1e5ef> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/654c655e-96d2-40ce-8068-fd779b619857> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/654c655e-96d2-40ce-8068-fd779b619857> a person:Person.
           <http://data.lblod.info/id/personen/654c655e-96d2-40ce-8068-fd779b619857> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/654c655e-96d2-40ce-8068-fd779b619857> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jean-Paul".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/654c655e-96d2-40ce-8068-fd779b619857> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/5071ff7be266d1e7ca7bd6cbef15d486abd7be99ed8319529497cc184bef56a9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5071ff7be266d1e7ca7bd6cbef15d486abd7be99ed8319529497cc184bef56a9> a person:Person.
           <http://data.lblod.info/id/personen/5071ff7be266d1e7ca7bd6cbef15d486abd7be99ed8319529497cc184bef56a9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5071ff7be266d1e7ca7bd6cbef15d486abd7be99ed8319529497cc184bef56a9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Raf".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5071ff7be266d1e7ca7bd6cbef15d486abd7be99ed8319529497cc184bef56a9> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/a2ddeae9-43bd-4e96-a292-2bfb12820701> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a2ddeae9-43bd-4e96-a292-2bfb12820701> a person:Person.
           <http://data.lblod.info/id/personen/a2ddeae9-43bd-4e96-a292-2bfb12820701> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a2ddeae9-43bd-4e96-a292-2bfb12820701> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Mieke".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a2ddeae9-43bd-4e96-a292-2bfb12820701> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/b017dd51-207a-4d00-8f2d-3ba989592bf8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b017dd51-207a-4d00-8f2d-3ba989592bf8> a person:Person.
           <http://data.lblod.info/id/personen/b017dd51-207a-4d00-8f2d-3ba989592bf8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b017dd51-207a-4d00-8f2d-3ba989592bf8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Magda".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b017dd51-207a-4d00-8f2d-3ba989592bf8> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f1907fff-a602-4b4e-bf99-97cfece88b07> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f1907fff-a602-4b4e-bf99-97cfece88b07> a person:Person.
           <http://data.lblod.info/id/personen/f1907fff-a602-4b4e-bf99-97cfece88b07> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f1907fff-a602-4b4e-bf99-97cfece88b07> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Stijn".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f1907fff-a602-4b4e-bf99-97cfece88b07> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/67cbb49a-821a-4456-841c-84a19ef3e897> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/67cbb49a-821a-4456-841c-84a19ef3e897> a person:Person.
           <http://data.lblod.info/id/personen/67cbb49a-821a-4456-841c-84a19ef3e897> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/67cbb49a-821a-4456-841c-84a19ef3e897> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Herlinde".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/67cbb49a-821a-4456-841c-84a19ef3e897> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/7e6d8c85-6ebd-48ba-af0b-48c368e40a58> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7e6d8c85-6ebd-48ba-af0b-48c368e40a58> a person:Person.
           <http://data.lblod.info/id/personen/7e6d8c85-6ebd-48ba-af0b-48c368e40a58> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7e6d8c85-6ebd-48ba-af0b-48c368e40a58> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ferry".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7e6d8c85-6ebd-48ba-af0b-48c368e40a58> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/caf1f504-2217-4c56-8808-91b1926ad3c6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/caf1f504-2217-4c56-8808-91b1926ad3c6> a person:Person.
           <http://data.lblod.info/id/personen/caf1f504-2217-4c56-8808-91b1926ad3c6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/caf1f504-2217-4c56-8808-91b1926ad3c6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Gert".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/caf1f504-2217-4c56-8808-91b1926ad3c6> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/1a96bb9d-b013-4092-a597-8199ef3efb9f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1a96bb9d-b013-4092-a597-8199ef3efb9f> a person:Person.
           <http://data.lblod.info/id/personen/1a96bb9d-b013-4092-a597-8199ef3efb9f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1a96bb9d-b013-4092-a597-8199ef3efb9f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Fabienne".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1a96bb9d-b013-4092-a597-8199ef3efb9f> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/502187f0-3855-4863-99ce-6d82029c18ed> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/502187f0-3855-4863-99ce-6d82029c18ed> a person:Person.
           <http://data.lblod.info/id/personen/502187f0-3855-4863-99ce-6d82029c18ed> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/502187f0-3855-4863-99ce-6d82029c18ed> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Erik".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/502187f0-3855-4863-99ce-6d82029c18ed> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2b21d987-f6a8-42db-8ee4-8d9a8f9c05d9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2b21d987-f6a8-42db-8ee4-8d9a8f9c05d9> a person:Person.
           <http://data.lblod.info/id/personen/2b21d987-f6a8-42db-8ee4-8d9a8f9c05d9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2b21d987-f6a8-42db-8ee4-8d9a8f9c05d9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Elke".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2b21d987-f6a8-42db-8ee4-8d9a8f9c05d9> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/84cac0b6-c82b-4d19-8abb-6bcefb4f0fcd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/84cac0b6-c82b-4d19-8abb-6bcefb4f0fcd> a person:Person.
           <http://data.lblod.info/id/personen/84cac0b6-c82b-4d19-8abb-6bcefb4f0fcd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/84cac0b6-c82b-4d19-8abb-6bcefb4f0fcd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jean".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/84cac0b6-c82b-4d19-8abb-6bcefb4f0fcd> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/6a3c60b3-7bf6-4770-99fe-6f6007b48d9c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6a3c60b3-7bf6-4770-99fe-6f6007b48d9c> a person:Person.
           <http://data.lblod.info/id/personen/6a3c60b3-7bf6-4770-99fe-6f6007b48d9c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6a3c60b3-7bf6-4770-99fe-6f6007b48d9c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Leen".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6a3c60b3-7bf6-4770-99fe-6f6007b48d9c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/26fbe818-9c72-4987-b4d2-fe6fdc98bad1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/26fbe818-9c72-4987-b4d2-fe6fdc98bad1> a person:Person.
           <http://data.lblod.info/id/personen/26fbe818-9c72-4987-b4d2-fe6fdc98bad1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/26fbe818-9c72-4987-b4d2-fe6fdc98bad1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Liliane".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/26fbe818-9c72-4987-b4d2-fe6fdc98bad1> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/0946e103-8603-4b7c-a458-a65c09461b06> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0946e103-8603-4b7c-a458-a65c09461b06> a person:Person.
           <http://data.lblod.info/id/personen/0946e103-8603-4b7c-a458-a65c09461b06> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0946e103-8603-4b7c-a458-a65c09461b06> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Maria".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0946e103-8603-4b7c-a458-a65c09461b06> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/43def539-4d9e-4951-b5c6-80f58f5dcaf8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/43def539-4d9e-4951-b5c6-80f58f5dcaf8> a person:Person.
           <http://data.lblod.info/id/personen/43def539-4d9e-4951-b5c6-80f58f5dcaf8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/43def539-4d9e-4951-b5c6-80f58f5dcaf8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Daan".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/43def539-4d9e-4951-b5c6-80f58f5dcaf8> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/9fb72da9-9a1c-4427-8c88-548610526704> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9fb72da9-9a1c-4427-8c88-548610526704> a person:Person.
           <http://data.lblod.info/id/personen/9fb72da9-9a1c-4427-8c88-548610526704> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9fb72da9-9a1c-4427-8c88-548610526704> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Linda".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9fb72da9-9a1c-4427-8c88-548610526704> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/054d1699-71b0-4e18-8b98-6c068d8d9e37> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/054d1699-71b0-4e18-8b98-6c068d8d9e37> a person:Person.
           <http://data.lblod.info/id/personen/054d1699-71b0-4e18-8b98-6c068d8d9e37> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/054d1699-71b0-4e18-8b98-6c068d8d9e37> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jakke".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/054d1699-71b0-4e18-8b98-6c068d8d9e37> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/4ecf00f0-0293-49e0-b27a-c174905eb33a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4ecf00f0-0293-49e0-b27a-c174905eb33a> a person:Person.
           <http://data.lblod.info/id/personen/4ecf00f0-0293-49e0-b27a-c174905eb33a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4ecf00f0-0293-49e0-b27a-c174905eb33a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Tine".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4ecf00f0-0293-49e0-b27a-c174905eb33a> [] [].
          }
        }
     # finished voornamen-update-18180-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:20+00:00