# started voornamen-update-20457-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:26+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/419b1c763b7271cd57b31b1b29f714581898a2da7dd524908c555a2df3bd3edb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/419b1c763b7271cd57b31b1b29f714581898a2da7dd524908c555a2df3bd3edb> a person:Person.
           <http://data.lblod.info/id/personen/419b1c763b7271cd57b31b1b29f714581898a2da7dd524908c555a2df3bd3edb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/419b1c763b7271cd57b31b1b29f714581898a2da7dd524908c555a2df3bd3edb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Hendrik".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/419b1c763b7271cd57b31b1b29f714581898a2da7dd524908c555a2df3bd3edb> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e6b6ec79-c156-4ac2-9bfa-d3b72e6829e1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e6b6ec79-c156-4ac2-9bfa-d3b72e6829e1> a person:Person.
           <http://data.lblod.info/id/personen/e6b6ec79-c156-4ac2-9bfa-d3b72e6829e1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e6b6ec79-c156-4ac2-9bfa-d3b72e6829e1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Arne".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e6b6ec79-c156-4ac2-9bfa-d3b72e6829e1> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2292907e-c4e4-4350-b8e0-85bb23836882> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2292907e-c4e4-4350-b8e0-85bb23836882> a person:Person.
           <http://data.lblod.info/id/personen/2292907e-c4e4-4350-b8e0-85bb23836882> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2292907e-c4e4-4350-b8e0-85bb23836882> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Dominique".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2292907e-c4e4-4350-b8e0-85bb23836882> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/456a1bdc-89ff-4033-9766-9642f1443d3c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/456a1bdc-89ff-4033-9766-9642f1443d3c> a person:Person.
           <http://data.lblod.info/id/personen/456a1bdc-89ff-4033-9766-9642f1443d3c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/456a1bdc-89ff-4033-9766-9642f1443d3c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Isabelle".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/456a1bdc-89ff-4033-9766-9642f1443d3c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/a7752f0e-9253-4fe4-8327-eb3b06a6dbf9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a7752f0e-9253-4fe4-8327-eb3b06a6dbf9> a person:Person.
           <http://data.lblod.info/id/personen/a7752f0e-9253-4fe4-8327-eb3b06a6dbf9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a7752f0e-9253-4fe4-8327-eb3b06a6dbf9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Stanislas".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a7752f0e-9253-4fe4-8327-eb3b06a6dbf9> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/30cb8e7b-0c4b-4030-ad5b-156a12974b8d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/30cb8e7b-0c4b-4030-ad5b-156a12974b8d> a person:Person.
           <http://data.lblod.info/id/personen/30cb8e7b-0c4b-4030-ad5b-156a12974b8d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/30cb8e7b-0c4b-4030-ad5b-156a12974b8d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Thany".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/30cb8e7b-0c4b-4030-ad5b-156a12974b8d> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/1e50659d-8df2-459c-bdf0-d9431f5a2a97> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1e50659d-8df2-459c-bdf0-d9431f5a2a97> a person:Person.
           <http://data.lblod.info/id/personen/1e50659d-8df2-459c-bdf0-d9431f5a2a97> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1e50659d-8df2-459c-bdf0-d9431f5a2a97> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ulla".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1e50659d-8df2-459c-bdf0-d9431f5a2a97> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/58cd43f1-5286-431d-a1d6-51cc57a56d41> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/58cd43f1-5286-431d-a1d6-51cc57a56d41> a person:Person.
           <http://data.lblod.info/id/personen/58cd43f1-5286-431d-a1d6-51cc57a56d41> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/58cd43f1-5286-431d-a1d6-51cc57a56d41> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Arne".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/58cd43f1-5286-431d-a1d6-51cc57a56d41> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/012067d9-193e-47ba-997c-db2316f9c2ba> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/012067d9-193e-47ba-997c-db2316f9c2ba> a person:Person.
           <http://data.lblod.info/id/personen/012067d9-193e-47ba-997c-db2316f9c2ba> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/012067d9-193e-47ba-997c-db2316f9c2ba> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Rowena".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/012067d9-193e-47ba-997c-db2316f9c2ba> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/5fe2286a-36d7-40f2-b038-35c7d0ddbabf> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5fe2286a-36d7-40f2-b038-35c7d0ddbabf> a person:Person.
           <http://data.lblod.info/id/personen/5fe2286a-36d7-40f2-b038-35c7d0ddbabf> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5fe2286a-36d7-40f2-b038-35c7d0ddbabf> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Eddy".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5fe2286a-36d7-40f2-b038-35c7d0ddbabf> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/54c5cf7d629bf856daa37e0cfe9d1ca2526588f72ddb2a88644ffee46f8e6c13> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/54c5cf7d629bf856daa37e0cfe9d1ca2526588f72ddb2a88644ffee46f8e6c13> a person:Person.
           <http://data.lblod.info/id/personen/54c5cf7d629bf856daa37e0cfe9d1ca2526588f72ddb2a88644ffee46f8e6c13> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/54c5cf7d629bf856daa37e0cfe9d1ca2526588f72ddb2a88644ffee46f8e6c13> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Heidi".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/54c5cf7d629bf856daa37e0cfe9d1ca2526588f72ddb2a88644ffee46f8e6c13> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/af7a700c7b59bbba447e491f1c45ff35e575df56a1882162a9f7bc638656c3c0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/af7a700c7b59bbba447e491f1c45ff35e575df56a1882162a9f7bc638656c3c0> a person:Person.
           <http://data.lblod.info/id/personen/af7a700c7b59bbba447e491f1c45ff35e575df56a1882162a9f7bc638656c3c0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/af7a700c7b59bbba447e491f1c45ff35e575df56a1882162a9f7bc638656c3c0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Dion".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/af7a700c7b59bbba447e491f1c45ff35e575df56a1882162a9f7bc638656c3c0> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/9010b794-75c8-4043-8c2a-fe6f5589f6ed> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9010b794-75c8-4043-8c2a-fe6f5589f6ed> a person:Person.
           <http://data.lblod.info/id/personen/9010b794-75c8-4043-8c2a-fe6f5589f6ed> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9010b794-75c8-4043-8c2a-fe6f5589f6ed> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Michael".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9010b794-75c8-4043-8c2a-fe6f5589f6ed> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/176ce618-5abe-436e-9507-0468518ba86e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/176ce618-5abe-436e-9507-0468518ba86e> a person:Person.
           <http://data.lblod.info/id/personen/176ce618-5abe-436e-9507-0468518ba86e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/176ce618-5abe-436e-9507-0468518ba86e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Filip".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/176ce618-5abe-436e-9507-0468518ba86e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/5abeb9fe-e2f9-4ae7-857f-50b52eec7383> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5abeb9fe-e2f9-4ae7-857f-50b52eec7383> a person:Person.
           <http://data.lblod.info/id/personen/5abeb9fe-e2f9-4ae7-857f-50b52eec7383> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5abeb9fe-e2f9-4ae7-857f-50b52eec7383> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Stijn".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5abeb9fe-e2f9-4ae7-857f-50b52eec7383> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/54cbe2bf-15c8-4554-9863-7a1583bc1f0c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/54cbe2bf-15c8-4554-9863-7a1583bc1f0c> a person:Person.
           <http://data.lblod.info/id/personen/54cbe2bf-15c8-4554-9863-7a1583bc1f0c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/54cbe2bf-15c8-4554-9863-7a1583bc1f0c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Veerle".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/54cbe2bf-15c8-4554-9863-7a1583bc1f0c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/87f03751-72f5-4942-9b52-01f98711210f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/87f03751-72f5-4942-9b52-01f98711210f> a person:Person.
           <http://data.lblod.info/id/personen/87f03751-72f5-4942-9b52-01f98711210f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/87f03751-72f5-4942-9b52-01f98711210f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Evelyne".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/87f03751-72f5-4942-9b52-01f98711210f> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/3f0eda92-8a36-4a5e-9e52-e31645bdaf4a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3f0eda92-8a36-4a5e-9e52-e31645bdaf4a> a person:Person.
           <http://data.lblod.info/id/personen/3f0eda92-8a36-4a5e-9e52-e31645bdaf4a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3f0eda92-8a36-4a5e-9e52-e31645bdaf4a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Aline".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3f0eda92-8a36-4a5e-9e52-e31645bdaf4a> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/93120541-2c2d-4e63-8e70-10a0d8f9cd2d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/93120541-2c2d-4e63-8e70-10a0d8f9cd2d> a person:Person.
           <http://data.lblod.info/id/personen/93120541-2c2d-4e63-8e70-10a0d8f9cd2d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/93120541-2c2d-4e63-8e70-10a0d8f9cd2d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Greta".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/93120541-2c2d-4e63-8e70-10a0d8f9cd2d> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e5b64f54-4b8b-4542-a948-2147e0019d18> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e5b64f54-4b8b-4542-a948-2147e0019d18> a person:Person.
           <http://data.lblod.info/id/personen/e5b64f54-4b8b-4542-a948-2147e0019d18> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e5b64f54-4b8b-4542-a948-2147e0019d18> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Luc".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e5b64f54-4b8b-4542-a948-2147e0019d18> [] [].
          }
        }
     # finished voornamen-update-20457-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:26+00:00