# started voornamen-update-24105-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:35+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/088031d6-2cd0-4d84-9eae-095df0a2eb2e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/088031d6-2cd0-4d84-9eae-095df0a2eb2e> a person:Person.
           <http://data.lblod.info/id/personen/088031d6-2cd0-4d84-9eae-095df0a2eb2e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/088031d6-2cd0-4d84-9eae-095df0a2eb2e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Frans".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/088031d6-2cd0-4d84-9eae-095df0a2eb2e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/5f025599-8677-4819-a7b5-01001330e7e2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5f025599-8677-4819-a7b5-01001330e7e2> a person:Person.
           <http://data.lblod.info/id/personen/5f025599-8677-4819-a7b5-01001330e7e2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5f025599-8677-4819-a7b5-01001330e7e2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Pascale".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5f025599-8677-4819-a7b5-01001330e7e2> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/7949be7e-2a12-4012-a8a8-597a30c84bc1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7949be7e-2a12-4012-a8a8-597a30c84bc1> a person:Person.
           <http://data.lblod.info/id/personen/7949be7e-2a12-4012-a8a8-597a30c84bc1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7949be7e-2a12-4012-a8a8-597a30c84bc1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Dirk".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7949be7e-2a12-4012-a8a8-597a30c84bc1> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/b54743c1a8491dc05636b1259ec338afa99affbba43589054bb0cdc07829146d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b54743c1a8491dc05636b1259ec338afa99affbba43589054bb0cdc07829146d> a person:Person.
           <http://data.lblod.info/id/personen/b54743c1a8491dc05636b1259ec338afa99affbba43589054bb0cdc07829146d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b54743c1a8491dc05636b1259ec338afa99affbba43589054bb0cdc07829146d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Myriam".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b54743c1a8491dc05636b1259ec338afa99affbba43589054bb0cdc07829146d> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/4c98e0cf-beb6-4af8-8ecd-017968b6e41e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4c98e0cf-beb6-4af8-8ecd-017968b6e41e> a person:Person.
           <http://data.lblod.info/id/personen/4c98e0cf-beb6-4af8-8ecd-017968b6e41e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4c98e0cf-beb6-4af8-8ecd-017968b6e41e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Patricia".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4c98e0cf-beb6-4af8-8ecd-017968b6e41e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ea425705-4b55-4217-bb55-43f1f96bc8c6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ea425705-4b55-4217-bb55-43f1f96bc8c6> a person:Person.
           <http://data.lblod.info/id/personen/ea425705-4b55-4217-bb55-43f1f96bc8c6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ea425705-4b55-4217-bb55-43f1f96bc8c6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Nadine".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ea425705-4b55-4217-bb55-43f1f96bc8c6> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/5a1ad1a1-b7ba-4986-8718-e3f45611f014> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5a1ad1a1-b7ba-4986-8718-e3f45611f014> a person:Person.
           <http://data.lblod.info/id/personen/5a1ad1a1-b7ba-4986-8718-e3f45611f014> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5a1ad1a1-b7ba-4986-8718-e3f45611f014> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marnick".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5a1ad1a1-b7ba-4986-8718-e3f45611f014> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/62ada4f1-0e70-4ae8-896c-8d83029aa06f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/62ada4f1-0e70-4ae8-896c-8d83029aa06f> a person:Person.
           <http://data.lblod.info/id/personen/62ada4f1-0e70-4ae8-896c-8d83029aa06f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/62ada4f1-0e70-4ae8-896c-8d83029aa06f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Daniël (Absjaar)".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/62ada4f1-0e70-4ae8-896c-8d83029aa06f> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/fa3d4e3c-36f2-4fa6-9701-29fc5a1c1de3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/fa3d4e3c-36f2-4fa6-9701-29fc5a1c1de3> a person:Person.
           <http://data.lblod.info/id/personen/fa3d4e3c-36f2-4fa6-9701-29fc5a1c1de3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/fa3d4e3c-36f2-4fa6-9701-29fc5a1c1de3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Richard".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/fa3d4e3c-36f2-4fa6-9701-29fc5a1c1de3> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/b63a9eb7fc87d289e56e2129d205f2ff534e40feb07cea075b8a1d2a01dfab89> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b63a9eb7fc87d289e56e2129d205f2ff534e40feb07cea075b8a1d2a01dfab89> a person:Person.
           <http://data.lblod.info/id/personen/b63a9eb7fc87d289e56e2129d205f2ff534e40feb07cea075b8a1d2a01dfab89> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b63a9eb7fc87d289e56e2129d205f2ff534e40feb07cea075b8a1d2a01dfab89> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Martine".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b63a9eb7fc87d289e56e2129d205f2ff534e40feb07cea075b8a1d2a01dfab89> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/7a406e3d-b06a-4835-8eb0-7de8c9fa592b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7a406e3d-b06a-4835-8eb0-7de8c9fa592b> a person:Person.
           <http://data.lblod.info/id/personen/7a406e3d-b06a-4835-8eb0-7de8c9fa592b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7a406e3d-b06a-4835-8eb0-7de8c9fa592b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Eva".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7a406e3d-b06a-4835-8eb0-7de8c9fa592b> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/3f77efa5-f0ae-4537-94f5-201f9b999ea7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3f77efa5-f0ae-4537-94f5-201f9b999ea7> a person:Person.
           <http://data.lblod.info/id/personen/3f77efa5-f0ae-4537-94f5-201f9b999ea7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3f77efa5-f0ae-4537-94f5-201f9b999ea7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Conny".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3f77efa5-f0ae-4537-94f5-201f9b999ea7> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/10cc10e7-a83e-43d0-9182-2bdcac73e36d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/10cc10e7-a83e-43d0-9182-2bdcac73e36d> a person:Person.
           <http://data.lblod.info/id/personen/10cc10e7-a83e-43d0-9182-2bdcac73e36d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/10cc10e7-a83e-43d0-9182-2bdcac73e36d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Luc".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/10cc10e7-a83e-43d0-9182-2bdcac73e36d> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ff3de4ab-786b-4078-b853-bbcdb1a8b488> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ff3de4ab-786b-4078-b853-bbcdb1a8b488> a person:Person.
           <http://data.lblod.info/id/personen/ff3de4ab-786b-4078-b853-bbcdb1a8b488> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ff3de4ab-786b-4078-b853-bbcdb1a8b488> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Patrick".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ff3de4ab-786b-4078-b853-bbcdb1a8b488> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2c3b8e80-4c8c-4aea-a022-44f6df4dfda8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2c3b8e80-4c8c-4aea-a022-44f6df4dfda8> a person:Person.
           <http://data.lblod.info/id/personen/2c3b8e80-4c8c-4aea-a022-44f6df4dfda8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2c3b8e80-4c8c-4aea-a022-44f6df4dfda8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Johan".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2c3b8e80-4c8c-4aea-a022-44f6df4dfda8> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f323ab2613fab2a95026ce2c784f3aa43997cabd81718ddcb6d14c39944a1617> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f323ab2613fab2a95026ce2c784f3aa43997cabd81718ddcb6d14c39944a1617> a person:Person.
           <http://data.lblod.info/id/personen/f323ab2613fab2a95026ce2c784f3aa43997cabd81718ddcb6d14c39944a1617> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f323ab2613fab2a95026ce2c784f3aa43997cabd81718ddcb6d14c39944a1617> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Sarah-Amilia".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f323ab2613fab2a95026ce2c784f3aa43997cabd81718ddcb6d14c39944a1617> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ce99de54-6e8f-45f6-b060-cb5409df62e3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ce99de54-6e8f-45f6-b060-cb5409df62e3> a person:Person.
           <http://data.lblod.info/id/personen/ce99de54-6e8f-45f6-b060-cb5409df62e3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ce99de54-6e8f-45f6-b060-cb5409df62e3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Bart".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ce99de54-6e8f-45f6-b060-cb5409df62e3> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/6bb922c77a7ce596f3db286f0c9debfecc05d2503492d06d98b9521ad32ab10f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6bb922c77a7ce596f3db286f0c9debfecc05d2503492d06d98b9521ad32ab10f> a person:Person.
           <http://data.lblod.info/id/personen/6bb922c77a7ce596f3db286f0c9debfecc05d2503492d06d98b9521ad32ab10f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6bb922c77a7ce596f3db286f0c9debfecc05d2503492d06d98b9521ad32ab10f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Elmire".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6bb922c77a7ce596f3db286f0c9debfecc05d2503492d06d98b9521ad32ab10f> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/a3dd23c2-ba22-43d7-8a4c-970d7d0c6d56> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a3dd23c2-ba22-43d7-8a4c-970d7d0c6d56> a person:Person.
           <http://data.lblod.info/id/personen/a3dd23c2-ba22-43d7-8a4c-970d7d0c6d56> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a3dd23c2-ba22-43d7-8a4c-970d7d0c6d56> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Gabriël".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a3dd23c2-ba22-43d7-8a4c-970d7d0c6d56> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/969ee25e-6449-451b-821a-16c078e29027> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/969ee25e-6449-451b-821a-16c078e29027> a person:Person.
           <http://data.lblod.info/id/personen/969ee25e-6449-451b-821a-16c078e29027> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/969ee25e-6449-451b-821a-16c078e29027> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marjolein".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/969ee25e-6449-451b-821a-16c078e29027> [] [].
          }
        }
     # finished voornamen-update-24105-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:35+00:00