# restore
DELETE {
  GRAPH <http://mu.semte.ch/application> {
    ?s ?p ?o
  }
}
INSERT {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s ?p ?o
  }
}
WHERE {
  GRAPH <http://mu.semte.ch/application> {
    ?s a <http://mu.semte.ch/vocabularies/ext/Template>;
    ?s ?p ?o.
  }
};
