# started voornamen-update-28459-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:46+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2168a9eb819c2fa9580cc71637264fc9aa1735551d4529dbf193d46c180c77c7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2168a9eb819c2fa9580cc71637264fc9aa1735551d4529dbf193d46c180c77c7> a person:Person.
           <http://data.lblod.info/id/personen/2168a9eb819c2fa9580cc71637264fc9aa1735551d4529dbf193d46c180c77c7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2168a9eb819c2fa9580cc71637264fc9aa1735551d4529dbf193d46c180c77c7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Erwin".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2168a9eb819c2fa9580cc71637264fc9aa1735551d4529dbf193d46c180c77c7> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/45e2f824-7b54-4176-bc71-4571ad684a9a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/45e2f824-7b54-4176-bc71-4571ad684a9a> a person:Person.
           <http://data.lblod.info/id/personen/45e2f824-7b54-4176-bc71-4571ad684a9a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/45e2f824-7b54-4176-bc71-4571ad684a9a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Steve".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/45e2f824-7b54-4176-bc71-4571ad684a9a> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/05f3d776-a540-41f7-8e06-349ea42b56fa> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/05f3d776-a540-41f7-8e06-349ea42b56fa> a person:Person.
           <http://data.lblod.info/id/personen/05f3d776-a540-41f7-8e06-349ea42b56fa> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/05f3d776-a540-41f7-8e06-349ea42b56fa> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marijke".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/05f3d776-a540-41f7-8e06-349ea42b56fa> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/4c1dc3ff31a20fc48487d73f815cbaedae23cef0b742dd839001ceb0425c3c7a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4c1dc3ff31a20fc48487d73f815cbaedae23cef0b742dd839001ceb0425c3c7a> a person:Person.
           <http://data.lblod.info/id/personen/4c1dc3ff31a20fc48487d73f815cbaedae23cef0b742dd839001ceb0425c3c7a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4c1dc3ff31a20fc48487d73f815cbaedae23cef0b742dd839001ceb0425c3c7a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Sabine".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4c1dc3ff31a20fc48487d73f815cbaedae23cef0b742dd839001ceb0425c3c7a> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f1f1885c-5bfe-4ffb-a9ff-b9cb9cfd7576> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f1f1885c-5bfe-4ffb-a9ff-b9cb9cfd7576> a person:Person.
           <http://data.lblod.info/id/personen/f1f1885c-5bfe-4ffb-a9ff-b9cb9cfd7576> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f1f1885c-5bfe-4ffb-a9ff-b9cb9cfd7576> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Veronique".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f1f1885c-5bfe-4ffb-a9ff-b9cb9cfd7576> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/efeeab73-57e9-46e6-a4f7-8e83f9b2011d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/efeeab73-57e9-46e6-a4f7-8e83f9b2011d> a person:Person.
           <http://data.lblod.info/id/personen/efeeab73-57e9-46e6-a4f7-8e83f9b2011d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/efeeab73-57e9-46e6-a4f7-8e83f9b2011d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Tim".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/efeeab73-57e9-46e6-a4f7-8e83f9b2011d> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/6953fb0820719d8192bd154c5b6b6d71a144699d624626287b85071f427fd30c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6953fb0820719d8192bd154c5b6b6d71a144699d624626287b85071f427fd30c> a person:Person.
           <http://data.lblod.info/id/personen/6953fb0820719d8192bd154c5b6b6d71a144699d624626287b85071f427fd30c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6953fb0820719d8192bd154c5b6b6d71a144699d624626287b85071f427fd30c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Philippe".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6953fb0820719d8192bd154c5b6b6d71a144699d624626287b85071f427fd30c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/9e99508f-158c-4d4f-bc70-1dc3b4b3bf50> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9e99508f-158c-4d4f-bc70-1dc3b4b3bf50> a person:Person.
           <http://data.lblod.info/id/personen/9e99508f-158c-4d4f-bc70-1dc3b4b3bf50> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9e99508f-158c-4d4f-bc70-1dc3b4b3bf50> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Preben".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9e99508f-158c-4d4f-bc70-1dc3b4b3bf50> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/af44c8286cb6c0481e0795947ef7a066d12d106d21c8bfc71995bb4d110489b0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/af44c8286cb6c0481e0795947ef7a066d12d106d21c8bfc71995bb4d110489b0> a person:Person.
           <http://data.lblod.info/id/personen/af44c8286cb6c0481e0795947ef7a066d12d106d21c8bfc71995bb4d110489b0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/af44c8286cb6c0481e0795947ef7a066d12d106d21c8bfc71995bb4d110489b0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Inge".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/af44c8286cb6c0481e0795947ef7a066d12d106d21c8bfc71995bb4d110489b0> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/424ea8c5-a92b-4d4c-8d8a-efb8240ffd49> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/424ea8c5-a92b-4d4c-8d8a-efb8240ffd49> a person:Person.
           <http://data.lblod.info/id/personen/424ea8c5-a92b-4d4c-8d8a-efb8240ffd49> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/424ea8c5-a92b-4d4c-8d8a-efb8240ffd49> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Godelieve".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/424ea8c5-a92b-4d4c-8d8a-efb8240ffd49> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/c0c743ad5ab95a1d1b1dfa2f88fde853677f05b6d5c8ede50727b98aa0acbafc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c0c743ad5ab95a1d1b1dfa2f88fde853677f05b6d5c8ede50727b98aa0acbafc> a person:Person.
           <http://data.lblod.info/id/personen/c0c743ad5ab95a1d1b1dfa2f88fde853677f05b6d5c8ede50727b98aa0acbafc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c0c743ad5ab95a1d1b1dfa2f88fde853677f05b6d5c8ede50727b98aa0acbafc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Roger".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c0c743ad5ab95a1d1b1dfa2f88fde853677f05b6d5c8ede50727b98aa0acbafc> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2a5be91e08f3d81f11a1ead4167e887cd4fe349f7b77bf147d491b7a084778a2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2a5be91e08f3d81f11a1ead4167e887cd4fe349f7b77bf147d491b7a084778a2> a person:Person.
           <http://data.lblod.info/id/personen/2a5be91e08f3d81f11a1ead4167e887cd4fe349f7b77bf147d491b7a084778a2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2a5be91e08f3d81f11a1ead4167e887cd4fe349f7b77bf147d491b7a084778a2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marc".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2a5be91e08f3d81f11a1ead4167e887cd4fe349f7b77bf147d491b7a084778a2> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/799ed81058b5923fe6656cf52b3a10bf8cfa50e4ed4139303e8ca5db3c78e639> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/799ed81058b5923fe6656cf52b3a10bf8cfa50e4ed4139303e8ca5db3c78e639> a person:Person.
           <http://data.lblod.info/id/personen/799ed81058b5923fe6656cf52b3a10bf8cfa50e4ed4139303e8ca5db3c78e639> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/799ed81058b5923fe6656cf52b3a10bf8cfa50e4ed4139303e8ca5db3c78e639> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Pieter".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/799ed81058b5923fe6656cf52b3a10bf8cfa50e4ed4139303e8ca5db3c78e639> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/8223a2e71f59fb8cf54c753a167eebb35cef3f5e0003e66a4536aedfe56e2ac6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8223a2e71f59fb8cf54c753a167eebb35cef3f5e0003e66a4536aedfe56e2ac6> a person:Person.
           <http://data.lblod.info/id/personen/8223a2e71f59fb8cf54c753a167eebb35cef3f5e0003e66a4536aedfe56e2ac6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8223a2e71f59fb8cf54c753a167eebb35cef3f5e0003e66a4536aedfe56e2ac6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Gerda".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8223a2e71f59fb8cf54c753a167eebb35cef3f5e0003e66a4536aedfe56e2ac6> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/953d3b49dc52aff5c71cc690cfb55d556d11d25835038e1ea769a7f74206a1e1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/953d3b49dc52aff5c71cc690cfb55d556d11d25835038e1ea769a7f74206a1e1> a person:Person.
           <http://data.lblod.info/id/personen/953d3b49dc52aff5c71cc690cfb55d556d11d25835038e1ea769a7f74206a1e1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/953d3b49dc52aff5c71cc690cfb55d556d11d25835038e1ea769a7f74206a1e1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Veerle".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/953d3b49dc52aff5c71cc690cfb55d556d11d25835038e1ea769a7f74206a1e1> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e03dfccf-887f-456a-9f60-97f81ef55ff9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e03dfccf-887f-456a-9f60-97f81ef55ff9> a person:Person.
           <http://data.lblod.info/id/personen/e03dfccf-887f-456a-9f60-97f81ef55ff9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e03dfccf-887f-456a-9f60-97f81ef55ff9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Lorin".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e03dfccf-887f-456a-9f60-97f81ef55ff9> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2e69e7ebe3e8c57833698aa5457bb722dac00c057b53a369f47ba6b1832b0110> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2e69e7ebe3e8c57833698aa5457bb722dac00c057b53a369f47ba6b1832b0110> a person:Person.
           <http://data.lblod.info/id/personen/2e69e7ebe3e8c57833698aa5457bb722dac00c057b53a369f47ba6b1832b0110> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2e69e7ebe3e8c57833698aa5457bb722dac00c057b53a369f47ba6b1832b0110> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Roland".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2e69e7ebe3e8c57833698aa5457bb722dac00c057b53a369f47ba6b1832b0110> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/5edbf683-6294-45b8-b475-bb4def61bc45> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5edbf683-6294-45b8-b475-bb4def61bc45> a person:Person.
           <http://data.lblod.info/id/personen/5edbf683-6294-45b8-b475-bb4def61bc45> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5edbf683-6294-45b8-b475-bb4def61bc45> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Lowie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5edbf683-6294-45b8-b475-bb4def61bc45> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2b7062906d59b596eed3d5ecf827ba161ef82d4b41ed696158832427ea3c3e17> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2b7062906d59b596eed3d5ecf827ba161ef82d4b41ed696158832427ea3c3e17> a person:Person.
           <http://data.lblod.info/id/personen/2b7062906d59b596eed3d5ecf827ba161ef82d4b41ed696158832427ea3c3e17> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2b7062906d59b596eed3d5ecf827ba161ef82d4b41ed696158832427ea3c3e17> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Alex".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2b7062906d59b596eed3d5ecf827ba161ef82d4b41ed696158832427ea3c3e17> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/d2a4383b-2897-45dd-bc84-2a5134cf0e9b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d2a4383b-2897-45dd-bc84-2a5134cf0e9b> a person:Person.
           <http://data.lblod.info/id/personen/d2a4383b-2897-45dd-bc84-2a5134cf0e9b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d2a4383b-2897-45dd-bc84-2a5134cf0e9b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marjolein".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d2a4383b-2897-45dd-bc84-2a5134cf0e9b> [] [].
          }
        }
     # finished voornamen-update-28459-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:46+00:00