# started voornamen-update-32778-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:58+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/9deb013c-2d5d-407f-a9d0-f6bceff3987c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9deb013c-2d5d-407f-a9d0-f6bceff3987c> a person:Person.
           <http://data.lblod.info/id/personen/9deb013c-2d5d-407f-a9d0-f6bceff3987c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9deb013c-2d5d-407f-a9d0-f6bceff3987c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Dorinda".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9deb013c-2d5d-407f-a9d0-f6bceff3987c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/d7e366b8e321bfe0c50bb038a51d8d504b89bc59117547bfe2d7d6805c3f697c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d7e366b8e321bfe0c50bb038a51d8d504b89bc59117547bfe2d7d6805c3f697c> a person:Person.
           <http://data.lblod.info/id/personen/d7e366b8e321bfe0c50bb038a51d8d504b89bc59117547bfe2d7d6805c3f697c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d7e366b8e321bfe0c50bb038a51d8d504b89bc59117547bfe2d7d6805c3f697c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Danny".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d7e366b8e321bfe0c50bb038a51d8d504b89bc59117547bfe2d7d6805c3f697c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/40a0075a-7701-4b6e-b038-f48e6fbffec4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/40a0075a-7701-4b6e-b038-f48e6fbffec4> a person:Person.
           <http://data.lblod.info/id/personen/40a0075a-7701-4b6e-b038-f48e6fbffec4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/40a0075a-7701-4b6e-b038-f48e6fbffec4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Tina".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/40a0075a-7701-4b6e-b038-f48e6fbffec4> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ac718379-b753-4b35-8125-80da7de7c5d6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ac718379-b753-4b35-8125-80da7de7c5d6> a person:Person.
           <http://data.lblod.info/id/personen/ac718379-b753-4b35-8125-80da7de7c5d6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ac718379-b753-4b35-8125-80da7de7c5d6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jos".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ac718379-b753-4b35-8125-80da7de7c5d6> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/a4b07319-11f2-40b9-8041-6d80fc3beeb4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a4b07319-11f2-40b9-8041-6d80fc3beeb4> a person:Person.
           <http://data.lblod.info/id/personen/a4b07319-11f2-40b9-8041-6d80fc3beeb4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a4b07319-11f2-40b9-8041-6d80fc3beeb4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Johan".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a4b07319-11f2-40b9-8041-6d80fc3beeb4> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/dfa4147479be25502d1446e7e14a4179588ebb84c0b0aa6a701369fd84319c0c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/dfa4147479be25502d1446e7e14a4179588ebb84c0b0aa6a701369fd84319c0c> a person:Person.
           <http://data.lblod.info/id/personen/dfa4147479be25502d1446e7e14a4179588ebb84c0b0aa6a701369fd84319c0c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/dfa4147479be25502d1446e7e14a4179588ebb84c0b0aa6a701369fd84319c0c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Kris".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/dfa4147479be25502d1446e7e14a4179588ebb84c0b0aa6a701369fd84319c0c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/9414852b-9dc8-475e-a332-9ed988ee693b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9414852b-9dc8-475e-a332-9ed988ee693b> a person:Person.
           <http://data.lblod.info/id/personen/9414852b-9dc8-475e-a332-9ed988ee693b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9414852b-9dc8-475e-a332-9ed988ee693b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Frans".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9414852b-9dc8-475e-a332-9ed988ee693b> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/6cc57a57-3d8a-4435-8b92-d6bc3f0f9053> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6cc57a57-3d8a-4435-8b92-d6bc3f0f9053> a person:Person.
           <http://data.lblod.info/id/personen/6cc57a57-3d8a-4435-8b92-d6bc3f0f9053> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6cc57a57-3d8a-4435-8b92-d6bc3f0f9053> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Kristin".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6cc57a57-3d8a-4435-8b92-d6bc3f0f9053> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f9801205-9efc-4d0c-b3ac-5b41dab3e872> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f9801205-9efc-4d0c-b3ac-5b41dab3e872> a person:Person.
           <http://data.lblod.info/id/personen/f9801205-9efc-4d0c-b3ac-5b41dab3e872> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f9801205-9efc-4d0c-b3ac-5b41dab3e872> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Leen".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f9801205-9efc-4d0c-b3ac-5b41dab3e872> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/eabc502a-49a3-44a1-97e9-dea482038f83> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/eabc502a-49a3-44a1-97e9-dea482038f83> a person:Person.
           <http://data.lblod.info/id/personen/eabc502a-49a3-44a1-97e9-dea482038f83> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/eabc502a-49a3-44a1-97e9-dea482038f83> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jean-Pierre".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/eabc502a-49a3-44a1-97e9-dea482038f83> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/a9f7e436-7ef2-463f-8c62-75e2c51264a5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a9f7e436-7ef2-463f-8c62-75e2c51264a5> a person:Person.
           <http://data.lblod.info/id/personen/a9f7e436-7ef2-463f-8c62-75e2c51264a5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a9f7e436-7ef2-463f-8c62-75e2c51264a5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Rein".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a9f7e436-7ef2-463f-8c62-75e2c51264a5> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/4c04d2ad5672fbf392595fbb5deae4a623c74a1efa3c56f4620a7bd7e9e65a3c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4c04d2ad5672fbf392595fbb5deae4a623c74a1efa3c56f4620a7bd7e9e65a3c> a person:Person.
           <http://data.lblod.info/id/personen/4c04d2ad5672fbf392595fbb5deae4a623c74a1efa3c56f4620a7bd7e9e65a3c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4c04d2ad5672fbf392595fbb5deae4a623c74a1efa3c56f4620a7bd7e9e65a3c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jos".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4c04d2ad5672fbf392595fbb5deae4a623c74a1efa3c56f4620a7bd7e9e65a3c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/b6e00302-1934-4ac7-8bf2-369102ac8670> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b6e00302-1934-4ac7-8bf2-369102ac8670> a person:Person.
           <http://data.lblod.info/id/personen/b6e00302-1934-4ac7-8bf2-369102ac8670> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b6e00302-1934-4ac7-8bf2-369102ac8670> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jean-Jacques".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b6e00302-1934-4ac7-8bf2-369102ac8670> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/61186ec6f3eec40de58d1350dc3bcfa7efe0ff69c4dcd9e7c0f3216ce1417438> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/61186ec6f3eec40de58d1350dc3bcfa7efe0ff69c4dcd9e7c0f3216ce1417438> a person:Person.
           <http://data.lblod.info/id/personen/61186ec6f3eec40de58d1350dc3bcfa7efe0ff69c4dcd9e7c0f3216ce1417438> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/61186ec6f3eec40de58d1350dc3bcfa7efe0ff69c4dcd9e7c0f3216ce1417438> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Linda".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/61186ec6f3eec40de58d1350dc3bcfa7efe0ff69c4dcd9e7c0f3216ce1417438> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/d3531378-3673-45b7-8297-7cc26cc3b032> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d3531378-3673-45b7-8297-7cc26cc3b032> a person:Person.
           <http://data.lblod.info/id/personen/d3531378-3673-45b7-8297-7cc26cc3b032> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d3531378-3673-45b7-8297-7cc26cc3b032> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Lode".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d3531378-3673-45b7-8297-7cc26cc3b032> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e02cb075-91c0-4382-86b9-9f1cc1c6fa08> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e02cb075-91c0-4382-86b9-9f1cc1c6fa08> a person:Person.
           <http://data.lblod.info/id/personen/e02cb075-91c0-4382-86b9-9f1cc1c6fa08> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e02cb075-91c0-4382-86b9-9f1cc1c6fa08> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Aurelie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e02cb075-91c0-4382-86b9-9f1cc1c6fa08> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/7d1774a2893d36077040087dec684dc59e7155c070644242b8abeff79a2b0a3a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7d1774a2893d36077040087dec684dc59e7155c070644242b8abeff79a2b0a3a> a person:Person.
           <http://data.lblod.info/id/personen/7d1774a2893d36077040087dec684dc59e7155c070644242b8abeff79a2b0a3a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7d1774a2893d36077040087dec684dc59e7155c070644242b8abeff79a2b0a3a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jos".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7d1774a2893d36077040087dec684dc59e7155c070644242b8abeff79a2b0a3a> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f8f71837-2b3f-4621-99f1-bb17d92688f9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f8f71837-2b3f-4621-99f1-bb17d92688f9> a person:Person.
           <http://data.lblod.info/id/personen/f8f71837-2b3f-4621-99f1-bb17d92688f9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f8f71837-2b3f-4621-99f1-bb17d92688f9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Claire".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f8f71837-2b3f-4621-99f1-bb17d92688f9> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/69a3e950-e4aa-4d10-8bde-ba554448f127> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/69a3e950-e4aa-4d10-8bde-ba554448f127> a person:Person.
           <http://data.lblod.info/id/personen/69a3e950-e4aa-4d10-8bde-ba554448f127> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/69a3e950-e4aa-4d10-8bde-ba554448f127> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Lieve".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/69a3e950-e4aa-4d10-8bde-ba554448f127> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/71029e69-daad-4e5d-bd4e-019fc1c8004c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/71029e69-daad-4e5d-bd4e-019fc1c8004c> a person:Person.
           <http://data.lblod.info/id/personen/71029e69-daad-4e5d-bd4e-019fc1c8004c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/71029e69-daad-4e5d-bd4e-019fc1c8004c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Kris".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/71029e69-daad-4e5d-bd4e-019fc1c8004c> [] [].
          }
        }
     # finished voornamen-update-32778-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:58+00:00