# started voornamen-update-36233-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:07:06+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/0605ffcff623bcbc304618b3d5127acbac4fd12305443d95727aadb958a2bef9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0605ffcff623bcbc304618b3d5127acbac4fd12305443d95727aadb958a2bef9> a person:Person.
           <http://data.lblod.info/id/personen/0605ffcff623bcbc304618b3d5127acbac4fd12305443d95727aadb958a2bef9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0605ffcff623bcbc304618b3d5127acbac4fd12305443d95727aadb958a2bef9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jean".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0605ffcff623bcbc304618b3d5127acbac4fd12305443d95727aadb958a2bef9> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/627378976fb78fe8baceb88fd9539e6849a1741f07f50b4ebf45f130697dd083> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/627378976fb78fe8baceb88fd9539e6849a1741f07f50b4ebf45f130697dd083> a person:Person.
           <http://data.lblod.info/id/personen/627378976fb78fe8baceb88fd9539e6849a1741f07f50b4ebf45f130697dd083> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/627378976fb78fe8baceb88fd9539e6849a1741f07f50b4ebf45f130697dd083> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Christa".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/627378976fb78fe8baceb88fd9539e6849a1741f07f50b4ebf45f130697dd083> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/c0c301b4-3eb9-4922-9476-869427046d8c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c0c301b4-3eb9-4922-9476-869427046d8c> a person:Person.
           <http://data.lblod.info/id/personen/c0c301b4-3eb9-4922-9476-869427046d8c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c0c301b4-3eb9-4922-9476-869427046d8c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "David".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c0c301b4-3eb9-4922-9476-869427046d8c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/b2b736e8-152a-41aa-89bd-16bb4f6f42b3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b2b736e8-152a-41aa-89bd-16bb4f6f42b3> a person:Person.
           <http://data.lblod.info/id/personen/b2b736e8-152a-41aa-89bd-16bb4f6f42b3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b2b736e8-152a-41aa-89bd-16bb4f6f42b3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Vanessa".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b2b736e8-152a-41aa-89bd-16bb4f6f42b3> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/16d11033-e566-4aa6-94e0-58cc380fd17c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/16d11033-e566-4aa6-94e0-58cc380fd17c> a person:Person.
           <http://data.lblod.info/id/personen/16d11033-e566-4aa6-94e0-58cc380fd17c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/16d11033-e566-4aa6-94e0-58cc380fd17c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jan".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/16d11033-e566-4aa6-94e0-58cc380fd17c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2b626059-4f69-4634-9d9a-b247888c07d0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2b626059-4f69-4634-9d9a-b247888c07d0> a person:Person.
           <http://data.lblod.info/id/personen/2b626059-4f69-4634-9d9a-b247888c07d0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2b626059-4f69-4634-9d9a-b247888c07d0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Mieke".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2b626059-4f69-4634-9d9a-b247888c07d0> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/c6975a8c-c6e3-4fb5-a73d-21f8acddd805> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c6975a8c-c6e3-4fb5-a73d-21f8acddd805> a person:Person.
           <http://data.lblod.info/id/personen/c6975a8c-c6e3-4fb5-a73d-21f8acddd805> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c6975a8c-c6e3-4fb5-a73d-21f8acddd805> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Vanessa".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c6975a8c-c6e3-4fb5-a73d-21f8acddd805> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/705aa0ba-c648-4485-b1b8-73968e1b4179> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/705aa0ba-c648-4485-b1b8-73968e1b4179> a person:Person.
           <http://data.lblod.info/id/personen/705aa0ba-c648-4485-b1b8-73968e1b4179> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/705aa0ba-c648-4485-b1b8-73968e1b4179> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Anja".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/705aa0ba-c648-4485-b1b8-73968e1b4179> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/45aae2bf-2545-4ef3-b2d3-c3c34e76ead8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/45aae2bf-2545-4ef3-b2d3-c3c34e76ead8> a person:Person.
           <http://data.lblod.info/id/personen/45aae2bf-2545-4ef3-b2d3-c3c34e76ead8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/45aae2bf-2545-4ef3-b2d3-c3c34e76ead8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ann-Paule".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/45aae2bf-2545-4ef3-b2d3-c3c34e76ead8> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/d545db9f-5b4a-418a-891e-17413dbebb65> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d545db9f-5b4a-418a-891e-17413dbebb65> a person:Person.
           <http://data.lblod.info/id/personen/d545db9f-5b4a-418a-891e-17413dbebb65> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d545db9f-5b4a-418a-891e-17413dbebb65> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Sabrina".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d545db9f-5b4a-418a-891e-17413dbebb65> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/94ef2f5e-5e8c-4414-857f-16e2cb0e75fe> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/94ef2f5e-5e8c-4414-857f-16e2cb0e75fe> a person:Person.
           <http://data.lblod.info/id/personen/94ef2f5e-5e8c-4414-857f-16e2cb0e75fe> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/94ef2f5e-5e8c-4414-857f-16e2cb0e75fe> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Frans".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/94ef2f5e-5e8c-4414-857f-16e2cb0e75fe> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/c2faaf47-34d8-4063-9942-8f6372a98c1e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c2faaf47-34d8-4063-9942-8f6372a98c1e> a person:Person.
           <http://data.lblod.info/id/personen/c2faaf47-34d8-4063-9942-8f6372a98c1e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c2faaf47-34d8-4063-9942-8f6372a98c1e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Benoit".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c2faaf47-34d8-4063-9942-8f6372a98c1e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/6612e376-d4f4-4113-9af5-ed205b7a1a9e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6612e376-d4f4-4113-9af5-ed205b7a1a9e> a person:Person.
           <http://data.lblod.info/id/personen/6612e376-d4f4-4113-9af5-ed205b7a1a9e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6612e376-d4f4-4113-9af5-ed205b7a1a9e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Emmy".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6612e376-d4f4-4113-9af5-ed205b7a1a9e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/3ab1b6de33f5622d4417863f671cd21fccd17c205a9a766122232faf6f008893> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3ab1b6de33f5622d4417863f671cd21fccd17c205a9a766122232faf6f008893> a person:Person.
           <http://data.lblod.info/id/personen/3ab1b6de33f5622d4417863f671cd21fccd17c205a9a766122232faf6f008893> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3ab1b6de33f5622d4417863f671cd21fccd17c205a9a766122232faf6f008893> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Christian".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3ab1b6de33f5622d4417863f671cd21fccd17c205a9a766122232faf6f008893> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f3dd70c3-d33c-46be-b7aa-977efd2446e4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f3dd70c3-d33c-46be-b7aa-977efd2446e4> a person:Person.
           <http://data.lblod.info/id/personen/f3dd70c3-d33c-46be-b7aa-977efd2446e4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f3dd70c3-d33c-46be-b7aa-977efd2446e4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Danny".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f3dd70c3-d33c-46be-b7aa-977efd2446e4> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/6525576aab64b9e195fb3efdb9c3dc656f1846923b7bb5fe5a88a4e8f01a3360> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6525576aab64b9e195fb3efdb9c3dc656f1846923b7bb5fe5a88a4e8f01a3360> a person:Person.
           <http://data.lblod.info/id/personen/6525576aab64b9e195fb3efdb9c3dc656f1846923b7bb5fe5a88a4e8f01a3360> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6525576aab64b9e195fb3efdb9c3dc656f1846923b7bb5fe5a88a4e8f01a3360> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Louisa".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6525576aab64b9e195fb3efdb9c3dc656f1846923b7bb5fe5a88a4e8f01a3360> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/cf465f3722e3b99a461da269774e318d053e4d8cb2961c2a4e6143d145dc7a6d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cf465f3722e3b99a461da269774e318d053e4d8cb2961c2a4e6143d145dc7a6d> a person:Person.
           <http://data.lblod.info/id/personen/cf465f3722e3b99a461da269774e318d053e4d8cb2961c2a4e6143d145dc7a6d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cf465f3722e3b99a461da269774e318d053e4d8cb2961c2a4e6143d145dc7a6d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Heidi".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cf465f3722e3b99a461da269774e318d053e4d8cb2961c2a4e6143d145dc7a6d> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/d74268a8-bd46-4fd1-812b-912cc2de714f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d74268a8-bd46-4fd1-812b-912cc2de714f> a person:Person.
           <http://data.lblod.info/id/personen/d74268a8-bd46-4fd1-812b-912cc2de714f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d74268a8-bd46-4fd1-812b-912cc2de714f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marc".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d74268a8-bd46-4fd1-812b-912cc2de714f> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/370f6cf189677457eab9c87a0c0698f2f15088d42e84c2f19047d6b6f613f00f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/370f6cf189677457eab9c87a0c0698f2f15088d42e84c2f19047d6b6f613f00f> a person:Person.
           <http://data.lblod.info/id/personen/370f6cf189677457eab9c87a0c0698f2f15088d42e84c2f19047d6b6f613f00f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/370f6cf189677457eab9c87a0c0698f2f15088d42e84c2f19047d6b6f613f00f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jean-Pierre".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/370f6cf189677457eab9c87a0c0698f2f15088d42e84c2f19047d6b6f613f00f> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/717d0b8fbe8bce69eeb9670ae559cd48528a2824ea1ccf576d1ed259a9c80745> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/717d0b8fbe8bce69eeb9670ae559cd48528a2824ea1ccf576d1ed259a9c80745> a person:Person.
           <http://data.lblod.info/id/personen/717d0b8fbe8bce69eeb9670ae559cd48528a2824ea1ccf576d1ed259a9c80745> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/717d0b8fbe8bce69eeb9670ae559cd48528a2824ea1ccf576d1ed259a9c80745> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marie-Elise".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/717d0b8fbe8bce69eeb9670ae559cd48528a2824ea1ccf576d1ed259a9c80745> [] [].
          }
        }
     # finished voornamen-update-36233-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:07:06+00:00