# started voornamen-update-34055-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:07:01+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/206a8964-61c8-4395-acf0-c95dee722a78> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/206a8964-61c8-4395-acf0-c95dee722a78> a person:Person.
           <http://data.lblod.info/id/personen/206a8964-61c8-4395-acf0-c95dee722a78> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/206a8964-61c8-4395-acf0-c95dee722a78> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Xavier".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/206a8964-61c8-4395-acf0-c95dee722a78> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/725363db5ec5a6237497291ced736d8dab92e088c618a718a2eee4fcf4b917f6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/725363db5ec5a6237497291ced736d8dab92e088c618a718a2eee4fcf4b917f6> a person:Person.
           <http://data.lblod.info/id/personen/725363db5ec5a6237497291ced736d8dab92e088c618a718a2eee4fcf4b917f6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/725363db5ec5a6237497291ced736d8dab92e088c618a718a2eee4fcf4b917f6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marc".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/725363db5ec5a6237497291ced736d8dab92e088c618a718a2eee4fcf4b917f6> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/bca1e830-7399-4827-a2a4-e6014e4bb1e1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bca1e830-7399-4827-a2a4-e6014e4bb1e1> a person:Person.
           <http://data.lblod.info/id/personen/bca1e830-7399-4827-a2a4-e6014e4bb1e1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bca1e830-7399-4827-a2a4-e6014e4bb1e1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Frieda".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bca1e830-7399-4827-a2a4-e6014e4bb1e1> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e23cd6b8446f3f66c280e5ddfdcb4911fa7489a934e271a4613ca6ec4a83e708> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e23cd6b8446f3f66c280e5ddfdcb4911fa7489a934e271a4613ca6ec4a83e708> a person:Person.
           <http://data.lblod.info/id/personen/e23cd6b8446f3f66c280e5ddfdcb4911fa7489a934e271a4613ca6ec4a83e708> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e23cd6b8446f3f66c280e5ddfdcb4911fa7489a934e271a4613ca6ec4a83e708> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Lode".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e23cd6b8446f3f66c280e5ddfdcb4911fa7489a934e271a4613ca6ec4a83e708> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/9a9ac3716c5f993c9149169904381fbd4845cd881613b84ed11f2577e904aea3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9a9ac3716c5f993c9149169904381fbd4845cd881613b84ed11f2577e904aea3> a person:Person.
           <http://data.lblod.info/id/personen/9a9ac3716c5f993c9149169904381fbd4845cd881613b84ed11f2577e904aea3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9a9ac3716c5f993c9149169904381fbd4845cd881613b84ed11f2577e904aea3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Roel".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9a9ac3716c5f993c9149169904381fbd4845cd881613b84ed11f2577e904aea3> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/81487466ea5b4c28f51a191e128bfa8527935274e6fb0dcf0f402f70dd993078> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/81487466ea5b4c28f51a191e128bfa8527935274e6fb0dcf0f402f70dd993078> a person:Person.
           <http://data.lblod.info/id/personen/81487466ea5b4c28f51a191e128bfa8527935274e6fb0dcf0f402f70dd993078> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/81487466ea5b4c28f51a191e128bfa8527935274e6fb0dcf0f402f70dd993078> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ben".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/81487466ea5b4c28f51a191e128bfa8527935274e6fb0dcf0f402f70dd993078> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/71a59e77-1e46-4f8b-ace0-5d93b1cb1f8c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/71a59e77-1e46-4f8b-ace0-5d93b1cb1f8c> a person:Person.
           <http://data.lblod.info/id/personen/71a59e77-1e46-4f8b-ace0-5d93b1cb1f8c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/71a59e77-1e46-4f8b-ace0-5d93b1cb1f8c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Nadine".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/71a59e77-1e46-4f8b-ace0-5d93b1cb1f8c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/eb77fc35-fcba-4a08-b9f2-8c4955a20106> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/eb77fc35-fcba-4a08-b9f2-8c4955a20106> a person:Person.
           <http://data.lblod.info/id/personen/eb77fc35-fcba-4a08-b9f2-8c4955a20106> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/eb77fc35-fcba-4a08-b9f2-8c4955a20106> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Luc".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/eb77fc35-fcba-4a08-b9f2-8c4955a20106> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/b31500d9-a1ae-4a61-bf7f-2ccb8d38e39e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b31500d9-a1ae-4a61-bf7f-2ccb8d38e39e> a person:Person.
           <http://data.lblod.info/id/personen/b31500d9-a1ae-4a61-bf7f-2ccb8d38e39e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b31500d9-a1ae-4a61-bf7f-2ccb8d38e39e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Stefanie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b31500d9-a1ae-4a61-bf7f-2ccb8d38e39e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/1679f0b2-e47b-4e76-84f4-83afb251f6b9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1679f0b2-e47b-4e76-84f4-83afb251f6b9> a person:Person.
           <http://data.lblod.info/id/personen/1679f0b2-e47b-4e76-84f4-83afb251f6b9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1679f0b2-e47b-4e76-84f4-83afb251f6b9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Leentje".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1679f0b2-e47b-4e76-84f4-83afb251f6b9> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/aa7386d5fa05e9c1f665d7810f9dbbad23da13f024ef561b878966e0a7ec05a6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/aa7386d5fa05e9c1f665d7810f9dbbad23da13f024ef561b878966e0a7ec05a6> a person:Person.
           <http://data.lblod.info/id/personen/aa7386d5fa05e9c1f665d7810f9dbbad23da13f024ef561b878966e0a7ec05a6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/aa7386d5fa05e9c1f665d7810f9dbbad23da13f024ef561b878966e0a7ec05a6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jaak".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/aa7386d5fa05e9c1f665d7810f9dbbad23da13f024ef561b878966e0a7ec05a6> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/35766788-03dc-441e-93ea-9caf6b9ecb16> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/35766788-03dc-441e-93ea-9caf6b9ecb16> a person:Person.
           <http://data.lblod.info/id/personen/35766788-03dc-441e-93ea-9caf6b9ecb16> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/35766788-03dc-441e-93ea-9caf6b9ecb16> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Werner".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/35766788-03dc-441e-93ea-9caf6b9ecb16> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/455566e5-d4b7-450e-a1fe-bc5c71cd1bc1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/455566e5-d4b7-450e-a1fe-bc5c71cd1bc1> a person:Person.
           <http://data.lblod.info/id/personen/455566e5-d4b7-450e-a1fe-bc5c71cd1bc1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/455566e5-d4b7-450e-a1fe-bc5c71cd1bc1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marida".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/455566e5-d4b7-450e-a1fe-bc5c71cd1bc1> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/30aa679d-88f7-4445-82b8-cc6d677f7a0d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/30aa679d-88f7-4445-82b8-cc6d677f7a0d> a person:Person.
           <http://data.lblod.info/id/personen/30aa679d-88f7-4445-82b8-cc6d677f7a0d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/30aa679d-88f7-4445-82b8-cc6d677f7a0d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Rudi".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/30aa679d-88f7-4445-82b8-cc6d677f7a0d> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/d48249c7-d3aa-45eb-bdd7-9ab4fc2f14c2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d48249c7-d3aa-45eb-bdd7-9ab4fc2f14c2> a person:Person.
           <http://data.lblod.info/id/personen/d48249c7-d3aa-45eb-bdd7-9ab4fc2f14c2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d48249c7-d3aa-45eb-bdd7-9ab4fc2f14c2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Julia".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d48249c7-d3aa-45eb-bdd7-9ab4fc2f14c2> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/93d6c393-8109-4b44-8fe7-6e6abe598326> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/93d6c393-8109-4b44-8fe7-6e6abe598326> a person:Person.
           <http://data.lblod.info/id/personen/93d6c393-8109-4b44-8fe7-6e6abe598326> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/93d6c393-8109-4b44-8fe7-6e6abe598326> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Erik".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/93d6c393-8109-4b44-8fe7-6e6abe598326> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f6f26a2f-18e4-40ee-8987-dbdb667346ce> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f6f26a2f-18e4-40ee-8987-dbdb667346ce> a person:Person.
           <http://data.lblod.info/id/personen/f6f26a2f-18e4-40ee-8987-dbdb667346ce> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f6f26a2f-18e4-40ee-8987-dbdb667346ce> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Curt".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f6f26a2f-18e4-40ee-8987-dbdb667346ce> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f57c18ca-3085-4679-a7cf-71497c78429f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f57c18ca-3085-4679-a7cf-71497c78429f> a person:Person.
           <http://data.lblod.info/id/personen/f57c18ca-3085-4679-a7cf-71497c78429f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f57c18ca-3085-4679-a7cf-71497c78429f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jasper".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f57c18ca-3085-4679-a7cf-71497c78429f> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ab139ae0-360e-44a0-b663-7ffe62775d74> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ab139ae0-360e-44a0-b663-7ffe62775d74> a person:Person.
           <http://data.lblod.info/id/personen/ab139ae0-360e-44a0-b663-7ffe62775d74> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ab139ae0-360e-44a0-b663-7ffe62775d74> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Yve".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ab139ae0-360e-44a0-b663-7ffe62775d74> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/7e25e3ae-f8c0-47d0-ab0b-6ce5ba588969> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7e25e3ae-f8c0-47d0-ab0b-6ce5ba588969> a person:Person.
           <http://data.lblod.info/id/personen/7e25e3ae-f8c0-47d0-ab0b-6ce5ba588969> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7e25e3ae-f8c0-47d0-ab0b-6ce5ba588969> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jean-François".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7e25e3ae-f8c0-47d0-ab0b-6ce5ba588969> [] [].
          }
        }
     # finished voornamen-update-34055-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:07:01+00:00