# started voornamen-update-17384-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:18+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/960d611d3ca0107a5cae0ca0a511de97782cd84561ea2dfab9ee5647fde1480b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/960d611d3ca0107a5cae0ca0a511de97782cd84561ea2dfab9ee5647fde1480b> a person:Person.
           <http://data.lblod.info/id/personen/960d611d3ca0107a5cae0ca0a511de97782cd84561ea2dfab9ee5647fde1480b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/960d611d3ca0107a5cae0ca0a511de97782cd84561ea2dfab9ee5647fde1480b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Agnes".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/960d611d3ca0107a5cae0ca0a511de97782cd84561ea2dfab9ee5647fde1480b> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/bafff225-abce-4a0c-a994-0568e944f8f6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bafff225-abce-4a0c-a994-0568e944f8f6> a person:Person.
           <http://data.lblod.info/id/personen/bafff225-abce-4a0c-a994-0568e944f8f6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bafff225-abce-4a0c-a994-0568e944f8f6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Chris".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bafff225-abce-4a0c-a994-0568e944f8f6> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/9ed9f194-8c98-491e-9d83-2d09e6dbb1df> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9ed9f194-8c98-491e-9d83-2d09e6dbb1df> a person:Person.
           <http://data.lblod.info/id/personen/9ed9f194-8c98-491e-9d83-2d09e6dbb1df> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9ed9f194-8c98-491e-9d83-2d09e6dbb1df> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jean".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9ed9f194-8c98-491e-9d83-2d09e6dbb1df> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/df55664f785b10610ed9bee2c90539b42de1e4f2d0d46a2e6d1ed45a846bd455> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/df55664f785b10610ed9bee2c90539b42de1e4f2d0d46a2e6d1ed45a846bd455> a person:Person.
           <http://data.lblod.info/id/personen/df55664f785b10610ed9bee2c90539b42de1e4f2d0d46a2e6d1ed45a846bd455> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/df55664f785b10610ed9bee2c90539b42de1e4f2d0d46a2e6d1ed45a846bd455> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Michiel".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/df55664f785b10610ed9bee2c90539b42de1e4f2d0d46a2e6d1ed45a846bd455> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/32174661f27e8b4d80a8efdd7f63a314cb4dd748d51bc343ecc2b34d621f04ca> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/32174661f27e8b4d80a8efdd7f63a314cb4dd748d51bc343ecc2b34d621f04ca> a person:Person.
           <http://data.lblod.info/id/personen/32174661f27e8b4d80a8efdd7f63a314cb4dd748d51bc343ecc2b34d621f04ca> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/32174661f27e8b4d80a8efdd7f63a314cb4dd748d51bc343ecc2b34d621f04ca> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jan".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/32174661f27e8b4d80a8efdd7f63a314cb4dd748d51bc343ecc2b34d621f04ca> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/7b5c354c3140673831ad717e2dd07df8106391dd47257ad9aa47d68211eae85d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7b5c354c3140673831ad717e2dd07df8106391dd47257ad9aa47d68211eae85d> a person:Person.
           <http://data.lblod.info/id/personen/7b5c354c3140673831ad717e2dd07df8106391dd47257ad9aa47d68211eae85d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7b5c354c3140673831ad717e2dd07df8106391dd47257ad9aa47d68211eae85d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Matthias".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7b5c354c3140673831ad717e2dd07df8106391dd47257ad9aa47d68211eae85d> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/da0f3d6044864074ef6bfe15dc661cddbe8f98b5d3985bb5724fa8911b208b1b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/da0f3d6044864074ef6bfe15dc661cddbe8f98b5d3985bb5724fa8911b208b1b> a person:Person.
           <http://data.lblod.info/id/personen/da0f3d6044864074ef6bfe15dc661cddbe8f98b5d3985bb5724fa8911b208b1b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/da0f3d6044864074ef6bfe15dc661cddbe8f98b5d3985bb5724fa8911b208b1b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Alain".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/da0f3d6044864074ef6bfe15dc661cddbe8f98b5d3985bb5724fa8911b208b1b> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/810594ad-cf6b-4816-9e4b-5e0fc388c973> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/810594ad-cf6b-4816-9e4b-5e0fc388c973> a person:Person.
           <http://data.lblod.info/id/personen/810594ad-cf6b-4816-9e4b-5e0fc388c973> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/810594ad-cf6b-4816-9e4b-5e0fc388c973> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Beryl".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/810594ad-cf6b-4816-9e4b-5e0fc388c973> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/0fb975e1-7cfd-4999-976b-a437277f6e2f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0fb975e1-7cfd-4999-976b-a437277f6e2f> a person:Person.
           <http://data.lblod.info/id/personen/0fb975e1-7cfd-4999-976b-a437277f6e2f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0fb975e1-7cfd-4999-976b-a437277f6e2f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Kevin".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0fb975e1-7cfd-4999-976b-a437277f6e2f> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/39235231-3837-4933-bf85-1eee9764d501> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/39235231-3837-4933-bf85-1eee9764d501> a person:Person.
           <http://data.lblod.info/id/personen/39235231-3837-4933-bf85-1eee9764d501> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/39235231-3837-4933-bf85-1eee9764d501> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Caroline".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/39235231-3837-4933-bf85-1eee9764d501> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/539b6380-498d-42d5-bea2-bb263aa1c192> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/539b6380-498d-42d5-bea2-bb263aa1c192> a person:Person.
           <http://data.lblod.info/id/personen/539b6380-498d-42d5-bea2-bb263aa1c192> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/539b6380-498d-42d5-bea2-bb263aa1c192> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Matthias".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/539b6380-498d-42d5-bea2-bb263aa1c192> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/4d1e1c17c0c60f9c83ca147ad6b6f44fdb58c39a77facc21228156b88dac8929> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4d1e1c17c0c60f9c83ca147ad6b6f44fdb58c39a77facc21228156b88dac8929> a person:Person.
           <http://data.lblod.info/id/personen/4d1e1c17c0c60f9c83ca147ad6b6f44fdb58c39a77facc21228156b88dac8929> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4d1e1c17c0c60f9c83ca147ad6b6f44fdb58c39a77facc21228156b88dac8929> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Elisabeth".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4d1e1c17c0c60f9c83ca147ad6b6f44fdb58c39a77facc21228156b88dac8929> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e45c74d8-379e-4d52-a1c1-ba68db573a25> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e45c74d8-379e-4d52-a1c1-ba68db573a25> a person:Person.
           <http://data.lblod.info/id/personen/e45c74d8-379e-4d52-a1c1-ba68db573a25> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e45c74d8-379e-4d52-a1c1-ba68db573a25> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Maxime".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e45c74d8-379e-4d52-a1c1-ba68db573a25> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/642a050c-8eb9-4b0f-bce8-9ba93faef6c1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/642a050c-8eb9-4b0f-bce8-9ba93faef6c1> a person:Person.
           <http://data.lblod.info/id/personen/642a050c-8eb9-4b0f-bce8-9ba93faef6c1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/642a050c-8eb9-4b0f-bce8-9ba93faef6c1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Katia".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/642a050c-8eb9-4b0f-bce8-9ba93faef6c1> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/daa9dc7c-7baa-4191-8a13-5b179bdb184b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/daa9dc7c-7baa-4191-8a13-5b179bdb184b> a person:Person.
           <http://data.lblod.info/id/personen/daa9dc7c-7baa-4191-8a13-5b179bdb184b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/daa9dc7c-7baa-4191-8a13-5b179bdb184b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Michiel".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/daa9dc7c-7baa-4191-8a13-5b179bdb184b> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/8bbb1287-731d-4e09-bddc-cf9efb234e96> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8bbb1287-731d-4e09-bddc-cf9efb234e96> a person:Person.
           <http://data.lblod.info/id/personen/8bbb1287-731d-4e09-bddc-cf9efb234e96> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8bbb1287-731d-4e09-bddc-cf9efb234e96> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Liesbeth".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8bbb1287-731d-4e09-bddc-cf9efb234e96> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2d4014bf-3fad-4533-a02a-96ae7cb43714> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2d4014bf-3fad-4533-a02a-96ae7cb43714> a person:Person.
           <http://data.lblod.info/id/personen/2d4014bf-3fad-4533-a02a-96ae7cb43714> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2d4014bf-3fad-4533-a02a-96ae7cb43714> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Andries".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2d4014bf-3fad-4533-a02a-96ae7cb43714> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/4751c6f7-ebf8-474e-9490-c3266a20a682> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4751c6f7-ebf8-474e-9490-c3266a20a682> a person:Person.
           <http://data.lblod.info/id/personen/4751c6f7-ebf8-474e-9490-c3266a20a682> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4751c6f7-ebf8-474e-9490-c3266a20a682> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Lisa".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4751c6f7-ebf8-474e-9490-c3266a20a682> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2b62ebb5-7999-4265-929a-28c01dfc0fe3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2b62ebb5-7999-4265-929a-28c01dfc0fe3> a person:Person.
           <http://data.lblod.info/id/personen/2b62ebb5-7999-4265-929a-28c01dfc0fe3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2b62ebb5-7999-4265-929a-28c01dfc0fe3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Keano".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2b62ebb5-7999-4265-929a-28c01dfc0fe3> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/7a5ae7e5-c35d-4dbe-9830-d2bef29ccf4d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7a5ae7e5-c35d-4dbe-9830-d2bef29ccf4d> a person:Person.
           <http://data.lblod.info/id/personen/7a5ae7e5-c35d-4dbe-9830-d2bef29ccf4d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7a5ae7e5-c35d-4dbe-9830-d2bef29ccf4d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Delphine".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7a5ae7e5-c35d-4dbe-9830-d2bef29ccf4d> [] [].
          }
        }
     # finished voornamen-update-17384-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:18+00:00