# started voornamen-update-33014-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:58+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/78df0831-dbbf-4bbb-a141-2f435cea5f23> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/78df0831-dbbf-4bbb-a141-2f435cea5f23> a person:Person.
           <http://data.lblod.info/id/personen/78df0831-dbbf-4bbb-a141-2f435cea5f23> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/78df0831-dbbf-4bbb-a141-2f435cea5f23> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jo".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/78df0831-dbbf-4bbb-a141-2f435cea5f23> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/947f0dd4-e58c-4bfa-a46a-0c3a7327e651> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/947f0dd4-e58c-4bfa-a46a-0c3a7327e651> a person:Person.
           <http://data.lblod.info/id/personen/947f0dd4-e58c-4bfa-a46a-0c3a7327e651> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/947f0dd4-e58c-4bfa-a46a-0c3a7327e651> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Annick".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/947f0dd4-e58c-4bfa-a46a-0c3a7327e651> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/0d76fae5f4ec7f91663680032a43202a0acb1e8d1749b33fe6a6155f3ff81193> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0d76fae5f4ec7f91663680032a43202a0acb1e8d1749b33fe6a6155f3ff81193> a person:Person.
           <http://data.lblod.info/id/personen/0d76fae5f4ec7f91663680032a43202a0acb1e8d1749b33fe6a6155f3ff81193> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0d76fae5f4ec7f91663680032a43202a0acb1e8d1749b33fe6a6155f3ff81193> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Firmin".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0d76fae5f4ec7f91663680032a43202a0acb1e8d1749b33fe6a6155f3ff81193> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/b45b3a88-33fe-4658-8d0d-3c2d5dd06362> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b45b3a88-33fe-4658-8d0d-3c2d5dd06362> a person:Person.
           <http://data.lblod.info/id/personen/b45b3a88-33fe-4658-8d0d-3c2d5dd06362> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b45b3a88-33fe-4658-8d0d-3c2d5dd06362> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Cynthia".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b45b3a88-33fe-4658-8d0d-3c2d5dd06362> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/529ba24f-0f2a-4d0a-ad3b-35d34003b487> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/529ba24f-0f2a-4d0a-ad3b-35d34003b487> a person:Person.
           <http://data.lblod.info/id/personen/529ba24f-0f2a-4d0a-ad3b-35d34003b487> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/529ba24f-0f2a-4d0a-ad3b-35d34003b487> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Mark".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/529ba24f-0f2a-4d0a-ad3b-35d34003b487> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/3b461c05-74e5-4366-9e91-42c222708d27> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3b461c05-74e5-4366-9e91-42c222708d27> a person:Person.
           <http://data.lblod.info/id/personen/3b461c05-74e5-4366-9e91-42c222708d27> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3b461c05-74e5-4366-9e91-42c222708d27> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Lindsey".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3b461c05-74e5-4366-9e91-42c222708d27> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/36afc039-bb8c-44c3-8434-67dfbd99093d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/36afc039-bb8c-44c3-8434-67dfbd99093d> a person:Person.
           <http://data.lblod.info/id/personen/36afc039-bb8c-44c3-8434-67dfbd99093d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/36afc039-bb8c-44c3-8434-67dfbd99093d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Greet".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/36afc039-bb8c-44c3-8434-67dfbd99093d> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/5158efd55f0b666cf39c32c2b435b87ab4a86e513fc2d38a834248fe2f02faa2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5158efd55f0b666cf39c32c2b435b87ab4a86e513fc2d38a834248fe2f02faa2> a person:Person.
           <http://data.lblod.info/id/personen/5158efd55f0b666cf39c32c2b435b87ab4a86e513fc2d38a834248fe2f02faa2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5158efd55f0b666cf39c32c2b435b87ab4a86e513fc2d38a834248fe2f02faa2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Josiane".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5158efd55f0b666cf39c32c2b435b87ab4a86e513fc2d38a834248fe2f02faa2> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/6a43ae2e260a78e87b34a34371388214baf4c890562872bb074ce6de71b20104> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6a43ae2e260a78e87b34a34371388214baf4c890562872bb074ce6de71b20104> a person:Person.
           <http://data.lblod.info/id/personen/6a43ae2e260a78e87b34a34371388214baf4c890562872bb074ce6de71b20104> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6a43ae2e260a78e87b34a34371388214baf4c890562872bb074ce6de71b20104> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Sophie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6a43ae2e260a78e87b34a34371388214baf4c890562872bb074ce6de71b20104> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/c3adf306583dda517b3d23f7003b61b6a1613f708d368eb1e2d53993ff880f0a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c3adf306583dda517b3d23f7003b61b6a1613f708d368eb1e2d53993ff880f0a> a person:Person.
           <http://data.lblod.info/id/personen/c3adf306583dda517b3d23f7003b61b6a1613f708d368eb1e2d53993ff880f0a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c3adf306583dda517b3d23f7003b61b6a1613f708d368eb1e2d53993ff880f0a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marie José".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c3adf306583dda517b3d23f7003b61b6a1613f708d368eb1e2d53993ff880f0a> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/35dc5f70e84ebfce4284217a415d46fbb96d42fe0970ac5a905a3829c96f6c7d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/35dc5f70e84ebfce4284217a415d46fbb96d42fe0970ac5a905a3829c96f6c7d> a person:Person.
           <http://data.lblod.info/id/personen/35dc5f70e84ebfce4284217a415d46fbb96d42fe0970ac5a905a3829c96f6c7d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/35dc5f70e84ebfce4284217a415d46fbb96d42fe0970ac5a905a3829c96f6c7d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Pritty".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/35dc5f70e84ebfce4284217a415d46fbb96d42fe0970ac5a905a3829c96f6c7d> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/791a17f0-6da2-4cdb-bf84-851ad1b9893f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/791a17f0-6da2-4cdb-bf84-851ad1b9893f> a person:Person.
           <http://data.lblod.info/id/personen/791a17f0-6da2-4cdb-bf84-851ad1b9893f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/791a17f0-6da2-4cdb-bf84-851ad1b9893f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marc".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/791a17f0-6da2-4cdb-bf84-851ad1b9893f> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ec3f268046fcabc6de993117038c50029c20bd2d82d0b21348a05a04a55ec85f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ec3f268046fcabc6de993117038c50029c20bd2d82d0b21348a05a04a55ec85f> a person:Person.
           <http://data.lblod.info/id/personen/ec3f268046fcabc6de993117038c50029c20bd2d82d0b21348a05a04a55ec85f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ec3f268046fcabc6de993117038c50029c20bd2d82d0b21348a05a04a55ec85f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Guy".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ec3f268046fcabc6de993117038c50029c20bd2d82d0b21348a05a04a55ec85f> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/11bbec90-64e4-4371-ad91-514df89b26aa> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/11bbec90-64e4-4371-ad91-514df89b26aa> a person:Person.
           <http://data.lblod.info/id/personen/11bbec90-64e4-4371-ad91-514df89b26aa> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/11bbec90-64e4-4371-ad91-514df89b26aa> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marijke".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/11bbec90-64e4-4371-ad91-514df89b26aa> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/eb79a2a7-d3ec-4f04-ba20-627717da244c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/eb79a2a7-d3ec-4f04-ba20-627717da244c> a person:Person.
           <http://data.lblod.info/id/personen/eb79a2a7-d3ec-4f04-ba20-627717da244c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/eb79a2a7-d3ec-4f04-ba20-627717da244c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Philip".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/eb79a2a7-d3ec-4f04-ba20-627717da244c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/988487ab57adff00118c3bdd6670b64069e237540b78c8ebfebd857984b47e95> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/988487ab57adff00118c3bdd6670b64069e237540b78c8ebfebd857984b47e95> a person:Person.
           <http://data.lblod.info/id/personen/988487ab57adff00118c3bdd6670b64069e237540b78c8ebfebd857984b47e95> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/988487ab57adff00118c3bdd6670b64069e237540b78c8ebfebd857984b47e95> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Line".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/988487ab57adff00118c3bdd6670b64069e237540b78c8ebfebd857984b47e95> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/67116476-2a12-43be-8b84-683a284ab1e8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/67116476-2a12-43be-8b84-683a284ab1e8> a person:Person.
           <http://data.lblod.info/id/personen/67116476-2a12-43be-8b84-683a284ab1e8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/67116476-2a12-43be-8b84-683a284ab1e8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Eddy".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/67116476-2a12-43be-8b84-683a284ab1e8> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/cd5b6a22-f4c5-4131-ab03-5a7690604c7c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cd5b6a22-f4c5-4131-ab03-5a7690604c7c> a person:Person.
           <http://data.lblod.info/id/personen/cd5b6a22-f4c5-4131-ab03-5a7690604c7c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cd5b6a22-f4c5-4131-ab03-5a7690604c7c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marleen".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cd5b6a22-f4c5-4131-ab03-5a7690604c7c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/58ecfdc92c3566d94f87a0a28b9045e46221358a610bc94963412530c2402167> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/58ecfdc92c3566d94f87a0a28b9045e46221358a610bc94963412530c2402167> a person:Person.
           <http://data.lblod.info/id/personen/58ecfdc92c3566d94f87a0a28b9045e46221358a610bc94963412530c2402167> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/58ecfdc92c3566d94f87a0a28b9045e46221358a610bc94963412530c2402167> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Eddy".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/58ecfdc92c3566d94f87a0a28b9045e46221358a610bc94963412530c2402167> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/90fbe308-ccff-4bd6-9eee-279154b67e6f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/90fbe308-ccff-4bd6-9eee-279154b67e6f> a person:Person.
           <http://data.lblod.info/id/personen/90fbe308-ccff-4bd6-9eee-279154b67e6f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/90fbe308-ccff-4bd6-9eee-279154b67e6f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Robby".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/90fbe308-ccff-4bd6-9eee-279154b67e6f> [] [].
          }
        }
     # finished voornamen-update-33014-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:58+00:00