# started voornamen-update-11744-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:04+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e17fcf96-6544-4f24-bc4d-1f353f0b0765> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e17fcf96-6544-4f24-bc4d-1f353f0b0765> a person:Person.
           <http://data.lblod.info/id/personen/e17fcf96-6544-4f24-bc4d-1f353f0b0765> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e17fcf96-6544-4f24-bc4d-1f353f0b0765> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Nicole".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e17fcf96-6544-4f24-bc4d-1f353f0b0765> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/89c08fd505d9916f632e713c7bb0a0d85e3a6f1d3a66aceace61c97d24780ea0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/89c08fd505d9916f632e713c7bb0a0d85e3a6f1d3a66aceace61c97d24780ea0> a person:Person.
           <http://data.lblod.info/id/personen/89c08fd505d9916f632e713c7bb0a0d85e3a6f1d3a66aceace61c97d24780ea0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/89c08fd505d9916f632e713c7bb0a0d85e3a6f1d3a66aceace61c97d24780ea0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Johan".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/89c08fd505d9916f632e713c7bb0a0d85e3a6f1d3a66aceace61c97d24780ea0> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/b1196d413a9a8f17302d6e0d3789eeb2085a30dba5a21b08f011f0bb9d48237a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b1196d413a9a8f17302d6e0d3789eeb2085a30dba5a21b08f011f0bb9d48237a> a person:Person.
           <http://data.lblod.info/id/personen/b1196d413a9a8f17302d6e0d3789eeb2085a30dba5a21b08f011f0bb9d48237a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b1196d413a9a8f17302d6e0d3789eeb2085a30dba5a21b08f011f0bb9d48237a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Frida".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b1196d413a9a8f17302d6e0d3789eeb2085a30dba5a21b08f011f0bb9d48237a> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/44d2871c-b640-49aa-903b-292bc9e85f6e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/44d2871c-b640-49aa-903b-292bc9e85f6e> a person:Person.
           <http://data.lblod.info/id/personen/44d2871c-b640-49aa-903b-292bc9e85f6e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/44d2871c-b640-49aa-903b-292bc9e85f6e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jeroen".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/44d2871c-b640-49aa-903b-292bc9e85f6e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/5d762498-f49e-436d-8dae-957b31c77c1d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5d762498-f49e-436d-8dae-957b31c77c1d> a person:Person.
           <http://data.lblod.info/id/personen/5d762498-f49e-436d-8dae-957b31c77c1d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5d762498-f49e-436d-8dae-957b31c77c1d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Elisa".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5d762498-f49e-436d-8dae-957b31c77c1d> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/adaad1292f884946ea64d1f068a59eba9f0216a40dc8ed353fc73646cda9d473> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/adaad1292f884946ea64d1f068a59eba9f0216a40dc8ed353fc73646cda9d473> a person:Person.
           <http://data.lblod.info/id/personen/adaad1292f884946ea64d1f068a59eba9f0216a40dc8ed353fc73646cda9d473> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/adaad1292f884946ea64d1f068a59eba9f0216a40dc8ed353fc73646cda9d473> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Olivier".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/adaad1292f884946ea64d1f068a59eba9f0216a40dc8ed353fc73646cda9d473> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/7541a637dfdfc494f6c16d67d8c539bb984f53e165e671af20e9ed197abba41c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7541a637dfdfc494f6c16d67d8c539bb984f53e165e671af20e9ed197abba41c> a person:Person.
           <http://data.lblod.info/id/personen/7541a637dfdfc494f6c16d67d8c539bb984f53e165e671af20e9ed197abba41c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7541a637dfdfc494f6c16d67d8c539bb984f53e165e671af20e9ed197abba41c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Gust".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7541a637dfdfc494f6c16d67d8c539bb984f53e165e671af20e9ed197abba41c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/379ea6e3dc11730578bd1cd2389c029748becb6cf6d8381f38a929f2010aa145> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/379ea6e3dc11730578bd1cd2389c029748becb6cf6d8381f38a929f2010aa145> a person:Person.
           <http://data.lblod.info/id/personen/379ea6e3dc11730578bd1cd2389c029748becb6cf6d8381f38a929f2010aa145> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/379ea6e3dc11730578bd1cd2389c029748becb6cf6d8381f38a929f2010aa145> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Siebe".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/379ea6e3dc11730578bd1cd2389c029748becb6cf6d8381f38a929f2010aa145> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2eb462ce42d9d2d09ecc952b1b0d7383837a1f9e314ffa5e97f12db28e87b6a0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2eb462ce42d9d2d09ecc952b1b0d7383837a1f9e314ffa5e97f12db28e87b6a0> a person:Person.
           <http://data.lblod.info/id/personen/2eb462ce42d9d2d09ecc952b1b0d7383837a1f9e314ffa5e97f12db28e87b6a0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2eb462ce42d9d2d09ecc952b1b0d7383837a1f9e314ffa5e97f12db28e87b6a0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Eddy Marc".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2eb462ce42d9d2d09ecc952b1b0d7383837a1f9e314ffa5e97f12db28e87b6a0> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/04332a6d-c4b0-44e1-8c33-0dc765e76b71> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/04332a6d-c4b0-44e1-8c33-0dc765e76b71> a person:Person.
           <http://data.lblod.info/id/personen/04332a6d-c4b0-44e1-8c33-0dc765e76b71> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/04332a6d-c4b0-44e1-8c33-0dc765e76b71> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Katleen".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/04332a6d-c4b0-44e1-8c33-0dc765e76b71> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/1f135e8d049bcf68e104c2652fc2e493f476cb95340ad4c1cfc854a76edcfb86> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1f135e8d049bcf68e104c2652fc2e493f476cb95340ad4c1cfc854a76edcfb86> a person:Person.
           <http://data.lblod.info/id/personen/1f135e8d049bcf68e104c2652fc2e493f476cb95340ad4c1cfc854a76edcfb86> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1f135e8d049bcf68e104c2652fc2e493f476cb95340ad4c1cfc854a76edcfb86> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Yves".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1f135e8d049bcf68e104c2652fc2e493f476cb95340ad4c1cfc854a76edcfb86> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/c97c7b9e-f695-43aa-a92a-ab0a3398578e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c97c7b9e-f695-43aa-a92a-ab0a3398578e> a person:Person.
           <http://data.lblod.info/id/personen/c97c7b9e-f695-43aa-a92a-ab0a3398578e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c97c7b9e-f695-43aa-a92a-ab0a3398578e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marylène".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c97c7b9e-f695-43aa-a92a-ab0a3398578e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/91de4fa3-effb-453a-bdd3-5841c4eb8eb0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/91de4fa3-effb-453a-bdd3-5841c4eb8eb0> a person:Person.
           <http://data.lblod.info/id/personen/91de4fa3-effb-453a-bdd3-5841c4eb8eb0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/91de4fa3-effb-453a-bdd3-5841c4eb8eb0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Wouter".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/91de4fa3-effb-453a-bdd3-5841c4eb8eb0> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/8efb15323dce97734f7fc45cb3aaf7effd95a56a1c15775fe49f1ad5a0ac2bfb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8efb15323dce97734f7fc45cb3aaf7effd95a56a1c15775fe49f1ad5a0ac2bfb> a person:Person.
           <http://data.lblod.info/id/personen/8efb15323dce97734f7fc45cb3aaf7effd95a56a1c15775fe49f1ad5a0ac2bfb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8efb15323dce97734f7fc45cb3aaf7effd95a56a1c15775fe49f1ad5a0ac2bfb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Monique".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8efb15323dce97734f7fc45cb3aaf7effd95a56a1c15775fe49f1ad5a0ac2bfb> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2d00c318-564d-4fd3-a94a-1c9a3da3dbc8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2d00c318-564d-4fd3-a94a-1c9a3da3dbc8> a person:Person.
           <http://data.lblod.info/id/personen/2d00c318-564d-4fd3-a94a-1c9a3da3dbc8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2d00c318-564d-4fd3-a94a-1c9a3da3dbc8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Stijn".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2d00c318-564d-4fd3-a94a-1c9a3da3dbc8> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/64f2102d-c944-483d-b95f-0d7336bc0778> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/64f2102d-c944-483d-b95f-0d7336bc0778> a person:Person.
           <http://data.lblod.info/id/personen/64f2102d-c944-483d-b95f-0d7336bc0778> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/64f2102d-c944-483d-b95f-0d7336bc0778> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Claudine".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/64f2102d-c944-483d-b95f-0d7336bc0778> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/9c8d0224e2d887fb57cd16eba62b5a34bcc1da85828f1d0dc265b88a534ef2a3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9c8d0224e2d887fb57cd16eba62b5a34bcc1da85828f1d0dc265b88a534ef2a3> a person:Person.
           <http://data.lblod.info/id/personen/9c8d0224e2d887fb57cd16eba62b5a34bcc1da85828f1d0dc265b88a534ef2a3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9c8d0224e2d887fb57cd16eba62b5a34bcc1da85828f1d0dc265b88a534ef2a3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Sylvia".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9c8d0224e2d887fb57cd16eba62b5a34bcc1da85828f1d0dc265b88a534ef2a3> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/3a0210bc87b585effebc2c1bde5b14511dc6b5892e3e751d941ed6b92f584819> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3a0210bc87b585effebc2c1bde5b14511dc6b5892e3e751d941ed6b92f584819> a person:Person.
           <http://data.lblod.info/id/personen/3a0210bc87b585effebc2c1bde5b14511dc6b5892e3e751d941ed6b92f584819> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3a0210bc87b585effebc2c1bde5b14511dc6b5892e3e751d941ed6b92f584819> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jacques".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3a0210bc87b585effebc2c1bde5b14511dc6b5892e3e751d941ed6b92f584819> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/0af21b823b6cb72629a04086f872c4d42d71dae1b6aa7e79d10438e69e680ec4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0af21b823b6cb72629a04086f872c4d42d71dae1b6aa7e79d10438e69e680ec4> a person:Person.
           <http://data.lblod.info/id/personen/0af21b823b6cb72629a04086f872c4d42d71dae1b6aa7e79d10438e69e680ec4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0af21b823b6cb72629a04086f872c4d42d71dae1b6aa7e79d10438e69e680ec4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Lieve".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0af21b823b6cb72629a04086f872c4d42d71dae1b6aa7e79d10438e69e680ec4> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/a6196941-79e9-407d-9171-40e3d385d03a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a6196941-79e9-407d-9171-40e3d385d03a> a person:Person.
           <http://data.lblod.info/id/personen/a6196941-79e9-407d-9171-40e3d385d03a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a6196941-79e9-407d-9171-40e3d385d03a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Annie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a6196941-79e9-407d-9171-40e3d385d03a> [] [].
          }
        }
     # finished voornamen-update-11744-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:04+00:00