# started voornamen-update-16243-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:15+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/1c4ee206-02be-46b3-b7f4-dec674d91625> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1c4ee206-02be-46b3-b7f4-dec674d91625> a person:Person.
           <http://data.lblod.info/id/personen/1c4ee206-02be-46b3-b7f4-dec674d91625> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1c4ee206-02be-46b3-b7f4-dec674d91625> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Sandra".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1c4ee206-02be-46b3-b7f4-dec674d91625> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/8b553be5-a6f2-420d-8d25-36dec0df2e61> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8b553be5-a6f2-420d-8d25-36dec0df2e61> a person:Person.
           <http://data.lblod.info/id/personen/8b553be5-a6f2-420d-8d25-36dec0df2e61> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8b553be5-a6f2-420d-8d25-36dec0df2e61> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Kathy".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8b553be5-a6f2-420d-8d25-36dec0df2e61> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/01976935-27cb-40f1-93a3-236a1c6036aa> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/01976935-27cb-40f1-93a3-236a1c6036aa> a person:Person.
           <http://data.lblod.info/id/personen/01976935-27cb-40f1-93a3-236a1c6036aa> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/01976935-27cb-40f1-93a3-236a1c6036aa> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Etienne".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/01976935-27cb-40f1-93a3-236a1c6036aa> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/b0158908-9c22-4ac3-90b0-4c45edcb33db> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b0158908-9c22-4ac3-90b0-4c45edcb33db> a person:Person.
           <http://data.lblod.info/id/personen/b0158908-9c22-4ac3-90b0-4c45edcb33db> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b0158908-9c22-4ac3-90b0-4c45edcb33db> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Isabelle".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b0158908-9c22-4ac3-90b0-4c45edcb33db> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e213232b-bb3b-459d-afe5-d7e63c863080> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e213232b-bb3b-459d-afe5-d7e63c863080> a person:Person.
           <http://data.lblod.info/id/personen/e213232b-bb3b-459d-afe5-d7e63c863080> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e213232b-bb3b-459d-afe5-d7e63c863080> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Carineke".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e213232b-bb3b-459d-afe5-d7e63c863080> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/8db0f84c-9560-41eb-8433-641227599b5a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8db0f84c-9560-41eb-8433-641227599b5a> a person:Person.
           <http://data.lblod.info/id/personen/8db0f84c-9560-41eb-8433-641227599b5a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8db0f84c-9560-41eb-8433-641227599b5a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Tim".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/8db0f84c-9560-41eb-8433-641227599b5a> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f5c91102-3848-4907-a102-32dbd28b94ae> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f5c91102-3848-4907-a102-32dbd28b94ae> a person:Person.
           <http://data.lblod.info/id/personen/f5c91102-3848-4907-a102-32dbd28b94ae> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f5c91102-3848-4907-a102-32dbd28b94ae> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Christel".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f5c91102-3848-4907-a102-32dbd28b94ae> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ac27a2b2-e9b3-4ce3-ae9f-4a345fe7bd41> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ac27a2b2-e9b3-4ce3-ae9f-4a345fe7bd41> a person:Person.
           <http://data.lblod.info/id/personen/ac27a2b2-e9b3-4ce3-ae9f-4a345fe7bd41> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ac27a2b2-e9b3-4ce3-ae9f-4a345fe7bd41> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Kelly".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ac27a2b2-e9b3-4ce3-ae9f-4a345fe7bd41> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/a9d81a5d-06cd-4a35-b4d2-05ce2d4dd58f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a9d81a5d-06cd-4a35-b4d2-05ce2d4dd58f> a person:Person.
           <http://data.lblod.info/id/personen/a9d81a5d-06cd-4a35-b4d2-05ce2d4dd58f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a9d81a5d-06cd-4a35-b4d2-05ce2d4dd58f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Yessin".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a9d81a5d-06cd-4a35-b4d2-05ce2d4dd58f> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/a2d83460-9776-416a-965d-9838f2c59f0d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a2d83460-9776-416a-965d-9838f2c59f0d> a person:Person.
           <http://data.lblod.info/id/personen/a2d83460-9776-416a-965d-9838f2c59f0d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a2d83460-9776-416a-965d-9838f2c59f0d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Tanguy".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a2d83460-9776-416a-965d-9838f2c59f0d> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/246245d4f3a61da6df0fd7e1c31f76c17fc96588e96fe72f97503e7d3c60c6fa> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/246245d4f3a61da6df0fd7e1c31f76c17fc96588e96fe72f97503e7d3c60c6fa> a person:Person.
           <http://data.lblod.info/id/personen/246245d4f3a61da6df0fd7e1c31f76c17fc96588e96fe72f97503e7d3c60c6fa> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/246245d4f3a61da6df0fd7e1c31f76c17fc96588e96fe72f97503e7d3c60c6fa> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Gerda".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/246245d4f3a61da6df0fd7e1c31f76c17fc96588e96fe72f97503e7d3c60c6fa> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/a9b484a4-5cd9-4021-aec3-0c2b6c4d26c5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a9b484a4-5cd9-4021-aec3-0c2b6c4d26c5> a person:Person.
           <http://data.lblod.info/id/personen/a9b484a4-5cd9-4021-aec3-0c2b6c4d26c5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a9b484a4-5cd9-4021-aec3-0c2b6c4d26c5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Nuri".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a9b484a4-5cd9-4021-aec3-0c2b6c4d26c5> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ad8d07a540ea89feb9e93485408f5792195c1d90433aac90c0b9057c5842e341> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ad8d07a540ea89feb9e93485408f5792195c1d90433aac90c0b9057c5842e341> a person:Person.
           <http://data.lblod.info/id/personen/ad8d07a540ea89feb9e93485408f5792195c1d90433aac90c0b9057c5842e341> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ad8d07a540ea89feb9e93485408f5792195c1d90433aac90c0b9057c5842e341> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Annemie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ad8d07a540ea89feb9e93485408f5792195c1d90433aac90c0b9057c5842e341> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/c604c299-5958-400d-a3bd-f0ed2b63128c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c604c299-5958-400d-a3bd-f0ed2b63128c> a person:Person.
           <http://data.lblod.info/id/personen/c604c299-5958-400d-a3bd-f0ed2b63128c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c604c299-5958-400d-a3bd-f0ed2b63128c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Hilde".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c604c299-5958-400d-a3bd-f0ed2b63128c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/6ae589b2-0cff-45b6-9a14-006c2f8d2295> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6ae589b2-0cff-45b6-9a14-006c2f8d2295> a person:Person.
           <http://data.lblod.info/id/personen/6ae589b2-0cff-45b6-9a14-006c2f8d2295> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6ae589b2-0cff-45b6-9a14-006c2f8d2295> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Geert".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6ae589b2-0cff-45b6-9a14-006c2f8d2295> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e6df64cc-744c-4d47-9eb7-b92c7f2d5f5f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e6df64cc-744c-4d47-9eb7-b92c7f2d5f5f> a person:Person.
           <http://data.lblod.info/id/personen/e6df64cc-744c-4d47-9eb7-b92c7f2d5f5f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e6df64cc-744c-4d47-9eb7-b92c7f2d5f5f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Bob".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e6df64cc-744c-4d47-9eb7-b92c7f2d5f5f> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/4418064f-1bbe-4033-b779-ea0599a0815c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4418064f-1bbe-4033-b779-ea0599a0815c> a person:Person.
           <http://data.lblod.info/id/personen/4418064f-1bbe-4033-b779-ea0599a0815c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4418064f-1bbe-4033-b779-ea0599a0815c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Mark".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4418064f-1bbe-4033-b779-ea0599a0815c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ff0e095c-4664-42a7-8680-a627d08d12ad> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ff0e095c-4664-42a7-8680-a627d08d12ad> a person:Person.
           <http://data.lblod.info/id/personen/ff0e095c-4664-42a7-8680-a627d08d12ad> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ff0e095c-4664-42a7-8680-a627d08d12ad> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ivan".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ff0e095c-4664-42a7-8680-a627d08d12ad> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/bd46c27b6e00f6491b93aa31b7b2251cbc1c8d527318ca6d7b545a6f1dbd936a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bd46c27b6e00f6491b93aa31b7b2251cbc1c8d527318ca6d7b545a6f1dbd936a> a person:Person.
           <http://data.lblod.info/id/personen/bd46c27b6e00f6491b93aa31b7b2251cbc1c8d527318ca6d7b545a6f1dbd936a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bd46c27b6e00f6491b93aa31b7b2251cbc1c8d527318ca6d7b545a6f1dbd936a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Danny".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/bd46c27b6e00f6491b93aa31b7b2251cbc1c8d527318ca6d7b545a6f1dbd936a> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/12714778-fc37-4acc-beaa-d4b245cc468a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/12714778-fc37-4acc-beaa-d4b245cc468a> a person:Person.
           <http://data.lblod.info/id/personen/12714778-fc37-4acc-beaa-d4b245cc468a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/12714778-fc37-4acc-beaa-d4b245cc468a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marc".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/12714778-fc37-4acc-beaa-d4b245cc468a> [] [].
          }
        }
     # finished voornamen-update-16243-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:15+00:00