# started voornamen-update-1419-2490de85e718ffa3e23344f4cd674bd5d9f40252833c8af6fb7fa3b82f44b008 at 2018-12-27T15:07:11+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/fddbcf76-baa7-41c3-9197-f71f80c24d4e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/fddbcf76-baa7-41c3-9197-f71f80c24d4e> a person:Person.
           <http://data.lblod.info/id/personen/fddbcf76-baa7-41c3-9197-f71f80c24d4e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/fddbcf76-baa7-41c3-9197-f71f80c24d4e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ria".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/fddbcf76-baa7-41c3-9197-f71f80c24d4e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/efdc0927a2e729973c1019234b8238c7fab125890b0223c46e76131c0ff19165> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/efdc0927a2e729973c1019234b8238c7fab125890b0223c46e76131c0ff19165> a person:Person.
           <http://data.lblod.info/id/personen/efdc0927a2e729973c1019234b8238c7fab125890b0223c46e76131c0ff19165> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/efdc0927a2e729973c1019234b8238c7fab125890b0223c46e76131c0ff19165> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Stan".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/efdc0927a2e729973c1019234b8238c7fab125890b0223c46e76131c0ff19165> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/5724e99fa9834b8cd31d3c2427a3b0cfb433ae10a15d5f9dc503508139120966> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5724e99fa9834b8cd31d3c2427a3b0cfb433ae10a15d5f9dc503508139120966> a person:Person.
           <http://data.lblod.info/id/personen/5724e99fa9834b8cd31d3c2427a3b0cfb433ae10a15d5f9dc503508139120966> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5724e99fa9834b8cd31d3c2427a3b0cfb433ae10a15d5f9dc503508139120966> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Kris".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5724e99fa9834b8cd31d3c2427a3b0cfb433ae10a15d5f9dc503508139120966> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/c16c90f8-f7ad-4858-9380-22a2d1f204b5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c16c90f8-f7ad-4858-9380-22a2d1f204b5> a person:Person.
           <http://data.lblod.info/id/personen/c16c90f8-f7ad-4858-9380-22a2d1f204b5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c16c90f8-f7ad-4858-9380-22a2d1f204b5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Peggy".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c16c90f8-f7ad-4858-9380-22a2d1f204b5> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/3dcb72a4-c27d-49d7-b107-6645d7199e35> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3dcb72a4-c27d-49d7-b107-6645d7199e35> a person:Person.
           <http://data.lblod.info/id/personen/3dcb72a4-c27d-49d7-b107-6645d7199e35> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3dcb72a4-c27d-49d7-b107-6645d7199e35> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Laura".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3dcb72a4-c27d-49d7-b107-6645d7199e35> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ec6dc814-30ed-465b-8ec0-140322450428> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ec6dc814-30ed-465b-8ec0-140322450428> a person:Person.
           <http://data.lblod.info/id/personen/ec6dc814-30ed-465b-8ec0-140322450428> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ec6dc814-30ed-465b-8ec0-140322450428> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Luc".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ec6dc814-30ed-465b-8ec0-140322450428> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/d1d5b1f5-59ba-4ffc-8dee-e869b6cb168a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d1d5b1f5-59ba-4ffc-8dee-e869b6cb168a> a person:Person.
           <http://data.lblod.info/id/personen/d1d5b1f5-59ba-4ffc-8dee-e869b6cb168a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d1d5b1f5-59ba-4ffc-8dee-e869b6cb168a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Regina".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d1d5b1f5-59ba-4ffc-8dee-e869b6cb168a> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ad2109c7-3e88-44a1-aa75-f0394c4fde50> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ad2109c7-3e88-44a1-aa75-f0394c4fde50> a person:Person.
           <http://data.lblod.info/id/personen/ad2109c7-3e88-44a1-aa75-f0394c4fde50> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ad2109c7-3e88-44a1-aa75-f0394c4fde50> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Thierry".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ad2109c7-3e88-44a1-aa75-f0394c4fde50> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/17fbcf0a-1750-4d04-b6e5-9576c02f5563> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/17fbcf0a-1750-4d04-b6e5-9576c02f5563> a person:Person.
           <http://data.lblod.info/id/personen/17fbcf0a-1750-4d04-b6e5-9576c02f5563> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/17fbcf0a-1750-4d04-b6e5-9576c02f5563> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Oona".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/17fbcf0a-1750-4d04-b6e5-9576c02f5563> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/7f014618-c01b-4c42-89cd-0bff55fdde23> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7f014618-c01b-4c42-89cd-0bff55fdde23> a person:Person.
           <http://data.lblod.info/id/personen/7f014618-c01b-4c42-89cd-0bff55fdde23> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7f014618-c01b-4c42-89cd-0bff55fdde23> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Kristine".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7f014618-c01b-4c42-89cd-0bff55fdde23> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f78241bc-3fb3-4573-b827-95e00c021586> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f78241bc-3fb3-4573-b827-95e00c021586> a person:Person.
           <http://data.lblod.info/id/personen/f78241bc-3fb3-4573-b827-95e00c021586> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f78241bc-3fb3-4573-b827-95e00c021586> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Stephan".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f78241bc-3fb3-4573-b827-95e00c021586> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/89f2df24-f46e-4441-a9fc-65b2a0635b2b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/89f2df24-f46e-4441-a9fc-65b2a0635b2b> a person:Person.
           <http://data.lblod.info/id/personen/89f2df24-f46e-4441-a9fc-65b2a0635b2b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/89f2df24-f46e-4441-a9fc-65b2a0635b2b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Annelies".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/89f2df24-f46e-4441-a9fc-65b2a0635b2b> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/68071a5a-1e08-4aed-b52e-7b0e7c29abc3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/68071a5a-1e08-4aed-b52e-7b0e7c29abc3> a person:Person.
           <http://data.lblod.info/id/personen/68071a5a-1e08-4aed-b52e-7b0e7c29abc3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/68071a5a-1e08-4aed-b52e-7b0e7c29abc3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Steven".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/68071a5a-1e08-4aed-b52e-7b0e7c29abc3> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e70c389f4df1ace1476337fcebd260eb61cfb754b1b3e998227a918f2dfc7e34> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e70c389f4df1ace1476337fcebd260eb61cfb754b1b3e998227a918f2dfc7e34> a person:Person.
           <http://data.lblod.info/id/personen/e70c389f4df1ace1476337fcebd260eb61cfb754b1b3e998227a918f2dfc7e34> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e70c389f4df1ace1476337fcebd260eb61cfb754b1b3e998227a918f2dfc7e34> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ward".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e70c389f4df1ace1476337fcebd260eb61cfb754b1b3e998227a918f2dfc7e34> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/cae64ba7-e1e8-4572-a08e-930acaff168a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cae64ba7-e1e8-4572-a08e-930acaff168a> a person:Person.
           <http://data.lblod.info/id/personen/cae64ba7-e1e8-4572-a08e-930acaff168a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cae64ba7-e1e8-4572-a08e-930acaff168a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Nicole".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/cae64ba7-e1e8-4572-a08e-930acaff168a> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/5c8bf1f8-6ded-489f-b3e8-82d5e723c9f0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5c8bf1f8-6ded-489f-b3e8-82d5e723c9f0> a person:Person.
           <http://data.lblod.info/id/personen/5c8bf1f8-6ded-489f-b3e8-82d5e723c9f0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5c8bf1f8-6ded-489f-b3e8-82d5e723c9f0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Diane".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5c8bf1f8-6ded-489f-b3e8-82d5e723c9f0> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2c865cbe-3dbc-4ffa-9f11-2449fa982b07> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2c865cbe-3dbc-4ffa-9f11-2449fa982b07> a person:Person.
           <http://data.lblod.info/id/personen/2c865cbe-3dbc-4ffa-9f11-2449fa982b07> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2c865cbe-3dbc-4ffa-9f11-2449fa982b07> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Bruno".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2c865cbe-3dbc-4ffa-9f11-2449fa982b07> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/b2c88a725b3d84304c8b53b8c516c7daab04a3ab7101195d300324474f6c0edc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b2c88a725b3d84304c8b53b8c516c7daab04a3ab7101195d300324474f6c0edc> a person:Person.
           <http://data.lblod.info/id/personen/b2c88a725b3d84304c8b53b8c516c7daab04a3ab7101195d300324474f6c0edc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b2c88a725b3d84304c8b53b8c516c7daab04a3ab7101195d300324474f6c0edc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Wendy".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b2c88a725b3d84304c8b53b8c516c7daab04a3ab7101195d300324474f6c0edc> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ec7e7d40-394a-44cb-b05f-e36743e105fa> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ec7e7d40-394a-44cb-b05f-e36743e105fa> a person:Person.
           <http://data.lblod.info/id/personen/ec7e7d40-394a-44cb-b05f-e36743e105fa> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ec7e7d40-394a-44cb-b05f-e36743e105fa> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Bart".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ec7e7d40-394a-44cb-b05f-e36743e105fa> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/da8e9b19-1176-4935-beba-b963fa987744> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/da8e9b19-1176-4935-beba-b963fa987744> a person:Person.
           <http://data.lblod.info/id/personen/da8e9b19-1176-4935-beba-b963fa987744> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/da8e9b19-1176-4935-beba-b963fa987744> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Hilde".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/da8e9b19-1176-4935-beba-b963fa987744> [] [].
          }
        }
     # finished voornamen-update-1419-2490de85e718ffa3e23344f4cd674bd5d9f40252833c8af6fb7fa3b82f44b008 at 2018-12-27T15:07:11+00:00