# started voornamen-update-22447-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:31+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/fc5c953b-e402-49f4-8498-0abeeddd286e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/fc5c953b-e402-49f4-8498-0abeeddd286e> a person:Person.
           <http://data.lblod.info/id/personen/fc5c953b-e402-49f4-8498-0abeeddd286e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/fc5c953b-e402-49f4-8498-0abeeddd286e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Lieven".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/fc5c953b-e402-49f4-8498-0abeeddd286e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/26cf07fe-ff75-450c-9027-f32a31e92517> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/26cf07fe-ff75-450c-9027-f32a31e92517> a person:Person.
           <http://data.lblod.info/id/personen/26cf07fe-ff75-450c-9027-f32a31e92517> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/26cf07fe-ff75-450c-9027-f32a31e92517> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Andel".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/26cf07fe-ff75-450c-9027-f32a31e92517> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/78390ffa-8ada-457e-8027-02a82a60d2dc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/78390ffa-8ada-457e-8027-02a82a60d2dc> a person:Person.
           <http://data.lblod.info/id/personen/78390ffa-8ada-457e-8027-02a82a60d2dc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/78390ffa-8ada-457e-8027-02a82a60d2dc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Stijn".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/78390ffa-8ada-457e-8027-02a82a60d2dc> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/b8049279-0944-40d0-afb1-92236f1fa03f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b8049279-0944-40d0-afb1-92236f1fa03f> a person:Person.
           <http://data.lblod.info/id/personen/b8049279-0944-40d0-afb1-92236f1fa03f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b8049279-0944-40d0-afb1-92236f1fa03f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Kathleen".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b8049279-0944-40d0-afb1-92236f1fa03f> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/09c2c82d-f292-47ff-af44-626264e64290> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/09c2c82d-f292-47ff-af44-626264e64290> a person:Person.
           <http://data.lblod.info/id/personen/09c2c82d-f292-47ff-af44-626264e64290> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/09c2c82d-f292-47ff-af44-626264e64290> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Thierry".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/09c2c82d-f292-47ff-af44-626264e64290> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/c6189bf8aa804e0a20423e8266fe0a1a155d4b224245080d11dfd280921a7fd3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c6189bf8aa804e0a20423e8266fe0a1a155d4b224245080d11dfd280921a7fd3> a person:Person.
           <http://data.lblod.info/id/personen/c6189bf8aa804e0a20423e8266fe0a1a155d4b224245080d11dfd280921a7fd3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c6189bf8aa804e0a20423e8266fe0a1a155d4b224245080d11dfd280921a7fd3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jannick".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c6189bf8aa804e0a20423e8266fe0a1a155d4b224245080d11dfd280921a7fd3> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/566b7568-a32a-4483-a391-33a8efec9eed> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/566b7568-a32a-4483-a391-33a8efec9eed> a person:Person.
           <http://data.lblod.info/id/personen/566b7568-a32a-4483-a391-33a8efec9eed> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/566b7568-a32a-4483-a391-33a8efec9eed> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Katrien".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/566b7568-a32a-4483-a391-33a8efec9eed> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/53e05aa3-b12b-4887-81d8-b9570c18baa2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/53e05aa3-b12b-4887-81d8-b9570c18baa2> a person:Person.
           <http://data.lblod.info/id/personen/53e05aa3-b12b-4887-81d8-b9570c18baa2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/53e05aa3-b12b-4887-81d8-b9570c18baa2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Lina".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/53e05aa3-b12b-4887-81d8-b9570c18baa2> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e27d3c46-b905-47ef-a705-12f02f4840c9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e27d3c46-b905-47ef-a705-12f02f4840c9> a person:Person.
           <http://data.lblod.info/id/personen/e27d3c46-b905-47ef-a705-12f02f4840c9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e27d3c46-b905-47ef-a705-12f02f4840c9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Peter".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e27d3c46-b905-47ef-a705-12f02f4840c9> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/602311c6-2fb9-446d-9d1c-eb466c269f4c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/602311c6-2fb9-446d-9d1c-eb466c269f4c> a person:Person.
           <http://data.lblod.info/id/personen/602311c6-2fb9-446d-9d1c-eb466c269f4c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/602311c6-2fb9-446d-9d1c-eb466c269f4c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Geert".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/602311c6-2fb9-446d-9d1c-eb466c269f4c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/af9d48fc-3a98-475e-b365-5cffe7b53058> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/af9d48fc-3a98-475e-b365-5cffe7b53058> a person:Person.
           <http://data.lblod.info/id/personen/af9d48fc-3a98-475e-b365-5cffe7b53058> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/af9d48fc-3a98-475e-b365-5cffe7b53058> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ann".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/af9d48fc-3a98-475e-b365-5cffe7b53058> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e5e0d2ab-077c-4117-a3fd-1434755d97f2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e5e0d2ab-077c-4117-a3fd-1434755d97f2> a person:Person.
           <http://data.lblod.info/id/personen/e5e0d2ab-077c-4117-a3fd-1434755d97f2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e5e0d2ab-077c-4117-a3fd-1434755d97f2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Francis".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e5e0d2ab-077c-4117-a3fd-1434755d97f2> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/7955a490c90fe79934057535d0282f21a7f803a0e3b4aa295825e461efa3422d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7955a490c90fe79934057535d0282f21a7f803a0e3b4aa295825e461efa3422d> a person:Person.
           <http://data.lblod.info/id/personen/7955a490c90fe79934057535d0282f21a7f803a0e3b4aa295825e461efa3422d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7955a490c90fe79934057535d0282f21a7f803a0e3b4aa295825e461efa3422d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Greet".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7955a490c90fe79934057535d0282f21a7f803a0e3b4aa295825e461efa3422d> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2081057d89ea260d7ab70d7c2603a7c19cb142fab714039551e011ff7f973ae7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2081057d89ea260d7ab70d7c2603a7c19cb142fab714039551e011ff7f973ae7> a person:Person.
           <http://data.lblod.info/id/personen/2081057d89ea260d7ab70d7c2603a7c19cb142fab714039551e011ff7f973ae7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2081057d89ea260d7ab70d7c2603a7c19cb142fab714039551e011ff7f973ae7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Fino".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2081057d89ea260d7ab70d7c2603a7c19cb142fab714039551e011ff7f973ae7> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/7e3be652-5cc1-4d8b-b9ef-7617d556d222> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7e3be652-5cc1-4d8b-b9ef-7617d556d222> a person:Person.
           <http://data.lblod.info/id/personen/7e3be652-5cc1-4d8b-b9ef-7617d556d222> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7e3be652-5cc1-4d8b-b9ef-7617d556d222> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Nele".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/7e3be652-5cc1-4d8b-b9ef-7617d556d222> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/d39a24744a5dc2adf94ef56f0f8fcc01aa6da1608394f6b13d59b5918e387c4a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d39a24744a5dc2adf94ef56f0f8fcc01aa6da1608394f6b13d59b5918e387c4a> a person:Person.
           <http://data.lblod.info/id/personen/d39a24744a5dc2adf94ef56f0f8fcc01aa6da1608394f6b13d59b5918e387c4a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d39a24744a5dc2adf94ef56f0f8fcc01aa6da1608394f6b13d59b5918e387c4a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Bram".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d39a24744a5dc2adf94ef56f0f8fcc01aa6da1608394f6b13d59b5918e387c4a> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/da6da27c-296f-495f-b85d-34475faf5454> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/da6da27c-296f-495f-b85d-34475faf5454> a person:Person.
           <http://data.lblod.info/id/personen/da6da27c-296f-495f-b85d-34475faf5454> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/da6da27c-296f-495f-b85d-34475faf5454> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Xavier".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/da6da27c-296f-495f-b85d-34475faf5454> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/5b9c1e45-1ffb-431b-bb64-069cdf8fa8b6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5b9c1e45-1ffb-431b-bb64-069cdf8fa8b6> a person:Person.
           <http://data.lblod.info/id/personen/5b9c1e45-1ffb-431b-bb64-069cdf8fa8b6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5b9c1e45-1ffb-431b-bb64-069cdf8fa8b6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Christel".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5b9c1e45-1ffb-431b-bb64-069cdf8fa8b6> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/30a4e7538163504a18460153525e3a2a88b8c6c951166a963c31b98686d50db9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/30a4e7538163504a18460153525e3a2a88b8c6c951166a963c31b98686d50db9> a person:Person.
           <http://data.lblod.info/id/personen/30a4e7538163504a18460153525e3a2a88b8c6c951166a963c31b98686d50db9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/30a4e7538163504a18460153525e3a2a88b8c6c951166a963c31b98686d50db9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ben".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/30a4e7538163504a18460153525e3a2a88b8c6c951166a963c31b98686d50db9> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/5457f7ee70f408e51859a30ea2f8464a80a1e8c56d4abfd441cd3be5e0d61afe> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5457f7ee70f408e51859a30ea2f8464a80a1e8c56d4abfd441cd3be5e0d61afe> a person:Person.
           <http://data.lblod.info/id/personen/5457f7ee70f408e51859a30ea2f8464a80a1e8c56d4abfd441cd3be5e0d61afe> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5457f7ee70f408e51859a30ea2f8464a80a1e8c56d4abfd441cd3be5e0d61afe> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Isabel".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5457f7ee70f408e51859a30ea2f8464a80a1e8c56d4abfd441cd3be5e0d61afe> [] [].
          }
        }
     # finished voornamen-update-22447-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:31+00:00