# started voornamen-update-19773-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:24+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e598060b5a48626c22e6a8ecee6c8c8587070fa68745b611fc5ed3a81491e082> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e598060b5a48626c22e6a8ecee6c8c8587070fa68745b611fc5ed3a81491e082> a person:Person.
           <http://data.lblod.info/id/personen/e598060b5a48626c22e6a8ecee6c8c8587070fa68745b611fc5ed3a81491e082> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e598060b5a48626c22e6a8ecee6c8c8587070fa68745b611fc5ed3a81491e082> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Maarten".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e598060b5a48626c22e6a8ecee6c8c8587070fa68745b611fc5ed3a81491e082> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/87ac0d68-a637-4f14-9ddd-b99feae407b1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/87ac0d68-a637-4f14-9ddd-b99feae407b1> a person:Person.
           <http://data.lblod.info/id/personen/87ac0d68-a637-4f14-9ddd-b99feae407b1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/87ac0d68-a637-4f14-9ddd-b99feae407b1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Els".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/87ac0d68-a637-4f14-9ddd-b99feae407b1> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/65ac48ed-0025-4374-86d5-17fb7289c314> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/65ac48ed-0025-4374-86d5-17fb7289c314> a person:Person.
           <http://data.lblod.info/id/personen/65ac48ed-0025-4374-86d5-17fb7289c314> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/65ac48ed-0025-4374-86d5-17fb7289c314> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Arno".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/65ac48ed-0025-4374-86d5-17fb7289c314> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/94ab6c04-0ca0-4521-bb90-0acc2eb30f0a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/94ab6c04-0ca0-4521-bb90-0acc2eb30f0a> a person:Person.
           <http://data.lblod.info/id/personen/94ab6c04-0ca0-4521-bb90-0acc2eb30f0a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/94ab6c04-0ca0-4521-bb90-0acc2eb30f0a> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marc".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/94ab6c04-0ca0-4521-bb90-0acc2eb30f0a> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f38ffd54-644f-4281-8607-750fc33c5b64> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f38ffd54-644f-4281-8607-750fc33c5b64> a person:Person.
           <http://data.lblod.info/id/personen/f38ffd54-644f-4281-8607-750fc33c5b64> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f38ffd54-644f-4281-8607-750fc33c5b64> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Annemieke".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f38ffd54-644f-4281-8607-750fc33c5b64> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e71baa121aa27c85d3319573dec154df53572633ce1c4aea770495da122172e6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e71baa121aa27c85d3319573dec154df53572633ce1c4aea770495da122172e6> a person:Person.
           <http://data.lblod.info/id/personen/e71baa121aa27c85d3319573dec154df53572633ce1c4aea770495da122172e6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e71baa121aa27c85d3319573dec154df53572633ce1c4aea770495da122172e6> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Onwuka Otisi".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e71baa121aa27c85d3319573dec154df53572633ce1c4aea770495da122172e6> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/ab9141fb-d1e3-44a5-856f-abf36b026844> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ab9141fb-d1e3-44a5-856f-abf36b026844> a person:Person.
           <http://data.lblod.info/id/personen/ab9141fb-d1e3-44a5-856f-abf36b026844> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ab9141fb-d1e3-44a5-856f-abf36b026844> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Julie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/ab9141fb-d1e3-44a5-856f-abf36b026844> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/6e08f73b-6673-4e2f-bce9-9565fd38fc85> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6e08f73b-6673-4e2f-bce9-9565fd38fc85> a person:Person.
           <http://data.lblod.info/id/personen/6e08f73b-6673-4e2f-bce9-9565fd38fc85> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6e08f73b-6673-4e2f-bce9-9565fd38fc85> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Moïse".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/6e08f73b-6673-4e2f-bce9-9565fd38fc85> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2f5ce97e-405c-43bb-a2e9-d9122bc3464e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2f5ce97e-405c-43bb-a2e9-d9122bc3464e> a person:Person.
           <http://data.lblod.info/id/personen/2f5ce97e-405c-43bb-a2e9-d9122bc3464e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2f5ce97e-405c-43bb-a2e9-d9122bc3464e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Bart".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2f5ce97e-405c-43bb-a2e9-d9122bc3464e> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/95519adf-884f-4ca3-be92-3996617befb5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/95519adf-884f-4ca3-be92-3996617befb5> a person:Person.
           <http://data.lblod.info/id/personen/95519adf-884f-4ca3-be92-3996617befb5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/95519adf-884f-4ca3-be92-3996617befb5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Bernard".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/95519adf-884f-4ca3-be92-3996617befb5> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f2c12e442a9b9b4186ad1e7c9fa6d41ff1664c9a5dc5e99c2bec1ab2515e3121> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f2c12e442a9b9b4186ad1e7c9fa6d41ff1664c9a5dc5e99c2bec1ab2515e3121> a person:Person.
           <http://data.lblod.info/id/personen/f2c12e442a9b9b4186ad1e7c9fa6d41ff1664c9a5dc5e99c2bec1ab2515e3121> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f2c12e442a9b9b4186ad1e7c9fa6d41ff1664c9a5dc5e99c2bec1ab2515e3121> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Driek".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f2c12e442a9b9b4186ad1e7c9fa6d41ff1664c9a5dc5e99c2bec1ab2515e3121> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/d5b9e804d3148a7c8eb4c86a60911fb43fe257900fb45a977b2feb8d98c03b40> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d5b9e804d3148a7c8eb4c86a60911fb43fe257900fb45a977b2feb8d98c03b40> a person:Person.
           <http://data.lblod.info/id/personen/d5b9e804d3148a7c8eb4c86a60911fb43fe257900fb45a977b2feb8d98c03b40> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d5b9e804d3148a7c8eb4c86a60911fb43fe257900fb45a977b2feb8d98c03b40> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Wendy".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d5b9e804d3148a7c8eb4c86a60911fb43fe257900fb45a977b2feb8d98c03b40> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/a3bf162d-06bf-46f3-a99c-3d687f0809bc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a3bf162d-06bf-46f3-a99c-3d687f0809bc> a person:Person.
           <http://data.lblod.info/id/personen/a3bf162d-06bf-46f3-a99c-3d687f0809bc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a3bf162d-06bf-46f3-a99c-3d687f0809bc> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Frank".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a3bf162d-06bf-46f3-a99c-3d687f0809bc> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/9b0ba6f0-4fde-410a-ad0e-e699017e988f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9b0ba6f0-4fde-410a-ad0e-e699017e988f> a person:Person.
           <http://data.lblod.info/id/personen/9b0ba6f0-4fde-410a-ad0e-e699017e988f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9b0ba6f0-4fde-410a-ad0e-e699017e988f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Olivier".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9b0ba6f0-4fde-410a-ad0e-e699017e988f> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/4afb3ccd-8de0-4c9a-9d07-7097577250e4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4afb3ccd-8de0-4c9a-9d07-7097577250e4> a person:Person.
           <http://data.lblod.info/id/personen/4afb3ccd-8de0-4c9a-9d07-7097577250e4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4afb3ccd-8de0-4c9a-9d07-7097577250e4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Viviane".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4afb3ccd-8de0-4c9a-9d07-7097577250e4> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/f21947fc-32d1-4351-b0e2-35dfcbfc80f2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f21947fc-32d1-4351-b0e2-35dfcbfc80f2> a person:Person.
           <http://data.lblod.info/id/personen/f21947fc-32d1-4351-b0e2-35dfcbfc80f2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f21947fc-32d1-4351-b0e2-35dfcbfc80f2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Nico".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/f21947fc-32d1-4351-b0e2-35dfcbfc80f2> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/c7c3b054-cfc1-4d8c-8645-a07787291096> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c7c3b054-cfc1-4d8c-8645-a07787291096> a person:Person.
           <http://data.lblod.info/id/personen/c7c3b054-cfc1-4d8c-8645-a07787291096> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c7c3b054-cfc1-4d8c-8645-a07787291096> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Carine".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c7c3b054-cfc1-4d8c-8645-a07787291096> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/4fb08fb1-054e-4ecf-8ad9-2b73be0da762> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4fb08fb1-054e-4ecf-8ad9-2b73be0da762> a person:Person.
           <http://data.lblod.info/id/personen/4fb08fb1-054e-4ecf-8ad9-2b73be0da762> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4fb08fb1-054e-4ecf-8ad9-2b73be0da762> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Elana".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4fb08fb1-054e-4ecf-8ad9-2b73be0da762> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/db037bf8-bc72-4e77-b0af-1035569bcf25> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/db037bf8-bc72-4e77-b0af-1035569bcf25> a person:Person.
           <http://data.lblod.info/id/personen/db037bf8-bc72-4e77-b0af-1035569bcf25> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/db037bf8-bc72-4e77-b0af-1035569bcf25> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marc".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/db037bf8-bc72-4e77-b0af-1035569bcf25> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/72ff6ddc-4b11-4ba8-877e-391b02954feb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/72ff6ddc-4b11-4ba8-877e-391b02954feb> a person:Person.
           <http://data.lblod.info/id/personen/72ff6ddc-4b11-4ba8-877e-391b02954feb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/72ff6ddc-4b11-4ba8-877e-391b02954feb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Sarah".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/72ff6ddc-4b11-4ba8-877e-391b02954feb> [] [].
          }
        }
     # finished voornamen-update-19773-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:24+00:00