# started voornamen-update-15855-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:15+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/05db9f0afafafc38fdc7204a6d9f5c5f52a7a0d2effd115a493f77035274e29d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/05db9f0afafafc38fdc7204a6d9f5c5f52a7a0d2effd115a493f77035274e29d> a person:Person.
           <http://data.lblod.info/id/personen/05db9f0afafafc38fdc7204a6d9f5c5f52a7a0d2effd115a493f77035274e29d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/05db9f0afafafc38fdc7204a6d9f5c5f52a7a0d2effd115a493f77035274e29d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Pieter".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/05db9f0afafafc38fdc7204a6d9f5c5f52a7a0d2effd115a493f77035274e29d> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/0e6f1cdbe8e8aa90e6f05629da32d59f9f8cad4ba3c95e394ef238aab232cb67> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0e6f1cdbe8e8aa90e6f05629da32d59f9f8cad4ba3c95e394ef238aab232cb67> a person:Person.
           <http://data.lblod.info/id/personen/0e6f1cdbe8e8aa90e6f05629da32d59f9f8cad4ba3c95e394ef238aab232cb67> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0e6f1cdbe8e8aa90e6f05629da32d59f9f8cad4ba3c95e394ef238aab232cb67> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Mieke".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0e6f1cdbe8e8aa90e6f05629da32d59f9f8cad4ba3c95e394ef238aab232cb67> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/c0ab613b-6027-40ec-be9e-b9d86adb074f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c0ab613b-6027-40ec-be9e-b9d86adb074f> a person:Person.
           <http://data.lblod.info/id/personen/c0ab613b-6027-40ec-be9e-b9d86adb074f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c0ab613b-6027-40ec-be9e-b9d86adb074f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Pieterjan".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c0ab613b-6027-40ec-be9e-b9d86adb074f> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/466e0dc70e891d24b3a0e6848f8f85d9abc8a2a7e194a4988cce4831ccd1cdfb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/466e0dc70e891d24b3a0e6848f8f85d9abc8a2a7e194a4988cce4831ccd1cdfb> a person:Person.
           <http://data.lblod.info/id/personen/466e0dc70e891d24b3a0e6848f8f85d9abc8a2a7e194a4988cce4831ccd1cdfb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/466e0dc70e891d24b3a0e6848f8f85d9abc8a2a7e194a4988cce4831ccd1cdfb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ilse".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/466e0dc70e891d24b3a0e6848f8f85d9abc8a2a7e194a4988cce4831ccd1cdfb> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/d926f2d8-5063-4470-8723-64b83b0970c1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d926f2d8-5063-4470-8723-64b83b0970c1> a person:Person.
           <http://data.lblod.info/id/personen/d926f2d8-5063-4470-8723-64b83b0970c1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d926f2d8-5063-4470-8723-64b83b0970c1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Lou".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d926f2d8-5063-4470-8723-64b83b0970c1> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/03c7a2342a7e6c9650f6d2a16eff94f1f57ddc6d73d54fbefca42c13e84df9ec> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/03c7a2342a7e6c9650f6d2a16eff94f1f57ddc6d73d54fbefca42c13e84df9ec> a person:Person.
           <http://data.lblod.info/id/personen/03c7a2342a7e6c9650f6d2a16eff94f1f57ddc6d73d54fbefca42c13e84df9ec> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/03c7a2342a7e6c9650f6d2a16eff94f1f57ddc6d73d54fbefca42c13e84df9ec> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Roos".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/03c7a2342a7e6c9650f6d2a16eff94f1f57ddc6d73d54fbefca42c13e84df9ec> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/50e1048fef0630bd70a0540ad90cbf13f93f1e2c7d741024f62bff33aca27922> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/50e1048fef0630bd70a0540ad90cbf13f93f1e2c7d741024f62bff33aca27922> a person:Person.
           <http://data.lblod.info/id/personen/50e1048fef0630bd70a0540ad90cbf13f93f1e2c7d741024f62bff33aca27922> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/50e1048fef0630bd70a0540ad90cbf13f93f1e2c7d741024f62bff33aca27922> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Mieke".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/50e1048fef0630bd70a0540ad90cbf13f93f1e2c7d741024f62bff33aca27922> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/0b6e1a000f8879b23f3b48e84c20159e13d59a4b7477d64586173e2e0ccf2c83> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0b6e1a000f8879b23f3b48e84c20159e13d59a4b7477d64586173e2e0ccf2c83> a person:Person.
           <http://data.lblod.info/id/personen/0b6e1a000f8879b23f3b48e84c20159e13d59a4b7477d64586173e2e0ccf2c83> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0b6e1a000f8879b23f3b48e84c20159e13d59a4b7477d64586173e2e0ccf2c83> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Raf".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0b6e1a000f8879b23f3b48e84c20159e13d59a4b7477d64586173e2e0ccf2c83> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/00e9c922132a63f5ed47683dff819cf626ab588b6e92bb07746aca28fd1337cf> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/00e9c922132a63f5ed47683dff819cf626ab588b6e92bb07746aca28fd1337cf> a person:Person.
           <http://data.lblod.info/id/personen/00e9c922132a63f5ed47683dff819cf626ab588b6e92bb07746aca28fd1337cf> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/00e9c922132a63f5ed47683dff819cf626ab588b6e92bb07746aca28fd1337cf> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marleen".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/00e9c922132a63f5ed47683dff819cf626ab588b6e92bb07746aca28fd1337cf> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/effc206c-9d50-4151-8d43-df213c25edcd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/effc206c-9d50-4151-8d43-df213c25edcd> a person:Person.
           <http://data.lblod.info/id/personen/effc206c-9d50-4151-8d43-df213c25edcd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/effc206c-9d50-4151-8d43-df213c25edcd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Geert".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/effc206c-9d50-4151-8d43-df213c25edcd> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/1180e5ed-d563-4047-9d21-34cf949c3486> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1180e5ed-d563-4047-9d21-34cf949c3486> a person:Person.
           <http://data.lblod.info/id/personen/1180e5ed-d563-4047-9d21-34cf949c3486> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1180e5ed-d563-4047-9d21-34cf949c3486> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Hans".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1180e5ed-d563-4047-9d21-34cf949c3486> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/17ff0fa5-5ae0-4f19-8d3d-3dfcc9459508> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/17ff0fa5-5ae0-4f19-8d3d-3dfcc9459508> a person:Person.
           <http://data.lblod.info/id/personen/17ff0fa5-5ae0-4f19-8d3d-3dfcc9459508> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/17ff0fa5-5ae0-4f19-8d3d-3dfcc9459508> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Sigrid".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/17ff0fa5-5ae0-4f19-8d3d-3dfcc9459508> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/a1295559575a81a047bdf988c34d4a5c28293207c08155e1edb251ecb7c27cda> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a1295559575a81a047bdf988c34d4a5c28293207c08155e1edb251ecb7c27cda> a person:Person.
           <http://data.lblod.info/id/personen/a1295559575a81a047bdf988c34d4a5c28293207c08155e1edb251ecb7c27cda> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a1295559575a81a047bdf988c34d4a5c28293207c08155e1edb251ecb7c27cda> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Dirk".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a1295559575a81a047bdf988c34d4a5c28293207c08155e1edb251ecb7c27cda> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/b9959c0baef5ffc77ed0a0800179e3c9998fd01b72cb05702c36121026dcee03> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b9959c0baef5ffc77ed0a0800179e3c9998fd01b72cb05702c36121026dcee03> a person:Person.
           <http://data.lblod.info/id/personen/b9959c0baef5ffc77ed0a0800179e3c9998fd01b72cb05702c36121026dcee03> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b9959c0baef5ffc77ed0a0800179e3c9998fd01b72cb05702c36121026dcee03> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Relinde".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b9959c0baef5ffc77ed0a0800179e3c9998fd01b72cb05702c36121026dcee03> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/b3571400-b0a1-4729-89d1-920017a651eb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b3571400-b0a1-4729-89d1-920017a651eb> a person:Person.
           <http://data.lblod.info/id/personen/b3571400-b0a1-4729-89d1-920017a651eb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b3571400-b0a1-4729-89d1-920017a651eb> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Steven".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b3571400-b0a1-4729-89d1-920017a651eb> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/db0b173bb4d9cfea698e95edf7f08214ee11be823f36b5da45227ccd34e9ddc0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/db0b173bb4d9cfea698e95edf7f08214ee11be823f36b5da45227ccd34e9ddc0> a person:Person.
           <http://data.lblod.info/id/personen/db0b173bb4d9cfea698e95edf7f08214ee11be823f36b5da45227ccd34e9ddc0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/db0b173bb4d9cfea698e95edf7f08214ee11be823f36b5da45227ccd34e9ddc0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Els".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/db0b173bb4d9cfea698e95edf7f08214ee11be823f36b5da45227ccd34e9ddc0> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/0d25b8455acbab7b62f6f69ea95a08b48ed15b985a5d3b405c0968630efecaa0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0d25b8455acbab7b62f6f69ea95a08b48ed15b985a5d3b405c0968630efecaa0> a person:Person.
           <http://data.lblod.info/id/personen/0d25b8455acbab7b62f6f69ea95a08b48ed15b985a5d3b405c0968630efecaa0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0d25b8455acbab7b62f6f69ea95a08b48ed15b985a5d3b405c0968630efecaa0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Heidi".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/0d25b8455acbab7b62f6f69ea95a08b48ed15b985a5d3b405c0968630efecaa0> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/5768bc0a953ff78c45afb0957ded333f484be639052e8d8497e2cf7d81cc1258> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5768bc0a953ff78c45afb0957ded333f484be639052e8d8497e2cf7d81cc1258> a person:Person.
           <http://data.lblod.info/id/personen/5768bc0a953ff78c45afb0957ded333f484be639052e8d8497e2cf7d81cc1258> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5768bc0a953ff78c45afb0957ded333f484be639052e8d8497e2cf7d81cc1258> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Stefan".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/5768bc0a953ff78c45afb0957ded333f484be639052e8d8497e2cf7d81cc1258> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/19a11730-2189-41f9-8e76-cdef6879ebae> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/19a11730-2189-41f9-8e76-cdef6879ebae> a person:Person.
           <http://data.lblod.info/id/personen/19a11730-2189-41f9-8e76-cdef6879ebae> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/19a11730-2189-41f9-8e76-cdef6879ebae> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Stella".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/19a11730-2189-41f9-8e76-cdef6879ebae> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/d28441be-8285-442b-8c46-d42f9f454f6e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d28441be-8285-442b-8c46-d42f9f454f6e> a person:Person.
           <http://data.lblod.info/id/personen/d28441be-8285-442b-8c46-d42f9f454f6e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d28441be-8285-442b-8c46-d42f9f454f6e> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Eric".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/d28441be-8285-442b-8c46-d42f9f454f6e> [] [].
          }
        }
     # finished voornamen-update-15855-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:15+00:00