# started voornamen-update-170-2490de85e718ffa3e23344f4cd674bd5d9f40252833c8af6fb7fa3b82f44b008 at 2018-12-27T15:07:08+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/4f7094c0ad79184cfb3b3f8d59c5d5092f1bb9671ece726b08225b638a2d835f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4f7094c0ad79184cfb3b3f8d59c5d5092f1bb9671ece726b08225b638a2d835f> a person:Person.
           <http://data.lblod.info/id/personen/4f7094c0ad79184cfb3b3f8d59c5d5092f1bb9671ece726b08225b638a2d835f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4f7094c0ad79184cfb3b3f8d59c5d5092f1bb9671ece726b08225b638a2d835f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Lidwina".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4f7094c0ad79184cfb3b3f8d59c5d5092f1bb9671ece726b08225b638a2d835f> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/9b34d83f-3a30-4fc9-8ed4-27ff3c20472b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9b34d83f-3a30-4fc9-8ed4-27ff3c20472b> a person:Person.
           <http://data.lblod.info/id/personen/9b34d83f-3a30-4fc9-8ed4-27ff3c20472b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9b34d83f-3a30-4fc9-8ed4-27ff3c20472b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Gust".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9b34d83f-3a30-4fc9-8ed4-27ff3c20472b> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2d4d7458-1662-4ed4-afd3-767f7897bcec> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2d4d7458-1662-4ed4-afd3-767f7897bcec> a person:Person.
           <http://data.lblod.info/id/personen/2d4d7458-1662-4ed4-afd3-767f7897bcec> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2d4d7458-1662-4ed4-afd3-767f7897bcec> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Clara".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2d4d7458-1662-4ed4-afd3-767f7897bcec> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/4c0c612b-5bf0-41fa-b6cf-06396275218d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4c0c612b-5bf0-41fa-b6cf-06396275218d> a person:Person.
           <http://data.lblod.info/id/personen/4c0c612b-5bf0-41fa-b6cf-06396275218d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4c0c612b-5bf0-41fa-b6cf-06396275218d> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Cyriel".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/4c0c612b-5bf0-41fa-b6cf-06396275218d> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/640c0b300684908053091f40d7b6ba99c0d1255f7d688f413103ae5a85b4a5da> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/640c0b300684908053091f40d7b6ba99c0d1255f7d688f413103ae5a85b4a5da> a person:Person.
           <http://data.lblod.info/id/personen/640c0b300684908053091f40d7b6ba99c0d1255f7d688f413103ae5a85b4a5da> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/640c0b300684908053091f40d7b6ba99c0d1255f7d688f413103ae5a85b4a5da> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Anthony".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/640c0b300684908053091f40d7b6ba99c0d1255f7d688f413103ae5a85b4a5da> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/2738da7e-e4f4-4bfe-b3bd-e3f918b8d976> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2738da7e-e4f4-4bfe-b3bd-e3f918b8d976> a person:Person.
           <http://data.lblod.info/id/personen/2738da7e-e4f4-4bfe-b3bd-e3f918b8d976> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2738da7e-e4f4-4bfe-b3bd-e3f918b8d976> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Stella".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/2738da7e-e4f4-4bfe-b3bd-e3f918b8d976> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/80da1e737ab56d756c1c9e96c9d4721aad57bc5191cc336a819445e5e7c26408> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/80da1e737ab56d756c1c9e96c9d4721aad57bc5191cc336a819445e5e7c26408> a person:Person.
           <http://data.lblod.info/id/personen/80da1e737ab56d756c1c9e96c9d4721aad57bc5191cc336a819445e5e7c26408> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/80da1e737ab56d756c1c9e96c9d4721aad57bc5191cc336a819445e5e7c26408> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Steve".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/80da1e737ab56d756c1c9e96c9d4721aad57bc5191cc336a819445e5e7c26408> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/403af861-7613-4047-bda4-9a6dd859aac9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/403af861-7613-4047-bda4-9a6dd859aac9> a person:Person.
           <http://data.lblod.info/id/personen/403af861-7613-4047-bda4-9a6dd859aac9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/403af861-7613-4047-bda4-9a6dd859aac9> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Magalie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/403af861-7613-4047-bda4-9a6dd859aac9> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/9eb9958f-d809-47b0-bd84-677d3c676405> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9eb9958f-d809-47b0-bd84-677d3c676405> a person:Person.
           <http://data.lblod.info/id/personen/9eb9958f-d809-47b0-bd84-677d3c676405> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9eb9958f-d809-47b0-bd84-677d3c676405> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Brigitta".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9eb9958f-d809-47b0-bd84-677d3c676405> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e48d9e72f9b32576aa0a6df95b04de8849ab84a88bcd018d1044d71336b65bb5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e48d9e72f9b32576aa0a6df95b04de8849ab84a88bcd018d1044d71336b65bb5> a person:Person.
           <http://data.lblod.info/id/personen/e48d9e72f9b32576aa0a6df95b04de8849ab84a88bcd018d1044d71336b65bb5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e48d9e72f9b32576aa0a6df95b04de8849ab84a88bcd018d1044d71336b65bb5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jeroen-Vincent".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e48d9e72f9b32576aa0a6df95b04de8849ab84a88bcd018d1044d71336b65bb5> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/71607a2d-e15d-4b45-8f9c-4c08d0fadc06> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/71607a2d-e15d-4b45-8f9c-4c08d0fadc06> a person:Person.
           <http://data.lblod.info/id/personen/71607a2d-e15d-4b45-8f9c-4c08d0fadc06> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/71607a2d-e15d-4b45-8f9c-4c08d0fadc06> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ellen".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/71607a2d-e15d-4b45-8f9c-4c08d0fadc06> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/496987b86f51d0af5291377112028eb1066b4d954c762a3e15ffdf7af02b8d88> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/496987b86f51d0af5291377112028eb1066b4d954c762a3e15ffdf7af02b8d88> a person:Person.
           <http://data.lblod.info/id/personen/496987b86f51d0af5291377112028eb1066b4d954c762a3e15ffdf7af02b8d88> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/496987b86f51d0af5291377112028eb1066b4d954c762a3e15ffdf7af02b8d88> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Sofie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/496987b86f51d0af5291377112028eb1066b4d954c762a3e15ffdf7af02b8d88> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/1d528ab8-0c9f-4f1d-b91a-e2f2e0e93fd1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1d528ab8-0c9f-4f1d-b91a-e2f2e0e93fd1> a person:Person.
           <http://data.lblod.info/id/personen/1d528ab8-0c9f-4f1d-b91a-e2f2e0e93fd1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1d528ab8-0c9f-4f1d-b91a-e2f2e0e93fd1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Kim".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1d528ab8-0c9f-4f1d-b91a-e2f2e0e93fd1> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/eae68808-f3f4-468b-ac09-5be22dcf5dbe> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/eae68808-f3f4-468b-ac09-5be22dcf5dbe> a person:Person.
           <http://data.lblod.info/id/personen/eae68808-f3f4-468b-ac09-5be22dcf5dbe> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/eae68808-f3f4-468b-ac09-5be22dcf5dbe> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "William".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/eae68808-f3f4-468b-ac09-5be22dcf5dbe> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/eaae397d6429cbf86498c39518fe2b966739447acfcecd636e8b152b4b80f94f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/eaae397d6429cbf86498c39518fe2b966739447acfcecd636e8b152b4b80f94f> a person:Person.
           <http://data.lblod.info/id/personen/eaae397d6429cbf86498c39518fe2b966739447acfcecd636e8b152b4b80f94f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/eaae397d6429cbf86498c39518fe2b966739447acfcecd636e8b152b4b80f94f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Steven".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/eaae397d6429cbf86498c39518fe2b966739447acfcecd636e8b152b4b80f94f> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/798e5cf9-d553-4ba3-b67a-0696d3c1504c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/798e5cf9-d553-4ba3-b67a-0696d3c1504c> a person:Person.
           <http://data.lblod.info/id/personen/798e5cf9-d553-4ba3-b67a-0696d3c1504c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/798e5cf9-d553-4ba3-b67a-0696d3c1504c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Sotirios".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/798e5cf9-d553-4ba3-b67a-0696d3c1504c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/3aca38c2-68c8-43ff-9e3c-2ca4eefa3618> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3aca38c2-68c8-43ff-9e3c-2ca4eefa3618> a person:Person.
           <http://data.lblod.info/id/personen/3aca38c2-68c8-43ff-9e3c-2ca4eefa3618> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3aca38c2-68c8-43ff-9e3c-2ca4eefa3618> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Dorien".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/3aca38c2-68c8-43ff-9e3c-2ca4eefa3618> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/c3e81ebd-2ec2-4f97-a0e8-8a7786393f15> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c3e81ebd-2ec2-4f97-a0e8-8a7786393f15> a person:Person.
           <http://data.lblod.info/id/personen/c3e81ebd-2ec2-4f97-a0e8-8a7786393f15> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c3e81ebd-2ec2-4f97-a0e8-8a7786393f15> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Karel".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c3e81ebd-2ec2-4f97-a0e8-8a7786393f15> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/61336dda-0d2a-4d54-adde-cab59d3bb793> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/61336dda-0d2a-4d54-adde-cab59d3bb793> a person:Person.
           <http://data.lblod.info/id/personen/61336dda-0d2a-4d54-adde-cab59d3bb793> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/61336dda-0d2a-4d54-adde-cab59d3bb793> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Stephanie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/61336dda-0d2a-4d54-adde-cab59d3bb793> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/c154c172dbb3a1a9170507a6900fca37daa87a5ee95f99d124dd61bea16c3655> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c154c172dbb3a1a9170507a6900fca37daa87a5ee95f99d124dd61bea16c3655> a person:Person.
           <http://data.lblod.info/id/personen/c154c172dbb3a1a9170507a6900fca37daa87a5ee95f99d124dd61bea16c3655> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c154c172dbb3a1a9170507a6900fca37daa87a5ee95f99d124dd61bea16c3655> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Michelle".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c154c172dbb3a1a9170507a6900fca37daa87a5ee95f99d124dd61bea16c3655> [] [].
          }
        }
     # finished voornamen-update-170-2490de85e718ffa3e23344f4cd674bd5d9f40252833c8af6fb7fa3b82f44b008 at 2018-12-27T15:07:08+00:00