# started voornamen-update-27175-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:43+00:00
        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/98771937-ca08-4399-b957-dd966d4856f3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/98771937-ca08-4399-b957-dd966d4856f3> a person:Person.
           <http://data.lblod.info/id/personen/98771937-ca08-4399-b957-dd966d4856f3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/98771937-ca08-4399-b957-dd966d4856f3> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Dominique".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/98771937-ca08-4399-b957-dd966d4856f3> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/a499e9ca-cee9-40c7-a31d-df3a58703525> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a499e9ca-cee9-40c7-a31d-df3a58703525> a person:Person.
           <http://data.lblod.info/id/personen/a499e9ca-cee9-40c7-a31d-df3a58703525> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a499e9ca-cee9-40c7-a31d-df3a58703525> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Ivo".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a499e9ca-cee9-40c7-a31d-df3a58703525> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/db70fd1b-0db7-4cca-8ec2-e1a429198ca4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/db70fd1b-0db7-4cca-8ec2-e1a429198ca4> a person:Person.
           <http://data.lblod.info/id/personen/db70fd1b-0db7-4cca-8ec2-e1a429198ca4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/db70fd1b-0db7-4cca-8ec2-e1a429198ca4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Jackie".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/db70fd1b-0db7-4cca-8ec2-e1a429198ca4> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/a0d19d2e6a4babc9f5a65729193d43f2a70d1e366f536638f104bd7e4d34c5bd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a0d19d2e6a4babc9f5a65729193d43f2a70d1e366f536638f104bd7e4d34c5bd> a person:Person.
           <http://data.lblod.info/id/personen/a0d19d2e6a4babc9f5a65729193d43f2a70d1e366f536638f104bd7e4d34c5bd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a0d19d2e6a4babc9f5a65729193d43f2a70d1e366f536638f104bd7e4d34c5bd> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Martine".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/a0d19d2e6a4babc9f5a65729193d43f2a70d1e366f536638f104bd7e4d34c5bd> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/1ed6f9d4-e1ae-4dc0-9615-a46310522744> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1ed6f9d4-e1ae-4dc0-9615-a46310522744> a person:Person.
           <http://data.lblod.info/id/personen/1ed6f9d4-e1ae-4dc0-9615-a46310522744> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1ed6f9d4-e1ae-4dc0-9615-a46310522744> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Marie-Louise".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/1ed6f9d4-e1ae-4dc0-9615-a46310522744> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/eadf401724df4dafda11f67a3f2332f8c69e5fbf2b898490e141b3fea0ba808f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/eadf401724df4dafda11f67a3f2332f8c69e5fbf2b898490e141b3fea0ba808f> a person:Person.
           <http://data.lblod.info/id/personen/eadf401724df4dafda11f67a3f2332f8c69e5fbf2b898490e141b3fea0ba808f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/eadf401724df4dafda11f67a3f2332f8c69e5fbf2b898490e141b3fea0ba808f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Andréa".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/eadf401724df4dafda11f67a3f2332f8c69e5fbf2b898490e141b3fea0ba808f> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/b04a2034-3761-4592-9cfe-a016df5c6ce4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b04a2034-3761-4592-9cfe-a016df5c6ce4> a person:Person.
           <http://data.lblod.info/id/personen/b04a2034-3761-4592-9cfe-a016df5c6ce4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b04a2034-3761-4592-9cfe-a016df5c6ce4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Mario".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/b04a2034-3761-4592-9cfe-a016df5c6ce4> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/fe368e2bec03eb9a5966c6658d671dd3b73c2dcbd40a313d8d4cddbcb0557e59> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/fe368e2bec03eb9a5966c6658d671dd3b73c2dcbd40a313d8d4cddbcb0557e59> a person:Person.
           <http://data.lblod.info/id/personen/fe368e2bec03eb9a5966c6658d671dd3b73c2dcbd40a313d8d4cddbcb0557e59> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/fe368e2bec03eb9a5966c6658d671dd3b73c2dcbd40a313d8d4cddbcb0557e59> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Gino".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/fe368e2bec03eb9a5966c6658d671dd3b73c2dcbd40a313d8d4cddbcb0557e59> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/54ce18eace0b47449190f17dc928318db0688e802f113fc119e7889c015866f8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/54ce18eace0b47449190f17dc928318db0688e802f113fc119e7889c015866f8> a person:Person.
           <http://data.lblod.info/id/personen/54ce18eace0b47449190f17dc928318db0688e802f113fc119e7889c015866f8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/54ce18eace0b47449190f17dc928318db0688e802f113fc119e7889c015866f8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Noël".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/54ce18eace0b47449190f17dc928318db0688e802f113fc119e7889c015866f8> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/befde03b-7105-4801-92d8-f26d7c3aeb8f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/befde03b-7105-4801-92d8-f26d7c3aeb8f> a person:Person.
           <http://data.lblod.info/id/personen/befde03b-7105-4801-92d8-f26d7c3aeb8f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/befde03b-7105-4801-92d8-f26d7c3aeb8f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Bernard".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/befde03b-7105-4801-92d8-f26d7c3aeb8f> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/31d35653-bb21-4650-ac79-37476d0fd268> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/31d35653-bb21-4650-ac79-37476d0fd268> a person:Person.
           <http://data.lblod.info/id/personen/31d35653-bb21-4650-ac79-37476d0fd268> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/31d35653-bb21-4650-ac79-37476d0fd268> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Manuel".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/31d35653-bb21-4650-ac79-37476d0fd268> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/9352695f-d2f2-48b0-992d-05a8e08c70b8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9352695f-d2f2-48b0-992d-05a8e08c70b8> a person:Person.
           <http://data.lblod.info/id/personen/9352695f-d2f2-48b0-992d-05a8e08c70b8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9352695f-d2f2-48b0-992d-05a8e08c70b8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Koen".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9352695f-d2f2-48b0-992d-05a8e08c70b8> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/390eb808-d3e1-4aa8-b5d3-749a3fab8735> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/390eb808-d3e1-4aa8-b5d3-749a3fab8735> a person:Person.
           <http://data.lblod.info/id/personen/390eb808-d3e1-4aa8-b5d3-749a3fab8735> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/390eb808-d3e1-4aa8-b5d3-749a3fab8735> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Rita".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/390eb808-d3e1-4aa8-b5d3-749a3fab8735> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/9fb62e0b-d1eb-4743-9d20-cb754944781c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9fb62e0b-d1eb-4743-9d20-cb754944781c> a person:Person.
           <http://data.lblod.info/id/personen/9fb62e0b-d1eb-4743-9d20-cb754944781c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9fb62e0b-d1eb-4743-9d20-cb754944781c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Daisy".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/9fb62e0b-d1eb-4743-9d20-cb754944781c> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/c84758d748570b4f199e37ac78686ed2cc1b1a55c8ce836421fe607fbfedce3b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c84758d748570b4f199e37ac78686ed2cc1b1a55c8ce836421fe607fbfedce3b> a person:Person.
           <http://data.lblod.info/id/personen/c84758d748570b4f199e37ac78686ed2cc1b1a55c8ce836421fe607fbfedce3b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c84758d748570b4f199e37ac78686ed2cc1b1a55c8ce836421fe607fbfedce3b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Wendy".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/c84758d748570b4f199e37ac78686ed2cc1b1a55c8ce836421fe607fbfedce3b> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/405da396efc21b0479585545ef3cb95a73fd7d1da67f849a8d4b8b31b9269ff7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/405da396efc21b0479585545ef3cb95a73fd7d1da67f849a8d4b8b31b9269ff7> a person:Person.
           <http://data.lblod.info/id/personen/405da396efc21b0479585545ef3cb95a73fd7d1da67f849a8d4b8b31b9269ff7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/405da396efc21b0479585545ef3cb95a73fd7d1da67f849a8d4b8b31b9269ff7> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Patrick".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/405da396efc21b0479585545ef3cb95a73fd7d1da67f849a8d4b8b31b9269ff7> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/46063000eac4f9dc8c6fc01b6c9d2cd8d10971e4ed3164f178c99d4cfcdecfb5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/46063000eac4f9dc8c6fc01b6c9d2cd8d10971e4ed3164f178c99d4cfcdecfb5> a person:Person.
           <http://data.lblod.info/id/personen/46063000eac4f9dc8c6fc01b6c9d2cd8d10971e4ed3164f178c99d4cfcdecfb5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/46063000eac4f9dc8c6fc01b6c9d2cd8d10971e4ed3164f178c99d4cfcdecfb5> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Guido".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/46063000eac4f9dc8c6fc01b6c9d2cd8d10971e4ed3164f178c99d4cfcdecfb5> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/540ec8dd-044f-4756-ad2e-21ed0565b4b1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/540ec8dd-044f-4756-ad2e-21ed0565b4b1> a person:Person.
           <http://data.lblod.info/id/personen/540ec8dd-044f-4756-ad2e-21ed0565b4b1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/540ec8dd-044f-4756-ad2e-21ed0565b4b1> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Frederik".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/540ec8dd-044f-4756-ad2e-21ed0565b4b1> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/e3df1bd7-9d44-4c85-b03f-5de2d063f4a0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e3df1bd7-9d44-4c85-b03f-5de2d063f4a0> a person:Person.
           <http://data.lblod.info/id/personen/e3df1bd7-9d44-4c85-b03f-5de2d063f4a0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e3df1bd7-9d44-4c85-b03f-5de2d063f4a0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Carine".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/e3df1bd7-9d44-4c85-b03f-5de2d063f4a0> [] [].
          }
        }
     ;

        PREFIX person: <http://www.w3.org/ns/person#>
        DELETE {
          GRAPH ?g {
            <http://data.lblod.info/id/personen/54d95509-eee5-4742-a458-c636449bfd3c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/54d95509-eee5-4742-a458-c636449bfd3c> a person:Person.
           <http://data.lblod.info/id/personen/54d95509-eee5-4742-a458-c636449bfd3c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?first_name.
          }
        };
        INSERT {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/54d95509-eee5-4742-a458-c636449bfd3c> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Sylvia".
          }
        }
        WHERE {
          GRAPH ?g {
           <http://data.lblod.info/id/personen/54d95509-eee5-4742-a458-c636449bfd3c> [] [].
          }
        }
     # finished voornamen-update-27175-2d1ac8ebd0605d749de79ebdf03b52091a8fc8b05a6ae0f0816150b0e9c13189 at 2018-12-27T15:06:43+00:00