INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/bestuurseenheden/1820266bfcf4c0c9cf62582e1d2e4f7295224cbe24726fde42fd9bd31c76e632> <http://purl.org/dc/terms/identifier> "0212206801" ;
        <http://mu.semte.ch/vocabularies/ext/kbonummer> "0212206801" .
  }
}
