clients:
  - id: "1c5d34ca-4a76-456e-9cac-5c39fabeb90f"
    name: "example client"
    endpoint: "https://identityservicenotulenbeheer.azurewebsites.net/api/IdentityService?code=Ro9oOtnzBLqAkhFFdbcG3HybdtPpL5MVo4dMNfaBOm9XV8JFieaRCQ=="
