(in-package :mu-cl-resources)

(defparameter *cache-count-queries* nil)
(defparameter *supply-cache-headers-p* t
  "when non-nil, cache headers are supplied.  this works together with mu-cache.")
;;(setf *cache-model-properties-p* t)
(defparameter *include-count-in-paginated-responses* t
  "when non-nil, all paginated listings will contain the number
   of responses in the result object's meta.")
(defparameter *max-group-sorted-properties* nil)
(setf sparql:*experimental-no-application-graph-for-sudo-select-queries* t)

(read-domain-file "models/account.lisp")
(read-domain-file "models/adres.lisp")
(read-domain-file "models/agenda.lisp")
(read-domain-file "models/agenda-position.lisp")
(read-domain-file "models/agendapunt.lisp")
(read-domain-file "models/artikel.lisp")
(read-domain-file "models/attachment.lisp")
(read-domain-file "models/behandeling-van-agendapunt.lisp")
(read-domain-file "models/beleidsdomein-code.lisp")
(read-domain-file "models/besluitenlijst.lisp")
(read-domain-file "models/besluit.lisp")
(read-domain-file "models/bestuurseenheid-classificatie-code.lisp")
(read-domain-file "models/bestuurseenheid.lisp")
(read-domain-file "models/bestuursfunctie-code.lisp")
(read-domain-file "models/bestuursfunctie.lisp")
(read-domain-file "models/bestuursorgaan-classificatie-code.lisp")
(read-domain-file "models/bestuursorgaan.lisp")
(read-domain-file "models/blockchain-status.lisp")
(read-domain-file "models/concept.lisp")
(read-domain-file "models/concept-scheme.lisp")
(read-domain-file "models/contact-punt.lisp")
(read-domain-file "models/data-container.lisp")
(read-domain-file "models/document-container.lisp")
(read-domain-file "models/editor-document-folder.lisp")
(read-domain-file "models/editor-document.lisp")
(read-domain-file "models/editor-document-status.lisp")
(read-domain-file "models/file.lisp")
(read-domain-file "models/fractie.lisp")
(read-domain-file "models/fractietype.lisp")
(read-domain-file "models/functionaris.lisp")
(read-domain-file "models/functionaris-status-code.lisp")
(read-domain-file "models/geboorte.lisp")
(read-domain-file "models/gebruiker.lisp")
(read-domain-file "models/geslacht-code.lisp")
(read-domain-file "models/identificator.lisp")
(read-domain-file "models/intermission.lisp")
(read-domain-file "models/job-error.lisp")
(read-domain-file "models/job.lisp")
(read-domain-file "models/kandidatenlijst.lisp")
(read-domain-file "models/lidmaatschap.lisp")
(read-domain-file "models/lijsttype.lisp")
(read-domain-file "models/log-entry.lisp")
(read-domain-file "models/log-level.lisp")
(read-domain-file "models/log-source.lisp")
(read-domain-file "models/maatregelconcept.lisp")
(read-domain-file "models/mandaat.lisp")
(read-domain-file "models/mandataris.lisp")
(read-domain-file "models/mandataris-status-code.lisp")
(read-domain-file "models/notulen.lisp")
(read-domain-file "models/persoon.lisp")
(read-domain-file "models/positie.lisp")
(read-domain-file "models/publication-status-code.lisp")
(read-domain-file "models/published-resource.lisp")
(read-domain-file "models/publishing-log.lisp")
(read-domain-file "models/rdfs-class.lisp")
(read-domain-file "models/rdfs-property.lisp")
(read-domain-file "models/rechtsgrond-aanstelling.lisp")
(read-domain-file "models/rechtsgrond-artikel.lisp")
(read-domain-file "models/rechtsgrond-beeindiging.lisp")
(read-domain-file "models/rechtsgrond-besluit.lisp")
(read-domain-file "models/rechtsgrond.lisp")
(read-domain-file "models/rechtstreekse-verkiezing.lisp")
(read-domain-file "models/report.lisp")
(read-domain-file "models/rol.lisp")
(read-domain-file "models/signed-resource.lisp")
(read-domain-file "models/status-code.lisp")
(read-domain-file "models/stemming.lisp")
(read-domain-file "models/task.lisp")
(read-domain-file "models/tasklist.lisp")
(read-domain-file "models/tasklist-solution.lisp")
(read-domain-file "models/task-solution.lisp")
(read-domain-file "models/template.lisp")
(read-domain-file "models/tijdsinterval.lisp")
(read-domain-file "models/uittreksel.lisp")
(read-domain-file "models/verkeersbordcategorie.lisp")
(read-domain-file "models/verkeersbordcombinatie.lisp")
(read-domain-file "models/verkeersbordconcept.lisp")
(read-domain-file "models/verkeersbordconcept-status-code.lisp")
(read-domain-file "models/verkiezingsresultaat-gevolg-code.lisp")
(read-domain-file "models/verkiezingsresultaat.lisp")
(read-domain-file "models/versioned-agenda.lisp")
(read-domain-file "models/versioned-behandeling.lisp")
(read-domain-file "models/versioned-besluiten-lijst.lisp")
(read-domain-file "models/versioned-notulen.lisp")
(read-domain-file "models/versioned-regulatory-statement.lisp")
(read-domain-file "models/vestiging.lisp")
(read-domain-file "models/werkingsgebied.lisp")
(read-domain-file "models/zitting.lisp")

