(in-package :mu-cl-resources)

(add-prefix "ext" "http://mu.semte.ch/vocabularies/ext/")
(add-prefix "tmp" "http://mu.semte.ch/vocabularies/tmp/")

(add-prefix "besluit" "http://data.vlaanderen.be/ns/besluit#")
(add-prefix "mandaat" "http://data.vlaanderen.be/ns/mandaat#")
(add-prefix "persoon" "http://data.vlaanderen.be/ns/persoon#")
(add-prefix "generiek" "http://data.vlaanderen.be/ns/generiek#")

(add-prefix "eli" "http://data.europa.eu/eli/ontology#")
(add-prefix "m8g" "http://data.europa.eu/m8g/")
(add-prefix "dct" "http://purl.org/dc/terms/")
(add-prefix "cpsv" "http://purl.org/vocab/cpsv#")
(add-prefix "dul" "http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#")
(add-prefix "adms" "https://www.w3.org/ns/adms#")
(add-prefix "person" "http://www.w3.org/ns/person#")
(add-prefix "org" "http://www.w3.org/ns/org#")
(add-prefix "prov" "http://www.w3.org/ns/prov#")
(add-prefix "regorg" "https://www.w3.org/ns/regorg#")
(add-prefix "skos" "http://www.w3.org/2004/02/skos/core#")
(add-prefix "foaf" "http://xmlns.com/foaf/0.1/")
(add-prefix "nao" "http://www.semanticdesktop.org/ontologies/2007/08/15/nao#")
(add-prefix "pav" "http://purl.org/pav/")
(add-prefix "schema" "http://schema.org/")
