(in-package :mu-cl-resources)

(add-prefix "ext" "http://mu.semte.ch/vocabularies/ext/")
(add-prefix "tmp" "http://mu.semte.ch/vocabularies/tmp/")

(add-prefix "besluit" "http://data.vlaanderen.be/ns/besluit#")
(add-prefix "bv" "http://data.vlaanderen.be/ns/besluitvorming#")
(add-prefix "mandaat" "http://data.vlaanderen.be/ns/mandaat#")
(add-prefix "persoon" "http://data.vlaanderen.be/ns/persoon#")
(add-prefix "generiek" "http://data.vlaanderen.be/ns/generiek#")
(add-prefix "mobiliteit" "https://data.vlaanderen.be/ns/mobiliteit#")

(add-prefix "eli" "http://data.europa.eu/eli/ontology#")
(add-prefix "m8g" "http://data.europa.eu/m8g/")
(add-prefix "dct" "http://purl.org/dc/terms/")
(add-prefix "cpsv" "http://purl.org/vocab/cpsv#")
(add-prefix "dul" "http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#")
(add-prefix "adms" "http://www.w3.org/ns/adms#")
(add-prefix "person" "http://www.w3.org/ns/person#")
(add-prefix "org" "http://www.w3.org/ns/org#")
(add-prefix "prov" "http://www.w3.org/ns/prov#")
(add-prefix "regorg" "https://www.w3.org/ns/regorg#")
(add-prefix "skos" "http://www.w3.org/2004/02/skos/core#")
(add-prefix "foaf" "http://xmlns.com/foaf/0.1/")
(add-prefix "nao" "http://www.semanticdesktop.org/ontologies/2007/08/15/nao#")
(add-prefix "pav" "http://purl.org/pav/")
(add-prefix "schema" "http://schema.org/")
(add-prefix "rdfs" "http://www.w3.org/2000/01/rdf-schema#")

(add-prefix "sign" "http://mu.semte.ch/vocabularies/ext/signing/")
(add-prefix "lblodlg" "http://data.lblod.info/vocabularies/leidinggevenden/")
(add-prefix "lblodmow" "http://data.lblod.info/vocabularies/mobiliteit/")
(add-prefix "locn" "http://www.w3.org/ns/locn#")
(add-prefix "adres" "https://data.vlaanderen.be/ns/adres#")
(add-prefix "lblodlg" "http://data.lblod.info/vocabularies/leidinggevenden/")
(add-prefix "bibo" "http://purl.org/ontology/bibo/")
(add-prefix "notulen" "http://lblod.data.gift/vocabularies/notulen/")

(add-prefix "nfo" "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#")
(add-prefix "nie" "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#")
(add-prefix "dbpedia" "http://dbpedia.org/ontology/")