(define-resource report ()
  :class (s-url "http://lblod.data.gift/vocabularies/reporting/Report")
  :properties `((:title :string ,(s-prefix "dct:title"))
    (:description :string ,(s-prefix "dct:description"))
    (:created :string ,(s-prefix "dct:created"))
  )
  :has-one `((file :via ,(s-prefix "prov:generated ")
                    :as "file"))
  :resource-base (s-url "http://data.lblod.info/id/reports/")
  :features '(include-uri)
  :on-path "reports")
