(define-resource agenda-position ()
  :class (s-prefix "ext:AgendaPosition")
  :has-one `((agendapunt :via ,(s-prefix "dct:related")
                         :as "agendapoint")
                (concept :via ,(s-prefix "ext:location")
                         :as "position"))
  :resource-base (s-url "http://data.lblod.info/id/agenda-positions/")
  :features '(include-uri)
  :on-path "agenda-positions")