(define-resource besluitenlijst ()
  :class (s-prefix "ext:Besluitenlijst")
  :properties `((:inhoud :string ,(s-prefix "prov:value"))
                (:publicatiedatum :date ,(s-prefix "eli:date_publication")))
  :has-one `((published-resource :via ,(s-prefix "prov:wasDerivedFrom")
                                 :as "publication")
             (zitting :via ,(s-prefix "ext:besluitenlijst")
                      :inverse t
                      :as "zitting"))
  :has-many `((besluit :via ,(s-prefix "ext:besluitenlijstBesluit")
                                          :as "besluiten"))
  :resource-base (s-url "http://data.lblod.info/id/besluitenlijsten/")
  :features '(include-uri)
  :on-path "besluitenlijsten")