(define-resource document-container ()
  :class (s-prefix "ext:DocumentContainer")
  :has-one `((editor-document :via ,(s-prefix "pav:hasCurrentVersion")
                              :as "current-version")
             (concept :via ,(s-prefix "ext:editorDocumentStatus")
                                     :as "status")
             (editor-document-folder :via ,(s-prefix "ext:editorDocumentFolder")
                                     :as "folder")
             (bestuurseenheid :via ,(s-prefix "dct:publisher")
                              :as "publisher"))
  :has-many `((editor-document :via ,(s-prefix "pav:hasVersion")
                               :as "revisions")
              (versioned-agenda :via ,(s-prefix "ext:hasVersionedAgenda")
                                :as "versioned-agendas")
              (versioned-behandeling :via ,(s-prefix "ext:hasVersionedBehandeling")
                                     :as "versioned-behandelingen")
              (versioned-notulen :via ,(s-prefix "ext:hasVersionedNotulen")
                                 :as "versioned-notulen")
              (versioned-besluiten-lijst :via ,(s-prefix "ext:hasVersionedBesluitenLijst")
                                         :as "versioned-besluiten-lijsten")
              (attachment :via ,(s-prefix "ext:hasAttachments")
                          :as "attachments")
              (editor-document :via ,(s-prefix "dct:isPartOf")
                  :as "is-part-of"))
  :resource-base (s-url "http://data.lblod.info/document-containers/")
  :features `(include-uri)
  :on-path "document-containers")