(define-resource editor-document ()
  :class (s-prefix "ext:EditorDocument")
  :properties `((:title :string ,(s-prefix "dct:title"))
                (:content :string ,(s-prefix "ext:editorDocumentContent"))
                (:context :string ,(s-prefix "ext:editorDocumentContext"))
                (:created-on :datetime ,(s-prefix "pav:createdOn"))
                (:updated-on :datetime ,(s-prefix "pav:lastUpdateOn"))
                (:starred :boolean ,(s-prefix "tmp:starred"))
                (:identifier :string ,(s-prefix "dct:identifier"))
                (:origin :string ,(s-prefix "pav:providedBy"))) ;;de gemeente Niel
  :has-one `((editor-document :via ,(s-prefix "pav:previousVersion")
                              :as "previous-version")
             (concept :via ,(s-prefix "dct:type")
                   :as "type")
             (concept :via ,(s-prefix "ext:editorDocumentStatus")
                      :as "status")
             (editor-document :via ,(s-prefix "pav:previousVersion")
                              :inverse t
                              :as "next-version")
             (document-container :via ,(s-prefix "pav:hasVersion")
                                 :inverse t
                                 :as "document-container"))
  :has-many `((tasklist-solution :via ,(s-prefix "ext:editorDocumentTasklistSolution")
                                 :as "tasklist-solutions")
              (document-container :via ,(s-prefix "dct:isPartOf")
                                         :inverse t
                                         :as "parts"))
  :resource-base (s-url "http://data.lblod.info/editor-documents/")
  :features `(no-pagination-defaults)
  :on-path "editor-documents")