(define-resource log-entry ()
  :class (s-prefix "rlog:Entry")
  :properties `((:class-name :url ,(s-prefix "rlog:className"))
                (:message :string ,(s-prefix "rlog:message"))
                (:specific-information :string ,(s-prefix "ext:specificInformation"))
                (:datetime :datetime ,(s-prefix "rlog:date")))
  :has-one `((log-level :via ,(s-prefix "rlog:level")
                   :as "log-level")
              (status-code :via ,(s-prefix "rlog:hasCode")
                   :as "status-code")
              (log-source :via ,(s-prefix "dct:source")
                   :as "log-source"))
  :has-many `((report-content :via ,(s-prefix "ext:belongsToReport")
                   :as "report-content"))
  :resource-base (s-url "http://data.lblod.info/id/log-entries/")
  :features `(include-uri)
  :on-path "log-entries")
