(define-resource mandataris ()
  :class (s-prefix "mandaat:Mandataris")
  :properties `((:rangorde :language-string ,(s-prefix "mandaat:rangorde"))
                (:start :datetime ,(s-prefix "mandaat:start"))
                (:einde :datetime ,(s-prefix "mandaat:einde"))
                (:datum-eedaflegging :datetime ,(s-prefix "ext:datumEedaflegging"))
                (:datum-ministrieel-besluit :datetime ,(s-prefix "ext:datumMinistrieelBesluit"))
                (:generated-from :uri-set ,(s-prefix "ext:generatedFrom"))) ;;if it e.g. comes from gelinkt-notuleren
  :has-many `((rechtsgrond-aanstelling :via ,(s-prefix "mandaat:isAangesteldDoor")
                                       :as "rechtsgronden-aanstelling")
              (rechtsgrond-beeindiging :via ,(s-prefix "mandaat:isOntslagenDoor")
                                       :as "rechtsgronden-beeindiging")
              (mandataris :via ,(s-prefix "mandaat:isTijdelijkVervangenDoor")
                          :as "tijdelijke-vervangingen")
              (beleidsdomein-code :via ,(s-prefix "mandaat:beleidsdomein")
                                  :as "beleidsdomein")
              (behandeling-van-agendapunt :via ,(s-prefix "besluit:heeftAanwezige")
                           :inverse t
                           :as "aanwezig-bij-behandeling")
              (behandeling-van-agendapunt :via ,(s-prefix "ext:heeftAfwezige")
                           :inverse t
                           :as "afwezig-bij-behandeling")
              (zitting :via ,(s-prefix "besluit:heeftAanwezigeBijStart")
                           :inverse t
                           :as "aanwezig-bij-zitting")
              (zitting :via ,(s-prefix "ext:heeftAfwezigeBijStart")
                           :inverse t
                           :as "afwezig-bij-zitting"))
  :has-one `((mandaat :via ,(s-prefix "org:holds")
                      :as "bekleedt")
             (lidmaatschap :via ,(s-prefix "org:hasMembership")
                           :as "heeft-lidmaatschap")
             (persoon :via ,(s-prefix "mandaat:isBestuurlijkeAliasVan")
                      :as "is-bestuurlijke-alias-van")
             (mandataris-status-code :via ,(s-prefix "mandaat:status")
                                      :as "status"))
  :resource-base (s-url "http://data.lblod.info/id/mandatarissen/")
  :features '(include-uri)
  :on-path "mandatarissen")