(define-resource notulen ()
  :class (s-prefix "ext:Notulen")
  :properties `((:inhoud :string ,(s-prefix "prov:value")))
  :has-one `((zitting :via ,(s-prefix "besluit:heeftNotulen")
                      :inverse t
                      :as "zitting"))
  :has-many `((published-resource :via ,(s-prefix "prov:wasDerivedFrom")
                                  :as "publications"))
  :resource-base (s-url "http://data.lblod.info/id/notulen/")
  :features '(include-uri)
  :on-path "notulen")