(define-resource rechtsgrond-artikel ()
  :class (s-prefix "eli:LegalResourceSubdivision")
  :properties `((:buitenwerkingtreding :date ,(s-prefix "eli:date_no_longer_in_force"))
                (:inwerkingtreding :date ,(s-prefix "eli:first_date_entry_in_force")))
  :has-one `((rechtsgrond-besluit :via ,(s-prefix "eli:has_part")
                                  :inverse t
                                  :as "rechtsgrond-besluit"))
  :resource-base (s-url "http://data.lblod.info/id/rechtsgronden-artikel/")
  :features '(include-uri)
  :on-path "rechtsgronden-artikel")