(define-resource rechtsgrond-aanstelling ()
  :class (s-prefix "mandaat:RechtsgrondAanstelling")
  :properties `((:buitenwerkingtreding :date ,(s-prefix "eli:date_no_longer_in_force"))
                (:inwekingtreding :date ,(s-prefix "eli:first_date_entry_in_force"))
                (:type-document :uri-set ,(s-prefix "eli:type_document")))
  :has-many `((mandataris :via ,(s-prefix "mandaat:isAangesteldDoor")
                          :inverse t
                          :as "bekrachtigt-aanstellingen-van"))
  :resource-base (s-url "http://data.ldblod.info/id/rechtsgronden-aanstelling/")
  :features '(include-uri)
  :on-path "rechtsgronden-aanstelling")