(define-resource signed-resource ()
  :class (s-prefix "sign:SignedResource")
  :properties `((:content :string ,(s-prefix "sign:text"))
                (:hash-value :string ,(s-prefix "sign:hashValue"))
                (:created-on :datetime ,(s-prefix "dct:created"))
                (:deleted :boolean ,(s-prefix "ext:deleted")))
  :has-one `((blockchain-status :via ,(s-prefix "sign:status")
                                :as "status")
             (agenda :via ,(s-prefix "ext:signsAgenda")
                               :as "agenda")
             (versioned-besluiten-lijst :via ,(s-prefix "ext:signsBesluitenlijst")
                                        :as "versioned-besluiten-lijst")
             (versioned-notulen :via ,(s-prefix "ext:signsNotulen")
                                :as "versioned-notulen")
             (versioned-behandeling :via ,(s-prefix "ext:signsBehandeling")
                                    :as "versioned-behandeling")
             (gebruiker :via ,(s-prefix "sign:signatory")
                        :as "gebruiker"))
  :resource-base (s-url "http://data.lblod.info/signed-resources/")
  :features '(include-uri)
  :on-path "signed-resources")