(define-resource uittreksel ()
  :class (s-prefix "ext:Uittreksel")
  :properties `((:inhoud :string ,(s-prefix "prov:value")))
  :has-one `((published-resource :via ,(s-prefix "prov:wasDerivedFrom")
                                 :as "publication")
             (behandeling-van-agendapunt :via ,(s-prefix "ext:uittrekselBvap")
                                         :as "behandeling-van-agendapunt")
             (zitting :via ,(s-prefix "ext:uittreksel")
                      :inverse t
                      :as "zitting"))
  :resource-base (s-url "http://data.lblod.info/id/uittreksels/")
  :features '(include-uri)
  :on-path "uittreksels")