clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      lfs: false
      remote: ${CI_REPO_CLONE_URL}

steps:
  validate-resource-models:
    image: madnificent/cl-resources-plantuml-generator
    commands:
      - mkdir /config/output
      - cp -R ./config/resources/* /app/configuration/
      - cd /
      - sbcl --disable-debugger --load /usr/src/startup.lisp
when:
  event:
    - pull_request